### PR TITLE
add support for a remote (RDS) buttonmen database

### LINKED ISSUE #2523: move the staging and prod databases to RDS
Move the databases for a small number of site types (staging, prod, and presumably a dev branch to use for initial development of this change) from on-system-hosted MySQL to RDS-hosted MySQL.

### PR DESCRIPTION
**Pull request by cgolubi1**
* Fixes #2523 

DO NOT MERGE THIS - it needs to be rebased, and i need to actually create the staging and production databases and put their FQDNs in.  I'm putting it up for review to make sure the approach looks fine.

### CODE REVIEW

**Comment by blackshadowshade** [comment]
Added the incomplete label to remind me not to merge this.

**Comment by cgolubi1** [comment]
I also need to do two more tests (both of these are in progress):
* Stand up a dev site with a local database on this branch, to make sure i didn't break that functionality
* Load the prod database onto my dev instance, to make sure there's nothing terribly awry in terms of DB size and whatnot when i go to put this in place for prod

**Comment by cgolubi1** [comment]
The public dev site is at http://54.163.4.93/ui/index.html --- people can check it out.  I'm not going to put it in the listing and ask for a domain name and stuff; either it works or it doesn't work, so i expect the testing to be quick.

**Comment by blackshadowshade** [comment]
Right, this looks okay to me.

To test, I played a turn, checked that nothing changes in the local database, and that the change happened in the remote database.

**Comment by cgolubi1** [comment]
I realised we're not going to get very far without a user-friendly CLI for database access --- i don't think we should be connecting to the prod database without a good reason and a second set of eyes on what commands we're going to run, but nonetheless we have those things when we're doing database updates as part of a site upgrade, and copy/pasting FQDNs and passwords doesn't make me any safer then either.  So i added `/usr/local/bin/mysql_root_cli`.  Usage examples:

Interactive:
```
$ sudo mysql_root_cli
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 111
Server version: 5.7.29-0ubuntu0.16.04.1 (Ubuntu)

Copyright (c) 2000, 2020, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> show tables;
+-------------------------------------------------------+
| Tables_in_buttonmen                                   |
+-------------------------------------------------------+
| button                                                |
| button_tag_map                                        |
| button_view                                           |
| buttonset                                             |
| config                                                |
| dhs_button                                            |
| dhs_player                                            |
| dhs_site_button_player_stats                          |
| dhs_site_button_vs_button_stats                       |
| die                                                   |
| die_status                                            |
| forum_board                                           |
| forum_board_player_map                                |
| forum_player_post_view                                |
| forum_post                                            |
| forum_thread                                          |
| forum_thread_player_map                               |
| game                                                  |
| game_action_log                                       |
| game_action_log_type_add_auxiliary                    |
| game_action_log_type_add_reserve                      |
| game_action_log_type_choose_die_values                |
| game_action_log_type_choose_die_values_option         |
| game_action_log_type_choose_die_values_swing          |
| game_action_log_type_create_game                      |
| game_action_log_type_determine_initiative             |
| game_action_log_type_determine_initiative_die         |
| game_action_log_type_determine_initiative_slow_button |
| game_action_log_type_end_draw                         |
| game_action_log_type_end_winner                       |
| game_action_log_type_play_another_turn                |
| game_action_log_type_reroll_chance                    |
| game_action_log_type_turndown_focus_die               |
| game_chat_log                                         |
| game_option_map                                       |
| game_player_map                                       |
| game_player_view                                      |
| game_status                                           |
| game_swing_map                                        |
| game_turbo_cache                                      |
| open_game_possible_button_view                        |
| open_game_possible_buttons                            |
| open_game_possible_buttonsets                         |
| player                                                |
| player_auth                                           |
| player_reset_verification                             |
| player_status                                         |
| player_verification                                   |
| player_view                                           |
| tag                                                   |
| tournament                                            |
+-------------------------------------------------------+
51 rows in set (0.00 sec)

mysql> ^DBye
```

Pipelined:
```
$ echo "select id from player where name_ingame='glassonion'" | sudo mysql_root_cli
id
1
$
```

Now that we have password reset, after i get the stats code working, i'm going to go on a serious tear against adhoc interactive database access.  But for now there's no safety benefit to making us mess up syntax.

**Comment by cgolubi1** [comment]
irilyth: good thought, but the actual right thing to do is to use IAM creds to talk to the database, which RDS supports, but i've never used.  I don't want to tackle figuring that out as a blocker to fixing the "prod disk is filling" issue, but i'm going to make an issue to sort it out once we've pushed all of this.  I don't think there's enough difference between on-disk-password-storage formats to be worth futzing with.

**Comment by irilyth** [comment]
Works for me. (We haven't done IAM-based access at work for various historical reasons, but now that you mention it, I'm dimly aware of it, and it sounds like a fine idea. :^)

**Comment by blackshadowshade** [comment]
Okay, mysql_root_cli works fine for me.

**Comment by blackshadowshade** [comment]
Wait a moment. I use mysql_root_cli, and I end up at the wrong database. It's not showing the game turn I played yesterday, even though I can still see it on the game page.

**Comment by blackshadowshade** [comment]
Do I need to set up my environment variable ${CREDS_FILE}?

**Comment by cgolubi1** [comment]
As noted on #2525 it looks like mysqld on my dev instance went nuts and got OOM-killed.

I don't know what's up with that.  I know we don't need a running mysqld if we're using RDS, and presumably it would be less confusing if we didn't have one.  So what if i shut off mysqld when we're running RDS?  Let me try that and see what breaks --- i expect it'll take more than one git commit to debug.

**Comment by cgolubi1** [comment]
Okay, done, and verified that my dev site is still running (and mysql_root_cli still works, as does backup_buttonmen_database), and that standing up a virtualbox site still works fine.  We're obviously going to want a bit of baketime here in case this problem is on the RDS end rather than the mysql end.  But i think i can go ahead and create the staging and prod databases, and get this PR ready to go for real.

**Comment by blackshadowshade** [comment]
mysql_root_cli is now showing me the correct data for game 164, which is excellent.

**Comment by cgolubi1** [comment]
Interesting:

```
$ dmesg -T | grep Out
[Mon Feb  3 00:06:12 2020] Out of memory: Kill process 20066 (mysqld) score 345 or sacrifice child
[Mon Feb  3 00:06:12 2020] Out of memory: Kill process 20088 (mysqld) score 350 or sacrifice child
[Tue Feb  4 00:17:06 2020] Out of memory: Kill process 6643 (mysqld) score 375 or sacrifice child
```

So probably just bad luck that i happened to be running vagrant at mysqld death spiral o'clock.  But that's definitely not something that happens on other sites, i don't think.  So we definitely want to bake past another midnight UTC, to make sure nothing gets OOM-killed once mysqld isn't running.  But that actually makes me feel more optimistic, because we should be able to see there be a problem (or not be one) this time tomorrow.

**Comment by cgolubi1** [comment]
I defined the database endpoints for staging and prod, and rebased down to one commit.

In an ideal world, i'd get rid of the defined config for the temporary dev site, but in this world, i want to keep it around in case we need to do any more testing as we go, and i'll get rid of it once we're happy with everything later.

**Comment by blackshadowshade** [comment]
Okay, rebase looks good. Merging this now.

**Pull request merged**
