### PR TITLE
Fix isset() and empty() calls broken by PHP version upgrade

### LINKED ISSUE #1167: Upgrade to PHP 5.5 or higher
We're apparently currently using PHP 5.3.10. We should upgrade to a newer version at some point. (This would particularly help with #884.)

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #1167.

So, this pull request is intended to fix the calls to isset() and empty() in the code and test code that were broken by the upgrade from PHP 5.2 to PHP 7.0.

We already know from Chaos's replay testing that these changes break something with Dead Guy, so I'll mark this as incomplete until we have a responder test for that problem and the problem has been fixed.

### CODE REVIEW

**Comment by blackshadowshade** [comment]
Just bumping this as a reminder that I'm still waiting on a Dead Guy responder test that breaks with these changes.

**Comment by cgolubi1** [comment]
I stood up a replay site, and i'm kicking off some Dead Guy games.

**Comment by blackshadowshade** [comment]
I agree that it's an improvement! Looking forward to seeing what else pops up.

**Comment by cgolubi1** [comment]
Another thing which i think is a bug in RandomAI, not in the backend.  The backend thinks this attack is legal, where my bot couldn't find a valid skill attack:

hairy_skill_attack

**Comment by cgolubi1** [comment]
To elaborate, i assume my bot got tripped up by the fact that one of the twin stinger dice needs to contribute 1 to the attack, and in fact `g(1,1)` can't contribute 1, but `g(0,2)` can.  I can probably fix that in randomAI pretty easily --- i'm just mentioning it here to make sure my read of the desired behavior (that this attack indeed should be legal) is correct.

In retrospect, i wish i'd spent more time arguing against the implementation of zero-sided dice --- i think on the order of 50% of our logic debugging time is spent on zero-sided-die-related problems, and i think that was predictable at the time, and we should have been intelligent enough to say "is the fun quotient this brings worth it relative to other features?"  I know that's hard to predict, but i'm raising it now because i think "we will be debugging issues related to this implementation every time we touch the codebase" *was* predictable, and when we go to implement other features like that, we should be asking ourselves "is this actually going to add a sufficient amount of fun?"

**Comment by blackshadowshade** [comment]
I guess my take on this is that we're going to have to make calls about fractional sided dice (like the 19.5 for Dr. Lucky), negative sided dice (like Fudge), and strange-sided dice (like Wildcard).

Our experience with zero-sided dice will give us a better perspective on how much angst these potential changes will give us. The major one that we'll probably have to implement at some stage is Wildcard, but there's a good reason I haven't touched that yet.

**Comment by blackshadowshade** [comment]
And just noticed that I didn't explicitly confirm that I agree with your understanding of stinger, that a g(0,2) should be able to contribute a value of 1, but a g(1,1) cannot.

**Comment by cgolubi1** [comment]
Thanks.  That's not why i hadn't gotten back to this (recently, it's because of the RDS thing, so... soon?  (!)), but it's good to have confirmed.

**Comment by cgolubi1** [comment]
Starting over with this a bit --- the first 3000 or so games i replayed had about 13 failures, and all of them were of the form of the example i had very early in this thread, where the defending die is zero-sided, and used to be rerolled, and now isn't any more.  So i've modified the updater to account for the simplest form of that case, and i'm hoping that'll get the number of failures down to a number i can spot-check easily:

```python
#!/usr/bin/python
##### update_replay_games
# This should have the same functionality as prep_replay_games, but
# can be modified to adjust the API output to account for changes
# between the master version against which games were recorded, and
# the version under test.  One-off changes which will not be needed
# once the API update is committed should be made in this file and
# should not be committed.  Support for permanent API changes should
# be made in random_ai.py.

import sys
sys.path.append('lib')

import random_ai

########################################################################
# Custom classes
class PHPBMClientOutputWriter(random_ai.PHPBMClientOutputWriter):
  # If you need to make any changes to the syntax of PHP output which is
  # translated from the internal game state format for regression-testing
  # previously recorded games against this PR (e.g. if the new code
  # changes the API and you need to reflect those changes for replays
  # to succeed), make those overrides here for clarity during testing.
  #
  # As a first resort, trying overriding apply_known_changes_to_game_data()
  def _write_entry_type_submitTurn(self, entry):
    # Set a flag so _php_rand_str() can know if this is a submitTurn entry
    self.in_submit_turn = True
    random_ai.PHPBMClientOutputWriter._write_entry_type_submitTurn(self, entry)
    self.in_submit_turn = False

  def _php_rand_str(self, retval):
    # This change corrects a bug in which a die is incorrectly rolled for a 0-sided die which is the target of an attack
    # Handle the most common case of that problem, a single 0-sider which is the target of an attack and is the first 0-sider to be rerolled during the attack.
    if self.in_submit_turn and 'against [(0):0]' in retval.message:
      self.f.write('// 1167_isset: removing first defender 0 from retval.rand_vals: %s\n' % retval.rand_vals)
      # If a 0 is the first thing, assume it's an attacker size change, and remove the second one
      if retval.rand_vals[0] == 0:
        nextzero = retval.rand_vals.index(0, 2)
        retval.rand_vals.pop(nextzero)
      else:
        retval.rand_vals.remove(0)
    return random_ai.PHPBMClientOutputWriter._php_rand_str(self, retval)

########################################################################
# Initial setup
if len(sys.argv) < 2:
  raise ValueError("Usage: update_replay_games <dirname>")

DIRNAME = sys.argv[1]

d = PHPBMClientOutputWriter(DIRNAME)
for gamepath in d.find_games():
  sys.stderr.write("Updating and prepping game for replay from: %s\n" % gamepath)
  d.in_submit_turn = False
  d.translate_game(gamepath)
```

**Comment by cgolubi1** [comment]
Replayed about 17000 games with the above recipe.  They included 7 failures, all of which were obvious corner cases which i got to pass by hand (e.g. target is `t(0)` instead of `(0)`.  I think we should merge this --- want to rebase it down to a single commit?

**Comment by blackshadowshade** [comment]
Okay, that's been rebased.

Now I can implement zero-sided option dice and get my Fanatic playable!  :)

**Comment by cgolubi1** [comment]
I'm not sure that's the right takeaway, James...

Anyway, merging, and apologies that it took so long.

**Pull request merged**
