### PR TITLE
Refactored part of BMInterface into BMInterfaceForum

### PR DESCRIPTION
**Pull request by blackshadowshade**
Continues to address #974.

This should leave all functionality unchanged.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/868/

### CODE REVIEW

**Comment by blackshadowshade** [comment]
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/888/

**Comment by cgolubi1** [comment]
Okay.  Basically just:
* load this and click around the forums for awhile to make sure nothing has changed
* do a manual diff of the contents of the various files between which code was moved, to make sure the code hasn't been changed other than being moved between files and/or if it has that the differences make sense to me

**Comment by cgolubi1** [comment]
Diffs look fine.

**Comment by cgolubi1** [comment]
Forums look fine.  Merging.

**Pull request merged**
