### PR TITLE
Added Jolt skill

### LINKED ISSUE #275: Jolt die skill needed
Jolt: J
(Exclusive to this website; unofficial)
Jolt Dice were created by Randy Chertkow (aka Famous) for this web site. They are represented by a "J" before a die. They are normal in all respects, except that when they attack, or are attacked. If a Jolt die attacks, or participates in an attack, the player will get to take another turn and the Jolt die losses the Jolt skill. If a Jolt die is captured, then the player who captured it takes another turn.

Inconsistencies:

```
J^ (Jolt Time & Space): Will not give more than 1 extra turn if rerolled to an odd number. 
```

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #275.

At some stage, this should probably have a responder test added (e.g., Button of Loathing vs Tirade), but from my testing, it looks like it works okay.

### CODE REVIEW

**Comment by blackshadowshade** [comment]
One comment on this: I'll also need to update the description of Radioactive, but I don't want to have this conflict with the new wording that will be happening to address #2307.

**Comment by cgolubi1** [comment]
Alright, i'm starting to try caching `update_replay_games` versions that work for various cases because i can't keep the details in my tiny brain.  In this case, it took me much longer than it should have to remember that the *only* purpose of $RANDOMBM_SKILL_ARRAY in responderTestFramework.php is to make it so that we don't have to renumber all skills in all tests recorded in the codebase (i.e. we can refer to skills by letter within the PHP tests).  It has nothing to do with the mapping from `bm_skill_rand()`'s output to skills, because that's handled by the backend, not by the test code.

So here's the `update_replay_games` override i'm now trying for this site:

```
class PHPBMClientOutputWriter(random_ai.PHPBMClientOutputWriter):
  # If you need to make any changes to the syntax of PHP output which is
  # translated from the internal game state format for regression-testing
  # previously recorded games against this PR (e.g. if the new code
  # changes the API and you need to reflect those changes for replays
  # to succeed), make those overrides here for clarity during testing.
  #
  # As a first resort, trying overriding apply_known_changes_to_game_data()
  def _php_dict_style_rand_str(self, retval):
    if retval.skill_rand_vals:
      for i in range(len(retval.skill_rand_vals)):
        if retval.skill_rand_vals[i] >= 5:
          retval.skill_rand_vals[i] += 1
    return random_ai.PHPBMClientOutputWriter._php_dict_style_rand_str(self, retval)
```

**Comment by cgolubi1** [comment]
Replay testing looks good --- it's played nearly 19000 novel and replayed games.  I'm going to hack the client to play only RandomBMPentaskill novel games, to try to find any internal errors faster, but i don't think i'm going to find anything else via replay testing.  Time to stand up a dev site.

**Comment by cgolubi1** [comment]
Dev site created.  irilyth, at your leisure, can you sync up: ephemeral 3.91.68.115

**Comment by irilyth** [comment]
> Dev site created. irilyth, at your leisure, can you sync up: ephemeral 3.91.68.115

Done!

```
+$ host ephemeral.dev.buttonweavers.com
ephemeral.dev.buttonweavers.com has address 3.91.68.115
```

**Comment by dwvanstone** [comment]
I did a bunch of testing on the dev site and found Jolt to be working well.

**Comment by cgolubi1** [comment]
Okay, replay testing is still doing fine.  I say let's merge this; thanks, all.

**Pull request merged**
