### PR TITLE
Filled in tutorial page

### LINKED ISSUE #2467: Fill in tutorial page
Spawned from #1924.

Fill in the contents of the tutorial page getting-started.html

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #2467.

This is a first draft, I'm happy to take input on the content.

@cgolubi1, could we have a test site for this so that testers can take a look at the new tutorial page, please?

To do:
- [x] Deal with the situation where the viewer is not logged in (add a Getting Started When You're Not Logged In page)
- [x] Add text changes suggested by others

### CODE REVIEW

**Comment by cgolubi1** [comment]
Dev site is up, at https://makeshift.dev.buttonweavers.com/

**Comment by cgolubi1** [comment]
One comment i'll make --- https://makeshift.dev.buttonweavers.com/ui/getting-started.html *is* accessible without logging into the site, but it's written with the assumption that you're logged in --- doesn't say how to create an account or login, and links to lots of pages that won't work if you're not logged in.

I think the right answer is probably to make the "getting started" page "getting started once you've logged in", but that means if you access it logged-out, you should get a reminder to create an account / login, rather than the contents that mostly won't work for you.

**Comment by cgolubi1** [comment]
Reminder that this needs review - the dev site is https://makeshift.dev.buttonweavers.com/ui/getting-started.html --- i left one comment for shadowshade to address, but someone needs to take a closer look at all the contents of the tutorial page.

**Comment by jl8e** [comment]
It's reasonable.

Specific issues:

I'd prefer to have the rules of the game on-site, but that's a separate issue, I think.

The text refers to hovering for information, which doesn't work on mobile.

I'd like a section (probably after "join a game" and before "create a game") that suggests a set progression for new players, and also needs to warn them off of expecting random from set to work.

I can take a stab at doing these, probably this week.

**Comment by blackshadowshade** [comment]
I've added a logged out tutorial page which mentions creating an account, verifying the account, and then logging in to see the extended tutorial.

I've also updated the help regarding IRC since we don't use that any more.

**Comment by cgolubi1** [comment]
Dev site updated (and verified that i can see the new contents at https://makeshift.dev.buttonweavers.com/ui/getting-started.html )

**Comment by blackshadowshade** [comment]
So, basic rules on our site (Issue #2843) will be addressed by a subsequent pull request.

I've added a bit of wording to cover the fact that hover text only works for computers.

And I've added a section about which buttons to start with.

**Comment by blackshadowshade** [comment]
CircleCI passes, so @cgolubi1, this is ready to be updated.

**Comment by cgolubi1** [comment]
https://makeshift.dev.buttonweavers.com/ui/ should be updated

**Comment by blackshadowshade** [comment]
I see the updated site on Chrome, but I'm seeing #2818 again on Safari, even with a forced reload.

**Comment by blackshadowshade** [comment]
I've rebased this pull request.

**Comment by cgolubi1** [comment]
Okay, so i think we stopped working on this because of #2818.  Now that we've merged a possible fix to that, i think the right choice here is to redeploy this dev site, and then people can take a look at it.  Stand by.

**Comment by cgolubi1** [comment]
Okay, so this is updated --- see https://makeshift.dev.buttonweavers.com/ui/getting-started.html

Shadowshade, can you call out what additional feedback you need from folks before this can be merged?

**Comment by blackshadowshade** [comment]
This looks good to me. Looking forward to getting this merged as-is, which will enable us to look at merging #2859.

**Comment by cgolubi1** [comment]
I'm fine with that.  We can make more changes as we go.

**Pull request merged**
