### PR TITLE
Added more flavour text

### LINKED ISSUE #2548: Rediscovered Flavor Text
Skeeve sent me a couple of old files the original BMO used.  It used UNIX text files to reference, funny enough.

In there are some new flavor texts that this sit didn't have, including the requested seven deadly sins text.

Gluttony: Gluttony enjoys eating, eating and the Fat Albert Cartoon. When not eating, or thinking about eating, he spends his time beating people up with his Double-Drumstick Fu.
Pride: Pride is a diva of the nose harmonica. When not appearing on Live TV news casts, she enjoys flinging cats, radish carvings and beating people up.

Lust: Lust is out-of-work actress who is rather top heavy. While not trying to get bit parts on VIP, Baywatch or any USA shows, she enjoys humming and the color red. She also beats people up.

Envy: Envy wants to be just like you. When not imitating everything around him, he enjoys the periodic table, prime numbers and beating people up.

Sloth: Sloth is the ultimate armchair warrior. When not watching sports, he enjoys thinking about sports and encouraging others to talk about yams in loud voices. He beats people up with his special move 'Super Slow Motion Slam'. (It may take a while to get there, but it sure packs a wallop!)

Anger: Anger spends most of his time in useless debates with his sock puppet collection. When not playing in his Punk Band, The Rancid Spleen, he enjoys beating people up.

Greed: Greed is a fanatical collector of soup labels. While not surfing the net, or in her pimp-mobile searching flea markets, she enjoy beating people up and then running them over.

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #2548.

I've added the flavour text that @TheOrgg found.

I've left the flavour text for the Las Vegas alternate buttons (Pai Gow II, Shamrock II, Them Bones, Twenty-One) empty for the moment.

### CODE REVIEW

**Comment by cgolubi1** [comment]
DB diff check looks fine; standing up a dev site.

**Comment by cgolubi1** [comment]
irilyth: can you sync up 54.196.226.138 as momentary.dev.buttonweavers.com when you get a sec?

Everyone else, dev site is up to check out this flavor text.

**Comment by dwvanstone** [comment]
Checking the dev site. Looks good overall!

Lorrie: "Lorrie really is the power behind Hoover Dam." Is that missing the word "the" or is it okay? 

Tony: "He has 10,000 llamas, and has a masters in Christian ethics. "  Capital "M" and apostrophye on "Master's"? Capital "E" in ethics? 

GripTiger: "GripTiger is the quiet type who likes chocolate-peanutbutter ice cream..." Looks weird to me. How about just "chocolate peanut butter ice cream"?

myxozoa: I'm not a scientist, but "A sixed celled metazoan..." doesn't seem right. "A six-cell metazoan..." ??

Everything else looks fine. In fact, none of these are blockers in my mind - perhaps the fanatics folks wanted oddly worded descriptions, but they could make newcomers think there are typos on the site.


Just for calrity...this issue fixes all missing descriptions except for the Ice Cream set which is also addressed in #2553. This also doesn't fix any missing art found in the BMJPEG.zip file. I would recommend that get a new bug number.

**Comment by irilyth** [comment]
> irilyth: can you sync up 54.196.226.138 as momentary.dev.buttonweavers.com when you get a sec?
> 
> Everyone else, dev site is up to check out this flavor text.

Done!

**Comment by TheOrgg** [comment]
I think it would be "Masters of Christian Ethics" if I recall correctly.  So capitals and change 'in' to 'of.'

I'm please how these flavor texts coincidentally fit the 'aethral beings' theme I adapted the set to.

**Comment by blackshadowshade** [comment]
I believe that there is no consensus about either the capitalisation or apostrophisation changes suggestion regarding "masters in Christian ethics".

See https://liberalarts.oregonstate.edu/shpr/philosophy/academic-programs/masters-degree-applied-ethics for an example of "in".

See https://en.wikipedia.org/wiki/List_of_masters_programs_in_bioethics for an example without capitalisation.

So, barring any major disagreements, I'd rather leave this alone.

**Comment by blackshadowshade** [comment]
As for the other changes, the only convincing one I see is myxozoa's, that is an obvious fix.

**Comment by blackshadowshade** [comment]
So, what about "six celled metazoan" or "six-celled metazoan"?

**Comment by dwvanstone** [comment]
> So, what about "six celled metazoan" or "six-celled metazoan"?

The first reads that there are six "celled metazoan"s out there. The second reads better.

**Comment by blackshadowshade** [comment]
I've made the two changes agreed above.

To keep this pull request with only one database update, I've modified the update file and rebased. This needs to be redeployed for final perusal by testers.

**Comment by cgolubi1** [comment]
Updated.  irilyth, can you resync momentary == 18.204.44.255 when you have a second?

**Comment by cgolubi1** [comment]
Reminder to self: i haven't actually redone the update-vs-reinstall test on this version.

**Comment by blackshadowshade** [comment]
I've checked a couple of the new flavour texts (including those with the most recent two changes) on the new dev site, and they look okay to me.

**Comment by dwvanstone** [comment]
These look good to me as well.

**Comment by irilyth** [comment]
Done!
```
+$ host momentary.dev.buttonweavers.com
momentary.dev.buttonweavers.com has address 18.204.44.255
```

**Comment by cgolubi1** [comment]
Okay, doing the database test now, and if it's fine, i'll merge this.

**Pull request merged**
