### PR TITLE
RandomAI should fail on obviously-buggy game creation failures

### PR DESCRIPTION
**Pull request by cgolubi1**
* Partially addresses #2801

### CODE REVIEW

**Comment by cgolubi1** [comment]
Shadowshade, i'm just checking this out on a replay site to make sure it behaves the way i want it to, then i'll ask you to merge it.

**Comment by cgolubi1** [comment]
Without this fix, if i hardcode in a bug in the `create_game()` function that just always throws "Could not load game" no matter what:
```
$ ./replay_loop 
mysqlshow: Unknown database 'buttonmen'
Creating buttonmen
Populating buttonmen
buttonmen_test already exists - recreating it
Creating buttonmen_test
Populating buttonmen_test
mysql: [Warning] Using a password on the command line interface can be insecure.
Starting game 1
Starting game 2
Starting game 3
Starting game 4
Starting game 5
...
```

and replay of those games succeeds too, because the error is the same on playback.

With this fix:
```
$ ./replay_loop 
mysqlshow: Unknown database 'buttonmen'
Creating buttonmen
Populating buttonmen
buttonmen_test already exists - recreating it
Creating buttonmen_test
Populating buttonmen_test
mysql: [Warning] Using a password on the command line interface can be insecure.
Starting game 1
Traceback (most recent call last):
  File "./test_log_games", line 71, in <module>
    c.log_test_game(i, button1, button2)
  File "lib/random_ai.py", line 1818, in log_test_game
    self.record_create_game(button1, button2, use_prev_game=use_prev_game)
  File "lib/random_ai.py", line 1731, in record_create_game
    retval and retval.message or "NULL"))
  File "lib/random_ai.py", line 1696, in bug
    raise ValueError, message
ValueError: create_game(Montague, Apples, 3, custom_recipe_array=[]) unexpectedly failed: Game create failed: Could not load newly-created game 1
```

So that seems better.

**Comment by cgolubi1** [comment]
Replay seems fine otherwise, at the "basic smoke test" level, which is all this should need.

Shadowshade, this is ready for review.

**Comment by blackshadowshade** [comment]
Change is to RandomAI only, merging this now.

**Pull request merged**
