### PR TITLE
Fixed logging of attacking trip dice that split

### LINKED ISSUE #1452: Logging for konstant trip dice performing trip attacks is incorrect
Konstant trip dice performing attacks against radioactive dice behave correctly, but the splitting doesn't log correctly.

capture

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #1452.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/654/

### CODE REVIEW

**Comment by blackshadowshade** [comment]
This may also fix #1440, but will need to be verified via testing.

**Comment by cgolubi1** [comment]
What am i doing here?
* Playing back those 500 games i captured from buttonmen-master this morning, to look for any regressions
* Playing a bunch of games involving twin dice, to look for internal errors

**Comment by cgolubi1** [comment]
So... here's another thing i found because of a regression, and am not sure what its state is.  Here's the situation --- BlackOmega's trip morphing 6 unsuccessfully Trip attacks grend's radioactive die... and splits.

I believe this demonstrates that this fix works in the morphing case --- the message changed:
```
-            'message' => 'responder004 performed Trip attack using [tm(6):4] against [%(4):3]; Attacker tm(6) rerolled 4 => 2; Defender %(4) rerolled 3 => 3, was not captured'
+            'message' => 'responder004 performed Trip attack using [tm(6):4] against [%(4):3]; Attacker tm(6) rerolled 4 => 2; Defender %(4) rerolled 3 => 3, was not captured; Attacker tm(6) showing 2 split into: tm(3) showing 3, and tm(3) showing 2'
```

and, to the extent that that's what actually happened, the message is an improvement.

However, the underlying behavior is a bug --- the `tm(6)` should not have split.  Is this a known issue or a new one?

unsuccessful_trip_split

**Comment by cgolubi1** [comment]
Okay, so, in fact, this was discussed at length in #1432.  I dunno, the current behavior still feels wrong to me, but it's what we decided.  So it's not a bug.  Anyway, given that, the game above is a successful example of the fix on this ticket improving the situation.

**Comment by irilyth** [comment]
> However, the underlying behavior is a bug --- the `tm(6)` should not have split.

Why not? Radioactive says "If a radioactive die is either the attacking die or the target die in an attack with a single attacking die and a single target die, the attacking die splits", which we've previously concluded means that the Trip die in a failed Trip Attack against a Radioactive die does split (because it's attacking, and Radioactive doesn't say anything about capture).

**Comment by irilyth** [comment]
Ah, crossing e-mail there, ignore my last comment.

**Comment by cgolubi1** [comment]
I ran 100 games including some combination of trip, radioactive, and twin dice.  No internal errors, and the action logs i spot-checked looked reasonable.  Merging this.

**Pull request merged**
