### PR TITLE
Shifted description column

### LINKED ISSUE #1769: Move Description column to next-to-last position
I think the Description column would look better in the next-to-last position, rather than dividing score from opponent (which blend nicely together on the prod site now).

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #1769.

This change is entirely untested.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/939/ (if it passes)

### CODE REVIEW

**Comment by cgolubi1** [comment]
Okay, i'll bring this up, see how it looks, and merge it.

**Comment by cgolubi1** [comment]
Looks like this isn't right in the Active Games table.  I'm not sure why it's right in the others, but never mind that for now:
description_in_wrong_place

**Comment by cgolubi1** [comment]
The same error is present in the Completed Games table as well, unsurprisingly.

**Comment by cgolubi1** [comment]
It's hard to be sure until the other bug is fixed, but it looks like the nbsp in the score column header does fix my linewrapping problem.

**Comment by blackshadowshade** [comment]
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/940/ (if it passes)

**Comment by cgolubi1** [comment]
This looks good.  I'll go ahead and merge it, and if jenkins complains, we'll revisit later.

**Pull request merged**
