### PR TITLE
Added Rush skill, take 3

### LINKED ISSUE #2176: Rush dice
Rush dice have been added in the Kickstarter. Our current knowledge about this skill is directly from James Ernest:

> Rush Dice are exactly like Focus Dice but are worth zero points if you keep them. A small handicap for an otherwise strictly better die type.

My suggestion for the recipe encoding of this skill is to use '#'.

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #2176.

This pull request implements the version of Rush most recently proposed by James Ernest.

This requires a responder test to lock in the behaviour of Rush dice.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1333/

### CODE REVIEW

**Comment by blackshadowshade** [comment]
Note that this is not really testable without the database updates in #2187.

**Comment by blackshadowshade** [comment]
TODO:
- Correctly descend skill interactions from Speed Attacks
- Disambiguate a Default Attack that could be a Rush or Speed Attack in favour of Speed Attack

**Comment by blackshadowshade** [comment]
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1334/ (if it passes)

**Comment by cgolubi1** [comment]
You introduced a PMD warning (unused formal parameter) - http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1334/pmdResult/new/source.0/#145

**Comment by blackshadowshade** [comment]
Let's see if that fixes the pro**lem.**

**Comment by cgolubi1** [comment]
Obviously given the number of logic changes here, i'm going to want to do some replay testing.

**Comment by cgolubi1** [comment]
Okay, i've taken a first stab at RandomAI support for Rush attacks, and stood up a replay site, so we'll see how that goes.

**Comment by blackshadowshade** [comment]
Note to self: this will need to be logically deconflicted from #2214.

**Comment by AdmiralJota** [comment]
After doing a bunch of testing with @blackshadowshade, I'd say that this looks pretty solid. We couldn't find any bugs in it between us. I think it should be merged.

**Comment by cgolubi1** [comment]
Okay, this needs two types of things: one is a deconflict in order to be mergeable, and one is that i need to finish getting the replay testing into shape where i can run it, which i started but never completed.

**Comment by blackshadowshade** [comment]
This has been deconflicted and rebased to one commit.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1342/ (if it passes)

**Comment by cgolubi1** [comment]
So... my current problem in figuring out how to do the replay testing here is kind of a head-scratcher.  You can see the problem if you look at one of the annotated responderTest entries:
```php
        $gameId = $this->verify_api_createGame(
            array(
                0, 5, 0, 2, 3,     // die sizes for r3: 4, 4, 8, 10, 20 (these get sorted)
                $RANDOMBM_SKILL['k'], $RANDOMBM_SKILL['p'], $RANDOMBM_SKILL['n'],
                0, 0, 1, 2, 1, 2, 3,  // distribution of skills onto dice for r3 (one reroll)
                4, 4, 0, 3, 0,     // die sizes for r4: 4, 4, 10, 12, 12 (these get sorted)
                $RANDOMBM_SKILL['h'], $RANDOMBM_SKILL['k'], $RANDOMBM_SKILL['M'],
                3, 0, 0, 0, 0, 2, 0, 1, // distribution of skills onto dice for r4 (some rerolls)
                1, 3, 6, 3, 3,     // initial die rolls for r3
                5, 2, 7,           // initial die rolls for r4
            ),
            'responder003', 'responder004', 'RandomBMMixed', 'RandomBMMixed', 3
        );
```

That's cool, because we wrote that by hand.  But in order to do replay testing, i need to gather die rolls and translate from the number to `$RANDOMBM_SKILL['k']` or whatever when i store, so that the replay will work.  That means i have to figure out which rolls are the skill ones.  I guess that logic looks like:
* I can know how many dice the button should have (based on its name)
* I can know how many skills the button should have (based on its name), and they all have to be distinct, so i just keep counting until i get that many distinct ones
* Distribution of skills onto dice is a bit painful, because for each recipe i have to track both how many dice i distribute the skills onto, and how many dupes are okay, to know how many rerolls.

I mean, i can do that all in replay code, but it's pretty lousy and brittle.  I'm almost tempted to ask for a different die-roller function name to use when choosing skills, so we can instrument it a different way on test sites.

Shadowshade: any preferences about this?  No worries if you have no thoughts, mostly just wanted to update and note what i'm currently blocked on.

**Comment by blackshadowshade** [comment]
I can see the problem here, and I agree that it's not the simplest problem to solve.

What about a different form of createGame for testing, where the skill allocation draws from a different pool of random numbers?

Also, dare I say it, but #2083 may actually make things slightly easier for you, since it will make the counting of zero-values correct.

**Comment by cgolubi1** [comment]
When i get a chance, i'll demo this with a separate `bm_rand()` function for skill selection, and you can see if you think it looks too intrusive to the non-test code.  I think it might not be too bad.

**Comment by cgolubi1** [comment]
I'm actively working on this, and have a branch with my bm_rand() mods to support skill-list-change replay testing now.  I just need to test it and make sure it actually works in a replay context.

**Comment by cgolubi1** [comment]
Whew.  Okay, for those playing the home game, i've now proven that i've fixed the replay regressions from `isChatPrivate` and third-party game creation, so i can get back to the project of instrumenting `bm_rand()` to work for new skill replay testing.

**Comment by blackshadowshade** [comment]
I've rebased this to remove the conflict in the unit tests. @cgolubi1, you'll need to do a fresh deploy of this once I confirm that Jenkins passes.

Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1359/ (if it passes)

**Comment by cgolubi1** [comment]
Okay, where are we?  I got bogged down on this last summer because my replay test rig was in bad shape.  Now it isn't, or at least shouldn't be, so let me try to get this train moving again.

**Comment by cgolubi1** [comment]
Okay, i have a random_ai mod in a working directory which i believe supports Rush attacks.  Hopefully sometime this weekend i'll have a chance to:
* Put up a PR with that mod
* Update the replay site to use that mod and try to get some decent test data

**Comment by cgolubi1** [comment]
I'm pretty happy with the replay testing.  With the already-merged Rush support and the following mod to fix changed skill values, it played at least 4000 novel and replay games without regressions:

```
diff --git a/tools/api-client/python/update_replay_games b/tools/api-client/python/update_replay_games
index 3243e4f..2fc682a 100755
--- a/tools/api-client/python/update_replay_games
+++ b/tools/api-client/python/update_replay_games
@@ -23,7 +23,12 @@ class PHPBMClientOutputWriter(random_ai.PHPBMClientOutputWriter):
   # to succeed), make those overrides here for clarity during testing.
   #
   # As a first resort, trying overriding apply_known_changes_to_game_data()
-  pass
+  def _php_dict_style_rand_str(self, retval):
+    if retval.skill_rand_vals:
+      for i in range(len(retval.skill_rand_vals)):
+        if retval.skill_rand_vals[i] >= 13:
+          retval.skill_rand_vals[i] += 1
+    return random_ai.PHPBMClientOutputWriter._php_dict_style_rand_str(self, retval)
 
 ########################################################################
 # Initial setup
```

The only other thing i want to do is play some novel games with RandomBMPentaskill, to try to find bugs with Rush vs other skills.  That's running now, and should give me enough confidence to merge this by tomorrow.

Anything else we need to test before we can merge this?  I don't see manual testing as particularly germane for this pull --- we can worry about that on the pull which brings in the new sets, which will get much easier to test once this is merged.

**Comment by blackshadowshade** [comment]
I would suggest that we've already done a lot of the manual testing (see @AdmiralJota's comment on 26 May 2017).

**Comment by cgolubi1** [comment]
Still working on it; my test loop got 600 games in and died on a random_ai trip bug (#2329).  There are rush dice in the game, but the mechanic of the bug is obvious and has nothing to do with rush, so i just got unlucky.  Trying again.

**Comment by cgolubi1** [comment]
Okay.  The bad news is that i'm going to have to actually address #2329 if i want to do serious testing with RandomBMPentaskill, but the good news is that i think i feel fine about Rush, and we should merge this PR already, so i'm doing that.

**Pull request merged**
