### PR TITLE
Exclude ApiResponder and DummyApiResponder from PHPDoc targets

### PR DESCRIPTION
**Pull request by blackshadowshade**
Addresses part of #1130.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/735/

### CODE REVIEW

**Comment by cgolubi1** [comment]
Hmm, i definitely agree that we should exclude DummyApiResponder.php, because that's test code which has to be in the non-test tree for implementation reasons.

But why exclude ApiResponder.php - that's part of the user-visible code path, and we should document it IMO.

**Comment by blackshadowshade** [comment]
Okay, I'll change the exclusion to be only DummyApiResponder.php

**Comment by blackshadowshade** [comment]
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/747/

**Comment by cgolubi1** [comment]
Thanks.

**Pull request merged**
