### PR TITLE
Removed "Forum thread: " text from forum links and updated help

### LINKED ISSUE #2460: I can't figure out how to use the forum [forum=1,6]text[/forum] element.
I can't figure out how to use the forum [forum=1,6]text[/forum] element.  This feature is in place, but I can't figure out how to use it.  :(  Is there any way to add help text for it?  Or how about a single help page that describes all the forum elements?  Maybe with the settings help or something.

### LINKED ISSUE #2461: Remove "Forum thread:"
The forum thread link element adds "forum thread: " to any link you create using [forum=n,m]text[/forum].  That makes it awkward to make inline links.  Not everyone wants their links to include the text "forum thread:"  Since the text part of the element lets you put whatever text you want in, including "forum thread", can you please un-hard-code "forum thread" from the forum links?

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #2460. Fixes #2461.

We'll need to test that the relative link I've used here actually works correctly on a deployed server.

### CODE REVIEW

**Comment by cgolubi1** [comment]
Playtesters, check out http://makeshift.dev.buttonweavers.com/ui/ and see if the new forum link behavior looks good.

**Comment by dwvanstone** [comment]
It's all very good, but I have minor changes on the help page.


"When you are posting in a forum, use the [forum] element to link to another forum post. The syntax is [forum=t,p]text[/forum], where text is the text that appears as the link. The number t is the thread id, and the number p is the post id. The numbers appear at the bottom of the post that you want to link to, in the footer of the post, to the left of the Quote button. "

I'd change "in the footer of the post" to "in the footer of the post in a very light color". If you don't know it's going to be in light print you may miss it.


I'm not sure if "If you want to quote another post in the same thread, use the Quote button instead." is quite right. The forum link works fine to go elsewhere on the same page. Perhaps:

"If you want to refer to another post in the same thread, you can either use the [forum] element or simply use the Quote button instead."

**Comment by blackshadowshade** [comment]
Text has been updated, but no rebase yet, so the update goes through easily.

**Comment by cgolubi1** [comment]
Thanks.  Dev site should be updated.

**Comment by cgolubi1** [comment]
This exception wound up in the apache error log on this site:

```
[Mon Dec 21 20:56:51.993492 2020] [:error] [pid 27864] [client X.X.X.X:Y] Wrong number of records returned for forum_thread.id = 93, referer: http://makeshift.dev.buttonweavers.com/ui/forum.html
```

I don't have a theory about why.

**Comment by dwvanstone** [comment]
I created a Forum link to threadid=93 which doesn't exist. I then tried clicking on it. I got the error "Error from loadForumThread: Forum thread loading failed". That seems fine.

It seems reasonable to me.

**Comment by cgolubi1** [comment]
> I created a Forum link to threadid=93 which doesn't exist. I then tried clicking on it. I got the error "Error from loadForumThread: Forum thread loading failed". That seems fine.
> 
> It seems reasonable to me.

Sounds good.  Thanks!

**Comment by blackshadowshade** [comment]
Do I need to do anything more on the forum thread error message? Or is this ready for a rebase?

**Comment by cgolubi1** [comment]
Sounds like this is ready to rebase.  Thanks!

**Pull request merged**
