### PR TITLE
Change "reject" link to "cancel" link for user who created game.

### LINKED ISSUE #1754: when you create a game and are waiting for the other player to decide whether to accept it, "Reject" is confusing
When you create a new game, the "New Games" table gives you the option to "Reject" it.  That's confusing, because you're the one who created the game.  "Cancel" would be clearer.

### PR DESCRIPTION
**Pull request by dwvanstone**
Fixes #1754 

http://jenkins.buttonweavers.com:8080/job/buttonmen-dwvanstone/5/  which will hopefully pass...

### CODE REVIEW

**Comment by cgolubi1** [comment]
If you're implementing it this way, you could duplicate `Overview.formRejectGame()` as `Overview.formCancelGame()`, and change the displayed message that way.

Note that at the moment Jenkins requires a UI test for every function, so if you create a new function, you'll need to create a new test (though it's fine with me if you make the test unimplemented for now, and i can show you how to do that).

Anyway, no obligation, but since you're making the code flow different for Reject vs Cancel, you do open the option of fixing the message without touching the API or backend.

**Comment by dwvanstone** [comment]
Just to add a note here: even though the link says "cancel" the response message says "Successfully rejected game". I'd like to leave it as is and can work on a fix for another release.

**Comment by dwvanstone** [comment]
New Jenkins test:

http://jenkins.buttonweavers.com:8080/job/buttonmen-dwvanstone/6/    (hopefully it passes...!)

**Comment by cgolubi1** [comment]
Okay.  I'm going to just bring this up in vagrant and see if it works for me.

**Comment by cgolubi1** [comment]
Looks to me like this works as advertised - i'm going to tag it "ready to merge" because i want to get shadowshade's okay before actually merging it, since he's actively working on reject-game.

**Comment by blackshadowshade** [comment]
This looks okay, with the proviso that the two remaining issues need to be resolved (probably by @dwvanstone or me) in the near future, namely:
- the message after cancelling
- auto dismiss after cancel

I'm going to merge this, so that I can incorporate it immediately into what I'm doing with the rejected games table.

**Comment by blackshadowshade** [comment]
For info, the remaining issues will be addressed in #1749.

**Pull request merged**
