### PR TITLE
Removed "Any button" option when filters are selected

### LINKED ISSUE #1796: don't show "Any Button" when button restrictions are selected either
We reduced some of the player confusion around the state of #1234 by changing things so that the create game UI no longer displays "Random Button" as an option when you have button restrictions specified.  We should do the same thing with "Any Button" so players don't think they can currently let their opponent pick any button with a given skill/buttonset/etc.

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #1796.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1444/ (if it passes)

### CODE REVIEW

**Comment by cgolubi1** [comment]
This failed some of the QUnit tests.

**Comment by blackshadowshade** [comment]
I've updated and expanded the QUnit tests so we're actually testing something meaningful. I've also rebased.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1445/ (if it passes)

**Comment by cgolubi1** [comment]
Eww, sorry this has been sitting for so long. Let me put up a dev site so we can take a look at it.

**Comment by cgolubi1** [comment]
Irilyth, can you sync up: ephemeral = 54.163.26.189

**Comment by cgolubi1** [comment]
Anyway, this looks fine to me.  Leaving the site up for a day or two for other opinions.

**Comment by irilyth** [comment]
> Irilyth, can you sync up: ephemeral = 54.163.26.189

Done!

**Comment by cgolubi1** [comment]
No other opinions forthcame.  Merging.

**Pull request merged**
