### PR TITLE
Add LotFR flavour text and support accents in flavour text

### LINKED ISSUE #1699: support unicode in button flavor text
We should be able to display Unicode characters as part of the flavor text for various buttons, e.g. Zoe and Paul Erdos.  Figure out how to store Unicode characters in the database source files, load them into the live database on at least vagrant-managed sites, and make sure they display reasonably in browsers.

### LINKED ISSUE #2485: Add flavour text for LoFR buttons
theorgg found the flavour texts for the LoFR buttons, and has cached them here:

https://buttonmen.fandom.com/wiki/Legend_of_the_Five_Rings

Add them

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #2485. Fixes #1699.

This pull request adds the LotFR flavour text.

To support line breaks, I changed the JS to allow rendering of HTML.

Since the change to HTML rendering allows painless support of accents, I updated various flavour texts that should have accents to actually contain them.

This pull request is dependent on #2519, since it requires the increase in column width specified there.

### CODE REVIEW

**Comment by blackshadowshade** [comment]
CircleCI run: https://circleci.com/gh/blackshadowshade/buttonmen/329

**Comment by cgolubi1** [comment]
Holding off on this until 2020 Fanatics is merged; separate out the database change into a different pull if that doesn't suit you, but i think we're pretty close with that one, so it should be fine.

**Comment by cgolubi1** [comment]
Looks like this got dropped.  I think we'd better have a dev site so people can verify that the HTML-format flavor text actually loads.  Also i'd better do a local database test before i forget.

**Comment by cgolubi1** [comment]
There's something wrong with the DB update script.  I'll have to do some parsing of my diff to figure out what it is, but there's some flavor text changes that aren't the same between the two files.

**Comment by cgolubi1** [comment]
Here you go, it's TJB:

```
$ diff ~/buttonmen_db.rebuilt.sql ~/buttonmen_db.updated.sql 
189c189
<   (144,'The Japanese Beetle','(6) (8) (12) (X)',1,1,29,NULL,0),
---
>   (144,'The Japanese Beetle','(6) (8) (12) (X)',1,1,29,'The Japanese Beetle fights for truth, justice, and the American way - as long as it doesn\'t get in the way of his quest for fame and fortune. He likes tall blondes, sexy communists, and beating people up.',0),
2332c2332
< -- Dump completed on 2020-03-26 13:47:03
---
> -- Dump completed on 2020-03-26 13:46:53
```

**Comment by blackshadowshade** [comment]
Right, this has been fixed and rebased.

**Comment by cgolubi1** [comment]
Thanks, that fixed it.  Standing up a dev site now.

**Comment by cgolubi1** [comment]
Irilyth, can you sync up ephemeral  = 54.145.47.176?

Playtesters, take a look at the LotFR and Paul Erdos flavor text, and make sure everything looks fine.

**Comment by irilyth** [comment]
> Irilyth, can you sync up ephemeral = 54.145.47.176?

Done!

```
[23:17:41] irilyth@azazel:/home/irilyth
+$ host ephemeral.dev.buttonweavers.com
ephemeral.dev.buttonweavers.com has address 54.145.47.176

```

**Comment by blackshadowshade** [comment]
The LotFR flavour text is truncated. I believe that the database updates that were applied to master in #2519 were not applied here.

**Comment by cgolubi1** [comment]
Oh, blah, probably because we haven't done a staging/prod release since then.

**Comment by cgolubi1** [comment]
I'm going to tear down this dev site and try again with a new staging DB once i've downloaded one as part of the April release; sorry about that.

**Comment by cgolubi1** [comment]
Okay, round 2: irilyth, can you setup ephemeral == 54.91.44.98?

**Comment by irilyth** [comment]
Done!

```
+$ host ephemeral.dev.buttonweavers.com
ephemeral.dev.buttonweavers.com has address 54.91.44.98

```

**Comment by blackshadowshade** [comment]
Ah! Spotted a typo in the flavour text for Dragon!

"Even if the only teach the use of one sword."

Testers, take a good close look and see if you can spot any other typos lurking in the new flavour texts!

**Comment by blackshadowshade** [comment]
Apart from that, I don't see any problems. I'll add a second database update file now.

**Comment by dwvanstone** [comment]
When I look at Zoe, her description has an umlaut over her name but the name below her button appears without the umlaut. Same with Paul Erdos (with the double acute symbols over the o). It looks inconsistent.

It will take a while to read through the LOT5R text. I'll work on that over the day.

**Comment by blackshadowshade** [comment]
> When I look at Zoe, her description has an umlaut over her name but the name below her button appears without the umlaut. Same with Paul Erdos (with the double acute symbols over the o). It looks inconsistent.

This is not a trivial problem to solve, so I'd suggest filing an issue for it.

**Comment by cgolubi1** [comment]
I think given that we're moving the umlauts-in-button-names business to a different issue, it should be possible to address the rest of dwvanstone's comments and get this merged.  I know it's not hugely consequential, but it seems appealing to keep small PRs moving (pot, kettle, of course).

**Comment by blackshadowshade** [comment]
The whole "periods inside quotes" thing is one of those US vs British English things.

https://www.thepunctuationguide.com/british-versus-american-style.html

Personally, since I use Australian English that follows the British rules, I'm more at home with how it currently is, which is also how I received it---I've not changed anything from the original here.

**Comment by blackshadowshade** [comment]
Or maybe I did, subconsciously? I've gone back to the original source text and it has the periods and commas inside the quotes. I'll shift them.

**Comment by blackshadowshade** [comment]
Okay, I've both compressed the updates into one file (with the punctuation fixes) and rebased this, because I figured that's the safest way. It'll require a redeploy, but it also reduces the update files from three to one.

**Comment by cgolubi1** [comment]
No problem on the redeploy - it turns out the instance is being retired by AWS, so i'd have to do that anyway.  I'll get to it soon!

**Comment by cgolubi1** [comment]
New dev site is up.  irilyth, can you resync ephemeral == 3.235.98.184?

**Comment by cgolubi1** [comment]
Reminder to self: i haven't actually redone the update-vs-reinstall test on this version.

**Comment by blackshadowshade** [comment]
The dev site looks good to me!

**Comment by dwvanstone** [comment]
These look good to me too.

What does irilyth "resyncing ephemeral" do? I assume I can just use the IP address without having an official name to resolve, yes? (I'm not sure if I'm supposed to start testing with just the IP address...)

**Comment by blackshadowshade** [comment]
It's just a convenience measure, more for test sites that we need loads of testers on. Testing via the IP address should be fine.

**Comment by irilyth** [comment]
Indeed, and it's increasingly hard for me to do them during the day, because my employer's VPN no longer lets me talk to my home network while I'm connected to work, so I have to remember to do it before or after work, which, as you can tell, I often don't. :^p

But, I did this one:

```
+$ host ephemeral.dev.buttonweavers.com
ephemeral.dev.buttonweavers.com has address 3.235.98.184

```

**Comment by cgolubi1** [comment]
Doing the database test as soon as i can, and if it's fine, i'll merge this.

**Pull request merged**
