### PR TITLE
Push changes from master to staging on 2021-01-18

### PR DESCRIPTION
**Pull request by cgolubi1**
This update brings these approved pulls to the staging branch:

* User-visible:
    * #2594: fix Morphing Maximum logic bug
    * #2583: allow third-party creator to cancel games
    * #2631: fix incorrect Durak666 recipe on button art
    * #2635, #2639: improve game action logging around size-changing dice and trip attacks
    * #2632: add text to "about this site" page
    * #2633: flavor text for ZOECon buttons
    * #2642: images for MegaTokyo buttons
    * #2647: update Mississippi button art
    * #2663: trim username field on password reset page
    * #2651: better warning message when not changing chat text
    * #2648: images for Las Vegas buttons
    * #2646: visually indicate dice which are irrelevant for initiative
    * #2649: remove "Forum thread: " text from forum links
    * #2655: during game creation, make selected button persistent on filter change
    * #2691: copyright year is 2021
* Ideally not user-visible:
    * #2630, #2643, #2674, #2688, #2690: improve consistency of casting numeric arguments to int at the API and database layers
    * #2634, #2656, #2680: updates to stats and python scripts in codebase
    * #2650: improve try/catch blocks on interface functions
    * #2671, #2686: handle invalid API args better
    * #2654, #2684: noop flavor text changes to improve MAMP testing

Database updates:
```
UPDATES="02627_zoecon_flavour_text_01.sql 02653_mysql_semicolon_01.sql 02653_mysql_semicolon_02.sql"
SCRIPTS=""
```

Once this pull is merged, i will load the changes on staging.buttonweavers.com as part of #2694.

### CODE REVIEW

**Comment by cgolubi1** [comment]
So this PR says it can't be merged because there are conflicts in bmapi.py and bmutils.py.  I'm pretty sure this isn't the first time this has happened, but i can't immediately find the record of the previous time, so i'm just going to muddle through it.

**Comment by cgolubi1** [comment]
Merging, and i'll load this on the staging site.

**Comment by cgolubi1** [comment]
I had to fix ui/js/Config.1611008307.js by hand --- the issue contines to be that the sed commands in ./modules/buttonmen/manifests/init.pp don't include the follow-links flag.

**Comment by cgolubi1** [comment]
Can folks check out the staging site?  Basically this should just be a bunch of changes you've already looked at and some art.  Given the number of under-the-hood changes, i'd love it if people would play one or two actual games.  If you want some skills to include, how about trip attacks and mood or morphing dice?  All of the changes were tested individually, and most of them have been in the code base for awhile, so i think we're just looking for unexpected large blowups.

**Comment by blackshadowshade** [comment]
Gee, that *is* a lot of individual changes.

**Comment by dwvanstone** [comment]
> Can folks check out the staging site?

**Comment by cgolubi1** [comment]
Yes, that's right.

**Comment by blackshadowshade** [comment]
Taking a look at staging, I see the following:
- I can cancel third-part games that I have created
- Durak666 recipe on button art is correct
- "about this site" page is correct
- flavor text for ZOECon buttons is correct
- images for MegaTokyo buttons are correct
- image for Mississippi is correct
- username field on password reset page now trims correctly
- warning messages make sense when not changing chat text
- images for Las Vegas buttons are correct
- dice which are irrelevant for initiative are correctly greyed out
- forum links now have no preface text
- during game creation, selected button is now persistent on filter change
- copyright year is correct

To come: testing the morphing maximum bug; and game action logging for trip attacks of size-changing dice

**Comment by blackshadowshade** [comment]
Morphing maximum bug looks like it's correctly fixed.

**Comment by blackshadowshade** [comment]
Trip logging looks like it's working fine for mighty and mood:

trip_logging

**Comment by blackshadowshade** [comment]
There were no unexpected errors in my testing, so a cursory attempt to start games, play turns, and finish games seemed to work.

**Comment by cgolubi1** [comment]
Thanks for testing, Shadowshade, and sorry to be so slow to wrap this up!

**Pull request merged**
