### PR TITLE
Fixed determination of possible attack types in the presence of optional attacks

### LINKED ISSUE #1538: in a warrior game, i wasn't allowed skill as an option
In the previous state of this game, i selected my first five dice:
```
(1):1, (2):1, z(12):1, z(20):10, `(4):4
```

and irilyth's first die `z(15,15):17` and clicked "Beat People UP!", and it told me there was no valid attack.
post_no_skill_offered

The pulldown did not offer me Skill as an option, only Power and Speed.

I submitted the attack successfully using python:
```python
d = b.load_game_data(1472)
r = b.submit_turn(1472, 0, 1, {
  'playerIdx_0_dieIdx_0': 'true',
  'playerIdx_0_dieIdx_1': 'true',
  'playerIdx_0_dieIdx_2': 'true',
  'playerIdx_0_dieIdx_3': 'true',
  'playerIdx_0_dieIdx_4': 'true',
  'playerIdx_0_dieIdx_5': 'false',
  'playerIdx_0_dieIdx_6': 'false',
  'playerIdx_0_dieIdx_7': 'false',
  'playerIdx_1_dieIdx_0': 'true',
  'playerIdx_1_dieIdx_1': 'false',
  'playerIdx_1_dieIdx_2': 'false',
  'playerIdx_1_dieIdx_3': 'false',
  'playerIdx_1_dieIdx_4': 'false',
  'playerIdx_1_dieIdx_5': 'false',
}, 'Skill', 1, d.data['timestamp'])
```

and now the game is in the state shown.  So the bug is that the API and/or UI didn't offer "Skill Attack" as a valid option during loadGameData.

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #1538.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/643/

### CODE REVIEW

**Comment by cgolubi1** [comment]
This has a merge conflict now.

**Comment by cgolubi1** [comment]
Okay, what do i want to test here?
* I know the case we came up with for the test works now, because the test passes, so nothing to do there
* I should manually play two scenarios in which Pass is the only option, one involving Warrior dice and one not, just to make sure
* I should run some regression tests using my existing corpus of pre-Warrior games, since nothing should have changed about that scenario
* I should generate some tests using master prior to this pull, and play them back.  There *should* be changes to those tests, and i should make sure those changes correspond to instances of this bug which are now fixed

**Comment by blackshadowshade** [comment]
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/645/ (assuming it passes)

**Comment by blackshadowshade** [comment]
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/646/ (assuming it passes)

**Comment by cgolubi1** [comment]
Approximately half of the warrior regression tests failed (48/99), and all of the failures were because the old game didn't offer 'Skill' as an option in the valid attack type array, and the new game did.  A representative example:

```
31) responderTest::test_interface_game_00058
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
         0 => 'Power'
-        1 => 'Berserk'
-        2 => 'Shadow'
+        1 => 'Skill'
+        2 => 'Berserk'
+        3 => 'Shadow'
     )
     'activePlayerIdx' => 1
     'gameSkillsInfo' => Array (...)
     'gameActionLog' => Array (...)
     'maxWins' => 3
     'playerDataArray' => Array (...)
     'currentPlayerIdx' => 0
 )

/buttonmen/test/src/api/responderTest.php:725
/buttonmen/test/src/api/responderTest.php:27140
```

This is exactly what i'd expect if the bug were fixed and no new bugs introduced.  So that's a good sign.

**Comment by cgolubi1** [comment]
Okay, the rest of my tests look fine.  Merging.

**Pull request merged**
