### PR TITLE
Adding a help link

### PR DESCRIPTION
**Pull request by blackshadowshade**
This starts to address part of #137.

Currently, the pull request is incomplete, and I'd like input (and help) before I push this through to completion. I'll attach a screenshot as the first response so that it's easier for people to start commenting.

@cgolubi1, is this going in roughly the right direction, and what sort of testing should we be doing here? @AdmiralJota, how would you make this look nicer? Everyone, what do you think about the text (which comes directly from #1149)?

Of course, there is also text there that will probably be commented out (because the pages don't already exist). I'm happy to also accept comments about obvious stuff like that.  :)

### CODE REVIEW

**Comment by blackshadowshade** [comment]
Screenshot:

help

**Comment by blackshadowshade** [comment]
For information, the intent is to shorten the text at the bottom, below the footer nav bar, once we have appropriate links in the footer nav bar.

**Comment by AdmiralJota** [comment]
My first thought is that centered text like that is a bit hard to read. It works well for most of our UI, since most pages are full of interactive elements or tabular data, but paragraphs of text work better when they're left justified.

On the other had, just making the whole page (aside from the headers) left justified would look really weird and would go against the aesthetics of the rest of the site.

Two ideas come to mind as potential compromises: 

One would be to have a container that's narrower than the page (maybe give it a max-width of something between 600-800 pixels -- you'd have to experiment to see what looks good), center *that* on the page, but left justify the text inside of it.

Another would be to split the content into two columns: "Site-specific info" on the left, "General info about Button Men" and "Developer info" on the right, left justifying the text within each column.

Unfortunately, I don't have access to the help page itself at the moment, so I can't mock up any examples of these. But between the two, I think I'd lean towards the first idea for several reasons: it's closer to our other pages' layouts; columns can be fiddly with HTML/CSS; we'd have to decide how we wanted the widths of the columns to work; narrower screens might not be two-column-friendly (e.g. mobile devices); we'll probably be adding/removing info from these sections, so we might have to rethink which sections wound up in which column... The only benefit to doing columns I can think of is saving vertical space, which might not matter on this page.

In either case, I think it might look nice to have something like "border-left: 1px solid #cccccc; border-right: 1px solid #cccccc;" on whatever container we use for our text, whether it's a narrowed central column or two columns (and a gutter -- i.e. margin-right on the left column and margin-left on the right one -- between the two columns, if we try that). But that's only a guess; I'm not really sure without seeing it mocked up.

**Comment by blackshadowshade** [comment]
Jota, here's a dump of the help page, for your convenience:

https://gist.github.com/blackshadowshade/5349fa4c86086e59aaac

**Comment by AdmiralJota** [comment]
How does this look?

bm

I did that by adding a "help_column" class to the div that contains the three help section divs (which I think is the one you define on line 32), and then adding this CSS:

    div.help_column {
        border-left: 1px solid #cccccc;
        border-right: 1px solid #cccccc;
        display: inline-block;
        padding-left: 30px;
        padding-right: 30px;
        width: 640px;
    }

    div.help_column p {
        text-align: left;
    }

As a side note, with the extra line of footer, I now need to scroll down to see it all.

**Comment by AdmiralJota** [comment]
Also, the footer with the link to this page is visible to people who aren't logged on (including ones who haven't even signed up yet). Will this page load for them? What about the pages that it links to?

**Comment by blackshadowshade** [comment]
I think that things in the footer *should* be visible to people who aren't logged on, since things like the copyright statement and the privacy policy are there. Whether they currentely *are* visible is something I hadn't yet considered, but it should be possible to add these pages to our list of pages that can be viewed without being logged in.

**Comment by blackshadowshade** [comment]
Regarding the size of the footer, I'm pretty sure that once we include the Help link, we can reduce the amount of text below the new footer line to one line at most, possibly only the copyright information.

**Comment by blackshadowshade** [comment]
I think the general look of the help page now matches what I would expect to see. Thanks, Jota!

Regarding the content, I think that we need to be more verbose about where players can go to find the rules and strategy for Button Men (even though the links are there currently). Also, I'd love for people to start writing meaningful stubs for some of the linked pages that currently don't exist.

**Comment by AdmiralJota** [comment]
Oh, one thing I forgot: the "width: 640px;" should probably be "max-width: 640px;", for people with already narrow displays.

**Comment by AdmiralJota** [comment]
> Also, I'd love for people to start writing meaningful stubs for some of the linked pages that currently don't exist.

Which of those links are to pages that do exist, and which are to pages that don't?

As for the skills list, I assume we're going to want that to be dynamically generated. I think the old site had a list of skills (with their symbols) at the top, with each one being a link to an anchor later on down the page where the full description was, in alphabetical order. It seems reasonable to do something similar here. Also, I think our skills page should also include special die types like swings and WildCard and so on, since novices who don't know skills also probably won't know the range of an S swing. (Heck, *I* don't know the range of an S swing.)

**Comment by AdmiralJota** [comment]
Since there's already a link to the main forum page in the first section, should the forum link in the last section link directly to "forum.html#!boardId=3", since that's the most relevant board for development stuff?

**Comment by AdmiralJota** [comment]
I've added #1925 as a suggestion for skills.html.

**Comment by cgolubi1** [comment]
Let me stand up a dev site for this to remind us that it exists, and give people something to click around on and make suggestions.

**Comment by cgolubi1** [comment]
irilyth: can you sync up helplink == 54.80.141.90

**Comment by irilyth** [comment]
Done! Also, FWIW, my process has changed enough that I no longer care about reusing names, so if using a different name for each dev site (or for some dev sites, or whatever) would serve your purposes, feel free.

**Comment by blackshadowshade** [comment]
Thanks for putting up a dev site for this, @cgolubi1. I think that will help a lot to advance this pull request.

**Comment by dwvanstone** [comment]
(Quick fix: thetwo links to the "forums" link should go to ui/forum.html and not forum.html)
(Quick fix # 2: the link to Button Men should be https://cheapass.com/button-men/ )

When I haven't logged in yet, when I click on Help on the bottom it says "You must be logged in in order to view this page." 

I wonder if it really is a footer item. I tried going in as a new user and it's still lost in the footer. Maybe it could float right in the upper right corner? I think it should be in the header. 

Since every page has the copyright info in the footer, I'm not sure we need the "General Info about Button Men." The link to Spindisc's strategy article would fit in better in the Wikia page, as would anything about the history of the webpage.

The centering of the text on the page looks awkward to me. 

Great start!

**Comment by blackshadowshade** [comment]
Okay, reminded by @nkmcalli, this pull request has gone very very stale.

I'll try to address @dwvanstone's issues this weekend.

However, are people generally okay with this approach or not?

**Comment by blackshadowshade** [comment]
Actually, considering that the deployed site is three years old, I'll need to rebase this and we'll need to get it redeployed before it's worth properly testing. I'll put out another call to test once I've got the changes in requested by @dwvanstone.

**Comment by blackshadowshade** [comment]
I've put a few hours of work into this, and we now have a help page with QUnit tests that pass.

I'd like this to be redeployed so that testers can have another look at this.

Also, I'd like opinions on what we do with the as-yet-unwritten stubs (e.g., the tutorial and the FAQ): comment them out, create stub pages, write skeleton pages, write basic first drafts, etc.

**Comment by cgolubi1** [comment]
My off-the-cuff comment is that stub pages sounds good --- create an issue to populate each page, and have each stub link to that issue, so it's easy for players to let us know they went looking for a page by +1-ing the issue.

**Comment by cgolubi1** [comment]
Redeployed the site: irilyth, when you get a second, can you sync up the DNS: helplink -> 54.226.121.85

**Comment by cgolubi1** [comment]
irilyth, when you get a second, can you sync up the DNS: helplink -> 54.226.121.85

**Comment by irilyth** [comment]
Done! (Sorry for the delay; IT wiped my laptop and I'm still recovering non-work-related things, like Button Men tools and AWS keys and such.)

**Comment by dwvanstone** [comment]
I think this looks good. It could be that, after the FAQ is written, some elements should be pulled onto this page, or some pages could link to the FAQ. But this is still a great start.

I'd be happy to work on contents of a page, but would want someone else to review and actually check it in to the system.

**Comment by cgolubi1** [comment]
Sure, we (speaking for Shadowshade somewhat) would be more than happy to fold your text into a pull request.

**Comment by blackshadowshade** [comment]
Stub files have been added, and new issues have been created for each extra stub file.

Once CircleCI is happy with the new code, this should be ready for updating.

**Comment by cgolubi1** [comment]
Okay, i've finally updated the helplink dev site.  I think what we want from reviewers right now is:
* Does what's here look good?
* Which if any of the stubs need to be populated before this can be merged?  ("None" is a fine answer, like, maybe it's fine to merge with the stubs as now to keep momentum; i'd be fine with that afaik.)

**Comment by dwvanstone** [comment]
I think this looks great! It cleans up the footer (less text overall).

The stubs could simply be ... wait, they already are! This is excellent and can be merged as is.

**Comment by dwvanstone** [comment]
> The stubs could simply be ... wait, they already are! This is excellent and can be merged as is.

I meant to note that the stubs could be filled in with a blank "under construction" page which they are. Nice!

**Comment by cgolubi1** [comment]
Okay, cool.  I say we go forward with this --- shadowshade, any reason not to rebase this and then we can merge it?

**Comment by blackshadowshade** [comment]
I've rebased this, and I assume that CircleCI should be fine with it.

**Pull request merged**
