### PR TITLE
Update page title in forum topic

### LINKED ISSUE #1684: make forum topic visible from the bottom of the page
This is just a thought, and i'm open to ideas --- when you get taken to the end of a long thread by clicking the "New Post" link, you go to the end of the thread, and thus it may not be obvious what the thread is.  That seems non-ideal.

What if we repeated the thread topic banner at the bottom of the post?  Alternately, maybe we could put the thread topic in the page title?

### PR DESCRIPTION
**Pull request by dwvanstone**
Fixes #1684 by putting the forum topic in the page title.

For consistency, I also added forum board title to the page title when on a specific board.

Tested on Chrome, Firefox, & Safari on my Mac. Did not test on any mobile devices. Note that most of the time the forum topic is not visible because the page title is truncated on tabs. 

http://jenkins.buttonweavers.com:8080/job/buttonmen-dwvanstone/10/

### CODE REVIEW

**Comment by cgolubi1** [comment]
Okay, i think all i have to do here is bring this up in vagrant and try it out and see if it looks basically reasonable and seems to solve the issue.

**Comment by cgolubi1** [comment]
Hmm, i see an issue: if i do this:
* Click on "Forum" in the top bar (now the page title is "Button Men Online - Forum")
* Click on "Tournaments" in the table (now the page title is "Button Men Online - Forum: Tournaments")
* Click on "Forum" in the top-left of the table

then i'm back at the top-level forums page, but the page title is still "Button Men Online - Forum: Tournaments".

So that "Forum" label in the top-left of the forums table needs to somehow get the page title explicitly set.

**Comment by dwvanstone** [comment]
Okay - I'm on it!

**Comment by dwvanstone** [comment]
This is fixed, assuming Jenkins passes:

http://jenkins.buttonweavers.com:8080/job/buttonmen-dwvanstone/14/

[Great catch!]

**Comment by dwvanstone** [comment]
I have another branch coming later which will supercede this one, so I'm closing it.

**Pull request closed without merging**
