### PR TITLE
Added new script buttons-with-skills for getting a list of the buttons with a set of skills

### PR DESCRIPTION
**Pull request by irilyth**
http://jenkins.buttonweavers.com:8080/job/buttonmen-irilyth/51/ (if it passes)

### CODE REVIEW

**Comment by cgolubi1** [comment]
```
leocrotta,[~/src/git/cgolubi1/TEST-buttonmen-utton-scripts/tools/api-client/python],20:30(0)$ ./buttons-with-skills Trip Weak
WARNING: Unknown skill specified (Trip), ignoring
WARNING: Unknown skill specified (Weak), ignoring
ERROR: No known skills specified, exiting
leocrotta,[~/src/git/cgolubi1/TEST-buttonmen-utton-scripts/tools/api-client/python],20:30(1)$ ./buttons-with-skills t h
ABCGi: %Ho(1) pdw(7) mhv(13) zkt(23) (X,X)!
CestWhat: p(2) sf(12) sz(20) pho(8,8) t(T,T)!
Da Pimp: t(4) (8) (12) (20) wHor(4) wHor(4) whor(20) whor(20)
Dr. Jekyll: (X)? (X)? r^(20) rvkt(20) rsfp(20) rhop(20)
North Carolina: pF(10) o(10) (V)! gt(V) h(V)
leocrotta,[~/src/git/cgolubi1/TEST-buttonmen-utton-scripts/tools/api-client/python],20:30(0)$ ./buttons-with-skills trip weak
ABCGi: %Ho(1) pdw(7) mhv(13) zkt(23) (X,X)!
CestWhat: p(2) sf(12) sz(20) pho(8,8) t(T,T)!
Da Pimp: t(4) (8) (12) (20) wHor(4) wHor(4) whor(20) whor(20)
Dr. Jekyll: (X)? (X)? r^(20) rvkt(20) rsfp(20) rhop(20)
North Carolina: pF(10) o(10) (V)! gt(V) h(V)
leocrotta,[~/src/git/cgolubi1/TEST-buttonmen-utton-scripts/tools/api-client/python],20:31(0)$ 
```

So that first one is not a good user experience, and it's trivial to fix by lowercasing the stuff in args.skills before you look for it in the map.

Mind making that change, then i'll merge this?

**Comment by cgolubi1** [comment]
Note: since i'm not loading a dev site, there's no need to go two iterations --- you can go ahead and make that one change and rebase in one go.

**Comment by irilyth** [comment]
Whoops, yep, I forgot to test everything after refactoring that stuff. Fixed!

http://jenkins.buttonweavers.com:8080/job/buttonmen-irilyth/52/ (if it passes)

**Comment by cgolubi1** [comment]
Looks good; merging.

**Pull request merged**
