### PR TITLE
Added new sets: The Core, West Side, Delta, Uptown

### PR DESCRIPTION
**Pull request by blackshadowshade**
Addresses part of #2186.

Requires database updates 02186_kickstarter_01.sql

### CODE REVIEW

**Comment by cgolubi1** [comment]
The tests that count the number of buttons and sets failed.  But i can load this on a dev site anyway.

**Comment by blackshadowshade** [comment]
New button sets added, The Core updated.

I've added a new update file 02186_kickstarter_02.sql

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1319/ (if it passes)

**Comment by blackshadowshade** [comment]
When deploying this, if you're happy with the implementation of Rush dice, you might want to merge that branch also into the deployment.

**Comment by AdmiralJota** [comment]
Shouldn't the duplicate button names (like Tony and Steve) have a space before the parenthesis? E.g., "Tony (The Core)", not "Tony(The Core)"?

**Comment by blackshadowshade** [comment]
If you look at Carson(p) or some of the other duplicates, I believe that they have no space.

**Comment by blackshadowshade** [comment]
Thanks, Chaos.

If anyone wants to proof-read the recipes for me, that would be much appreciated. Basically, compare the recipes in #2186 to the recipes on the dev site.

**Comment by irilyth** [comment]
One difference is that the other parenthesized parts are just one or two letters, and  don't have spaces in them. I don't think it matters so much for the dev site, but we might want to stick to that in the long run. (Or, if we don't, I think "Tony (The Core)" looks better than "Tony(The Core)".)

**Comment by AdmiralJota** [comment]
> If you look at Carson(p) or some of the other duplicates, I believe that they have no space.

Good point. Added #2196.

**Comment by AdmiralJota** [comment]
The only thing I spotted in proofreading is that #2186 has "Lady B 4-8-8-20-X", but the SQL just calls that button "Lady" (without the "B").

**Comment by blackshadowshade** [comment]
Good catch. I'll fix that in the next database update.

**Comment by blackshadowshade** [comment]
The new changes have been captured in the next database update file.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1323/ (if it passes)

**Comment by cgolubi1** [comment]
Just as a heads-up: i'm not fully keeping up on update-vs-rebuild testing of the DB files for this; for now i'm just assuming they're right, and i'll do the update-vs-rebuild testing all at once before merging it when we're done.

**Comment by blackshadowshade** [comment]
I've updated the recipes in the West Side.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1337/ (if it passes)

**Comment by cgolubi1** [comment]
What's the status of this pull?  We're not going to merge it until the buttons are finalized, presumably, which probably means until James Ernest's kickstarter actually ships.  Is there anything we should be doing in the mean time?  Should people be playing games and providing feedback, or are we kind of in a holding pattern?

**Comment by blackshadowshade** [comment]
I think the next step would be to play with the images that we have and come to a consensus about how we intend to proceed with those. Do we use round images, or are we also okay with rectangular card images? That sort of thing.

**Comment by blackshadowshade** [comment]
I've updated the ids of the buttons and sets to take the new Steven Universe set into account.

**Comment by blackshadowshade** [comment]
So, when I use the files that Kaori sent me, the first (replacing Avis's image) sized to 103 x 150 px, the second (replacing Bauer's image) sized to 150 x 217 px, we get the following:

rectangular

Obviously, the images are not showing at the correct height, so I'll need to work out how to specify the image size based on height instead of width. This should help to address #1950 also.

**Comment by blackshadowshade** [comment]
After changing Game.js, line 2818 from width: 150 px to height: 150 px, the new layout looks like this:

rectangular2

What do you all think about the rectangular card image in this layout?

**Comment by AdmiralJota** [comment]
That looks good to me.

**Comment by irilyth** [comment]
I asked the Cheapass folks if they had art they could share with us, and Cassidy Werner sent me these two images:

buttonartexample
cardartexample

What do we think of those?

**Comment by blackshadowshade** [comment]
These images look great, and I think that we can certainly turn these sorts of images into the correct format and size very quickly.

**Comment by irilyth** [comment]
Should I ask for both, or do we only want the round ones, the better to match the rest of the site?

**Comment by blackshadowshade** [comment]
So, if they have all the pics as round ones, they'd be great.

The only work needed to deal with the round ones is to:
- crop
- change white to transparent, and
- scale down to 150 x 150 px

Pretty easy, and any number of our very talented users should be able to do this for us.

**Comment by blackshadowshade** [comment]
Oh, if we want pseudo reflections, they shouldn't be too difficult to add either. I believe @Hurtay has a method for adding those.

**Comment by irilyth** [comment]
Cool, I've followed up saying that we're interested in the round images, will keep ya posted!

**Comment by AdmiralJota** [comment]
Is all that stuff something that someone can script easily? If not, it seems like a lot of work to do it for every button.

Personally, I think either version would work fine: the circles are more consistent with the rest of the site, but the rectangles are less work, have about the same actual image area (once you subtract the transparent pixels), and give a little visual distinctiveness to the new sets. So I could be happy either way.

**Comment by blackshadowshade** [comment]
I've done a bit of skimming of Google results, and it seems to me that such scripting could be done using something like Adobe Photoshop. Once we get the images, I'll have a chat to @Hurtay about possibly running a uniform script over all of them.

**Comment by irilyth** [comment]
ImageMagick can also do some of this sort of thing. Whoever has the time and interest, I'm sure they can find a tool that they like.

**Comment by AdmiralJota** [comment]
How will we handle it in the meantime? Just upload them raw?

**Comment by blackshadowshade** [comment]
No, we just send the files to whoever want to do the image processing, and they send me the finished product to add to the pull request.

**Comment by Hurtay** [comment]
I don‘t know anything about scripts and I‘m not sure if my old version of photoshop can do them. But I can crop them by hand. It‘s not very much work, most of all will be the time I have to wait for my slow laptop to do what I‘ve asked it to do.

**Comment by irilyth** [comment]
Hey, so I've got a zip file with sixty 937x937 button images, courtesy of Cassidy Werner at Cheapass Games. They say they'd prefer if the zip file didn't get shared around publicly, but it's fine to have 150x150 versions of all the images at Github.

I can convert them to 150x150, and put them on a PR, and let @Hurtay take it from there; or hand off the whole zip file (one way or another) and let @Hurtay take it from there.

Any preferences?

**Comment by irilyth** [comment]
The whole zip file is 34 MB BTW.

**Comment by Hurtay** [comment]
I prefer to work with the best quality you have. I‘ll send you my email address via ingame chat.

**Comment by irilyth** [comment]
I probably have your address from Mad Robin, unless you'd rather I use a different one for this.

I can probably e-mail you a 34 MB .zip attachment, but if that fails, we can come up with something else I'm sure.

**Comment by Hurtay** [comment]
@blackshadowshade I‘ve sent you the images. They are cropped, with transparent background, 150 px scale, shadow and light reflex for each of the 60 buttons.

**Comment by blackshadowshade** [comment]
They look superb! Okay, it's on my plate now, I'll see if I can get everything together right now.

**Comment by blackshadowshade** [comment]
Oh, one question. I don't see Mutton Bob anywhere. Was his image provided?

**Comment by blackshadowshade** [comment]
One other question, possibly for a future pull request: Do we have the flavour text for these new buttons?

**Comment by blackshadowshade** [comment]
Oh, just a reminder that the code from #2210 (Rush) will need to be also deployed to this dev site if we want the recipes to be playable.

**Comment by blackshadowshade** [comment]
A third question: Is the name of the Delta set "Delta" or "The Delta"?

**Comment by Hurtay** [comment]
In the zip-archive of the images the set was called „The Delta“. And Mutton Ben was not among them.

**Comment by irilyth** [comment]
On the cards, it's "The Delta" (and "The Core").

**Comment by blackshadowshade** [comment]
Okay, the button set name has been updated and the pull request rebased.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1456/ (if it passes)

**Comment by cgolubi1** [comment]
My physical set of buttons arrived within the past couple of days, so i can fill in the flavor text *at some point* if no one beats me to it.  But i think it would be fine, perhaps even good, if someone beat me to it.

**Comment by blackshadowshade** [comment]
I'd be happy to get this pull request approved without flavour text, and to add the flavour text some time later.

**Comment by irilyth** [comment]
I've followed up with Cassidy Werner at Cheapass Games to ask about Mutton Ben.

**Comment by blackshadowshade** [comment]
Okay, a status report from my end:
- I'm going to update all the button names here to use full names, certainly first name and surname. The question here is what constitutes a full name. For example, one of the button names is

> "Thick" Tony DeLuca

So, would you expect the nickname to appear in the button name on the site?
- Chaos has made a start on flavour texts and since I also have a physical copy of the cards, I can work on this too. I'll be adding these as I can.

**Comment by blackshadowshade** [comment]
Oh, one of the other button names is

> Captain Stephen Send

So does the title also get added to the button name?

**Comment by irilyth** [comment]
I think it's ok that the full name doesn't match the button art.

I have mixed feelings about the full names. I don't mind Captain Stephen Send, but I don't like the double-quotes in "Thick" Tony DeLuca. :^p Blah.

**Comment by cgolubi1** [comment]
HMM, can i pause us for a sec and ask what the rationale for using full names is?  I definitely think the full names should appear in the flavor text, but the physical buttons in the new set have short names, and IMO short names are much more like what we do for other buttons on the site.

Can someone recap the pro-full-names argument?

**Comment by irilyth** [comment]
Many of the short names are duplicates of names of other buttons. Do we add a suffix to some or all of these? Some or all of the other ones, since these or more official? Using full names seemed like a good way to disambiguate.

**Comment by cgolubi1** [comment]
Hmm.  I feel like suffixes are pretty time-honored on the site.  What's in the PR right now looks pretty good, modulo that there should be a space before the '(' IMO.

**Comment by blackshadowshade** [comment]
Good catch on the spaces, @cgolubi1. I'll update the PR now.

As for the full name idea, I agree that it seemed like a good idea initially, but the corner cases (quotes indicating nicknames) and mismatches with the actual names on buttons make it problematic for me.

We can think about this more, but I'm happy to deal with that in a future pull request if people feel strongly about the issue. For the moment, I'll leave the names the way they are.

**Comment by blackshadowshade** [comment]
PR updated and rebased.

Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1462/ (if it passes)

**Comment by cgolubi1** [comment]
Okay, sorry so sloooow on this.  Given all the changes and rebases, and now that we have Rush merged, i'm going to rebuild this dev site now.

**Comment by blackshadowshade** [comment]
Cool. The flavour texts will be following in another pull request, when I get around to it.

**Comment by blackshadowshade** [comment]
Actually, thinking about it, it's probably easier to just update this pull request with a standard commit including the new flavour texts. Once we're okay with the content, I can always do another rebase later.

**Comment by blackshadowshade** [comment]
Okay, hit a problem. We haven't yet resolved #1699, and we have a number of umlauts and other accents in the flavour texts. Suggestions?

**Comment by blackshadowshade** [comment]
@cgolubi1, FYI, I've also added the flavour text for the characters in the funvelope. All flavour texts are now in 02186_kickstarter_02.sql only, and I won't put them in data.button.sql until we decide what to do about the accents on the letters.

**Comment by cgolubi1** [comment]
Oops.  Well, let's not boil the ocean: my suggestion:
* make a version without the accents for now, so we can merge something and make this not a blocker
* prioritize #1699 when we can, because it's the 21st century, yeesh (::sheepish::)

**Comment by blackshadowshade** [comment]
Cool, I'll deal with this in the next couple of hours then.

**Comment by blackshadowshade** [comment]
Right, flavour texts should now have no accented characters, and a couple of typos have been fixed. I've also added the flavour texts to data.button.sql, so you should be able to do a build/update database comparison.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1468/ (if it passes)

**Comment by cgolubi1** [comment]
Okay, this site should be rebuilt --- irilyth, can you sync up the 'kickstarter' CNAME to 54.80.3.173?

**Comment by irilyth** [comment]
Done!

**Comment by blackshadowshade** [comment]
Hmmm, I don't see any of the new sets.

**Comment by cgolubi1** [comment]
Blech, sorry.  Try now.

**Comment by blackshadowshade** [comment]
Much better!   :)

**Comment by cgolubi1** [comment]
Okay, where are we?  Shall we merge this?  Anyone have any reason we shouldn't merge this?

**Comment by cgolubi1** [comment]
I say we merge this!  Shadowshade, want to rebase it down to one commit?  Everyone else, you've got a day to complain if you think we're not ready.

**Comment by blackshadowshade** [comment]
Jenkins can't connect to Github for some reason.

**Comment by cgolubi1** [comment]
Oh, drat.  FWIW, my intention was that only the stuff after the colon
would be included in the flavor text.  I put the bit before the colon
in my e-mail just so shadowshade would know which button was which.

Chaos

**Comment by blackshadowshade** [comment]
I chose to include the name for every button in these sets because they're not always present in the flavour text.

If people prefer that I leave the names out, I am happy to do so.

**Comment by blackshadowshade** [comment]
Incidentally, Jenkins is still unable to connect to Github.

**Comment by dwvanstone** [comment]
Does anyone else have any opinions?

I would propose using the full name in the beginning of the description only in the cases where the full name is not in the description. (Otherwise there's no way to see the full name, which is part of the flavor.)

So in my previous examples:

"Felicia Honora believes in the immutable tenets of objectivist capitalism and can make ten million dollars disappear with a pencil. She likes whales, absolute silence, and beating people up."

"Doctor William J. Fret has a bag of tools that you do not want to see. He likes patience, surprises, and getting to the truth, and he likes to beat people up."

"Gilroy Grimes: Gilroy is a drunken goofball who will cut you like a pack of cards. He likes the wee hours, cheating at pinochle, and beating people up."

**Comment by AdmiralJota** [comment]
I don't have a *strong* opinion about this, but I think my ideal preference would be to A) keep them all consistent, and B) keep all the info that's on the card. So if they all have full names on the back of the card, and that full name doesn't always appear elsewhere in the flavor text or the button name, then I think it would be best to include it consistently for all of them.

That said, the "Full Name: Flavor text." format might not be our only option. Aside from annoying things like adding a whole new full name field to the DB at the page, it shouldn't be too hard to support newlines in flavor text. Do folks think it would be better to put the name on its own line than to use the colon format? It would be a little more similar to how it is on the cards.

(For the sake of code compatibility and being able to roll things out quickly, we could theoretically include both: "Full Name: \nFlavor Text". With the current code, that should essentially just ignore the newline. Then once we added newline support to the front end, it would magically start rendering the newlines on the page.)

**Comment by irilyth** [comment]
I feel like I missed something here -- why are we putting "Button Name: Flavor text" as the flavor text, instead of just "Flavor text"? The existing buttons' flavor text doesn't generally start with "Button Name:", does it?

Oh, Chaos explained this: 

> Oh, drat.  FWIW, my intention was that only the stuff after the colon would be included in the flavor text.  I put the bit before the colon in my e-mail just so shadowshade would know which button was which.

I think we should leave the "Button Name:" part out; if the name isn't in the flavor text for some reason, that seems fine to me, there's no particular reason the flavor text can't just be "RAWR ME SMASH" or whatever. :^)

**Comment by AdmiralJota** [comment]
The original buttons don't have a separate full name on the back of each one.

E.g., the front of the card for Bobby (Uptown) has a picture, the name "Bobby", and the recipe. But the back of the card says:

> **Bobby McGinn**
> "Texas" Bobby McGinn knows every hoodlum on the streets of Leriston, Providence and Shepherd City. He likes carnuba wax, a strong handshake, and watching things burn, and he likes to beat people up.

(Along with some graphics and the rules for Rush dice.)

**Comment by irilyth** [comment]
Ok; so in that example, I think the flavor text is 

> "Texas" Bobby McGinn knows every hoodlum on the streets of Leriston, Providence and Shepherd City. He likes carnuba wax, a strong handshake, and watching things burn, and he likes to beat people up.

I don't think "Bobby McGinn" is part of the flavor text; I think it's the button name.

**Comment by AdmiralJota** [comment]
Correct.

Are you saying that you'd prefer if the full button names just don't appear on the site at all?

Or are you suggesting that we don't use the name on the *front* of the card at all, and instead use the *full* name from the back of the card everywhere on the site as the actual button name? E.g., instead of having a button "http://kickstarter.dev.buttonweavers.com/ui/buttons.html?button=Mississippi%20(Uptown)", we'd have "http://kickstarter.dev.buttonweavers.com/ui/buttons.html?button=Mississippi%20Max"?

**Comment by blackshadowshade** [comment]
If we use the full name, we're going to get mismatches with the name shown on the button.

For example, we have

    Tasha Rudenko: Natasha Rudenko is a wicked sorceress sent from an ...

and

    Clyde Fischer: Harold \"Clyde\" Fischer is a monstrous horse trainer ...

**Comment by blackshadowshade** [comment]
I guess the question for Chaos at the moment is whether we can deploy as-is at the moment, with the possibility of tweaking things like the flavour text afterwards.

I vote yes, contingent on us getting a successful Jenkins run.

**Comment by irilyth** [comment]
I think tweaking the flavor text later is fine.

Are we fine with the button names, or is there still some question about whether the button name should be the full name or the short name?

I don't personally have strong feelings about any of this. I feel like buttons should ideally have short unique names that don't require you to put the set in the button name, but James Ernest didn't ask us when he made up names for all these buttons. :^ ) Using the full names seems like it makes the names longer but more unique, and then they don't match what's on the button art, which is what people on the site will see. Using the names from the fronts of the buttons makes them match the art and makes them shorter, but less unique -- lots of things would need the set appended to deconflict them.

If this question is already settled, that's great; I wasn't sure, based on Jota's and James's comments above.

**Comment by blackshadowshade** [comment]
I'm pretty sure that we're fine with having the button name match the name shown on the button art. The question is really whether we want to present the full name somewhere in the button description---and if so, where?

**Comment by irilyth** [comment]
Aha, ok. I don't think it's particularly important that the full button name appear anywhere in the button description, but if we want it to, I like Jota's suggestion:

> **Bobby McGinn**
> "Texas" Bobby McGinn knows every hoodlum on the streets of Leriston, Providence and Shepherd City. He likes carnuba wax, a strong handshake, and watching things burn, and he likes to beat people up.

Newline-separated, with the name appearing like a header, seems nice.

I think it's ok if we go live with it as-is -- I think it's funny-looking, but we'll fix it, and it won't have any impact on people interacting with the site via other means (e.g. my Python scripts, wiki links, etc, which care about button names, so changing those later can break things).

**Comment by AdmiralJota** [comment]
Yeah, I think the only way that this would be a blocker would be if we wanted to use the full name from the back of the card as the main name that the site uses for the button.

As long as we're happy with using the name from the front of the card as the main name for the button -- the one that'll be in the button art -- then I can't see any problems with leaving the flavor text the way it is and tweaking it later once we come up with the best way to format it.

**Comment by dwvanstone** [comment]
> As long as we're happy with using the name from the front of the card as the main name for the button -- the one that'll be in the button art -- then I can't see any problems with leaving the flavor text the way it is and tweaking it later once we come up with the best way to format it.

This makes sense to me too.

**Comment by blackshadowshade** [comment]
Okay, I'll open a new issue for the appearance of the full name.

**Comment by blackshadowshade** [comment]
I've rebased this so that the CircleCI codebase is present. What's the next step to run CircleCI on this pull request?

**Comment by cgolubi1** [comment]
I think you want to setup a circleci account for yourself and attach the blackshadowshade/buttonmen repo to it.  Then you should be able to trigger a build or push to a branch and it'll trigger a build itself.

**Comment by cgolubi1** [comment]
So i think CircleCI only automagically builds your master branch at initial setup time.  So i bet you can tell it to trigger a build on a branch?  I'm not sure how.  Maybe rebase and force-push again now that you have circleci setup?

**Comment by blackshadowshade** [comment]
Ah, that's done it. A new rebase to change the commit ID triggered CircleCI. I'll go ahead and rebase all the pull requests then.

**Comment by blackshadowshade** [comment]
And CircleCI passed! It's like the end of the movie Frozen, when Elsa comes to the rescue.

**Comment by cgolubi1** [comment]
You should add links to your circle runs, though.  :>)   I mean, yes, i can find it.  But pretend i'm lazy.

**Comment by cgolubi1** [comment]
This one is: https://circleci.com/gh/blackshadowshade/buttonmen/2

**Comment by blackshadowshade** [comment]
I presume you've also found the direct link from the "All checks have passed"->"ci/circleci"->"Details" button?

Or did you want the direct link because you'll be looking at these via email?

**Comment by cgolubi1** [comment]
Ohh.  No, i hadn't noticed that github's UI integrates this.  Agreed, no need to add a manual link.

**Comment by cgolubi1** [comment]
Anyway, where were we?  We were at finally merging this business!

**Comment by cgolubi1** [comment]
I tore down this dev site --- irilyth, if you want to, you can garbage-collect the 'kickstarter' R53 name.

**Comment by irilyth** [comment]
Done!

**Pull request merged**
