### PR TITLE
Push changes from staging to production on 2018-11-16

### PR DESCRIPTION
**Pull request by cgolubi1**
This update brings these approved pulls to the production branch:

* User-visible: none
* Ideally not user-visible:
    * #2413: upgrade site to Ubuntu Xenial

Database updates:
```
UPDATES=""
SCRIPTS=""
```

Master issue for this release: #2407

master issue for all pushes to prod: #700

### CODE REVIEW

**Comment by cgolubi1** [comment]
Queueing this up for tomorrow so i can copy/paste/replace the deployment plan.

**Comment by cgolubi1** [comment]
Prod deployment plan:

1. Merge this PR: self-explanatory
2. Create the new instance:
```
cd ~/src/git/buttonmen-dev
git clone git@github.com:buttonmen-dev/buttonmen.git buttonmen-prod-bmt-2414
cd buttonmen-prod-bmt-2414
git checkout -b production
cd deploy/vagrant
./setup_aws_vagrantfile
# Edit Vagrantfile and set: aws.availability_zone = "us-east-1b"
vagrant up --provider=aws
```
3. Do a quick smoke test of whether the buttonmen website loads at the new IP
4. In the AWS console:
    * Name the instance buttonmen-prod-bmt-2414
    * Make sure the instance is in the same AZ as buttonmen-prod
5. Login to the new instance and shut it down:
```
sudo init 0
```
6. SSH into the old instance, stop apache, run a database backup, and shutdown the instance:
```
sudo service apache2 stop
sudo /usr/local/bin/backup_buttonmen_database
sudo init 0
```
7. In the AWS console:
    * Detach the EBS volume named prod-backup from the buttonmen-prod instance
    * Attach that volume to the buttonmen-prod-bmt-2414 instance
    * Boot the buttonmen-prod-bmt-2414 instance
8. Login to the new instance (note that it'll have a different IP because of the stop/start), mount the volume, and restore the database:
```
sudo mount -t ext3 /dev/xvdf1 /srv/backup
bzcat /srv/backup/buttonmen.`datefmt`.sql.bz2 | sudo mysql buttonmen
```
9. Browse to the new IP and verify that the buttonmen site loads and i can login and see the database state i expect
10. On the instance, setup the backup drive to mount on boot, and reboot:
```
# edit /etc/fstab by hand and add:
/dev/xvdf1              /srv/backup ext4 defaults       2 2
# shut down
sudo reboot
```
11. In the AWS console
    * Attach the www.buttonweavers.com EIP to the buttonmen-prod-bmt-2414 instance
12. Login to www.buttonweavers.com:
    * Verify that this is now the new instance
    * Verify that the backup volume is mounted
13. Browse to www.buttonweavers.com and verify that i can login and everything seems to be in order
14. In the AWS console
    * Rename the buttonmen-prod instance to buttonmen-prod-pre-bmt-2407
    * Rename the buttonmen-prod-bmt-2414 instance to buttonmen-prod
15. On my desktop, move directories around:
```
cd ~/src/git/buttonmen-dev
mv buttonmen-prod buttonmen-prod-pre-bmt-2407
mv buttonmen-prod-bmt-2414 buttonmen-prod
```

**Comment by cgolubi1** [comment]
Showtime.

**Comment by cgolubi1** [comment]
Hmm, minor problem: the existing buttonmen-prod instance is an m1.small, but the default Vagrantfile creates a t1.micro.  We probably want bigger than that.

**Comment by cgolubi1** [comment]
Well, maybe there's not much to say about it --- i changed the Vagrantfile to have an m1.small, recreated, and my instance is coming up.

**Comment by irilyth** [comment]
How did we even *get* an m1.small? How old is this thing? :^)

(Would we rather have something more modern? Enh, not if it messes with the plan I suppose.)

**Comment by cgolubi1** [comment]
We're not in a VPC.  :>)  I definitely don't want to deal with being in a VPC, but if you know offhand what a good drop-in replacement is, we can drop it in.  t2.medium?

**Comment by irilyth** [comment]
I don't offhand. Why aren't we in a VPC? :^) Never mind, I vote for "onward", and we can migrate to modern hardware on a modern network some other time.

**Comment by cgolubi1** [comment]
okay, sounds good.  :>)

**Comment by cgolubi1** [comment]
FTR, indeed, when i tried t2.medium:
```
VPCResourceNotSpecified => The specified instance type can only be used in a VPC. A subnet ID or network interface ID is required to carry out the request.
```

**Comment by irilyth** [comment]
I don't know if we actually want T class things anyway -- is our utilization bursty? Might be, but my guess is that we'd be a good fit for the smallest size of the current C, R, or M line, depending on whether we're harder on the CPU, memory, or balanced, respectively.

**Comment by cgolubi1** [comment]
Makes sense.  We should really setup an actual performance test rig at some point --- wouldn't be too heavy a lift on top of the existing replay testing --- so we could answer these types of questions.  I'll probably want such a thing as i get into the attack-related action log refactor, and it could also let us answer questions about whether getting a different instance type for prod would help performance.

**Comment by cgolubi1** [comment]
Okay, everything in the plan is done with no modifications except setting the instance type.

**Pull request merged**
