### PR TITLE
Changed game state REJECTED to CANCELLED

### PR DESCRIPTION
**Pull request by blackshadowshade**
Starts to address part of #1926.

Requires database update 01926_CANCELLED_01.sql

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1057/

### CODE REVIEW

**Comment by cgolubi1** [comment]
This has merge conflicts now.

**Comment by blackshadowshade** [comment]
Okay, let's see if this passes:

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1067/

**Comment by cgolubi1** [comment]
Seems reasonable.  Test plan:
* Do a database rebuild vs. update test
* Create and cancel some games both before and after the database update, and make sure they look (1) identical and (2) sane in the Overview, Game, and History UIs.

**Comment by cgolubi1** [comment]
I don't see any issues.

**Pull request merged**
