### PR TITLE
Added JQuery 1.9.0 sourcemap

### PR DESCRIPTION
**Pull request by blackshadowshade**
I've added the JQuery 1.9.0 sourcemap to the repository to allow the console in Safari to work correctly.

This should be invisible to Jenkins, but just in case: http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1185/ (if it passes)

### CODE REVIEW

**Comment by cgolubi1** [comment]
> I've added the JQuery 1.9.0 sourcemap to the repository to allow the console in Safari to work correctly.

Sorry, i've forgotten the context for this.  What's "the console in Safari"?

**Comment by blackshadowshade** [comment]
The error console, as displayed under the Developer menu. It's basically the same thing as Firebug gives us on Firefox.

**Comment by blackshadowshade** [comment]
Also, I'm expecting this pull request to be merged first before any other pull request from me, which is why I've merged it into a number of other pull requests. It allows me to catch QUnit errors that occur in Safari but not in Firefox.

**Comment by cgolubi1** [comment]
Okay, let's see --- without this pull, i open Safari, browse to a test, say http://localhost:8080/test-ui/?module=Game&testNumber=139 and click: Develop => Show Error Console.

I get "Failed to load resource: the server responded with a status of 404 (Not Found)".  So that's presumably the problem shadowshade is trying to solve.

**Comment by cgolubi1** [comment]
And with the file added, i can load the console.  Doing basic game stuff still works, and running all the unit tests in firefox still works.

Here's an article explaining what this file is - http://elijahmanor.com/the-magic-of-the-jquery-1-9-source-map/

Shadowshade: since you're bringing an outside file into the repo, i'd like to see a comment committed somewhere saying exactly where you got the file, in case we need to reproduce this in the future with a different jquery version.  In the git log, or in a README file within the js directory itself, or in a file in the notes directory.

**Comment by irilyth** [comment]
Any license issues from incorporating this file into our repo?

**Comment by blackshadowshade** [comment]
Let me put the download path here, as well as committing it in the repo:

https://cdnjs.cloudflare.com/ajax/libs/jquery/1.9.0/jquery.min.map

**Comment by blackshadowshade** [comment]
@irilyth, I anticipate that adding the sourcemap should be no issue.

JQuery is covered by the MIT license, which is pretty unrestrictive.

https://jquery.org/license/

**Comment by cgolubi1** [comment]
> @irilyth, I anticipate that adding the sourcemap should be no issue.

I'm inclined to agree --- we already have jquery in our repo, so adding the map shouldn't make anything worse.  :>)

**Comment by cgolubi1** [comment]
Thanks for adding the readme.  I have no other issues with this.

**Pull request merged**
