### PR TITLE
Added game description to overview page

### LINKED ISSUE #1508: Display Description on Game Page
I'd like to see the game description on the game page (between the game # and your button columns maybe).  Because:  when I'm playing in tournaments the description shows UBFC or MadRobin, and I like to play those games either first or last.  Having the description on the game page would let me pick those out quickly.

I suppose if a description is very long, this would either look terrible or not work.

An alternative would be to have a flag column, and a way for users to flag specific games themselves, but that seems like a much more complicated feature.  And the description gives more detail.

What do you think?

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #1508.

This should show game descriptions for new games, active games, and completed games.

Tested with 1-round haruspex vs haruspex games with descriptions.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/922/

### CODE REVIEW

**Comment by cgolubi1** [comment]
Okay, the task here is just to bring this up on a test site and see how it looks.  I'm a little worried about the timing for November if there's any controversy around how it renders for e.g. games with long descriptions, but i'll take a look and post a screencap and see where we are.

**Comment by cgolubi1** [comment]
One comment: in the "Open games" page, and in the game itself, the description is italicized.  I think it should be italicized on the overview too, for consistency.

**Comment by cgolubi1** [comment]
Okay, so it's not terrible with long descriptions.  I really do think we need the italics, though:

description_screencap

**Comment by cgolubi1** [comment]
Also, not sure how others feel, but my preference would be to have the description column later, after the basic game info columns - maybe i'd order them: Game #, Your Button, Opponent's Button, Opponent, Description, Score, Inactivity?

**Comment by cgolubi1** [comment]
My third comment is that i do think you need to solve the long description problem --- i know long descriptions can look ugly on the open games page, but the thing is the overview page is used frequently and its purpose is to be concise. So i don't think this visual passes muster.  My druthers would be to take a description substring of a *short* number of characters (something like 30) and replace everything after that with ..., because my druthers would be to have all the descriptions fit on one line to keep the overview compact:

description_with_long_game

**Comment by cgolubi1** [comment]
Okay, in summary:
* Italicize the description for consistency with the rest of the site
* I suggest putting the columns in a different order, so the (possibly blank) description field isn't the first thing
* Include a substring of the description, not the whole thing

**Comment by blackshadowshade** [comment]
So, these changes should now be addressed.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/923/ (if it passes)

**Comment by cgolubi1** [comment]
Okay.  This has become a prod blocker because #1749, which is a prod blocker, depends on it.  So let's bring it up and hope the issues above have been addressed.

**Comment by cgolubi1** [comment]
Good.  I agree that the bugs are fixed.  I bet there's some spiffy way to dynamically decide how much text to show based on the player's browser width so the column won't wrap, but for now, let's go with this.  Merging.

**Pull request merged**
