### PR TITLE
Added button images for Las Vegas set

### LINKED ISSUE #2559: New Las Vegas images!
So a friend of mine from High School is the artist behind the indie comic Bubble Gum Man.  Great satire of the Superhero genre and a big gamer in high school.  He found the idea of illustrating a set that never got its illustrations fun, and after a few months (he's busy!) this is the result!

I fixed up four 'alternate' button arts for the non-ability characters that were legal on here already.  I hope they're okay.

Logo2
BMO21
BMOBlackJack
BMOBones
BMOCraps
BMOCrypto
BMOFrank
BMOGow
BMOLadyLuck
BMOLola
BMOMagician
BMOSham
BMOSly
BMOWildcard
ButtonBlackJack
ButtonCraps
ButtonCrypto
ButtonFrankie
ButtonGow
ButtonLola
ButtonShamrock
ButtonSly
ButtonWildcard

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #2559.

### CODE REVIEW

**Comment by blackshadowshade** [comment]
And here's what it looks like on my local dev server:

las_vegas_set

**Comment by TheOrgg** [comment]
Are they smaller than normal?  Sets usually go four across on my screen.  Other than that, they look good to me.  (When Evil/Dual Dice get implemented, what'll happen to Pai Gow 2?)

**Comment by blackshadowshade** [comment]
The layout of that screen changes with the screen width. You'll probably be seeing them as smaller because your device is rendering the image to fill the screen.

**Comment by blackshadowshade** [comment]
I'll just call out here that some of the button recipes don't match the images. Is this an issue, or are we okay with this?

**Comment by TheOrgg** [comment]
I'd like to see it match the playtest version with the Triplet, personally.  That's one of the few changes I made to the set, as it made it more playable IRL and it still added up to 21 as was the intent.  The original recipe with the d11 is still on the site, too, as Twenty-One; Blackjack's "special" ability makes his T-swing unable to be 12 and that's why he's not active yet.

**Comment by cgolubi1** [comment]
Where are we on this?  It sounds like TheOrgg and Shadowshade are good with merging it?  Do we need any other input, or should i merge it?  I'm happy to.

**Comment by dwvanstone** [comment]
It looks fine to me too - three buttons on the production site will have new artwork, the artwork matches the recipes. We'll have to revisit Black Jack when its special skill gets implemented in the future.

**Pull request merged**
