### PR TITLE
Remove remaining unnecessary int casts from game/recipe/die code

### LINKED ISSUE #712: all number inputs to the backend should be cast to int immediately
James and i talked about this in the context of pull #707: we like the idea of having the backend use integers in integer format exclusively, and provide integers to the frontend via JSON.  That means that, whenever we bring in numbers in string form, we should cast them to integer right away.  So:
- Whenever numbers are read from the database, cast them to (int) right after fetching them
- Whenever numbers are submitted via POST, and validated via ApiSpec::verify_argument_of_type_number(), they should also be cast to int if they are strings
- Whenever numbers are read from session variables, they should be cast to int
- Whenever numbers are generated in the code, they should be generated as integers, not as strings
- We should not need or have casts to int in places in the code other than the above

Make it so.

### PR DESCRIPTION
**Pull request by cgolubi1**
* Refactor die parsing slightly so that validate_die_size() does all interaction with the die size as a string, including casting it to an int
* Also remove some bool casts which are not necessary under BMDB

* Fixes #712 (finally!  i think!)

### CODE REVIEW

**Comment by cgolubi1** [comment]
I'll kick off some replay testing as soon as i have a chance.  Shadowshade, anything you can see offhand that you think that won't catch?

**Comment by cgolubi1** [comment]
Ah, the UI test failures are real, because this change causes the backend to pass `optionArray` as ints rather than strings.  Let me take a closer look at that.  I think that change is *good*; i just need to check that the UI can handle it.

**Comment by cgolubi1** [comment]
Yeah, this looks fine; i hand-played some rounds of Fraquito vs Zoe, and everything seemed to work just fine.  Note that the responder tests have always put ints in `optRequestArray`, because PHP's equality-checking can't tell the difference (a sentence which really explains a lot of how we've wound up having so much variable type pain over the years, but never mind).

**Comment by blackshadowshade** [comment]
This all looks good to me.

Once you're happy with automated testing, I'm happy to merge this.

**Comment by cgolubi1** [comment]
I never actually did the replay testing i said i'd do on this.  Let's kick that off now.

**Comment by cgolubi1** [comment]
This has replayed 8900 games without issue, and i don't think there's anything in particular we were worried about.  Shadowshade, if you're still fine with this, want to merge it when you have a chance?  (I'm checking in again rather than merging it myself only because it's been a couple of months, not because of any specific concerns.)

**Comment by blackshadowshade** [comment]
This is fine, merging this now.

**Pull request merged**
