### PR TITLE
Added ability to cancel open games

### LINKED ISSUE #1733: Cancel an open game you created
[This may already be an issue -- I couldn't find it listed]

Sometimes I create an open game by mistake when I mean to invite a particular person. I'd like the ability on the Open Games page to cancel a game I've already created.

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #1733.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1408/

### CODE REVIEW

**Comment by blackshadowshade** [comment]
One design note: I chose to put the buttons to cancel games on the right hand side, so that there is no chance of confusing these buttons with those used to join games.

**Comment by blackshadowshade** [comment]
BTW, I'm addressing the appearance of cancelled games in relation to #1840, so this will appear in a different pull request. The main thing to address here is the 'null' that appears in the opponent's name column.

**Comment by cgolubi1** [comment]
Shadowshade: i don't really understand what you said about the relationship between this pull and #2292, sorry for skimming.  Do we need to merge one or the other of those first?  If so, which one?

**Comment by blackshadowshade** [comment]
There's no conflict here between the two pull requests. If this one is merged but #2292 not, then any search on the History page where there is a cancelled game and no opponent will show 'null' in the opponent column. Mildly cosmetically bad, but otherwise not a major drama. The cosmetics are fixed in #2292.

**Comment by blackshadowshade** [comment]
Rebased to remove debug comments.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1420/ (if it passes)

**Comment by cgolubi1** [comment]
This wants a dev site, so i stood one up.  irilyth, can you sync up 54.235.13.28 as ephemeral?

**Comment by irilyth** [comment]
Done!

**Comment by dwvanstone** [comment]
I created an open game Avis vs. Any Button. (Game 133) I then cancel it.

When I go to the game page, the opponent's button is a broken image:

54.235.13.28/ui/game.html?game=133

**Comment by dwvanstone** [comment]
I created an open game, changing "You" to be another player. I.e., I'm creating an open game for an opponent. 

I can not cancel this game, however. (Maybe this is okay - if I change the "You" of a game perhaps I change who can cancel the game.)

**Comment by irilyth** [comment]
I think the creator of a game generally can't cancel it -- if I create a game for two other players, I don't think I can cancel it at that point. (Maybe I should be able to, but I think that's different from this ticket.)

**Comment by dwvanstone** [comment]
My case was generating an open game, not a game for two other players. It's still a case.

Player A creates an open game owned by player B. Player A can not cancel the game. (Perhaps this is okay.)

Player B tries to cancel the game but gets the error: "Error from cancelOpenGame: You did not create this game."

**Comment by irilyth** [comment]
Ah, yeah, if B can't cancel the game either, that seems wrong.

(I was assuming that, much like how only the players in the game can accept and withdraw the game (and not the creator), only the player in an open game would be able to cancel it. Sounds like not, and I agree that they should be able to.)

**Comment by blackshadowshade** [comment]
Okay, sounds like a bug to me. I'll take a look at it.

**Comment by dwvanstone** [comment]
There were two bugs: the broken image (54.235.13.28/ui/game.html?game=133) and not being able to cancel a game when you pass on the owner.

**Comment by blackshadowshade** [comment]
Okay, I've changed the logic about who can cancel an open game. I've also reworked the appearance of the game page of a cancelled game.

However, this caused conflicts with the recently accepted changes dealing with null button names, so I've rebased this pull request. @cgolubi1, you'll need to do a fresh deploy here.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1435/ (if it passes)

**Comment by cgolubi1** [comment]
Sounds good.  I'll rip down the dev site and stand up a new one (if that turns out to cause a problem for anyone, i'll apologise and know for next time, but afaict the bugs were obvious enough that we're not going to need to introspect them later).

**Comment by cgolubi1** [comment]
irilyth: can you update the DNS for 'ephemeral' to point to 54.234.6.218?

**Comment by irilyth** [comment]
> irilyth: can you update the DNS for 'ephemeral' to point to 54.234.6.218?

Done!

**Comment by blackshadowshade** [comment]
Okay, testers, what do you think now of the functionality to cancel open games?

**Comment by dwvanstone** [comment]
It looks great! (I've confirmed the two bugs I reported are fixed.)

**Comment by cgolubi1** [comment]
Okay, are we ready to merge this?  I'm standing up a replay site, just in case i missed an API change that will break replay.

**Comment by cgolubi1** [comment]
No problem with replay testing.  So if dev testers tell me this is ready to go, i'll merge it.  dwvanstone, irilyth, we good?

**Comment by dwvanstone** [comment]
I think we are good, yes.

**Comment by cgolubi1** [comment]
Thanks!  Merging.

**Pull request merged**
