### PR TITLE
Added Peloton set (first draft)

### PR DESCRIPTION
**Pull request by blackshadowshade**
This is a preliminary pull request addressing #2360, to allow testing of the recipes on a dev site.

This pull request should not be accepted until:
- the recipes have been tested and finalised
- the images have been updated to include the recipes

### CODE REVIEW

**Comment by blackshadowshade** [comment]
Oh, let me comment here: I've edited a number of the button flavour texts for grammar, idiom, clarity, and gender neutrality. I think that the flavour texts need further discussion and refining from all those interested.

**Comment by cgolubi1** [comment]
Okay, todo here is a database sanity test, then stand up a dev site.

**Comment by cgolubi1** [comment]
irilyth: can you sync up 54.80.94.36 == fleeting in DNS?

playtesters: a dev site is up.  I have *not* yet had a chance to hack the randomizer to always create peloton games, and i might or might not have a chance, but anyway you can find the buttons at http://54.80.94.36/ui/buttons.html?set=Peloton

**Comment by cgolubi1** [comment]
Actually, i changed my mind.  Let's call the dev site "peloton" in DNS, since it might be up for awhile as we tinker with the recipes.

**Comment by dwvanstone** [comment]
Minor issue: Timea's flavortext is missing words at the end.  "However on the stages which require more climbing, such riders would perform better than pure sprinters who usually drop behind the"

**Comment by irilyth** [comment]
Done:
```
[09:58:44] jbs@osiris:/home/jbs
+$ host peloton.dev.buttonweavers.com
peloton.dev.buttonweavers.com has address 54.80.94.36
peloton.dev.buttonweavers.com is an alias for peloton.dev.buttonweavers.com.
peloton.dev.buttonweavers.com has address 54.80.94.36

```
@AnnoDomino, do you have any goals for playtesting here? In particular, do you want us to test the buttons against each other, or against a common set of other buttons, or ... ?

**Comment by cgolubi1** [comment]
I had time to hack the site to make "Random Button" only pick Peloton buttons, so i did that.  Here's the diff ftr:

```php
$ git diff src/
diff --git a/src/engine/BMInterface.php b/src/engine/BMInterface.php
index 1396934..eb2f445 100644
--- a/src/engine/BMInterface.php
+++ b/src/engine/BMInterface.php
@@ -928,7 +928,7 @@ class BMInterface {
             if (empty($allButtonData)) {
                 $allButtonData = $this->get_button_data(
                     NULL,
-                    NULL,
+                    'Peloton',
                     TRUE,
                     array('exclude_from_random' => 'false')
                 );
```

**Comment by blackshadowshade** [comment]
@dwvanstone, AnnoDomini has indicated that he would like entirely different flavour texts, so we'll deal  with those when we get proper flavour texts.

**Comment by AnnoDomino** [comment]
Hi guys, sorry for late response, 
First of all - thanks very much for creating the dev site. Its great i will be able to begin testing. 

What I have seen in the past is that people (Jota for example) announced on the production site that new buttons need testing and asked for help. Is it ok to do the same?
My general idea was to play each button against 15 buttons of average win percentage 50% (pick among those that have over 200 games played on prod site) and this way check if those Peloton buttons are good to go (win % between 30-65) or need amendments. 
But I am open for any suggestions here.

**Comment by AnnoDomino** [comment]
Thanks Irilyth, I will announce on the forum. Also I think I will be creating all games and would like people to join in. Of course if they wish they can stup their own games, but I would like to go through all the planned games and then treat any other games as additional testing.

**Comment by blackshadowshade** [comment]
I've had to rebase this pull request to deal with the splitting of responderTest into multiple files.

The easiest way to proceed here would be to apply the new database update file.

We can probably leave build-rebuild testing until the recipes are finalised, when I'll squash all the update files down into one file.

**Comment by blackshadowshade** [comment]
Oh, BTW, I've taken the new iteration of Peloton recipes from here:
http://www.buttonweavers.com/ui/forum.html#!threadId=651

**Comment by AnnoDomino** [comment]
Many thanks BSS!

**Comment by cgolubi1** [comment]
Okay, the Peloton site is updated!  Note that obviously games already in progress will keep being played with the previous recipes; the new recipes will be available for new games.

**Comment by blackshadowshade** [comment]
New update file 02360_peloton_03.sql added.

**Comment by cgolubi1** [comment]
How are things going?  Have we tested the new recipes?

**Comment by cgolubi1** [comment]
Remind me what the next step here is.  Have we tested the new recipes?

**Comment by blackshadowshade** [comment]
My understanding is that the recipes have been tested, and we're waiting on images. However, it's probably worth a ping to AnnoDomini.

**Comment by AnnoDomino** [comment]
Hi guys,
I have added the receipes to the button images and sent them to Kaori over a month ago but I guess she is busy recently with other things. 
Should i send it to someone else to get the images into the format acceptable by the site ?
I also posted the flavor text proposals on the forum in the same thread where testing was tracked. Let me know if those are good to go - and i would appreciate a language check as i am not a native speaker.

**Comment by AnnoDomino** [comment]
Hi,

Here are the images for the set which Kaori formatted for me.
Please let me know if they are ok to be uploaded.
Please also note there is a change in receipe for Mariusz button in relation to the current recipe which is on the dev site.
The remanining recipes are unchanged.

Flavor texts were suggested on the bug and feauters forum in the thread rleated to peloton set testing. 

Regards
AnnoDomini

**Comment by blackshadowshade** [comment]
@AnnoDomino, if you could send the final images, recipes, and flavour texts to me via email, I will then put up a fresh pull request containing those, and we can discuss further.

**Comment by blackshadowshade** [comment]
Closing this in favour of #2360.

**Comment by cgolubi1** [comment]
The peloton draft 1 dev site is still lying around, but nobody has logged into it for 3 months, and Peloton has been merged.  Shutting it down.

**Pull request closed without merging**
