### PR TITLE
Added button history links

### LINKED ISSUE #2190: Add Links to History to Button Pages
The Button page should include a link to the History page for that button. Or preferably two, like the player Profile page has (Active, Completed).

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #2190.

This is @AdmiralJota's proposed fix, taken directly from the gist provided.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1352/ (if it passes)

### CODE REVIEW

**Comment by cgolubi1** [comment]
Looks fine code-wise.  I'll bring this up on a dev site when i have a moment so people can eyeball it.

**Comment by cgolubi1** [comment]
There's no horizontal whitespace between active and completed, as in they look like a single word to me in Firefox:
no_whitespace

**Comment by cgolubi1** [comment]
The other functional problem i see is that the URL is hardcoded to go to buttonweavers.com - it shouldn't be at all necessary to put the site name in the URL; something like '/ui/whatever' should work just fine --- there are tons of examples of URLs in the codebase; let me know if you can't find one to copy from.

**Comment by blackshadowshade** [comment]
So, I'm having trouble working out why there is a space on the player profile page between "Active" and "Completed", but not here on the button page. I figure it's probably got something to do with the CSS, but my limited detective skills here have proven to be lacking.

Firefox indicates that there's a text-only whitespace on the player profile page, but I can't work out where this is coming from, since it doesn't seem to be added explicitly when historyLinksHolder is being constructed in Buttons.js.

**Comment by cgolubi1** [comment]
Shadowshade: the code on the profile page is:
```
  var gamesLinksHolder = $('<span>');
  gamesLinksHolder.append($('<a>', {
    'text': 'Active',
    'href':
      Env.ui_root + 'history.html#!playerNameA=' +
      Api.profile_info.name_ingame + '&status=ACTIVE',
  }));
  gamesLinksHolder.append(' ');
  gamesLinksHolder.append($('<a>', {
    'text': 'Completed',
    'href':
      Env.ui_root + 'history.html#!playerNameA=' +
      Api.profile_info.name_ingame + '&status=COMPLETE',
  }));
```

So there's literally a line in there which is appending a space, and that's why there's a space.

**Comment by blackshadowshade** [comment]
Okay, changes made as requested.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1361/ (if it passes)

**Comment by cgolubi1** [comment]
That addresses my issues; i think we could release this.  Anyone else have an opinion?

**Comment by irilyth** [comment]
Seems fine to me.

**Comment by cgolubi1** [comment]
Great.  Shadowshade, want to melt this down to one commit and i'll merge it?

**Comment by blackshadowshade** [comment]
Rebase done.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1365/ (if it passes)

**Comment by cgolubi1** [comment]
Looks good.  merging.

**Pull request merged**
