### PR TITLE
Added flavour text for Vysion and the Geekz button set

### LINKED ISSUE #2440: Add flavor text for Vysion
> Perpetually winking, this druid-monk-ranger reads, solves puzzles, plays video games, and consumes massive amounts of popular culture yet considerately makes time to beat people up.

(http://www.buttonweavers.com/ui/forum.html#!threadId=668&postId=14617)

### LINKED ISSUE #2446: Add flavour text for Geekz
(from Gryphon by email)

All copied exactly as is from the rules cards except for the
capitalization of Japanese in Cammy Neko's:

Caine struggles with a soul that is salved by darkness but addicted to
the heat of the limelight. He composes poetry in engrish and delights
in the ironic cruelty of beating people up.

Xylene is colorless and sweet-smelling. When subjected to fanboys, she
will exercise her right to beat people up.

Cammy Neko is a cosplayer who likes gashapon, nuigurumi, yaoi, and
many other Japanese words. She often cosplays with friends as fighting
game characters, who are always looking to beat people up.

Sailor Man likes eating, shopping, and playing video games. He also
likes to cross-play which makes people want to beat him up.

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #2440. Fixes #2446.

New flavour text for Vysion (written by Vysion himself), and filling in missing flavour text for the Geekz button set.

### CODE REVIEW

**Comment by cgolubi1** [comment]
Re Sailor Man's flavor text: this seems like another case of "the cards say what the cards say, but really, must we?"  How would folks feel about finding a way to update that for the 21st century?  My unconsidered thought is that my primary objection is to the "makes people want to" phrasing, because that puts us editorially on the side of, y'know, that.  What do other devs think?

**Comment by dwvanstone** [comment]
I don't like the "makes people want to" either, and it would make the site less fun for me. Maybe Vysion (who's been working on creating flavor text) would be willing to propose an alternative?

**Comment by AdmiralJota** [comment]
In light of the button art, I don't really see the text as being problematic: I don't interpret the text as being critical of cross-players in general, but rather of *this person's approach to it*. The "Sailor Man" button depicts someone who's intentionally dressing up to get a reaction out of people -- trolling, essentially -- rather than making a legitimate attempt at cosplay.

Or to put it another way: it seems surprising to me to be perfectly comfortable with featuring a character who exemplifies the "cross-dressing is comedy" trope, but *object* to having text that *calls him out on it*.

**Comment by irilyth** [comment]
Is it clear that Sailor Man's cross dressing is comedic rather than sincere? That hadn't really occurred to me before. What leads you to that conclusion?

**Comment by cgolubi1** [comment]
FWIW, i don't think we need to be 100% consistent in what we flag --- i'd rather err on the side of questioning things as we see them, even if the answer is "yep, that's consistent with how the site is" more often than not.

In this case, i feel like a minor wording change would remove the implication that the site is editorially in favor of beating up crossdressers, so i'd be pretty in favor of making such a change (i can try to wordsmith something, but if someone else beats me to it, so much the better).

**Comment by AdmiralJota** [comment]
> Is it clear that Sailor Man's cross dressing is comedic rather than sincere? That hadn't really occurred to me before. What leads you to that conclusion?

It's been quite a few years, but all the photos of the original Sailor Man seemed to pretty clearly be an attempt to combine elements of "big, burly bearded man" and "highly feminine schoolgirl" for comedic effect. But I don't know if you could even find any of the original ones on Google anymore.

**Comment by AdmiralJota** [comment]
This is an entirely different character, but [Man Faye](https://i.kym-cdn.com/entries/icons/original/000/006/582/100_-_Cowboy_Bebop_Faye_Valentine_Man-Faye_Rule_63.jpg) is another example of the same sort of attitude that Sailor Man seemed to me to be depicting.

In any case, while I'm not a fan of modifying or censoring other people's work, if you do choose to alter the text, my suggestion would be to make it a minimal change that maintains (or, if you don't think that's the original intent, *creates*) the notion of calling someone out for trolling cosplay rather than changing the sense of it entirely.

**Comment by cgolubi1** [comment]
I don't really want to get into the "trolling cosplay" discussion, because i don't think it's relevant.

An extremely cursory skim of our entire corpus of flavor text indicates that the vast vast majority of our buttons are beating people up rather than getting beaten up, so i feel justified in suggesting some extra care around the latter.  Why not just "He also like cross-playing while beating people up"?

**Comment by blackshadowshade** [comment]
Funnily enough, I've just googled cross-playing, and the term now appears to refer to playing the same game on different types of video game hardware.

Such flavour texts as these certainly do reflect on the time that they were written and the contexts in which they were written.

If we do decide to keep the original text for posterity's sake, I'd be all for adding an editorial note saying that we condemn any discrimination on the basis of gender or appearance, even in such a context where the cosplayer may be actively attempting to troll.

**Comment by AdmiralJota** [comment]
> If we do decide to keep the original text for posterity's sake, I'd be all for adding an editorial note saying that we condemn any discrimination on the basis of gender or appearance, even in such a context where the cosplayer may be actively attempting to troll.

That's a really good idea. This gets my vote.

**Comment by cgolubi1** [comment]
Trying again: my objection isn't about gender-nonconformity being played as a joke.  My objection is about the joke being that gender-nonconformity is legitimate grounds for violence.

I proposed some text above which i think circumvents that problem.  If it doesn't seem acceptable, i'm happy to hear other people's suggestions.  If folks see it as solving a problem for us to add a footnote saying we modified the wording from the original card, that doesn't seem particularly necessary to me, but i'm certainly fine with it.

But i'm not fine with the text as written.

**Comment by dwvanstone** [comment]
Here is what I've heard as the proposed revised text for Sailor Man:

"Sailor Man likes eating, shopping, and playing video games. He also
likes cross-playing while beating people up."

I think this is fine. We have documentation here in github that we made the change, so I don't think there's a need to put in a footnote on the live site. 

We could remove the hyphen - I find much more online usage of "crossplaying" than "cross-playing".

**Comment by blackshadowshade** [comment]
Does anyone else have anything they want to add to the discussion? Otherwise, I'll go with Chaos's suggestion and revise the flavour text for Sailor Man.

**Comment by blackshadowshade** [comment]
Files updated and rebased.

**Comment by cgolubi1** [comment]
Thanks.  Doing a database sanity-check, and assuming that passes i'll merge this.

**Pull request merged**
