### PR TITLE
Added boom skill

### LINKED ISSUE #506: Boom Dice
Boom: b
the die frame is a bomb

---

Boom Dice were created for the Unexploded Cow set by Cheapass Games.  They are like normal dice and they have an additional attack, the Boom attack. 
 
Boom Attack: To make a Boom Attack, remove one of your Boom Dice from play (neither player will score it). Choose one of your opponent's dice, and reroll it. Note that the targeted die is never captured, just re-rolled.

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #506.

This pull request needs additional responder and Javascript tests before it's really complete. Also, the unit tests in BMBtnSkillRandomBMMixedTest.php will conflict with the changes to RandomBM in #1579.

Requires database update 00506_boom_01.sql

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/698/

### CODE REVIEW

**Comment by cgolubi1** [comment]
Okay.  Obviously there's a lot of work to be done on the test end on this one, so i don't want to make any rash promises about timing.  (But if we can do this, why can't we do Rage dice, which have no UI component, and would let me play Rold?  `:>)`  Anyway.)

As a note to myself, the conflict with #1579 is just that the numeric IDs for the various skills will change once #1579 is merged, so that's no cause for alarm, and doesn't conflict with *testing* this. 

So, in terms of testing, i should:
* Do the standard database update test
* Do a test in which i load some games in progress and completed games into the DB before updating to make sure there's no backwards-compatibility issue with previous games
* Play a game with Boom dice myself and report some initial impressions of the UI and whatnot
* Create a responderTest for a game with Boom dice
* Create a UI test to go with the responder test
* There should be no regressions to any existing games, so replay a number of RandomAI games looking for regressions
* Play a number of RandomAI games with boom dice looking for internal errors

**Comment by cgolubi1** [comment]
Okay, first issue: it looks to me like boom dice can *only* perform boom attacks.  Here's output where i explicitly performed a power attack with a boom die:
boom_power_attack

But the effect was what i think the boom effect should be --- the attacking die was taken out of play, and the target die rerolled.

I don't know anything about boom dice, so for all i know they can't do power attacks.  But the description of the boom skill lists Boom as an additional attack, not a replacement for other attacks.  So i'm pretty sure this is a bug.

**Comment by cgolubi1** [comment]
Second bug, which you can see in the same issue --- the action log entry doesn't say that the target die rerolled from 6 => 1, just that it wasn't captured.  It looks to me like this is missing logic in `BMGameAction::messageDefender()` --- you need to be able to invoke `message_value_change()` as needed in the absence of `$defenderRerollsEarly`.

**Comment by cgolubi1** [comment]
Looks like the first bug is that any attack containing Boom dice turns into a Boom attack, since when i do a skill attack containing both Boom and non-Boom dice, i get an internal error:
skill_attack_with_boom_dice

The internal error is:
```
[Sun May 03 16:47:56 2015] [error] [client 10.0.2.2] PHP Warning:  assert(): Assertion failed in /var/www/engine/BMSkillBoom.php on line 42, referer: http://localhost:8080/ui/game.html?game=2
```

**Comment by cgolubi1** [comment]
Third bug: you have probably a simple copy/paste-o in the error message for whether a Boom attack can be performed:
boom_attack_failure_says_trip

The error message says "There must be exactly one attacking die for a trip attack.", and it should say "boom attack".

**Comment by cgolubi1** [comment]
The same issue exists if there's more than one defending die, i can see from the code.

**Comment by cgolubi1** [comment]
Okay.  Let's start with those, and i'll get back to my test plan once they're fixed.  Obviously, until the "all attacks are boom attacks" and "internal error on skill attack" bugs (which i assume are the same bug under the hood) are fixed, it doesn't make any sense to run RandomAI tests or make a responder test.

**Comment by cgolubi1** [comment]
This needs merge help in addition to the bugfixes, FYI.

**Comment by blackshadowshade** [comment]
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/707/

**Comment by cgolubi1** [comment]
If i make a Default attack in which a single Boom die targets another die:
* If the attacker is showing a lower value than the defender, the Default attack is interpreted as a Boom attack
* If the attacker is showing a higher value than the defender, the Default attack is interpreted as a Power attack

The first one of those seems okay, but the second is wrong.  The backend needs to report that the attack is ambiguous when Power/Skill and Boom are both valid options, the same way it would do for Power/Berserk.

**Comment by cgolubi1** [comment]
What do you think the interaction between Boom dice and other skills that limit capture should be?  I assumed that the purpose of Boom was to evade most restrictions on target dice, but i see:
```
Stealth dice cannot be the target of boom attacks.
```

That seems wrong to me --- the description of Stealth says that Stealth dice cannot be *captured* by any attack other than multi-die skill attacks, and we reasonably concluded that that means they can't be *targeted* by Trip attacks because Trip attacks might capture them.  But Boom attacks can't capture their targets.  So IMO Boom vs. Stealth should be legit.

**Comment by cgolubi1** [comment]
You haven't addressed the second bug which i mentioned in https://github.com/buttonmen-dev/buttonmen/pull/1605#issuecomment-98502429 - the action log doesn't mention the target die rerolling after a boom attack.

**Comment by cgolubi1** [comment]
Okay, so, rundown of the problems found so far.  At the moment, i'm playing a bunch of RandomBMMixed games with Boom dice to look for more internal errors.  There's still a fair bit of testing to do per above, but enough of the issues i'm mentioning here need logic changes that i'm waiting on it:
1. Game action log entry needs to say what value the target die rerolled.
2. Default attack assumes Power when Boom is also an option - this case should be reported as ambiguous.
3. Should stealth dice be targetable by Boom attacks?  The code says no, i think yes.

Item 3 isn't a blocker to dev testing, since dev testers may have opinions (but they can have opinions now too --- i don't think this is a "you have to see it in action to decide what you think about it" type question).  The other two are.

**Comment by blackshadowshade** [comment]
So, I think I've addressed all the issues.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/713/

**Comment by cgolubi1** [comment]
This needs merge help (unsurprisingly, given the modification affecting RandomBMMixed).

**Comment by blackshadowshade** [comment]
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/717/ (if it passes)

**Comment by blackshadowshade** [comment]
I'll add the interaction with Turbo once #1607 has been accepted.

**Comment by cgolubi1** [comment]
I can test this without the Turbo interaction change, since that change will only affect the interaction descriptions, and Turbo isn't implemented yet.

**Comment by cgolubi1** [comment]
Okay, testing which remains:

* Play some games with Boom dice myself and verify that the three things i mentioned above have been fixed
* Play a number of RandomAI games with boom dice, and with RandomBMMixed, looking for internal errors
* There should be no regressions to any existing games, so replay a number of RandomAI games looking for regressions
* Create a responderTest for a game with Boom dice (maybe i can pick an interesting sample from one of the RandomAI games)
* Create a UI test to go with the responder test

**Comment by cgolubi1** [comment]
Hmm, i noticed an API inconsistency here --- when activeDieArray is empty, the API passes it as an empty array.  Ditto for capturedDieArray.  But when outOfPlayDieArray is empty, the API doesn't pass it.

I'm inclined to file this as a separate bug rather than hold up this pull request, but IMO it *is* a bug --- testing against our API is painful because it's so internally inconsistent, so i don't think we should make it worse.

**Comment by blackshadowshade** [comment]
I'm happy to fix the API inconsistency once boom has been accepted, since it shouldn't affect any other UI functioning.

**Comment by cgolubi1** [comment]
I created a new issue, #1640, for the API inconsistency.

**Comment by cgolubi1** [comment]
I now have a responder test to submit for Boom dice.  I'm going to merge this, then submit the responder test as a pull request.

**Pull request merged**
