### PR TITLE
Replace gender with pronouns in preferences and profiles

### LINKED ISSUE #2709: Add pronouns to player profiles, and improve gender options
I see this was discussed back in #1068, but I think the gender field needs a bit of revisiting and supplementing.

Nonbinary people are common enough that I think they should have their own entry in the dropdown.

I also think that "It's complicated" opening up a text box isn't obvious, and something like "Enter your own" would be better.

Whether or not we adjust the gender field, I think it's worthwhile to have a separate pronoun field.

Like gender, it'd be a customizable text field.

Off the top of my head, I'd include the following options:

Unspecified
she/her
he/him
they/them
it/its (An actual robot)
none (use my name)
Custom

I'd probably also add a couple of the more common other pronouns (xie/hir), but that requires a bit more research.

### PR DESCRIPTION
**Pull request by cgolubi1**
* Fixes #2709

### CODE REVIEW

**Comment by blackshadowshade** [comment]
I've had a quick look at the code changes, and they look reasonable.

Once we get a dev site up, let's get testers onto this, and we'll iterate in the normal way.

**Comment by cgolubi1** [comment]
It's up at https://ephemeral.dev.buttonweavers.com/ui/ --- have a look, testers.

**Comment by dwvanstone** [comment]
When I go to preferences I see the option "Pronouns" but nothing to give it any context. Some of our users may never have heard of pronouns being a way to describe gender. Maybe it should be "Your Pronouns"? "Gender Pronouns?" Or "Pronouns (e.g. she/her/hers)"?

**Comment by cgolubi1** [comment]
> It didn't autopopulate for me

This is probably because you didn't have a gender field set in the staging site database --- almost no playtesters no, even people who have one on the production site.

**Comment by cgolubi1** [comment]
If we're hoping to give reasonable guidance for people who haven't seen a "pronouns" field before, i think that's going to take a couple of sentences, which isn't consistent with any other text we have on that page.  I think we'll want to use an info text box like we do for skills.  I'll try to mock that up in the next couple of days.

**Comment by jl8e** [comment]
We could do ghost text in the input field. "The pronouns that refer to you" is probably the shortest comprehensible explanatory text.

Or return to the menu we used for gender, with the common choices and an "enter your own" entry

**Comment by cgolubi1** [comment]
Okay, i finally updated https://ephemeral.dev.buttonweavers.com/ui/prefs.html and added some hover text.  Please take a look.  

(Shadowshade, it's no surprise that tests are failing, i haven't yet rebased to bring in the grunt fix.  JS tests pass on my virtualbox, and obviously i'll make sure they pass on the branch once testers like the change.)

**Comment by dwvanstone** [comment]
This looks perfect! Thank you!

**Comment by TheOrgg** [comment]
Looks great!

**Comment by blackshadowshade** [comment]
I think that info works well. Rebase this, and I'll check the code once again before merging it.

**Comment by blackshadowshade** [comment]
Okay, closing this one in favour of #2732.

**Pull request closed without merging**
