### PR TITLE
Added images for Chicago Crew

### LINKED ISSUE #2602: Chicago Crew artwork (approved by creator and artist)
With permission from JeffBoyArDee and FernandoBotero.com, here's artwork for the Chicago Crew, as closely matching the original cats as possible.

https://buttonmen.fandom.com/wiki/Chicago_Crew

150Audrey
150Cheathem
150Flint
150Lizzie
150Monty
150Octavia
150Spooky

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #2602.

chicaco_crew

### CODE REVIEW

**Comment by TheOrgg** [comment]
Looks good to me!

**Comment by cgolubi1** [comment]
I set up a dev site for this at http://momentary.dev.buttonweavers.com --- check it out, and i'll merge it when it's okayed by playtesters.

**Comment by dwvanstone** [comment]
These look great!

**Comment by cgolubi1** [comment]
Thanks, dwvanstone.  Merging.

**Pull request merged**
