### PR TITLE
Migrate "reroll_chance" action log entries to new database format

### PR DESCRIPTION
**Pull request by cgolubi1**
* Partially addresses #1991 
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/451/ (if it passes)

I think this is a pretty standard action log migration pull with no unusual design decisions.

### CODE REVIEW

**Comment by blackshadowshade** [comment]
This is apparently conflicted.

**Comment by cgolubi1** [comment]
Ah, whoops --- of course removing the hardcoded test value stuff i noticed while creating this pull, conflicted with this pull.

Simple enough.  Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/452/ (if it passes)

**Comment by blackshadowshade** [comment]
So, I have one reservation with this change. In RandomBM* buttons, it's possible to get something like a ch or cH die, where the die changes recipe on the chance action. We're apparently not logging such changes at the moment, but the information is there, and with the current pull request, we lose the recipe after reroll.

**Comment by blackshadowshade** [comment]
Linking #1626 for reference.

**Comment by cgolubi1** [comment]
Makes sense.  Updated everything to keep the post-reroll recipe (but not use it yet).

Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/453/ (if it passes)

**Comment by blackshadowshade** [comment]
I've tested this with normal chance buttons (John Kovalic vs FuzzFace) and confirmed that both winning and losing initiative with chance rerolls works fine.

I've also tested this with a cH die via RandomBMPentaskill, and the recipe changes correctly in the database.

**Pull request merged**
