### PR TITLE
testing: Added Steven Universe set

### PR DESCRIPTION
**Pull request by blackshadowshade**
Proposed fix for #1978.

This will need playtesting before the final pull request can be accepted.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1240/ (if it passes)

### CODE REVIEW

**Comment by AdmiralJota** [comment]
Do we have Turbo yet? We'll need that before we can playtest the set.

**Comment by blackshadowshade** [comment]
Turbo will be coming in #2048. I'm waiting for Chaos to finalise the new workflow before reworking that pull request into a testing and final pull request.

**Comment by cgolubi1** [comment]
DB test succeeded

Passes all criteria on https://github.com/buttonmen-dev/buttonmen/wiki/Developer-guide:-dev-site-acceptance-criteria - merging to dev where it will be loaded as part of #2132

**Comment by AdmiralJota** [comment]
Here are some revised recipes we should try for round 2 of testing: https://gist.github.com/AdmiralJota/ee4e30f7d34e70bb7181d161697738ef

**Pull request merged**
