### PR TITLE
Added logic for RandomBMAnime

### PR DESCRIPTION
**Pull request by blackshadowshade**
Addresses #779.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/630/

### CODE REVIEW

**Comment by cgolubi1** [comment]
This should be pretty straightforward.  I'll just play a few manual games and a number of RandomAI games with these new buttons.

**Comment by cgolubi1** [comment]
This needs merge help --- i think it conflicted with the RandomBMFixed DB changes.

**Comment by blackshadowshade** [comment]
So, this is deconflicted.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/631/ (if it passes)

**Comment by cgolubi1** [comment]
Looks reasonable.  I played some manual games, and then had RandomAI play Anime vs. Anime and Anime vs. Mixed.  (with random play, Mixed wins 54/99 games against Anime).

**Pull request merged**
