### PR TITLE
Added GWAR set

### PR DESCRIPTION
**Pull request by blackshadowshade**
Addresses #2408.

This is a tidied version of #2409, including the four missing buttons mentioned in my post [here](https://github.com/buttonmen-dev/buttonmen/issues/2408#issuecomment-480589012). Also, all button special flags have been set to zero, to allow Nala to test these buttons.

Since we're not going to be integrating the GWAR set into the production site, all button recipes are present in one database update file, 02408_gwar_01.sql (but not in data.button.sql).

The CustomBM database changes for using arbitrary test recipes are found in 00344_custom_recipe_01.sql.

### CODE REVIEW

**Comment by blackshadowshade** [comment]
I would suggest that this code be deployed to a fresh site, followed by the database updates.

TheOrgg, this will produce a site with a fresh (clean) game history, so that the button-vs-button stats are not polluted by games played with different version of the recipes.

**Comment by TheOrgg** [comment]
Those four left off were intentionally left off.  They're either confusing for a noob unfamiliar with the site, turned into Winslow-style cards or have a not-programmed special ability.

**Comment by blackshadowshade** [comment]
Great, I'll remove them again.

**Comment by blackshadowshade** [comment]
Okay, I've removed the four confusing buttons from the update script, although I've reserved their IDs for the future. (And yes, the set and button IDs are already highly artificial, so they don't cause any conflicts with anything else going on.)

**Comment by TheOrgg** [comment]
Thank you very much!  

I'm still waiting to hear back from the guys in GWAR about my intent to make a small amount and put them in the hands of gamer GWAR fans (to spread the Button Men love to another audience), but I want to be ready to present the site to them and let them try the set out without needing twenty dice sets and seven d30's.

**Comment by TheOrgg** [comment]
BTW:  Tried out the custom recepe feature the last two rounds of testing (when I realized I could use it instead of bothering ya'll) and it works pretty well, other than having to copy and paste to get it to take Warrior dice, and it not appearing when you choose 'custom set' in the "Sets" dropdown.  Nala was even cool with it if she knew the buttons involved!

**Comment by blackshadowshade** [comment]
The issue with the encoding for Warrior dice is that you need to get the correct character: backtick (`), not quote(').

**Comment by cgolubi1** [comment]
I stood up the new site at `54.160.185.88`: irilyth, can you repoint `gwar.dev.buttonweavers.com` to that new address when you get a moment, and then i'll tear down the old one.

**Comment by irilyth** [comment]
Done!

```
[08:03:18] jbs@osiris:/home/jbs
+$ host gwar.dev.buttonweavers.com
gwar.dev.buttonweavers.com has address 54.160.185.88
gwar.dev.buttonweavers.com is an alias for gwar.dev.buttonweavers.com.
gwar.dev.buttonweavers.com has address 54.160.185.88

```

**Comment by blackshadowshade** [comment]
So, I'm going to close this pull request considering that we're not going to include the functionality in the live site. If we want to come back to this, I'm happy to reopen it in the future.

**Pull request closed without merging**
