### PR TITLE
Added images for 50 states buttons

### PR DESCRIPTION
**Pull request by blackshadowshade**
Addresses part of #1961.

@Hurtay has provided me with these images of the 50 States buttons.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1105/

### CODE REVIEW

**Comment by blackshadowshade** [comment]
I've checked the recipes against the buttons on my local MAMP server (http://localhost:8178/ui/buttons.html?set=50%20States), and they seem to be correct except for Texas, since we use a backtick for Warrior and not an apostrophe.

The representation of warrior dice that we currently have (Shadow Warriors, fernworthy) is to show them as diamonds on the left side, while reserve dice (Sailor Moon, Heather) are shown as circles on the left side. I would suggest that we stick with this convention, which would mean that the following buttons would need to be reworked: Illinois, New York, Texas.

**Comment by Hurtay** [comment]
I don't know how to change the uploaded image files or how to upload new files. 
But here are the correct files.
image
image
image

**Comment by blackshadowshade** [comment]
Okay, those images are now updated.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1106/

**Comment by blackshadowshade** [comment]
The remaining images have also been added.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1107/

**Comment by blackshadowshade** [comment]
I've fixed the responder tests so that they now pass.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1109/ (if it passes)

**Comment by cgolubi1** [comment]
Okay, so i think all i need to do here is bring up a test site, create some games, make sure the images actually show up, and look for any dealbreaker issues with how the images fit into the boxes.

**Comment by cgolubi1** [comment]
I don't see any issues.  Thanks very much for putting these together, @Hurtay!

**Pull request merged**
