### PR TITLE
Visually distinguish warrior dice when they are active

### LINKED ISSUE #1606: Differentiate your own out-of-play Warrior dice from in-play dice
On #1548, I'd said

> What about your own Warrior dice? I think it'd be nice if they were also more clearly out-of-play than just the ` mark, but they surely shouldn't be the same gray as dizzy Focus dice. Maybe a pattern rather than a color, like a striped background or something?

I still think that'd be a good idea; especially dice with _other_ skills, some of which look like a ` mark (e.g. IIconfused T&S die), it's sometimes confusing to have them intermingled and undifferentiated.

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #1606.

### CODE REVIEW

**Comment by blackshadowshade** [comment]
And there we go, got the QUnit tests fixed too. Now CircleCI is happy.  :)

**Comment by cgolubi1** [comment]
I stood up a new dev site, http://blip.dev.buttonweavers.com/ui/ for testing this change to add a shield symbol to warrior dice when they are active, addressing an issue that @nkmcalli and @irilyth have both recently commented on.  Testers, please check it out.

**Comment by dwvanstone** [comment]
The shield symbol looks great and seems to function well if the die background is a circle, but it doesn't look so good if the die background is symmetric or realistic.

Screen Shot 2020-06-29 at 11 56 17 AM
Screen Shot 2020-06-29 at 11 57 00 AM

Also, after I do an attack, the shields disappear from the warrior dice which seems confusing. I'd expect the warrior shield to stay on the die even if it's not my turn.

**Comment by nkmcalli** [comment]
I added new feedback to the original issue.  I think the shield symbol is better than nothing, but I don't think it's the right solution for this problem.

**Comment by blackshadowshade** [comment]
I've updated the code to generate a stripe instead of the shield symbol.

If testers are happy with this, I'll update the help page too.

**Comment by blackshadowshade** [comment]
@cgolubi1, this dev site can be updated with the new code.

**Comment by cgolubi1** [comment]
Updated!

**Comment by cgolubi1** [comment]
What's the status here?  I see some suggestions on #1606 from a couple of weeks ago, but it looks like the conversation petered out.

**Comment by blackshadowshade** [comment]
I think we should deploy the site without waiting for this feature, it looks like we're not yet at an endpoint that people agree on.

**Comment by cgolubi1** [comment]
I updated this dev site with the latest CSS.  Check it out.

**Comment by blackshadowshade** [comment]
@nkmcalli, @irilyth, take a look at the dev site, tell us what you think!

**Comment by irilyth** [comment]
Not bad! Did we conclude that it was undesirable and/or difficult to keep all the Warrior dice always to the right of all the in-place dice, including moving a Warrior die left when it came into play?

Ah, that was here: https://github.com/buttonmen-dev/buttonmen/issues/1548#issuecomment-76104231:

> I'm sure it wouldn't be impossible, but it would be new logic that doesn't exist right now, whereas making them grey and unclickable is just like the existing focus case. IMO we should try that, and if we decide we also want "off to one side", make a separate ticket.

So, ok, let's continue to leave that aside for now.

**Comment by dwvanstone** [comment]
This looks good with all of my testing.

**Comment by cgolubi1** [comment]
I'll give this another day for nkmcalli to weigh in --- based on other comments, it seems like we're good to go.

**Comment by cgolubi1** [comment]
Merging!  Thanks for all the iteration, everyone.

**Comment by cgolubi1** [comment]
Sigh, of course that didn't get rebased before i merged it.  Oh well --- it happens.  Apologies, future us.

**Pull request merged**
