### PR TITLE
Removed files used for pagodabox

### LINKED ISSUE #1232: clean up deploy/pagodabox/
Deploying BM on pagodabox is no longer supported or expected to work well, so clean up the pagoda stuff from the repository:
- Remove the top-level Boxfile
- Remove deploy/pagodabox/
- Move anything that was in deploy/pagodabox/ that's still being used to a more appropriate directory for whatever is using it now.

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #1232.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1387/ (if it passes)

### CODE REVIEW

**Comment by blackshadowshade** [comment]
So, the Jenkins run has failed because the PHP file audit requires one of the files in the pagodabox directory.

Two questions to @cgolubi1:
- do we need the PHP file audit?
- if so, do you have a preferred target destination for the file audit_php_files.php when I move it?

**Comment by cgolubi1** [comment]
Hey, sorry to have been so slow to get back to this.  Yes, we are still using audit_php_files.php - i think i just never bothered to move it out of deploy/pagodabox.  All you should need to do is:
* move audit_php_files.php from deploy/pagodabox to deploy/jenkins
* Change the path in the two files that reference that:
```
./deploy/jenkins/build.xml
./deploy/vagrant/modules/buttonmen/templates/run_buttonmen_tests.erb
```

Then you should be good to go.

**Comment by blackshadowshade** [comment]
Okay, let's see if that did the trick.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1429/ (if it passes)

**Comment by blackshadowshade** [comment]
I'll rebase this after #2303 has been accepted, and I'll rerun Jenkins then.

**Comment by blackshadowshade** [comment]
Right, this has now been rebased.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1432/ (if it passes)

**Comment by cgolubi1** [comment]
looks good, thanks.

**Pull request merged**
