### PR TITLE
Added game page for rejected/cancelled games

### LINKED ISSUE #1766: Can't see full description on Rejected games.
Player A invites Player B to a game. Player B rejects the game. (Frowny face!)

Player A now has this game listed in their Rejected Games with the first 30 characters or so of the description, but no way to see the full description.

Perhaps the full description should be in the Rejected table (as it is in the New Games) or perhaps the link to the game should go to a game mat that shows the full description.

### LINKED ISSUE #1778: The rejected-game and canceled-game pages should include links to the previous game (if any)
If you cancel or reject a game, which was a follow-up to a previous game, the game page for the canceled or rejected game should include links to the previous game, like a completed game does.

### LINKED ISSUE #1779: The rejected-game and canceled-game pages should include a link to re-create the game
If you cancel or reject a game, the game page for the canceled or rejected game should include a link to re-create the game, in case you want to play it after all. (Maybe you changed your mind, maybe you intended all along to play it later but didn't want to play it at the time it was created, whatever.)

### PR DESCRIPTION
**Pull request by blackshadowshade**
Continues to address part of #1731. Fixes #1778. Fixes #1779. Fixes #1766.

Known issues: Currently, the game page says unspecifically that the game was "rejected or cancelled". This will eventually be sorted out properly when #1816 is addressed.

The opponent's button table has been reversed, similar to the change in #1822.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/985/

### CODE REVIEW

**Comment by cgolubi1** [comment]
Reading the code, it looks like if you create a game, the game is rejected, and you create a followon game, the newly-created game will be created continuing chat *from the rejected game itself*.

That may be a reasonable implementation --- at the moment, rejected games don't have chat, but you could imagine we could eventually use chat to kibbitz about whether to accept a game, and then the game continuation chain would contain that chat.

But i wanted to spell out that that's what this pull does, to make sure it matches what everyone had in mind.

**Comment by cgolubi1** [comment]
Okay, test plan:
* Take a look at the page from each of player, opponent, and nonparticipant, and make sure it looks reasonable and comparable to the completed game page
* Make sure that a chain of a completed game, a rejected game, and a new game works correctly
* See if i can easily propose a test for this page --- i think there is a rejected game in the responderTest corpus, so i think this is doable

**Comment by cgolubi1** [comment]
If the game still needs to be dismissed, the "Dismiss Game" link should show up on the rejected game page the same way it shows up on a completed game page.

**Comment by cgolubi1** [comment]
> This will eventually be sorted out properly when #1816 is addressed.

You mean #1801, right --- you closed #1816 as a duplicate of #1801.

**Comment by cgolubi1** [comment]
Okay, so here's the main difficulty with the chat as we currently have the site implemented and as i *think* we expect people's usage patterns to be.  Let me spell out two chains of events.  Assume the players are the same in all examples:

Chain A, no rejected game:
* Players play game 1, and put a lot of chat there
* Players create game 2 (continuation from 1)
* Game 2 is accepted

Chain B, rejected game:
* Players play game 1, and put a lot of chat there
* Players create game 2 (continuation from 1)
* Game 2 is rejected
* Players create game 3 (continuation from 2)
* Game 3 is accepted

In chain A, when you're playing game 2, you see all the chat which happened during game 1.  In chain B, you don't.

Having spelled this out, i don't think we should do anything about it now --- i think it's a more general problem with chat, in which games in which no one talks break the chat log up visually, and we might eventually want a solution in which more chat is brought in from previous games under some circumstances.

**Comment by cgolubi1** [comment]
Oh, i see --- there are new and rejected games in the responderTest corpus, but we never call loadGameData on them.  Well, that doesn't seem right to me --- we should definitely be regression-checking the behavior of loadGameData on new and rejected games; we need a responderTest that does this.  Should we make that a separate issue?

**Comment by blackshadowshade** [comment]
Yeah, let's make that a separate issue. I'd appreciate some help with getting these responder test for new and rejected games.

**Comment by cgolubi1** [comment]
Sure, that's fine - i'll create one now.

**Comment by cgolubi1** [comment]
Okay, the upshot of all of this:
* I want to verify that you intend your known issue at the top to refer to #1801, not #1816 - i'm being picky about making you say this for a reason, which is that i want to make sure i understand what implementation you have in mind.  The implementation in #1801 will use chat for players to communicate while rejecting games, and that's pretty compatible with the chat continuation behavior of this pull.  A different proposed solution might make me feel differently about the chat continuation behavior of this pull.
* The rejected game page needs a dismiss link where appropriate.

**Comment by blackshadowshade** [comment]
I'm as yet unsure how we will be implementing the "rejection message". I agree that if we can do it via chat, that would be the easiest solution.

I'll add the dismiss link now.

**Comment by blackshadowshade** [comment]
Dismiss link should now be there.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/986/ (if it passes)

**Comment by cgolubi1** [comment]
> I'm as yet unsure how we will be implementing the "rejection message". I agree that if we can do it via chat, that would be the easiest solution.

Okay.  But you see what i'm getting at, right?  If rejected games can't have chat, then chat continuation should skip past them and import chat from the previous game which can have chat.  Whereas if rejected games can have chat, then the game/chat continuation behavior used by this pull seems reasonable.

**Comment by blackshadowshade** [comment]
I understand completely, I just think that I won't be able to make the call until I'm actually solving #1801, and possibly changing the way that chat works.

**Comment by cgolubi1** [comment]
Dismiss link looks good.  If it passes jenkins, i'll merge it.

**Comment by irilyth** [comment]
FWIW, my two cents:

> Reading the code, it looks like if you create a game, the game is rejected, and you create a followon game, the newly-created game will be created continuing chat from the rejected game itself.

I think that's how it should work, especially (as you point out) if there might be chat about the new game before it's rejected/canceled.

Note also that if someone wants to create a followon to the previous game (which they might, especially if they're canceling), and explicitly *not* have the canceled game in the thread, it's not hard to do that: Go to the page for the rejected/canceled game (e.g. game 2012), which now says "This game has been rejected or cancelled", and click on the "Continued from Game 1732" link to get back to the game that 2012 was a followon to; then click one of the followon links there to try again. That's a lot of clicking, but it's for an unusual use case, and I think it fits the principle of "easy things easy, hard things possible".

**Pull request merged**
