### PR TITLE
Added spaces to button names before parentheses

### LINKED ISSUE #2196: Fix spacing for button names with parentheses
Some buttons have a parenthetical note after their name to differentiate them from similarly-named buttons from other sets. It looks like they're generally missing the space between the end of the name and the opening parenthesis, like "Tony(The Core)".

This wasn't as noticeable when it was mainly just single-letter notes (like "MAX(p)"), but it's kind of ugly when it's longer. 

I suspect that this was probably due to someone trying to avoid spaces in button names entirely at some point on the old site, but I don't think we have any problems with that here, so we should go back and add the space to existing button names so that we can move forward consistently.

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #2196.

Requires database update 02196_button_name_spacing_01.sql

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1381/

### CODE REVIEW

**Comment by cgolubi1** [comment]
Okay.  If this passes an update-vs-rebuild test, i'll merge it.

**Comment by cgolubi1** [comment]
Test failed - you're going to have to update the buttonweavers button names for matching in the DHS stats (data.stats.sql).  Here are the mismatches:
```
$ diff ~/buttonmen_db.rebuilt.sql ~/buttonmen_db.updated.sql
1026c1026
<   (70,'Carson(p)',NULL),
---
>   (70,'Carson(p)',4),
1240c1240
<   (284,'MAX(p)',NULL),
---
>   (284,'MAX(p)',9),
1344c1344
<   (388,'SC(The Deuce)',NULL),
---
>   (388,'SC(The Deuce)',510),
```

**Comment by blackshadowshade** [comment]
Okay, build script for DHS stats table updated.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1393/ (if it passes)

**Comment by cgolubi1** [comment]
LGTM.

**Pull request merged**
