### PR TITLE
Added images for The Fog and Tilili

### LINKED ISSUE #2693: Fog/Tilili generic art
Just had this idea while working on the Classic Fanatics images (PSP is NOT intuitive; might have to take the dice frames and templates into GIMP and export the names).  Generic image for Hodgepodge's Tilili (other missing images I've supplied possible substitutes) and a generic image for Fog's button in Bridge and Tunnel using elements of his CF design for each.  This seems fitting to me, as Fog has his image on his fanatic.

If ya'll don't feel this work for replacing the generic image, let me know your thoughts on it.  I'm going to try and get the currently active with no art Fanatics done within the next week, but no guarantees there.

GenericFog

150pxGenericFog
150pxTeliliGenericTeliliHodgepodge
TeliliGenericTeliliHodgepodge

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #2693

### CODE REVIEW

**Comment by TheOrgg** [comment]
If people are happy with them, replacing them sounds good.

**Comment by blackshadowshade** [comment]
Again, I've put you here as a reviewer to confirm that this pull request matches your intended changes.

**Comment by blackshadowshade** [comment]
As a hint, if you look on the Files Changed tab, you can press the page icons to display the rich diff for each image.

**Comment by TheOrgg** [comment]
Ok.  Yeah, that was my intent.  Is there a place to confirm the review happened, or is this post all that's needed?

**Comment by blackshadowshade** [comment]
That post is all I need from you.  :)

**Comment by cgolubi1** [comment]
My understanding is that this is ready to merge (in a couple of days, once we get out of the post-Feb-release merge freeze).

**Pull request merged**
