### PR TITLE
Push changes from master to staging on 2018-06-26

### PR DESCRIPTION
**Pull request by cgolubi1**
This update brings these approved pulls to the staging branch:

* User-visible:
    * #2348, #2355: fix TL status of several buttons
    * #2274: add forum markup to link to other forum threads
    * #2339, #2367: enable Oregon button
    * #2353: fix internal error involving skill attacks with more than two zero-sided dice
    * #2354: fix spurious internal error involving turbo-radioactive-fire interaction
    * #2311: reduce player confusion by removing "Any button" option when filters are selected in new game screen
    * #2359: add a utility page to produce syntax for forum tables
    * #2272: add description of interaction between chance and mighty/weak
* Ideally not user-visible:
    * #2363, #2364, #2366, #2370: various test infrastructure fixes
    * #2338: add logic to help us migrate to PHP 7 later
    * #2369: fix image file permissions

Database updates:
```
UPDATES="02333_reenable_oregon_01.sql 01167_php7_01.sql 02347_tl_status_01.sql"
```

Once this pull is merged, i will load the changes on staging.buttonweavers.com as part of #2371.

### CODE REVIEW

**Comment by cgolubi1** [comment]
I should be able to merge this in the morning: i want to test on a sandbox prior to staging, given that there are three database files from unrelated commits.

**Comment by cgolubi1** [comment]
Hah.  I should have more faith in our users.  Moving it to the "user-visible changes" section.

**Comment by cgolubi1** [comment]
Okay, FINALLY merging so i can test under virtualbox.

**Comment by cgolubi1** [comment]
Seems fine at a glance; updating live staging site.

**Comment by cgolubi1** [comment]
Done.  Check it out folks, and barring complaints, i'll try to push to prod Thursday morning.

**Comment by dwvanstone** [comment]
The "Oregon" button doesn't specify that its sizes need to be unique.

(Compare with Gordo & Guillermo which both have Special text specifying this restriction.)

Everything else looks good in my testing.

**Comment by cgolubi1** [comment]
dwvanstone: okay, should be fixed - try now.  Thank you!

**Comment by dwvanstone** [comment]
Looks good!

**Pull request merged**
