### PR TITLE
Autogenerate description of RandomBMMixed

### PR DESCRIPTION
**Pull request by blackshadowshade**
Continues to address #779.

Depends on pull request #1687.

I have also fixed the unit tests in BMDie that were being skipped because of a dependency on a method that has been recently removed.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/838/

### CODE REVIEW

**Comment by cgolubi1** [comment]
I'll wait to make a plan for this until after #1687 is merged.

**Comment by blackshadowshade** [comment]
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/842/ (if it passes)

**Comment by cgolubi1** [comment]
Okay, let's see if i can sneak this into this month.  Just going to check it out on vagrant and see if it looks fine, and then call it good.

**Comment by cgolubi1** [comment]
Looks good to me.  Let's make it so.

**Pull request merged**
