### PR TITLE
Remove singleton from BMAttack, and generate hit table only if it doesn't yet exist

### LINKED ISSUE #1404: looking up skill attacks can be unreasonably slow
During radioactive testing, i came across the following pathological case --- this game takes 5 seconds to load (on either firefox or safari, without firebug enabled):
slow_skill_lookup

It turns out that the full five seconds happens in one function, `BMAttackSkill::find_attack()`.  That's big enough that it might be worth an efficiency refactor of that function.

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #1404 better.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/644/

### CODE REVIEW

**Comment by cgolubi1** [comment]
Okay, what's there to do here?  Mostly regression testing, just make sure a bunch of RandomAI games look the same as they look now.  In terms of performance testing, i might as well go one round with xdebug, running a test game before and after and verifying that fewer function calls are made.  But i don't think it's worth doing anything more complicated than that at the expense of delaying the merge and the next push to dev.

**Comment by cgolubi1** [comment]
Hmm, the non-warrior regression tests looked fine, but here are the warrior ones (which happened to be a separate corpus because it's what i had around).  Basically 10% of them fail at some point, and the failure seems to be that the old code listed "Skill" as the only possible attack, whereas the new code also lists "Pass" as an option.

```php
...validate_game_info() failed because currentPlayerId (3) does not match playerIdArray[0] (1)
............I....ICaught exception in BMInterface::submit_die_values: Undefined offset: 2
....I...........II........................  63 / 167 ( 37%)
.....F.............F........F....F..F..............F........... 126 / 167 ( 75%)
.....F......F.................F.........F

Time: 2.9 minutes, Memory: 68.00Mb

There were 10 failures:

1) responderTest::test_interface_game_00001
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
         0 => 'Skill'
+        1 => 'Pass'
     )
     'activePlayerIdx' => 0
     'gameSkillsInfo' => Array (...)
     'gameActionLog' => Array (...)
     'maxWins' => 3
     'playerDataArray' => Array (...)
     'currentPlayerIdx' => 0
 )

/buttonmen/test/src/api/responderTest.php:725
/buttonmen/test/src/api/responderTest.php:9548

2) responderTest::test_interface_game_00015
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
         0 => 'Skill'
+        1 => 'Pass'
     )
     'activePlayerIdx' => 1
     'gameSkillsInfo' => Array (...)
     'gameActionLog' => Array (...)
     'maxWins' => 3
     'playerDataArray' => Array (...)
     'currentPlayerIdx' => 0
 )

/buttonmen/test/src/api/responderTest.php:725
/buttonmen/test/src/api/responderTest.php:13848

3) responderTest::test_interface_game_00024
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
         0 => 'Skill'
+        1 => 'Pass'
     )
     'activePlayerIdx' => 0
     'gameSkillsInfo' => Array (...)
     'gameActionLog' => Array (...)
     'maxWins' => 3
     'playerDataArray' => Array (...)
     'currentPlayerIdx' => 0
 )

/buttonmen/test/src/api/responderTest.php:725
/buttonmen/test/src/api/responderTest.php:16516

4) responderTest::test_interface_game_00029
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
         0 => 'Skill'
+        1 => 'Pass'
     )
     'activePlayerIdx' => 0
     'gameSkillsInfo' => Array (...)
     'gameActionLog' => Array (...)
     'maxWins' => 3
     'playerDataArray' => Array (...)
     'currentPlayerIdx' => 0
 )

/buttonmen/test/src/api/responderTest.php:725
/buttonmen/test/src/api/responderTest.php:18384

5) responderTest::test_interface_game_00032
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
         0 => 'Skill'
+        1 => 'Pass'
     )
     'activePlayerIdx' => 0
     'gameSkillsInfo' => Array (...)
     'gameActionLog' => Array (...)
     'maxWins' => 3
     'playerDataArray' => Array (...)
     'currentPlayerIdx' => 0
 )

/buttonmen/test/src/api/responderTest.php:725
/buttonmen/test/src/api/responderTest.php:19190

6) responderTest::test_interface_game_00047
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
         0 => 'Skill'
+        1 => 'Pass'
     )
     'activePlayerIdx' => 0
     'gameSkillsInfo' => Array (...)
     'gameActionLog' => Array (...)
     'maxWins' => 3
     'playerDataArray' => Array (...)
     'currentPlayerIdx' => 0
 )

/buttonmen/test/src/api/responderTest.php:725
/buttonmen/test/src/api/responderTest.php:23692

7) responderTest::test_interface_game_00064
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
         0 => 'Skill'
+        1 => 'Pass'
     )
     'activePlayerIdx' => 1
     'gameSkillsInfo' => Array (...)
     'gameActionLog' => Array (...)
     'maxWins' => 3
     'playerDataArray' => Array (...)
     'currentPlayerIdx' => 0
 )

/buttonmen/test/src/api/responderTest.php:725
/buttonmen/test/src/api/responderTest.php:27781

8) responderTest::test_interface_game_00071
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
         0 => 'Skill'
+        1 => 'Pass'
     )
     'activePlayerIdx' => 0
     'gameSkillsInfo' => Array (...)
     'gameActionLog' => Array (...)
     'maxWins' => 3
     'playerDataArray' => Array (...)
     'currentPlayerIdx' => 0
 )

/buttonmen/test/src/api/responderTest.php:725
/buttonmen/test/src/api/responderTest.php:30216

9) responderTest::test_interface_game_00089
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
         0 => 'Skill'
+        1 => 'Pass'
     )
     'activePlayerIdx' => 1
     'gameSkillsInfo' => Array (...)
     'gameActionLog' => Array (...)
     'maxWins' => 3
     'playerDataArray' => Array (...)
     'currentPlayerIdx' => 0
 )

/buttonmen/test/src/api/responderTest.php:725
/buttonmen/test/src/api/responderTest.php:36164

10) responderTest::test_interface_game_00099
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
         0 => 'Skill'
+        1 => 'Pass'
     )
     'activePlayerIdx' => 1
     'gameSkillsInfo' => Array (...)
     'gameActionLog' => Array (...)
     'maxWins' => 3
     'playerDataArray' => Array (...)
     'currentPlayerIdx' => 0
 )

/buttonmen/test/src/api/responderTest.php:725
/buttonmen/test/src/api/responderTest.php:39038

FAILURES!
Tests: 167, Assertions: 19502, Failures: 10, Incomplete: 5.
```

**Comment by cgolubi1** [comment]
So, what's actually right?  I pulled a screencap of one of these examples:
skill_or_pass

It's responder004's turn, and the new code says that player can do a Skill attack or Pass, whereas the old code said Skill was the only option.  Looks like the new code is right here --- the only skill attack i can see involves the warrior die.  Let me get another one to see if it's the same kind of situation, but if anyone else is around, i'd love a second confirmation that the new code is right, and responder004 should be allowed to pass here.

**Comment by blackshadowshade** [comment]
The only valid skill attack here would be the d(4) and the d(6) taking a die with value 4. That doesn't exist, so there is no obligatory attack.

**Comment by cgolubi1** [comment]
Here's another one --- new code says lackey can pass, old code said no:
skill_or_pass_2

Again, i think the new code is right.

**Comment by blackshadowshade** [comment]
Agreed. The values that an obligatory skill attack would hit are 3, 6, and 7, and none of those exist on the defender's side.

**Comment by cgolubi1** [comment]
Okay, since this fixes a bug (an obscure one, mind you --- in my test corpus, there were 180 instances of `"Skill", "Pass"` being correctly (i assume) offered as the options, and only 10 instances of "Pass" being wrongly omitted), i'm going to go ahead and merge it without worrying about whether there's a performance win.

**Comment by yawetag** [comment]
​> Agreed. The values that an obligatory skill attack would hit are 3, 6,
and 7, and none of those exist on the defender's side.

And 8, right (1-5-2)?

**Pull request merged**
