### PR TITLE
Fixed pending game count when games have been cancelled

### LINKED ISSUE #1771: Incorrect "pending game" count
I just made a move, and then clicked the link to go to my next "pending game (at least 3)":

screen shot 2015-11-03 at 4 21 31 pm

But when I did it took me to this screen. I actually didn't have any pending games.

screen shot 2015-11-03 at 4 21 45 pm

  Are unstarted / not-yet-accepted games being improperly included in that count?

### LINKED ISSUE #1788: "Next Game" link in the header, and "Next Game" link in game, disagree about how to count pending games
For now, this is a placeholder issue for me --- i want to understand this inconsistency before we push and make sure it isn't worse than we think, and i think we should fix it in December.

I don't fully understand it yet, which is why this issue has no details.  I noticed it while trying to reproduce #1771.

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #1771. Fixes #1788.

The dev database requires update 01771_pending_game_01_dev.sql

Once we add an appropriate responder test to this, I'll run Jenkins.

### CODE REVIEW

**Comment by blackshadowshade** [comment]
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/941/ (if it passes)

**Comment by blackshadowshade** [comment]
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/942/ (if it passes)

**Comment by cgolubi1** [comment]
Okay, so the second fix is going to mask the first fix here, so i think the right set of tests is:
* Create an unaccepted game and verify that the target player has no active games show up either via the top or bottom "next game" links
* Create and cancel an unaccepted game and verify that the target player's UI is reasonable (just to be sure)
* Look in the database and verify that the cancelled game does not show up as awaiting player action

**Comment by cgolubi1** [comment]
Okay, the game that needs to be accepted does show up in both Next Game links --- seems good.

**Comment by cgolubi1** [comment]
Looks good.  Merging.

**Pull request merged**
