### PR TITLE
Added extra check that the action log has an action by the active player

### LINKED ISSUE #1477: BMInterface::find_editable_chat_timestamp() assumes only one move per second
The function `BMInterface::find_editable_chat_timestamp()` uses the timestamp to figure out whether or not a chat log entry is associated with the most recent action.  If a player takes more than one action per second, this breaks.

### PR DESCRIPTION
**Pull request by blackshadowshade**
Addresses #1477.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/577/

### CODE REVIEW

**Comment by blackshadowshade** [comment]
I think that this fixes the bug, but I have no test for it, so tell me if there is more that needs to be done, Chaos.

**Comment by blackshadowshade** [comment]
Scrub that. I've found your unit test comment and fixed the test.

**Comment by blackshadowshade** [comment]
So, I'm getting some strange PDepend errors on my Jenkins runs:

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/578/
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/579/

"PHP Catchable fatal error:  Argument 1 passed to PHP_Depend_Code_ASTNode::setParent() must be an instance of PHP_Depend_Code_ASTNode, instance of PHP_Depend_Code_Class given, called in /usr/share/php/PHP/Depend/Code/AbstractType.php on line 293 and defined in /usr/share/php/PHP/Depend/Code/ASTNode.php on line 497"

It looks like perhaps Jenkins needs to be restarted, since the changes in this pull request are tiny.

**Comment by cgolubi1** [comment]
Okay, restarted.

**Comment by cgolubi1** [comment]
Waiting for a clean jenkins run on this one --- it looks like you're still having trouble?

One note: this does *not* actually fix #1477, which i should have reported as two separate issues.  It addresses one of them, but the "more than one action per second" issue will still be outstanding.

**Comment by blackshadowshade** [comment]
Yeah, I've got no idea how to get this to pass. I've also tried a fresh branch with the changes, and that fails too in the same way.

**Comment by blackshadowshade** [comment]
I guess the next step would be for you to checkout and push the branch, and see if your Jenkins passes.

**Comment by cgolubi1** [comment]
Will do.

**Comment by cgolubi1** [comment]
Yeah, sorry i never did anything useful here.  It seems like the fact that changing the commit id makes jenkins work again is a big hint --- i wonder if something broken is getting cached somewhere, indexed by commit id.

**Comment by cgolubi1** [comment]
Looking at jenkins' logs, it appears that you have the failed build, and then you have the successful build (i.e. under the hood jenkins reported:
```
INFO: buttonmen-blackshadowshade 1477_chat_bug#578 main build action completed: SUCCESS
```

and in both cases (the failure and the success), jenkins is whining about
```
/var/lib/jenkins/jobs/buttonmen-blackshadowshade/workspace/build/logs/junit.xml
```
being empty.  Whereas on a normal build, jenkins doesn't complain about that.  So that's a hint --- somehow these builds are succeeding, but some sort of broken state is causing junit.xml (the jenkins-readable output file for the phpunit tests) not to be generated.

Now that i have some idea of what to look for, the next time this happens, yell, and i'll look around.

**Comment by cgolubi1** [comment]
Okay, that digression notwithstanding, what was my actual plan in terms of verifying this fix?  Basically just a sanity-check test: can i create a game with editable chat and edit the chat?  I believe the responder tests cover that, but can't hurt to see it in action just to make sure the UI is still hooked up right.

**Comment by cgolubi1** [comment]
Looks good.  I can edit chat, and when i play a game where one player is autopassing a lot, the attacking player keeps getting the chance to add new chat (which worked before, but the point is it hasn't regressed).  Thanks.

**Pull request merged**
