### PR TITLE
Added Durer Rawg set

### LINKED ISSUE #2507: GWAR reskin with appropriate names and images ("Dürer Räwg")
Well, how's this for the fan set?

Dürer Räwg

Anna Lee (8) (6,6) (20) p(30) (U)
Anna Lee is an undead tyrant with a rotten streak.  She likes long arms, sharp teeth, and beating people up.

Bishop (6) (20) (30) (X) \`(8) \`(12)
Bishop is an academic heavy metal singer.  He likes civil war, wrestling, and beating people up.

Brad M(8) g(12) (20) (P)
Brad plays with dogs and sticks all day, sometimes at the same time.  He likes drums, flatulence, and beating people up.

Brenda (1) (1) M(2) M(3) (V)
Brenda is a fiery woman who was vegetarian for a month.  She likes rare steak, the number five, and beating people up.

Brent g(4) (12) g(12) (20) (X)
Brent is a musician who cannot find his glasses.  He likes his country, novelty nail files, and beating people up.

Cardie g(8) g(8) (8,8) (12) (X)
Cardie is a former nun who likes airplanes, outer space, and beating people up.

Cherry (6) (8) (T) M(T) \`(4) \`(8)
Cherry is a burlesque performer and gymnast who likes eating non-foods, non-dairy desserts, and beating people up.

Chuck (6,6) g(12) (X) (X) (X)
Chuck is a leather making enthusiast.  He likes whips, seafood, and beating people up.

Cuddy (4) (6) (8) (12) \`(1) \`(2)
Albrecht Cuddy is a dwarf with excess salivation.  They like court dramas, cherry pie, and beating people up.

Dave (6) (8) g(8) (12,12) (X)
Dave is an offensive cosplay enthusiast who likes yelling at crowds, being protested, and beating people up.

Derks M(8) M(12) (20) (P)
Derks is a master chef who enjoys the challenges of fixing food for vegans, bear trap headgear, and beating people up.

Dickie (4,4) (6,6), (8,8) (Y,Y)
Dickie works as a fast food mascot and enjoys banana splits, MC Chris, and beating people up.

Don g(4) (20) (X) (X) (X)
Don has the sickest last name of anyone you will ever meet.  He likes coke, shotguns, and beating people up.

Gorman (4) (6) (12) (20) \`(X) \`(Y)
Gorman is a puppeteer with no sense of direction.  He likes turtles, soft sculpture, and beating people up.

Hedy (X) (X) p(Y) g(Y)
Hedy is a doctor specializing in flesh reconstruction.  They like ambiguity, classic pin-ups, and beating people up.

Hunter (12) (8,8) p(30) p(30) g(X)
Hunter is a cannabis activist and comic book artist.  He likes cosplay, gigantic novelty wrenches, and beating people up.

Jamie H(6) H(12) (20) (V,V)
Jamie is a former star and current bus driver.  He likes peanut butter and mayonnaise sandwiches, slightly burned french fries, and beating people up.

Maggie (20) (20) (20) (30) (20/30)
Maggie is a chiropodist who specializes in maggot therapy.  She likes lost souls, telethons, and beating people up.

Matt Ron (12) (12) (20) (20) p(P)
Matt Ron is the lost son of Anna Lee.  He and his alternate personality Deborah like chainsaws, Pascal's pressure principle, and beating people up.

Orry b(4) b(4) b(12) b(P) [When you are taking an extra turn, your dice lose the Boom skill.  When you use a Boom Attack, take an extra turn.]
Orry is an artist with a heart of mud.  He likes Roman military history, the Grand Canyon, and beating people up.

Portia w(6) w(12) w(12) w(12) [Before rolling for initiative, remove one of your opponent's dice from the game this round.]
Portia is a professional plumber who really enjoys her work.  She likes clean toilets, monsters based on common household objects, and beating people up.

Reilly g(4) H(6) (8) (V,V) \`(4) \`(6)
Reilly is a copyright hawk with a heart of hair.  He likes ceasing, desisting, and beating people up.

Ashley Jay [Ashley Jay's recipe is all Standard Dice that are one size smaller than her opponent's.  Variable dice are copied as-are.  If the opponent's dice cannot be copied, Shae's recipe is four Y-Swing Dice instead.]
Ashley Jay is almost whatever you want them to be, but not quite.  They like tartar sauce, roasted puppies, and beating people up.

Smoot (6) (12) g(12) (20) p(X)
Smoot is giant with major flatulence problems.  He enjoys poutine, colorful hair brushes, and beating people up.

Stamps (4) (6) (8,8) g(12) o(Y,Y)
Stamps is a pyromaniac singer.  She likes fire, electricity, and beating people up.

Zedna (8) (30) (30) (30) (U)
Zedna easily learns anything within two and 17/18ths of a month.  She likes big butts, defenestration, and beating people up.

Bozo p(8,8) p(12,12) p(20,20) p(30,30) p(X,X)
Bozo is a band manager and weekly call-in podcast host. He likes big hair, big chins, and beating people up.

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #2507.

When I get this passing CircleCI, this can go to both manual and automated testing.

There is one point for discussion, namely the missing umlauts in the set name. Will this be okay without those umlauts, or do we need to revisit that issue again?

@cgolubi1, you can tear down the testing site gwar.dev, we're definitely not using that any more.

### CODE REVIEW

**Comment by cgolubi1** [comment]
My recommendation would be that we try to get it over the line without the umlauts, and then you put in a PR that just changes the set name to have them again, and we get everything working for that in isolation --- nothing bad should happen with changing a set name, and it means we don't block getting the set deployed on solving unicode problems.

**Comment by blackshadowshade** [comment]
#2836 opened regarding umlauts.

**Comment by blackshadowshade** [comment]
Working on this pull request reminds me of this comic:

https://xkcd.com/1296

**Comment by TheOrgg** [comment]
I agree with @cgolubi1; the umlauts can wait.  They're a reference to how the band members spell their names and their first album "Hell-O," where every letter in the name and the song titles had bits and bobs everywhere.

Also, once Blóthar was in an interview and the person doing the interview said his name as "Blyohft-thar."  It gave Blóthar a good laugh.

**Comment by blackshadowshade** [comment]
Okay, finally, CircleCI passes!

All the buttons seem to have images.

durer_button_pics

**Comment by TheOrgg** [comment]
Why's Dickie sanctioned off?  Is a Twin Y-Swing not supported?  He doesn't have any special skills or abilities.

**Comment by blackshadowshade** [comment]
Ah, good catch. There was an error in the recipe that you specified (an extra comma), I'll fix that now.

**Comment by TheOrgg** [comment]
D'oh!

**Comment by blackshadowshade** [comment]
Argh. I've fixed that now.

**Comment by cgolubi1** [comment]
Thanks, DB smoke test looks alright now.

**Comment by cgolubi1** [comment]
Dev site is up: https://blip.dev.buttonweavers.com/ui/buttons.html?set=Durer%20Rawg

**Comment by blackshadowshade** [comment]
I would expect that you'd need to accommodate the P-swing in your testing.

**Comment by blackshadowshade** [comment]
I've checked the flavour texts, and they all appear to be complete, typo-free, syntactically correct, and associated with the correct button.

Testers, can I suggest that you play a game or two involving the P swing die, just to check that this works fine when playing manually too?

**Comment by dwvanstone** [comment]
The P swing dice are working well.

**Comment by cgolubi1** [comment]
replay_loop has played around 17000 novel games with Rawg buttons, and replayed games, and it's all been fine.  That said, random_ai *does* hardcode swing ranges.  There hasn't been a problem with the Rawg buttons because it only needs them in cases where a swing is combined with some other size-changing or trip-legality-impacting skill like maximum or mood or whatever, and the Rawg buttons don't combine P with complex skills.  However, let me give you a diff for random_ai.py that you can put in this commit, if that's okay.

**Comment by cgolubi1** [comment]
```diff
diff --git a/tools/api-client/python/lib/random_ai.py b/tools/api-client/python/lib/random_ai.py
index a47f3bb0..0c2e55a2 100755
--- a/tools/api-client/python/lib/random_ai.py
+++ b/tools/api-client/python/lib/random_ai.py
@@ -19,8 +19,8 @@ import string
 VALID_SKILLS = '!#%&+?^`BbcDdFfGgHhIJkMmnopqrstvwz'
 VALID_ISH_SKILLS = string.punctuation + string.ascii_letters
 
-VALID_SHORT_SIDES_LIST = range(0, 20) + [30, 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
-VALID_SIDES_LIST = range(0, 100) + ['R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
+VALID_SHORT_SIDES_LIST = range(0, 20) + [30, 'P', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
+VALID_SIDES_LIST = range(0, 100) + ['P', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
 VALID_ISH_SIDES_LIST = range(-3, 102) + [x for x in string.ascii_uppercase]
 
 def get_fuzzy_skills():
@@ -39,7 +39,7 @@ def get_fuzzy_skills():
 
 def get_side_max(die_sides):
   SWING_MAX = {
-    'R': 16, 'S': 16, 'T': 12,
+    'P': 30, 'R': 16, 'S': 16, 'T': 12,
     'U': 30, 'V': 12, 'W': 12,
     'X': 20, 'Y': 20, 'Z': 30,
   }
@@ -162,6 +162,7 @@ UNUSED_DURING_AUTOPLAY_KEYS = [
 # TODO: we shouldn't need to hardcode this, there should always be
 # another source of the information - place a TODO anywhere we use this
 SWING_RANGES = {
+  'P': (1, 30),
   'R': (2, 16),
   'S': (6, 20),
   'T': (2, 12),
```

**Comment by cgolubi1** [comment]
I've installed that new file onto my replay site (which basically just means it'll start treating `(P)` as a legal option for CustomBM).  But basically i have no complaints about this PR from a replay testing standpoint.  I just want you to bring my random_ai changes into the commit.

What else needs to happen with this PR?

**Comment by blackshadowshade** [comment]
I think we're just about there then!

I'll add that change to random_ai.py, rebase, then if you're happy with how the pull request looks, I think this is right to go.

Any further issues, and we can address these with follow-up pull requests.

**Comment by blackshadowshade** [comment]
Rebase done.

**Comment by TheOrgg** [comment]
So...  March?

**Comment by blackshadowshade** [comment]
February, I would think. We're doing weekly deploys.

**Comment by cgolubi1** [comment]
Great, let's do this thing.  Thanks, all!

**Pull request merged**
