### PR TITLE
Remove unnecessary .empty() JQuery calls from QUnit tests

### PR DESCRIPTION
**Pull request by blackshadowshade**
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/792/ (if it passes)

### CODE REVIEW

**Comment by blackshadowshade** [comment]
Jenkins failed on this too during the PHPUnit tests. Again, I'll see what happens after another pull request is merged in. Otherwise, it looks like we might need to do some work on speeding up the newer version of PHPUnit.

**Comment by blackshadowshade** [comment]
And another passing Jenkins:

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/794/

**Comment by cgolubi1** [comment]
You know, i bet these .empty() calls were a relic from before we realised that Qunit was failing so much because we weren't waiting for all the tests to finish consistently.  Anyway, if it works it works, but i want to make sure it works under vagrant on the mac before merging.

**Comment by cgolubi1** [comment]
Looks good.

**Pull request merged**
