### PR TITLE
Added images for MegaTokyo buttons

### LINKED ISSUE #2640: Permission gotten for MegaTokyo.
Permission 1
Permission 2

Praise artists using Twitch.  First Evil Dice, now Art Permissions!

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #2640.

### CODE REVIEW

**Comment by cgolubi1** [comment]
Playtesters, check out the new art at http://fleeting.dev.buttonweavers.com/ui/buttons.html?set=MegaTokyo

**Comment by dwvanstone** [comment]
All the art looks great!

**Comment by TheOrgg** [comment]
Should I fix the little white spots on the bottom of th legs of Dom and Largo?

**Comment by dwvanstone** [comment]
> Should I fix the little white spots on the bottom of th legs of Dom and Largo?

I hadn't noticed those. I'd say it's your choice, or you could put it in a later patch.

**Comment by blackshadowshade** [comment]
I don't think it's a problem to have those white spots there.

**Comment by cgolubi1** [comment]
Sounds like consensus is this is fine as is; merging it!

**Pull request merged**
