### PR TITLE
Added privacy policy

### LINKED ISSUE #551: Privacy policy
We need a privacy policy for the site that specifies what we do with people's details, especially their email addresses.

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #551.

The wording of the privacy policy is still up for debate, if anyone wants anything changed.

### CODE REVIEW

**Comment by cgolubi1** [comment]
This wants a dev site; standing one up.

**Comment by cgolubi1** [comment]
Site should be up at http://blip.dev.buttonweavers.com/ - take a look.

**Comment by dwvanstone** [comment]
This looks great - well done, all!

**Comment by cgolubi1** [comment]
shadowshade submitted this, dwvanstone +1-ed it, checks pass.  Merging!

**Comment by cgolubi1** [comment]
shadowshade, after merging this, circleci failed on master - https://app.circleci.com/pipelines/github/buttonmen-dev/buttonmen/8/workflows/988bb990-9996-4798-ba6d-8c06b199eea8

I'm rerunning in case it's a fluke, but if that one fails too, can you take a look?  https://app.circleci.com/pipelines/github/buttonmen-dev/buttonmen/8/workflows/0929254f-5aac-404a-93a2-00ecf0f710d4

**Comment by blackshadowshade** [comment]
Looks like the re-run passed.

**Comment by cgolubi1** [comment]
Cool.  Let's not worry about it unless it keeps happening, then.

**Pull request merged**
