### PR TITLE
Added button table for new games

### LINKED ISSUE #1774: game page displayed in CHOOSE_JOIN_GAME does not show button recipes
See image --- the issue is that the API doesn't send dice until the game starts.  So possible fixes would include:
* Have the API send some dice
* Change the look of the page and make it look like the finished game page instead of the swing*-selection page, so there's a slot for the recipes
* Other

choose_join_game_no_recipe

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #1774.

### CODE REVIEW

**Comment by blackshadowshade** [comment]
Okay, I've got a problem here with JSHint:

Linting ../../src/ui/js/Api.js...ERROR
[L573:C32] W117: 'Game' is not defined.
    if ((Api.game.gameState == Game.GAME_STATE_CHOOSE_JOIN_GAME) ||
[L574:C32] W117: 'Game' is not defined.
        (Api.game.gameState == Game.GAME_STATE_REJECTED)) {

How do I tell JSHint that Api.js should also load Game.js? Or am I doing something fundamentally wrong here?

**Comment by cgolubi1** [comment]
Hmm, without looking at your code at all: Api.js is a set of base methods to talk to and parse the API that all other classes use.  It can't *depend* on Game.js --- that's backwards.  If Game.js is calling a function in Api.js and that function needs to use Game.js's variables, that function should pass those variables.

**Comment by cgolubi1** [comment]
Another idea: maybe the problem is that we've defined the game states as part of the game (putting them in Game.js), whereas really they are part of the API (and should be moved to Api.js).  I'd potentially buy that if it looked reasonable.

**Comment by blackshadowshade** [comment]
So, I tried creating a GameState.js and having that as a required module, but that caused race conditions for the loading of Api.js.

Eventually, I've fallen back to putting the game states into Api.js.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/972/ (if it passes)

**Comment by cgolubi1** [comment]
> Eventually, I've fallen back to putting the game states into Api.js

This seems unobjectionable to me, at least in principle.

**Comment by cgolubi1** [comment]
We discussed this on IRC, and agreed that the problem shadowshade ran into with game states, is that the `playerWLTText()` function doesn't actually belong in Api.js in the first place --- it's a game state processing function, and should be in Game.js.  Shadowshade agreed to do that piece of cleanup (thanks).

**Comment by cgolubi1** [comment]
I'm going to defer looking at the code any more until that fix is done, but i can go ahead and bring this up in a test site and start looking at it any time.

**Comment by blackshadowshade** [comment]
I think that I've done the cleanup as discussed.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/979/ (if it passes)

**Comment by cgolubi1** [comment]
Okay, now i see what this looks like.  Let me show two screencaps, comparing (1) the existing "game over" screen vs. (2) this new "new game" screen:
game_over_screen

new_game_screen

**Comment by cgolubi1** [comment]
So, two things:
1. At the end of the game, the opponent's mat is inverted, so that the button info is below the image rather than above it, so the left and right are symmetric.  We made that change at player request, and it's implemented in `Game.buttonImageDisplay()`.  I think we want the same visual in the new game state.
2. To my eye, there's very little whitespace between the top info and the mat in the new game UI - i think just adding a blank line would fix this.

**Comment by cgolubi1** [comment]
Otherwise this looks good, thanks for all the work on it.

**Comment by blackshadowshade** [comment]
Those last changes have been made.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/983/ (if it passes)

**Comment by cgolubi1** [comment]
Oh, good catch on fixing the page for the third party.  Taking a look at this now.

**Comment by cgolubi1** [comment]
LGTM.  Merging.

**Comment by blackshadowshade** [comment]
Just adding here that this partly addresses #1731.

**Pull request merged**
