### PR TITLE
Added extra check if chat already exists to prevent it being clobbered

### LINKED ISSUE #1481: editable chat UI bug
`Game.actionPlayTurnInactive()` clobbers `Game.activity.chat` if `Api.game.chatEditable` is set.  This means that if for some reason:
* You had previously chatted
* You are trying to add/edit chat and have modified the chat in the box
* When you click "Change game message", your submission is rejected, and `Api.game.chatEditable` is set at that time

then the UI will kill the text you just typed, and put the old saved chat message back in the edit box for you.

I can't actually figure out how to reproduce a situation in which this is relevant (i found the bug while modifying a unit test, but the unit test cheats in a way that doesn't correspond to a real situation).  But i'm sure it's a bug, in that if that situation ever were to arise, the desired behavior would be for the UI to retain the text you just typed in the edit box.

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #1481 

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/575/

### CODE REVIEW

**Comment by blackshadowshade** [comment]
I'm hoping that this fixes the bug in the way that you intended, Chaos. Let me know if it doesn't.

**Comment by cgolubi1** [comment]
Yes, this is what i had in mind.  I'll try it with a couple of live examples, and also test it against the test case i found in my 1468_migrate_ui_tests branch, to make sure the behavior now matches what i expect against tests.

**Comment by cgolubi1** [comment]
No good deed goes unpunished, sadly.  Since you merged my 1468_migrate_ui_tests pull request, there's now a test which fails on this, so you'll have to merge upstream and update that test.  The test is called `test_Game.actionPlayTurnInactive_chat_editable`, and it has a comment referring to #1481 which should make it pretty obvious what to do --- yell if it doesn't.

**Comment by blackshadowshade** [comment]
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/590/

**Comment by cgolubi1** [comment]
Thanks.

**Pull request merged**
