### PR TITLE
Changed Zodiac recipes, added images and flavour text

### PR DESCRIPTION
**Pull request by blackshadowshade**
Continues to address #1944.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1094/

### CODE REVIEW

**Comment by blackshadowshade** [comment]
I've received the images and flavour texts, so I'll add those to this pull request.

**Comment by blackshadowshade** [comment]
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1095/ (if it passes)

Apart from fixing a number of small grammatical details, I've changed the flavour text for Scorpio, since the original didn't make sense. I've got "being in opposition", instead of the original "taking the opposition". If Kaori wants something else, I'll put up a different pull request to amend the flavour text.

**Comment by cgolubi1** [comment]
Okay, i'll bring this up in vagrant and make sure nothing looks broken, do a database update-vs-rebuild test, and then merge it.

**Comment by cgolubi1** [comment]
I would imagine "taking the opposition" was intended to be like "playing devil's advocate".  But i don't know.  Anyway, most of the flavor text could probably use an edit, but i don't think it's a blocker.

**Comment by cgolubi1** [comment]
Seems fine.  Merging.

**Pull request merged**
