### PR TITLE
Cause degenerate games to move to the CANCELLED game state after 200 rounds

### LINKED ISSUE #779: Play with a randomly-generated button
The previous site had an option to create a game where the players had randomly-generated buttons, with different skill-densities ranging from no skills (though perhaps one Swing die?) up to what I think was termed the CRAZY level (most dice having one or more skills).  
Can someone recall what those levels of skill-density were? And more importantly, I'd officially like to request this functionality be added.
[edited title to make clear I didn't mean simply selecting an existing button randomly]

### LINKED ISSUE #1603: round number can only go up to 256, but the backend doesn't stop you from having more than 256 rounds
I just realised that RandomAI has been playing Dead Guy vs. Skomp for the past 3 days, and once it got up to 256 rounds, it appears that every round is number 256.  I'll include a grep of the round-ending lines below to demonstrate.

We could change the DB settings, but that only defers the problem for a game in an infinite loop.  In fact i don't think human players need more than 256 rounds --- the right answer is presumably for the backend to eventually say "you know what, you guys are done here" and end the game.

### LINKED ISSUE #1926: How to deal with degenerate games?
(I'm trying to pull this conversation out of #1920 and #1603 so we can find it later.)

Since games are not infinite [in terms of number of rounds] the site needs to end a game (even if the players may want to play a degenerate game forever). Also, players may jointly decide that a game is not worth playing and jointly decide to end the game.

I've seen several proposals:

1. Allow a game to end in a draw 
1a Consider a game a draw after N consecutive tied rounds or after N rounds
1b Allow players to agree to a draw 

2. Cancel or delete a game 
2a Consider a game canceled/deleted after N consecutive tied rounds or after N rounds
2b Allow players to jointly decide to cancel/delete a game

3. Use a coin flip to determine the winner
3a After N consecutive tied rounds or after N rounds determine winner with coin flip
3b Allow players to agree to end the game with a coin flip

My favorite of these is the third one because I think it will make tournaments easier to implement later.

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #1603. Fixes #1926.

I've not explicitly tested this code, so I presume that Chaos will run the responder tests against it and note whether degenerate games now stop appropriately.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1080/ (if it passes)

### CODE REVIEW

**Comment by cgolubi1** [comment]
Yeah, i think given that Jenkins passed, all i have to do is run this against some Envy vs. Dead Guy games and make sure the backend and UI can deal with what happens without blowing up.

**Comment by cgolubi1** [comment]
Hmm, this doesn't appear to work.  I couldn't tell you why not, but my Envy vs. Dead Guy game cheerfully blasted through round 200 and is currently at round 248 and still going.

**Comment by cgolubi1** [comment]
I'm suspicious about the fact that the variable `$this->roundNumber` does not appear anywhere else in BMGame.php.  It's declared, but is it actually used or set, or do you need to use `$this->get__roundNumber()` the way the other code does?  Arguably, maybe if `$this->roundNumber` isn't ever set, you should pull it out of the code to avoid confusion.

**Comment by blackshadowshade** [comment]
You're absolutely right about using get__roundNumber().

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1101/ (if it passes)

**Comment by cgolubi1** [comment]
Okay, let's try this again.

**Comment by cgolubi1** [comment]
Works.  The UI isn't super friendly, because when it shows a game in CANCELLED, it doesn't show W/L/T, and it doesn't give you an option to ask for more game history.  I think we should address those complaints the instant a pair of human players wind up in this situation and ask us to!

**Pull request merged**
