### PR TITLE
Added various flavour texts

### LINKED ISSUE #2659: Megatokyo flavor text
In the materials from Fog there was a text file with the text from the first post where Megatokyo was first posted.  I just noticed the flavor text wasn't on the buttons's pages.

Here's the flavor text for each:

Piro is a Quake savant and Puchiko cosplayer. He likes to frag people.

 "DC" is a zombie imitator and runs a fanboy manipulation racket. We're pretty sure she likes to beat people up. 
(Note, this is for Darkly Cute)

Dom is a winged bishounen flunkie and abstract stick figure artist. He likes to beat people up.

Erika generally works as eye candy for places trafficked by young males. She likes to beat fanboys up.

Largo is the possessor of 3vil l33t 5k1IIz and some-time zombie hunter. He likes to frag people.

Ping is every fanboy's dream and fully compatible with the Playstation 2. In self defense, she has been known to beat fanboys up.

### LINKED ISSUE #2779: Flavor Text for Effster and Fictitious Alan Clark
"The Effster writes constantly, using various pseudonyms like Stephen King, John Grisham, Danielle Steel, etc., but whenever he takes a break he likes to beat people up."

"The Fictitious Alan Clark likes to strip people naked and paint gaping wounds on their bodies, then he likes to beat them up."

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #2779. Fixes #2659. Addresses all known flavour text mentioned by #1176.

### CODE REVIEW

**Comment by blackshadowshade** [comment]
I've not taken a good look at these flavour texts, this pull request will probably need a dev site, and someone to trawl through the flavour texts on the dev site to check for obvious issues.

**Comment by cgolubi1** [comment]
Dev site up at: https://fleeting.dev.buttonweavers.com/

**Comment by blackshadowshade** [comment]
I've checked all the new flavour texts, they all appear to be correct and associated with the correct buttons.

**Comment by cgolubi1** [comment]
This has to be deconflicted.

**Comment by blackshadowshade** [comment]
Rebase done.

**Comment by cgolubi1** [comment]
I'm happy to merge this once the prod release is done.

**Pull request merged**
