### PR TITLE
Added Apple touch icon, and added HTML to make this work for Android too

### LINKED ISSUE #2257: Icon
Add icon for better mobile support. iOS can make a link on home screen, but it's just white for buttonmen right now.

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #2257.

The image for this pull request was generated by @AdmiralJota, many thanks for that.

I haven't tested this at all, so this will need to be tested on various Android and Apple phones and tablets.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1405/

### CODE REVIEW

**Comment by cgolubi1** [comment]
This obviously wants to be a dev site.

**Comment by cgolubi1** [comment]
Made a dev site.

irilyth, can you sync up ephemeral 54.224.224.246 in Route53?

**Comment by irilyth** [comment]
> irilyth, can you sync up ephemeral 54.224.224.246 in Route53?

Done!

```+$ host ephemeral.dev.buttonweavers.com
ephemeral.dev.buttonweavers.com has address 54.224.224.246
ephemeral.dev.buttonweavers.com is an alias for ephemeral.dev.buttonweavers.com.
ephemeral.dev.buttonweavers.com has address 54.224.224.246
```

**Comment by irilyth** [comment]
> irilyth, can you sync up ephemeral 54.224.224.246 in Route53?

Done!

```
+$ host ephemeral.dev.buttonweavers.com
ephemeral.dev.buttonweavers.com has address 54.224.224.246
ephemeral.dev.buttonweavers.com is an alias for ephemeral.dev.buttonweavers.com.
ephemeral.dev.buttonweavers.com has address 54.224.224.246
```

**Comment by cgolubi1** [comment]
So i think we should merge this, yes?

**Comment by blackshadowshade** [comment]
Let's do this. :)

**Pull request merged**
