### PR TITLE
Modify bm_rand() handling to use a separate function for skill-selection random numbers

### PR DESCRIPTION
**Pull request by cgolubi1**
* Unblock regression testing for #2210 
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/500/ (if it passes)

### CODE REVIEW

**Comment by blackshadowshade** [comment]
It seems to me that there might be missing function parameters to bm_skill_rand()?

**Comment by cgolubi1** [comment]
Huh, you're right.  It doesn't end up mattering, because we never call the test functions without `$BM_RAND_REQUIRE_OVERRIDE` so they always exit before that point.  But when you're right, you're right.  :>)  Will fix.

**Comment by cgolubi1** [comment]
I made that fix, but i think this isn't passing jenkins, so i'll keep working on that, and don't worry about it until then.

**Comment by cgolubi1** [comment]
Okay, sorry about all that - i've fixed the unit tests so Jenkins now passes - http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/502/ - and since no one has stood up a dev site for this, i went ahead and rebased back down to one commit.  (The only change from the previous commit was the fixing of the `BMBtn*` unit tests to use the new die-roller-override syntax.)  This is ready to review.

**Comment by blackshadowshade** [comment]
Okay, this looks fine to me. After looking specifically at the changes to BMBtnSkillRandomBM.php and the bootstrap files, I'm pretty sure that the changes should leave live functionality untouched, and that's the most important thing.

**Pull request merged**
