### PR TITLE
trimming username input

### PR DESCRIPTION
**Pull request by danlangford**
Fixes buttonmen-dev/buttonmen#2662 by simply trimming the input in JS

edit: s/addressing/Fixes/

### CODE REVIEW

**Comment by blackshadowshade** [comment]
Thanks for submitting a fix!

From https://guides.github.com/features/issues/, you'll see the following:

    By prefacing your commits with “Fixes”, “Fixed”, “Fix”, “Closes”, “Closed”, or “Close” when the commit is merged into main, it will also automatically close the issue.

Thus, if you change your opening comment to "Fixes #2662 ...", when we accept this pull request, it'll autoclose issue #2662.

I'll test this fix now on my local MAMP stack.

**Comment by blackshadowshade** [comment]
Okay, works for me on my local. This is so simple that it probably doesn't need much more looking at, but if you'd prefer, @cgolubi1, we can stand up a dev site and let @danlangford test with his mobile device there.

**Comment by danlangford** [comment]
As a software dev myself I'm inclined to want to write a unit test and also address the issue server side. I am also very unfamiliar with php and want to take your lead on how involved this simple enhancement is.

**Comment by jl8e** [comment]
I don't think it's necessary to fix it server-side as well. It can't cause a security issue if the JS is bypassed, just an error of the bypasser''s own making.

A more general question is whether we should be stripping leading and trailing whitespace from most string inputs in the preprocessing stage, which we should be, since we don't want accidental whitespace in usernames. (Or, if  we are, we should be doing it to this one as well.)

**Comment by blackshadowshade** [comment]
I think we fix errors as we come across them, and we haven't had any other feedback about whitespace issues around usernames.

**Comment by blackshadowshade** [comment]
Oh, I've noted one thing: @danlangford, it'd be useful if you set up a [CircleCI](https://circleci.com/) account (if you don't have one already). We'll then set it up so that when you submit a pull request, CircleCI will run.

**Comment by danlangford** [comment]
I logged into circleci with my GitHub account. I think my username is danlangford

**Comment by blackshadowshade** [comment]
So, I think the next step is that you need to set up CircleCI to follow the buttonmen project.

Try going to https://app.circleci.com/projects/project-dashboard/github/danlangford/, search for 'buttonmen', and then try to follow it.

**Comment by danlangford** [comment]
I can set up my own CI build on my fork. I don't think I can follow because I don't have any permissions for the buttonmen-dev/buttonmen project.

**Comment by blackshadowshade** [comment]
@cgolubi1, what more do we need to do to get Dan up and running with CircleCI?

**Comment by cgolubi1** [comment]
My notes about how i got setup with CircleCI aren't amazing:

```
* I'm trying to setup CircleCI with buttonmen
* It needs to use github's auth because it needs r/w access to my
  repos to put build results, and they claim github won't give them
  a more restrictive credential option; okay
* okay, i clicked on the clicky buttons, and got:
    https://circleci.com/gh/cgolubi1/buttonmen
  and it claimed a successful build
```

but i think what i have is more like "my own CI build on my fork" (i.e. on cgolubi1/buttonmen) than like following buttonmen-dev.

* Dan: did you try setting up a CI build on danlangford/buttonmen (which i think is == "your fork")?  Anything good/bad happen if so?
* Shadowshade: any particular reason to think that's not the right thing for Dan to do?

**Comment by cgolubi1** [comment]
Anyway: this change seems fine to me, and i agree with Shadowshade that we've historically been pretty adhoc in making JS changes across UI pages.  If you want a unit test, i think one at the JS level would be appropriate.  (Is it self-explanatory how to do that?  If not, complain.)

Basically: i'm happy to merge this given a passing CircleCI once we get CircleCI working for you.  Or i'm happy to see you add a test if you want one.

**Comment by cgolubi1** [comment]
For Dan as part of intro-to-bmdev (and i should really document this somewhere, but writing it in a comment is a start maybe): because i mostly process the PRs (and mostly don't have a lot of time and want to optimize for periodically scanning the inbox), i mostly own the label convention for PRs.  The labels i tend to use for PRs are:
* incomplete - this one is the most important for submitters.  It means i think the PR is in the submitter's court (either because there's a problem that needs to be fixed, because you said you were still working on something, or as in this case because it's waiting for a passing CircleCI run).  Feel free to remove the label when you want me to look at the PR again --- i'll try to check it anyway, so you're not doomed if you forget, but if you remember it's a good way to communicate about it
* ready to merge - means we've tested the PR and are happy with it, but there's some reason we're not merging it right now.  The most typical reason is because the PR has multiple commits and i want the committer to rebase it down to one before we merge it.  When i put this label, i'll put some comment explaining why i'm not just merging it, so it should be obvious what to do
* dev site, replay site - these labels are related to my workflow around PRs that are still being processed (i.e. we're still deciding whether they need to be changed or can be accepted).  For the curious, dev site == there's a [live test site up](https://github.com/buttonmen-dev/buttonmen/wiki/Dev-site-index) that testers can use for manual testing, replay site == there's a site running the python replay code to throw a lot of random games at the change and look for logic/crash bugs.  Regardless, i will become more confused and slow, which is bad for PR velocity, if other people change these tags.

HTH.

**Comment by danlangford** [comment]
Sounds good. I can set up circleci on my fork. Thanks for the run down own the labels. 

While I have your attention, do you guys have any interest in multiple repos within button-men dev? Maybe the python moves to it down repo ? Or maybe a fork if BMAI will want to be owned by the buttonmen-dev org. Or does your workflow work better if it's all in the same code base?

**Comment by cgolubi1** [comment]
Right now, all the testing expects everything to be in one repo (and in particular, we have a silly but moderately effective workflow in which the backend runs end-to-end tests of all the APIs, then stores the outputs of those tests, which get used in the tests of the JS and the python client.  The nominal goal of all of that is to keep us from changing the API behavior in a way that breaks the UI or python client without noticing.  I'm sure there's other ways to do it, but having one test workflow on one repo run both the tests that exercise the backend API and the tests that make sure the frontend can deal with those API outputs, is our current way).

But if you want to put a new thing in its own repo, make a suggestion for how you'd like it to be (and why it helps you to have it that way), and we'll ponder.

**Comment by danlangford** [comment]
i set up a circleci on my buttonmen fork and got a good build on this branch of mine. do i need to do anything to get circleci to publish the build result here ?

**Comment by cgolubi1** [comment]
Github is weirdly inconsistent about publishing checks sometimes, so i'm not sure without more information whether that means there's something you still need to setup, or not --- you can always link to the passing circleci run in the correspondence.

**Comment by danlangford** [comment]
here is the link to the working build https://app.circleci.com/pipelines/github/danlangford/buttonmen/2/workflows/46b5f86f-609e-4c63-b272-8fa46ca8276d/jobs/2 or here is this link https://app.circleci.com/pipelines/github/danlangford/buttonmen?branch=2662-forgotpw-username-trim

**Comment by blackshadowshade** [comment]
This branch now has pylint in it, which is not ideal.

Would you mind restricting it to the ForgotPassword.js change only, please, and then rebasing?

**Comment by danlangford** [comment]
oh no, thanks so much for catching that. i redid my commit to trigger a circleci build and accidentally picked it up.

**Comment by cgolubi1** [comment]
Thanks, Dan.  Welcome to being a buttonmen dev.

**Pull request merged**
