### PR TITLE
Removed an extraneous .orig from the sed command in setup_aws_vagrantfile.

### PR DESCRIPTION
**Pull request by irilyth**
http://jenkins.buttonweavers.com:8080/job/buttonmen-irilyth/27/

### CODE REVIEW

**Comment by cgolubi1** [comment]
If this works for me on the mac, i'll merge it.

**Comment by cgolubi1** [comment]
It does not:
```bash
leocrotta,[~/src/git/cgolubi1/TEST-buttonmen-2075_remove_extraneous_dot_orig/deploy/vagrant],07:46(0)$ ./setup_aws_vagrantfile 
sed: -e: No such file or directory
sed failed - debug what went wrong
leocrotta,[~/src/git/cgolubi1/TEST-buttonmen-2075_remove_extraneous_dot_orig/deploy/vagrant],07:46(1)$ 
```

My sed manpage tells me:
```
     -i extension
             Edit files in-place, saving backups with the specified extension.  If a zero-length extension is given, no backup will be saved.  It
             is not recommended to give a zero-length extension when in-place editing files, as you risk corruption or partial content in situa-
             tions where disk space is exhausted, etc.
```

I'm not sure what "zero-length extension" means offhand, because it doesn't like `-i""` either.  Ahh, i see, i can get away with `sed -i ""`, but if i'm going to give it an empty argument, there has to be whitespace before the argument.

For a non-empty argument, it will accept no whitespace, like `-i.orig`.  So if that solves your problem, that's what i'd suggest --- if you want an empty argument, you'll have to detect sed version or OS or something.

**Comment by irilyth** [comment]
Yeah, I dislike the .orig, but I dislike trying to do OS detection even more, so hey, a .orig it is.

http://jenkins.buttonweavers.com:8080/job/buttonmen-irilyth/29/

**Comment by irilyth** [comment]
I've rebased this down to one commit, and this PR should be ready to review now.

**Comment by irilyth** [comment]
http://jenkins.buttonweavers.com:8080/job/buttonmen-irilyth/32/

**Comment by cgolubi1** [comment]
Okay, i'm sure this will work for me, but it's been awhile, so testing it out.

**Comment by cgolubi1** [comment]
Yep, seems fine.  Merging.

**Pull request merged**
