### PR TITLE
Migrate action_log entries of type end_draw to new database structure

### PR DESCRIPTION
**Pull request by cgolubi1**
* This is the proposed framework for #1991
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/434/

In this pull:
* Create BMInterfaceGameActionLog.php and move the handful of existing action_log database functions there
* Add generic logic to action_log load and save methods to use dedicated tables where they exist
* Migrate the `end_draw` action log entry's load/store methods to use such a dedicated table, `game_action_log_type_end_draw`
* Provide an idempotent utility to be run as part of the deployment which migrates all existing `end_draw` entries

### CODE REVIEW

**Comment by cgolubi1** [comment]
How i tested this pull:
* Update-vs-rebuild test of database sql files
* On a fresh site, play an Envy vs. Dead Guy game and verify that the end_draw action log entry is stored and loaded correctly
* Load a recent backup of the prod site database onto virtualbox, update it using the test script, and spot-check that games with draws can still be loaded and display their action logs.

**Comment by blackshadowshade** [comment]
So, looking at this pull request, I note that we're requiring the action_type string to match the table name suffix. I wonder if we should eventually (i.e., not affecting this pull request) change action_type to an enumeration. What do you think?

**Comment by cgolubi1** [comment]
> So, looking at this pull request, I note that we're requiring the action_type string to match the table name suffix. I wonder if we should eventually (i.e., not affecting this pull request) change action_type to an enumeration. What do you think?

Yeah, i thought about that, and i do think we eventually should.  I just didn't want to juggle too many things at once, and there are a couple of stale action_types still floating around in the prod (and presumably dev) databases, so i think it would make more sense to get the data tidy first, then move over to ENUMs.

**Comment by blackshadowshade** [comment]
Excellent, we'll keep that on the horizon then.

**Comment by blackshadowshade** [comment]
So, I've tested on my MAMP stack and everything works in a Dead Guy vs Echo matchup.

There's one thing that I'm wondering about, namely your selection of a VARCHAR(10) to store the round_score, instead of a float representation. I can imagine a number of reasons that you might have done that, but I'd like to hear what your reasoning is.

**Comment by blackshadowshade** [comment]
Actually, there is one other point.

You're querying the last insertion ID to retrieve the log ID. However, if another insert happens to occur in the meanwhile, you're going to retrieve the wrong ID. Doesn't this actually _require_ a transaction explicitly to stop bad stuff happening?

**Comment by cgolubi1** [comment]
> You're querying the last insertion ID to retrieve the log ID. However, if another insert happens to occur in the meanwhile, you're going to retrieve the wrong ID. Doesn't this actually require a transaction explicitly to stop bad stuff happening?

Hmm.  Well, this isn't the only place we do it --- i would have flagged it for discussion if it had been.  It happens in `insert_new_game()` and it happens in `insert_forum_thread()`.  Maybe it's wrong in all of those places, and we should define a database helper function which does an insert and returns the ID, wrapped in a transaction?

**Comment by blackshadowshade** [comment]
Okay, answering myself.

According to http://stackoverflow.com/questions/10680943/pdo-get-the-last-id-inserted, a transaction shouldn't be needed, since last_insert_id is connection specific.

**Comment by cgolubi1** [comment]
Yep, i just found http://stackoverflow.com/questions/14827783/auto-increment-and-last-insert-id which says the same thing.

**Comment by cgolubi1** [comment]
> There's one thing that I'm wondering about, namely your selection of a VARCHAR(10) to store the round_score, instead of a float representation. I can imagine a number of reasons that you might have done that, but I'd like to hear what your reasoning is.

So, primarily expedience --- i didn't know what state the current data in the database would be in, and i wanted to make sure not to destroy any data we'd need during the migration.  Probably we should eventually use a float, but deferring that to a later migration as needed, means i don't have to worry about what will happen if something which happens to be in the DB right now has a format which the float i pick doesn't like.

**Comment by blackshadowshade** [comment]
Okay, fine, as long as we revisit this decision later and review whether it's still appropriate.

**Pull request merged**
