### PR TITLE
Added confirmation popups for rejecting and cancelling games

### LINKED ISSUE #1777: Prompt for confirmation before rejecting a game
Re-creating a rejected game is rather annoying now, and will probably at least somewhat annoying in the future, so it'd be nice if it prompted for confirmation, like surrendering.

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #1777.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/967/

### CODE REVIEW

**Comment by blackshadowshade** [comment]
In this pull request, I added conditionals in the live code for test parameters. If we want to avoid that, we can use Sinon.JS instead to mock window.confirm() instead.

http://stackoverflow.com/questions/6608278/avoid-capture-verify-a-javascript-alert-when-testing-a-method-that-displays

**Comment by blackshadowshade** [comment]
Jota suggests http://stackoverflow.com/questions/2274749/javascript-how-to-mock-confirm-method

**Comment by cgolubi1** [comment]
So... i think the idea Jota pointed to of using a wrapper for window is the right one.  There's a fair amount of mocking of functions in the QUnit tests.

Another specific thing you should look at is Env.js --- that has a bunch of functionality which sets up e.g. Env.window.location to be the actual window.location on the live site, and a mock object when testing is happening.

So it seems to me that if you're going to setup mocking on a second window object (window.confirm), it would be very straightforward to do so using the same kind of method that is already used for Env.window.location.  That would be my recommendation, and should be very easy --- then we're keeping all of the test-centric functionality in one place, in Env.js.

**Comment by blackshadowshade** [comment]
Okay, I've mocked Env.window.confirm, and that tidies things up nicely.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/973/ (if it passes)

**Comment by blackshadowshade** [comment]
If I understand correctly, this pull request has been invalidated by #1832. Is that right? If so, it can be closed.

**Comment by cgolubi1** [comment]
Oh, because the new button is only on the Overview page.  Yeah, that seems reasonable, but if i were you i wouldn't delete the branch yet --- that way if our flighty dev testers decide they'd prefer to bring back that column, we'll still have the code.  :>)

**Comment by cgolubi1** [comment]
That said,  i do like the mocked confirm box --- maybe we should get that in the codebase so we'll have it later when we inevitably need it for something?

**Comment by blackshadowshade** [comment]
I'm going to close this one, and we'll address the issue differently, i.e., directly from the game page.

**Pull request closed without merging**
