### PR TITLE
Push changes from master to staging on 2018-11-23

### PR DESCRIPTION
**Pull request by cgolubi1**
This update brings these approved pulls to the staging branch:

* User-visible:
    * #2419, #2420: fix bug which breaks user login on password change
* Ideally not user-visible: none

Database updates:
```
UPDATES=""
SCRIPTS=""
```

Once this pull is merged, i will load the changes on staging.buttonweavers.com as part of #2407.

### CODE REVIEW

**Comment by cgolubi1** [comment]
Merging.  I'll comment again once i've loaded the change on staging, because i may get interrupted for a couple of hours before that actually happens.

**Comment by cgolubi1** [comment]
Staging is updated.

**Comment by blackshadowshade** [comment]
Okay, I can now change a password successfully on staging.

**Comment by cgolubi1** [comment]
Thanks!

**Pull request merged**
