### PR TITLE
UI for setting chat privacy within a game

### LINKED ISSUE #464: allow privacy settings for game chat
Players in a game should be able to specify whether the game chat is visible only to the participants, or is visible to anyone who looks at the game.

### PR DESCRIPTION
**Pull request by cgolubi1**
* Fixes #464 
* Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/505/ (if it passes)

### CODE REVIEW

**Comment by cgolubi1** [comment]
Shadowshade: double-check this for obvious problems, and if you don't find any, i'll stand up a dev site, since i want to get eyeballs on the verbiage of the in-game display.

Reviewers/playtesters: what i really want here is full testing of the functionality and look-and-feel of the per-game privacy toggle.

Note that this is *not* a per-player default setting for game privacy; it's just a per-game toggle based on the current default of public chat.  If this is accepted, i'm going to make a separate issue for allowing a per-player default setting, and we can argue on that issue about what the default per-player default should be.

**Comment by blackshadowshade** [comment]
Jenkins passed, and the changes look reasonable to my tired eyes, so I'm happy for you to deploy this. I'll take another look at the code once the site is up and I can see what's actually going on.

**Comment by cgolubi1** [comment]
Okay, dev site is up - irilyth, can you link up `temporary=54.167.228.183` when you get a chance?

**Comment by irilyth** [comment]
> Okay, dev site is up - irilyth, can you link up `temporary=54.167.228.183` when you get a chance?

Done!

**Comment by cgolubi1** [comment]
Thanks.  Reminder to playtesters, i'm looking for functionality and UI feedback on the private chat stuff --- does all of the public/private toggle stuff work as expected?  Does the in-game UI make it clear what's going on?

**Comment by dwvanstone** [comment]
Mostly it's fantastic - it's clear that if one party asks for private that it will be private.

"Recent game chat" -- I'm not clear what "Recent" refers to. Is it just for this game and not for previous games? (It doesn't seem related to the "View full activity and chat history" -- clicking that doesn't remove the word "Recent".) I know this word has always been there, but I never noticed it before and it became confusing to me with this setting. I'd propose to remove the word "Recent" so the setting is clearer. 

I couldn't test the condition: what happens with completed games? Can I still change my setting for a completed game I was in?

**Comment by blackshadowshade** [comment]
So, I was wondering whether it would be better to entirely hide the chat side (as if there were no chat) if chat is private. That way, a third-party can't even tell if there's private chat, because it looks like there's no chat.

**Comment by blackshadowshade** [comment]
@dwvanstone, I've tested the case where a game is completed, and yes, you can still change the chat privacy settings there.

**Comment by cgolubi1** [comment]
> "Recent game chat" -- I'm not clear what "Recent" refers to. Is it just for this game and not for previous games? (It doesn't seem related to the "View full activity and chat history" -- clicking that doesn't remove the word "Recent".) I know this word has always been there, but I never noticed it before and it became confusing to me with this setting. I'd propose to remove the word "Recent" so the setting is clearer.

It has always been there, and it's related to "View full activity and chat history" - but you're right that we don't remove the word recent when the full log is shown.  I'm happy to get rid of it.

**Comment by cgolubi1** [comment]
> So, I was wondering whether it would be better to entirely hide the chat side for a third party (as if there were no chat) if chat is private. That way, a third party can't even tell if there's private chat, because it looks like there's no chat.

Hmm... so, i guess one thing i'll say is that, if chat is private, the third-party will see "chat is private", and game continuation messages, whether or not there is any chat (if you look at `BMInterfaceGameChat::load_game_chat_log()`, you'll see this implementation).  So the only reason that right now the "chat is private" message would alert you to the existence of chat, is that right now players only see the UI to set chat private when chat exists, and right now the default is public chat.

However, given that i expect we're going to implement a default chat privacy user preference pretty soon, at which point the fact that chat is private won't alert players to the existence of chat, i don't think this is a big problem.

I also think that telling non-players chat is private is a good thing, e.g. in the case of a story tournament runner who wants to verify that everyone has their chat set public.

That argument for not changing it convincing to others?

**Comment by blackshadowshade** [comment]
I'm okay with that argument. However, if we leave the message there, I think it looks a bit odd at the moment with the empty cell on the left hand side.

capture

**Comment by cgolubi1** [comment]
Hmm, yeah, let me see if i can do something about that.

**Comment by cgolubi1** [comment]
I haven't had a lot of time, and got sidetracked from this by the caching business (IMO correctly), but i expect to get another version of this up with the requested minor changes in the next day, and i'm hoping we'll be able to get it in for October.

**Comment by cgolubi1** [comment]
Here's the two minor requested UI fixes (change "Recent game chat" to "Game chat", and get rid of the first column when it's empty).

If http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/510/ passes, i'll update the dev site, in hopes i can get approval to merge this before the change freeze (which is nominally today, but i think if we don't have to go another iteration on this, we can push it to tomorrow).

**Comment by blackshadowshade** [comment]
Jenkins has passed. Once you update the dev site, I'll take a look ASAP, and we'll get this thing merged.  :)

**Comment by blackshadowshade** [comment]
BTW, feel free to rebase this either before or after you deploy. I'm happy with the code changes.

**Comment by cgolubi1** [comment]
I updated the dev site, and i'll rebase as soon as i get a chance.

**Comment by blackshadowshade** [comment]
Okay, this looks good to me. After the rebase, I just need to check that there are two files changed, with a diff of +148 and -18.

**Comment by cgolubi1** [comment]
Rebase done.  Jenkins: http://jenkins.buttonweavers.com:8080/job/buttonmen-cgolubi1/511/

**Comment by blackshadowshade** [comment]
Rebase looks good. I'm happy to accept this as is.

**Pull request merged**
