### PR TITLE
New and updated button images

### PR DESCRIPTION
**Pull request by blackshadowshade**
Addresses part of #138.

Kaori has created new images of Elihu and Frasquito which have a light reflex in the top left.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1091/ (if it passes)

### CODE REVIEW

**Comment by blackshadowshade** [comment]
I've just noticed that the background colour isn't set to transparent. I'll get onto her about fixing that.

**Comment by cgolubi1** [comment]
Since there's been no iteration on this yet, let's close it, and open another pull request when the branch is actually ready.  (Reopen if you disagree.)

**Comment by blackshadowshade** [comment]
Okay, reopening this now that it's been updated. I've also changed the title to make it more general.

**Comment by blackshadowshade** [comment]
So, the new images are up for discussion. Are all of these improvements, or would we rather keep some of the old images?

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1103/ (if it passes)

**Comment by blackshadowshade** [comment]
More images added.

**Comment by blackshadowshade** [comment]
I think these are clearly better: Aldric, Bruno, Dirgo, Dr Speculo, Elihu, Flaire, Frasquito, Guillermo, Kiki, Luce, Nerni, Nikolai, Pappy, Synthia, The GM

I think that these are clearly worse: Mothman, Riff, Torg, Vincent, Yeti, Zoe

I think that these are about the same: Aylee, Bun-Bun

Harry Pudding's button has the dice in the recipe in a different order, which is interesting.

**Comment by irilyth** [comment]
I generally agree with blackshadowshade's comments. Couple questions:

* Mothman didn't look any worse to me, and was maybe a little sharper. What didn't you like about it?
* I was amused that neither Torg has the name parallel to the horizontal -- I think *that* would look better.

I don't feel strongly about any of those.

> Harry Pudding's button has the dice in the recipe in a different order, which is interesting.

Wacky. I think it's better to have them in the same order as the recipe in the DB. How'd they even end up different? Is one of them not just a scan of the actual button?

**Comment by blackshadowshade** [comment]
For Mothman, I guess I don't like the look of the numbers in the recipe circles, which look artificial.

As for Harry Pudding, I'm guessing that the one that we currently have is a scan of the original button, while the other one has had the recipe Photoshopped on. It's only a guess though.

**Comment by blackshadowshade** [comment]
Okay, I've reverted the images for Bun-Bun, Riff, Torg, Vincent, Yeti, and Zoe.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1108/ (if it passes)

**Comment by blackshadowshade** [comment]
This only alters existing images, so no new Jenkins run should be necessary.

**Comment by cgolubi1** [comment]
Okay, my understanding from the discussion so far is that y'all would be fine with all these new images, so if i want to merge them, i can.  It sounds like y'all were on the fence about the new Mothman, but decided to keep it anyway?  And i'm not clear from this discussion which Harry Pudding has the same button order as the recipe, so i'll check that.

**Comment by cgolubi1** [comment]
So, for testing, i'm going to bring up a site and:
* Start games with all these buttons and look for problematic artifacts
* Look at the Sluggy Freelance buttonset page - the new Aylee and Kiki are significantly differently shaded (more green, less brown) than the old ones.  Is that good, or does it mean the set looks incongruous as a whole, since you reverted some of the other Sluggy buttons?

**Comment by cgolubi1** [comment]
Games look fine.

I don't see a problem with the Sluggy set overall --- all of the buttons are colored differently from each other, so the pattern i saw in the shading change of Aylee and Kiki doesn't make them look incongruous.

Merging this.

**Pull request merged**
