### PR TITLE
Added a script for calculating head-to-head win percentages

### PR DESCRIPTION
**Pull request by irilyth**
http://jenkins.buttonweavers.com:8080/job/buttonmen-irilyth/31/

### CODE REVIEW

**Comment by cgolubi1** [comment]
Hmm, i thought we thought executable script names didn't end with `.py` (or whatever) suffixes.  Anyway the others in this directory don't.

**Comment by cgolubi1** [comment]
Also:

I think your parser should include something like:
```
  parser.add_option(
    "-c", "--config",
    help="config file containing site parameters",
    type=str, default=".bmrc"
  )
```
the way the other scripts do, so the config file doesn't have to be .bmrc.

Other than that, this appears to work, and i'm fine merging it with those changes (add the -c option, make it executable, make it not end in .py), or let's discuss more if you disagree with any of those.

**Comment by irilyth** [comment]
Sure, seems reasonable.

http://jenkins.buttonweavers.com:8080/job/buttonmen-irilyth/33/changes (if it passes)

**Comment by cgolubi1** [comment]
Looks good.

**Pull request merged**
