### PR TITLE
Added Jota's page that converts XLS-pasted tables into forum tables

### LINKED ISSUE #2356: Allow tables in forum posts
Our users often try to use tables in their forum posts, and we should make it possible for them to do this in a way that actually looks like a table.

Blargh also mentioned that it would be nice to be able to cut and paste the table. For that, we'd need to know what sort of formats to support.

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #2356.

So, I'm just adding Jota's HTML/JQuery page that converts tables from Excel into a [code] block that can be posted into our forums.

I figure that other external tools (like Bagel's button filter) might also fit into the /external folder.

### CODE REVIEW

**Comment by irilyth** [comment]
Does this actually take a .xls file as input? If not, it might make sense to name it based on what it does actually take as input. (At a glance, it looks like maybe it's tab-delimited text?)

(It also doesn't matter a whole lot what it's called, so if no one else cares much, feel free to ignore me.)

**Comment by AdmiralJota** [comment]
Yeah, it takes line/tab delimited text, since that's what you get when you copy a group of cells from Excel and paste it into a textbox on a web page.

**Comment by irilyth** [comment]
Ah, it's for copy and paste from a spreadsheet screen, not for uploading a file or whatever; that makes sense.

If we wanted to give it an accurately descriptive name, we could call it table-converter-tab-to-spaces.html or something. Or just table-converter.html, maybe we'll update it in the future to convert between multiple table formats. :^ )

**Comment by blackshadowshade** [comment]
So, two things:
- I'm happy to change the name to table_converter.html
- I think it would be useful to have a title and instructions on the HTML sheet itself. Anyone feel like doing some wordsmithing here?

**Comment by cgolubi1** [comment]
Let's stand up a dev site and see if this is loadable, shall we?

Meanwhile, i want to take a brief moment to discuss naming, since we haven't had this kind of content on the website before.  You opted for /external/, presumably to indicate that it's not part of the main body of stuff.

Can i countersuggest /tools/, for consistency with the top-level branch where we're keeping the api client, stats stuff, etc?

**Comment by blackshadowshade** [comment]
I considered 'tools' and wondered if it would be confusing in the future, since we would then have ambiguity when referring to the tools folder. However, if you'd prefer 'tools', I'm okay with that.

**Comment by cgolubi1** [comment]
My theory is that it's one thing (user-contributed tools) some of which are displayed on the website and some of which aren't.  We don't get confused between tools/ and test/tools/, after all.

**Comment by blackshadowshade** [comment]
Okay, changes made. The dev site for this can be updated.

**Comment by cgolubi1** [comment]
Created a dev site --- irilyth, when you have a chance can you sync up: transient 54.167.251.230

**Comment by irilyth** [comment]
```transient.dev.buttonweavers.com has address 54.167.251.230```
Done!

**Comment by cgolubi1** [comment]
So one note is that this would be our first JS that people who aren't logged into the site can use (other than the "new player" and "login" code, of course).  I think that's fine because JS runs browser-side, but does anyone have qualms we should think about?

**Comment by blackshadowshade** [comment]
I have no problems with this particular case.

I think that if any future tool hits the database, we should think extra carefully about it.

**Comment by cgolubi1** [comment]
> I think that if any future tool hits the database, we should think extra carefully about it.

Disagree - i think that if any future tool hits the database, we should disallow unauthenticated access to it with no thought whatsoever.  :>)

But, indeed, i'm not going to veto this.  Have folks checked out the actual functionality?  Does it do what we want?

**Comment by cgolubi1** [comment]
It's at http://transient.dev.buttonweavers.com/ui/tools/table_converter.html for those who want to try it out but don't want to hunt for it.

**Comment by cgolubi1** [comment]
Still waiting for someone except the submitter to weigh in on this solution.  Since it's not part of the main site, the bar is pretty low, but i'd like to at least hear from Jota that the online converter does what it was designed to do.

If no one says anything in a couple more days, i'll go ahead and merge this since it is low-risk, but i haven't been able to actually test making it generate a table (i don't have an excel table handy and the input format isn't documented), so i can't +1 that it works.

**Comment by AdmiralJota** [comment]
It looks like it works in some browsers but not others. That is, it produces sensible output in any case, but copying and pasting the output may or may not preserve whitespace correctly depending on what browser/version you're using.

We might be able to fix that by changing the output area from a div to a textarea. Should we do that?

**Comment by blackshadowshade** [comment]
I'm happy to try that.

**Comment by blackshadowshade** [comment]
The div has been changed to a textarea. @cgolubi1, if you wouldn't mind updating the test site, please.

**Comment by blackshadowshade** [comment]
Oh, because I rebased before, I've rebased this again into one commit. You'll need to do a fresh deploy.

**Comment by cgolubi1** [comment]
Okay, no worries.  If you happen to remember not to rebase during dev-site testing, that's great.  Rebuilding now.

**Comment by cgolubi1** [comment]
Actually, i'm going to cheat on this to save the trouble of repointing the DNS, and just copy the new HTML file into place.

**Comment by cgolubi1** [comment]
Okay, should be updated.  Check it out.

**Comment by cgolubi1** [comment]
Next step: AdmiralJota should report on whether http://transient.dev.buttonweavers.com/ui/tools/table_converter.html looks good to merge now.

**Comment by AdmiralJota** [comment]
The </div> after <textarea> should be </textarea>.

Other than that, it seems to work fine.

**Comment by cgolubi1** [comment]
Aight.  I think we're good to go here.  Thanks, all.

**Pull request merged**
