### PR TITLE
Added logic to take into account the size of the die after a trip attack

### LINKED ISSUE #1660: Trip vs Weak or Mighty
In game http://www.buttonweavers.com/ui/game.html?game=6503, Matt wrote:

> It won't let me trip attack with my tH(8) against your Mhf(10), bc "the attacking die cannot roll high enough to capture the target die".  True now, but when they reroll my die should be a (10) and yours should be an (8).

That seems right to me; I think the Trip size check needs to take into account the effects of Weak and Mighty on the target.

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #1660.

Tested using a manual database change, testing a trip attack of a t(8) vs a Mh(10).

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/816/ (if it passes)

### CODE REVIEW

**Comment by cgolubi1** [comment]
This says "deceptively-simple change" to me - i want to see this work in a lot of cases, so i think what i need here is:
* Modify RandomAI so that instead of calculating what trip attacks are valid, it just tries to trip something and sees if it works
* Record a bunch of games on master using that modification, and play them back on this codebase
* Do a quick test for regressions on games which don't involve trip
* Play a bunch of new trip games with the modified RandomAI and look for internal errors
* Write a responderTest showing something like a `tH(8)` trying to target a `(12)` and being rejected, then successfully targeting an `h(12)`

**Comment by cgolubi1** [comment]
Okay, the test plan above was silly --- the whole point of API-based testing is that the backend tells me what attacks it thinks are valid, and if its logic doesn't match what RandomAI thinks the logic should be, eventually it'll break in one direction or the other.  So never mind all that --- the point is just to record a lot of games with trip attacks and play them back, and that should work just fine.

**Comment by cgolubi1** [comment]
Okay, it really took forever to find a game i could regression-test against, but the good news is that this means i'm pretty comfortable that this change doesn't cause any unexpected regressions.  Here's a responder test for you, and it does fail on the old codebase and succeed on the new.  With this test to fix the behavior, i'm happy to accept the pull:
```php
    /**
     * @group fulltest_deps
     *
     * This game regression-tests and fixes the behavior of trip attacks against size-changing Maximum opponents
     */
    public function test_interface_game_040() {

        // responder003 is the POV player, so if you need to fake
        // login as a different player e.g. to submit an attack, always
        // return to responder003 as soon as you've done so
        $this->game_number = 40;
        $_SESSION = $this->mock_test_user_login('responder003');


        $gameId = $this->verify_api_createGame(
            array(
                3, 0, 2, 5, 3,          // die sizes for r3: 6, 8, 10, 10, 20
                5, 6, 18,               // die skills for r3: H, M, v
                0, 3, 2, 0, 0, 1,       // distribution of skills onto dice for r3
                0, 5, 1, 3, 0,          // die sizes for r4: 4, 4, 6, 10, 20
                18, 0, 18, 17,          // die skills for r4: B, t, v
                2, 4, 2, 2, 2, 1, 2, 1, // distribution of skills onto dice for r4
                7, 10, 20,              // initial die rolls for r3 (note: Maximum dice don't use random values)
                3, 1, 1, 1, 3           // initial die rolls for r4
            ),
            'responder003', 'responder004', 'RandomBMMixed', 'RandomBMMixed', 3
        );

        $expData = $this->generate_init_expected_data_array($gameId, 'responder003', 'responder004', 3, 'START_TURN');
        $expData['gameSkillsInfo'] = $this->get_skill_info(array('RandomBMMixed', 'Berserk', 'Maximum', 'Mighty', 'Trip', 'Value'));
        $expData['playerDataArray'][0]['button'] = array('name' => 'RandomBMMixed', 'recipe' => 'vHM(4) v(8) H(10) M(10) (20)', 'artFilename' => 'BMdefaultRound.png');
        $expData['playerDataArray'][1]['button'] = array('name' => 'RandomBMMixed', 'recipe' => '(4) tB(4) tBv(6) (10) v(20)', 'artFilename' => 'BMdefaultRound.png');
        $expData['activePlayerIdx'] = 1;
        $expData['playerWithInitiativeIdx'] = 1;
        $expData['validAttackTypeArray'] = array('Skill', 'Trip');
        $expData['playerDataArray'][0]['waitingOnAction'] = FALSE;
        $expData['playerDataArray'][0]['roundScore'] = 25.5;
        $expData['playerDataArray'][1]['roundScore'] = 11;
        $expData['playerDataArray'][0]['sideScore'] = 9.7;
        $expData['playerDataArray'][1]['sideScore'] = -9.7;
        $expData['playerDataArray'][0]['activeDieArray'] = array(
            array('value' => 4, 'sides' => 4, 'skills' => array('Value', 'Mighty', 'Maximum'), 'properties' => array('ValueRelevantToScore'), 'recipe' => 'vHM(4)', 'description' => 'Value Mighty Maximum 4-sided die'),
            array('value' => 7, 'sides' => 8, 'skills' => array('Value'), 'properties' => array('ValueRelevantToScore'), 'recipe' => 'v(8)', 'description' => 'Value 8-sided die'),
            array('value' => 10, 'sides' => 10, 'skills' => array('Mighty'), 'properties' => array(), 'recipe' => 'H(10)', 'description' => 'Mighty 10-sided die'),
            array('value' => 10, 'sides' => 10, 'skills' => array('Maximum'), 'properties' => array(), 'recipe' => 'M(10)', 'description' => 'Maximum 10-sided die'),
            array('value' => 20, 'sides' => 20, 'skills' => array(), 'properties' => array(), 'recipe' => '(20)', 'description' => '20-sided die'),
        );
        $expData['playerDataArray'][1]['activeDieArray'] = array(
            array('value' => 3, 'sides' => 4, 'skills' => array(), 'properties' => array(), 'recipe' => '(4)', 'description' => '4-sided die'),
            array('value' => 1, 'sides' => 4, 'skills' => array('Trip', 'Berserk'), 'properties' => array(), 'recipe' => 'tB(4)', 'description' => 'Trip Berserk 4-sided die'),
            array('value' => 1, 'sides' => 6, 'skills' => array('Trip', 'Berserk', 'Value'), 'properties' => array('ValueRelevantToScore'), 'recipe' => 'tBv(6)', 'description' => 'Trip Berserk Value 6-sided die'),
            array('value' => 1, 'sides' => 10, 'skills' => array(), 'properties' => array(), 'recipe' => '(10)', 'description' => '10-sided die'),
            array('value' => 3, 'sides' => 20, 'skills' => array('Value'), 'properties' => array('ValueRelevantToScore'), 'recipe' => 'v(20)', 'description' => 'Value 20-sided die'),
        );
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => '', 'message' => 'responder004 won initiative for round 1. Initial die values: responder003 rolled [vHM(4):4, v(8):7, H(10):10, M(10):10, (20):20], responder004 rolled [(4):3, tB(4):1, tBv(6):1, (10):1, v(20):3]. responder004 has dice which are not counted for initiative due to die skills: [tB(4), tBv(6)].'));
        $expData['gameActionLogCount'] = 1;

        $retval = $this->verify_api_loadGameData($expData, $gameId, 10);


        // Verify that a Trip attack vHM(4):4 <= tB(4) is rejected because tB(4) won't be able to roll high enough once vHM(4) grows
        $_SESSION = $this->mock_test_user_login('responder004');
        $this->verify_api_submitTurn_failure(
            array(),
            'The attacking die cannot roll high enough to capture the target die',
            $retval, array(array(1, 1), array(0, 0)),
            $gameId, 1, 'Trip', 1, 0, '');
        $_SESSION = $this->mock_test_user_login('responder003');

        $retval = $this->verify_api_loadGameData($expData, $gameId, 10);

        // Verify that a Trip attack vHM(4):4 <= tBv(6) is allowed because tBv(6) will still be able to roll high enough once vHM(4) grows
        $_SESSION = $this->mock_test_user_login('responder004');
        $this->verify_api_submitTurn(
            array(5),
            'responder004 performed Trip attack using [tBv(6):1] against [vHM(4):4]; Attacker tBv(6) rerolled 1 => 5; Defender vHM(4) recipe changed to vHM(6), rerolled 4 => 6, was not captured. ',
            $retval, array(array(1, 2), array(0, 0)),
            $gameId, 1, 'Trip', 1, 0, '');
        $_SESSION = $this->mock_test_user_login('responder003');

        $expData['activePlayerIdx'] = 0;
        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder004', 'message' => 'responder004 performed Trip attack using [tBv(6):1] against [vHM(4):4]; Attacker tBv(6) rerolled 1 => 5; Defender vHM(4) recipe changed to vHM(6), rerolled 4 => 6, was not captured'));
        $expData['gameActionLogCount'] = 2;
        $expData['playerDataArray'][0]['activeDieArray'][0]['description'] = "Value Mighty Maximum 6-sided die";
        $expData['playerDataArray'][0]['activeDieArray'][0]['properties'] = array("ValueRelevantToScore", "HasJustGrown");
        $expData['playerDataArray'][0]['activeDieArray'][0]['recipe'] = "vHM(6)";
        $expData['playerDataArray'][0]['activeDieArray'][0]['sides'] = 6;
        $expData['playerDataArray'][0]['activeDieArray'][0]['value'] = 6;
        $expData['playerDataArray'][0]['roundScore'] = 26.5;
        $expData['playerDataArray'][0]['sideScore'] = 9.0;
        $expData['playerDataArray'][0]['waitingOnAction'] = true;
        $expData['playerDataArray'][1]['activeDieArray'][2]['properties'] = array("ValueRelevantToScore", "JustPerformedTripAttack", "JustPerformedUnsuccessfulAttack");
        $expData['playerDataArray'][1]['activeDieArray'][2]['value'] = 5;
        $expData['playerDataArray'][1]['roundScore'] = 13;
        $expData['playerDataArray'][1]['sideScore'] = -9.0;
        $expData['playerDataArray'][1]['waitingOnAction'] = false;
        $expData['validAttackTypeArray'] = array("Power");

        $retval = $this->verify_api_loadGameData($expData, $gameId, 10);
    }
 }
```

**Comment by blackshadowshade** [comment]
Okay, responder test added.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/852/ (if it passes)

**Comment by cgolubi1** [comment]
Looks good.  Merging.

**Pull request merged**
