### PR TITLE
Push changes from master to staging on 2017-12-29

### PR DESCRIPTION
**Pull request by cgolubi1**
This update brings these approved pulls to the staging branch:

* User-visible:
    * #2275, #2303: Remove "changed size due to turbo" message
    * #2277: Add interaction descriptions for skills lost during radioactive decay
    * #2273: Add description of interaction between Konstant and TimeAndSpace
    * #2279, #2305, #2308: Add support for Gordo and Guillermo
    * #2290: Add ability to cancel open games
    * #2306: Fix a memory exhaustion bug triggered by too many zero-sided dice
* Ideally not user-visible:
    * #2276: remove files used for pagodabox

Database updates: None

Once this pull is merged, i will load the changes on staging.buttonweavers.com as part of #2309.

### CODE REVIEW

**Comment by cgolubi1** [comment]
Merging and loading on staging.

**Comment by cgolubi1** [comment]
Okay, staging site is updated.  Check it out folks, and if i don't hear any complaints before the 2nd, i'll do a prod release.

**Comment by dwvanstone** [comment]
I've played with the staging site - the only part I found unclear was the change #2277. However, it's not a reason to hold the release.

**Comment by blackshadowshade** [comment]
#2316 should address @dwvanstone's concerns.

**Pull request merged**
