### PR TITLE
Add a cron job to test whether the database site_type matches the javascript site_type

### PR DESCRIPTION
**Pull request by cgolubi1**
There's not an issue for this, but i'm tired of getting bitten by it.

### CODE REVIEW

**Comment by cgolubi1** [comment]
Obviously no need to merge during the freeze, but take a look and see if it seems fine.

**Comment by blackshadowshade** [comment]
I take it you've run this script manually and that it works correctly.

Where does the echo go to? And what does the return value do?

Also, I'd consider putting this check slightly further away from the backup job, even perhaps before it, to guarantee no conflict.

**Comment by cgolubi1** [comment]
Oh, yeah, sorry.  Here's what the results looks like when the sites don't match:

```
ubuntu-xenial,[~],00:23(1)$ sudo /usr/local/bin/test_buttonmen_config
site_type configuration mismatch between database and config file
* database contains: development
* /var/www/ui/js/Config.js contains: production
ubuntu-xenial,[~],00:25(1)$
```

and here's when they do:

```
ubuntu-xenial,[~],00:25(0)$ sudo /usr/local/bin/test_buttonmen_config
ubuntu-xenial,[~],00:26(0)$
```

Sure, i can move the check half an hour away from the backup, no problem.

**Comment by blackshadowshade** [comment]
So, the output doesn't go into the logs, it just ends up on the command line somewhere?

**Comment by cgolubi1** [comment]
> So, the output doesn't go into the logs, it just ends up on the command line somewhere?

So the cron job runs it once a day, and if there's output, it'll get e-mailed to the same people who get the e-mails about weird things that showed up in the apache logs.  So that's how i expect to detect mismatches on dev/staging/prod sites.

**Comment by blackshadowshade** [comment]
Ah, excellent, that makes sense.

**Comment by blackshadowshade** [comment]
So, I'm happy to approve this once the pull freeze is over.

**Comment by blackshadowshade** [comment]
I'll just note that CircleCI passes: https://app.circleci.com/pipelines/github/cgolubi1/buttonmen/93/workflows/2a650c2b-c1e5-4f43-8aac-2e4677575852

**Comment by cgolubi1** [comment]
This should be mergeable now.

**Comment by blackshadowshade** [comment]
Merged.

**Pull request merged**
