### PR TITLE
Added new scripts game-create and game-data for creating and getting data about games

### PR DESCRIPTION
**Pull request by irilyth**
http://jenkins.buttonweavers.com:8080/job/buttonmen-irilyth/43/ (if it passes)

### CODE REVIEW

**Comment by cgolubi1** [comment]
Any interest in supporting users whose default python doesn't have yaml available?  This diff worked for me both under a non-yaml-having python (where i didn't get the format option, and json worked), and a yaml-having python (where i got the format option and yaml output worked):
```diff
diff --git a/tools/api-client/python/game-data b/tools/api-client/python/game-data
index 38f8f27..452c05e 100755
--- a/tools/api-client/python/game-data
+++ b/tools/api-client/python/game-data
@@ -13,7 +13,11 @@ import argparse
 import json
 import os
 import sys
-import yaml
+try:
+  import yaml
+  YAML_AVAILABLE = True
+except ImportError:
+  YAML_AVAILABLE = False
 
 # Import Button Men utilities.
 
@@ -24,9 +28,10 @@ import bmutils
 
 # A class to not use anchors and aliases when dumping YAML.
 
-class noalias_dumper(yaml.SafeDumper):
-  def ignore_aliases(self, _data):
-    return True
+if YAML_AVAILABLE:
+  class noalias_dumper(yaml.SafeDumper):
+    def ignore_aliases(self, _data):
+      return True
 
 ### Functions
 
@@ -38,9 +43,10 @@ def parse_arguments():
 
   parser.add_argument('gamenumber', help="game number")
 
-  parser.add_argument('--format',
-                      choices = ['json', 'yaml'], default = 'yaml',
-                      help = "output data format (default: yaml)")
+  if YAML_AVAILABLE:
+    parser.add_argument('--format',
+                        choices = ['json', 'yaml'], default = 'yaml',
+                        help = "output data format (default: yaml)")
 
   # Add general optional arguments.
 
@@ -79,7 +85,7 @@ game = bmconn.wrap_load_game_data(args.gamenumber)
 
 # Print the game data.
 
-if args.format == 'json':
+if not YAML_AVAILABLE or args.format == 'json':
   print(json.dumps(game, indent=1, sort_keys=True))
 else:
   print(yaml.dump(game, Dumper=noalias_dumper))
```

**Comment by irilyth** [comment]
Sure, seems reasonable. That's in aec2cec now; http://jenkins.buttonweavers.com:8080/job/buttonmen-irilyth/47/ (if it passes).

**Comment by cgolubi1** [comment]
Great, thank you!  Rebase and i'll merge it.

**Comment by irilyth** [comment]
Done! 4ee2608938edc312ed2181b5b34fb58d56cfea48, and http://jenkins.buttonweavers.com:8080/job/buttonmen-irilyth/48/ if it passes.

**Comment by cgolubi1** [comment]
Looks good; merging.

**Pull request merged**
