### PR TITLE
Added new die images

### PR DESCRIPTION
**Pull request by blackshadowshade**
This pull request just adds the new images that we'll need, once we add the logic allowing players to select the die images that they desire. This has been split out of #2022.

I presume that Jenkins shouldn't care one iota about this pull request.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1182/

### CODE REVIEW

**Comment by cgolubi1** [comment]
The realistic d6 active is oriented 180 degrees rotated from the d6 inactive and d6 taken.  I find that distracting paging through them.  Should all three be at the same orientation?

**Comment by cgolubi1** [comment]
Ditto for the d10.

**Comment by cgolubi1** [comment]
That's what i see --- i wasn't fully following the discussion about the images, so if we decided to do the 180 degree rotations intentionally, point me to that discussion.  My druthers would be to have the three images be identical modulo coloring for a given die size/style.

**Comment by blackshadowshade** [comment]
So, I've replaced the realistic active d6 and d10 images so that they now have the same shapes as the inactive and taken variants.

However, I've searched in my email, and I can't seem to find a version of the realistic active d10 image with solid inner lines. @Hurtay, could you help out here?

**Comment by Hurtay** [comment]
Maybe I didn't make/send them because I understood the discussion in issue #822 that we don't want the realistic shapes at all. I remember having concentrated all efforts on the symmetric shapes.
I'll check if I've got them, otherwise I'll hopefully create them soonish. But we've got no internet at home due to our provider's crashdown so I might not be able to send them this weekend.

**Comment by blackshadowshade** [comment]
Okay, @Hurtay has sent me the image for the realistic active d10, so I've replaced that. This should now be ready to go. I presume that you won't need a new Jenkins run for this now.

**Comment by cgolubi1** [comment]
LGTM; ready to merge once we're done with the July release.

**Pull request merged**
