### PR TITLE
Added images for Bridge and Tunnel buttons

### LINKED ISSUE #2702: Bridge and Tunnel button artwork
Here's what I put together for the rest of Bridge and Tunnel.  The artwork and photos are used with permission, and any images I used that were not in Fog's files were listed as royalty free.  This and the "Generic The Fog" should round out all the buttons in the set, both active and awaiting their time.

AgentOrange
GButton
Huitzilopochtil
PhantomZero
PinballWizard
Steve
TheGrotch

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #2702.

### CODE REVIEW

**Comment by TheOrgg** [comment]
Took a bit to figure out how to view the files, but it looks correct to me.

**Comment by cgolubi1** [comment]
Check out http://stopgap.dev.buttonweavers.com/ui/buttons.html?set=Bridge%20and%20Tunnel --- as soon as someone other than TheOrgg says it's good to go, i'll merge.

**Comment by TheOrgg** [comment]
The Grotch is missing (and misspelled as 'gratch.')

**Comment by blackshadowshade** [comment]
Do we have any evidence for the spelling being "Gratch" or "Grotch"? I'd like to get this right once and for all if we can.

**Comment by TheOrgg** [comment]
I do, actually!  Straight from the... *clears throat*...  Horse's Mouth.

Grotchhh

**Comment by blackshadowshade** [comment]
Excellent! I've added the necessary changes to update the name in the database.

@cgolubi1, let me know if you want me to rebase this pull request.

**Comment by TheOrgg** [comment]
Was the image for The Grotch updated?

**Comment by blackshadowshade** [comment]
The image remained unchanged, but the database was altered to change the spelling from Gratch to Grotch.

**Comment by TheOrgg** [comment]
The image for Grotch's button is on the original issue page.

**Comment by blackshadowshade** [comment]
The point is that there was no need for the image to be updated, as far as I am aware. The image we had in the first commit was correct, it just wasn't showing up because the page wasn't looking for the right name, because the name in the database was incorrect. Now that the mismatch has been corrected, the image should be showing up.

**Pull request merged**
