### PR TITLE
Push changes from staging to production on 2022-01-07

### PR DESCRIPTION
**Pull request by cgolubi1**
This update brings these approved pulls to the production branch:

* #2790
* #2796
* #2797
* #2706
* #2775
* #2771
* #2666
* #2802

Database updates:
```
UPDATES=deploy/database/updates/02346_2021fanatics_01.sql
deploy/database/updates/02664_corpo_world_01.sql
deploy/database/updates/02664_corpo_world_02.sql
SCRIPTS=
```

Once this pull is merged, i will load the changes on www.buttonweavers.com as part of #700.

### CODE REVIEW

**Comment by cgolubi1** [comment]
Fascinating.  On the prod site, the buttonset ID 86 is already in use, for the set Big Top, which is ID 76 on staging.  Well, i installed CyberCorp as ID 76, and i think we're okay.  Not sure if that's worth ever sorting out.  Definitely not right now.

**Comment by blackshadowshade** [comment]
We hardcode the button set IDs, so it's probably worthwhile cleaning this up so that the database matches what we have in the codebase.

**Comment by cgolubi1** [comment]
> We hardcode the button set IDs, so it's probably worthwhile cleaning this up so that the database matches what we have in the codebase.

I agree, but it's enough of a hassle that maybe it would be better to update the codebase to match prod (and make staging etc match that).  E.g. there is a player who has Big Top as their favorite buttonset, the buttons are attached to the set, etc.  My suggestion is that i futz around on staging to make it match prod, and then we make the codebase match them both.

**Comment by blackshadowshade** [comment]
Yep, I don't mind changing the codebase to match the database, just as long as the two are consistent.

**Comment by cgolubi1** [comment]
Filed #2807 so we don't lose this

**Pull request merged**
