### PR TITLE
Stopped mood skill triggering after a trip attack

### LINKED ISSUE #1723: Unexpected internal error during trip attack with mood swing die
I was attempting to do a trip attack on the dev site, and somehow, I got an internal error.

capture

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #1723.

Game 1857 on the dev site will need to be fixed manually once this pull request is accepted. The fix is simply to set the appropriate die value to a valid value, and then change the game status from BROKEN to ACTIVE.

Tested Jenniegirl vs Jenniegirl.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/912/

### CODE REVIEW

**Comment by cgolubi1** [comment]
shadowshade's comment on #1723:

> So, I'm looking at this one at the moment, and the issue seems to be that mood should trigger at the beginning of the trip attack, not at the end.

But here the fix simply removes the mood triggering if trip has just happened.  So, that might be the right fix or it might not, but i want to see it in a responderTest.  I'll create one using the dev-site game as a template.

**Comment by cgolubi1** [comment]
Here we go --- this responderTest reproduces the bug and, with the old code, throws an internal error on game load:
```diff
diff --git a/test/src/api/responderTest.php b/test/src/api/responderTest.php
index 01aa296..0a59d03 100644
--- a/test/src/api/responderTest.php
+++ b/test/src/api/responderTest.php
@@ -12383,4 +12383,107 @@ class responderTest extends PHPUnit_Framework_TestCase {
 
         $retval = $this->verify_api_loadGameData($expData, $gameId, 10);
     }
+
+    /**
+     * @depends test_request_savePlayerInfo
+     * @group fulltest_deps
+     *
+     * This test reproduces a trip mood bug, and standardizes the
+     * behavior of trip mood dice during successful trip attacks.
+     */
+    public function test_interface_game_043() {
+
+        // responder003 is the POV player, so if you need to fake
+        // login as a different player e.g. to submit an attack, always
+        // return to responder003 as soon as you've done so
+        $this->game_number = 43;
+        $_SESSION = $this->mock_test_user_login('responder003');
+
+
+        ////////////////////
+        // initial game setup
+
+        // 0 of JennieGirl's dice, and 6 of Giant's dice, are initially rolled
+        $gameId = $this->verify_api_createGame(
+            array(13, 2, 7, 4, 6, 20),
+            'responder003', 'responder004', 'JennieGirl', 'Giant', 3);
+
+        // Initial expected game data object
+        $expData = $this->generate_init_expected_data_array($gameId, 'responder003', 'responder004', 3, 'SPECIFY_DICE');
+        $expData['gameSkillsInfo'] = $this->get_skill_info(array('Giant', 'Chance', 'Mood', 'Ornery', 'Rage', 'Reserve', 'Shadow', 'TimeAndSpace', 'Trip'));
+        $expData['playerDataArray'][0]['button'] = array('name' => 'Jenniegirl', 'recipe' => 'Gst(S) Gst(S)? Gst(S)^ cor(V) cor@(X)!', 'artFilename' => 'BMdefaultRound.png');
+        $expData['playerDataArray'][1]['button'] = array('name' => 'Giant', 'recipe' => '(20) (20) (20) (20) (20) (20)', 'artFilename' => 'giant.png');
+        $expData['playerDataArray'][0]['swingRequestArray'] = array('S' => array(6, 20));
+        $expData['playerDataArray'][1]['waitingOnAction'] = FALSE;
+        $expData['playerDataArray'][0]['activeDieArray'] = array(
+            array('value' => null, 'sides' => null, 'skills' => array('Rage', 'Shadow', 'Trip'), 'properties' => array(), 'recipe' => 'Gst(S)', 'description' => 'Rage Shadow Trip S Swing Die'),
+            array('value' => null, 'sides' => null, 'skills' => array('Rage', 'Shadow', 'Trip', 'Mood'), 'properties' => array(), 'recipe' => 'Gst(S)?', 'description' => 'Rage Shadow Trip S Mood Swing Die'),
+            array('value' => null, 'sides' => null, 'skills' => array('Rage', 'Shadow', 'Trip', 'TimeAndSpace'), 'properties' => array(), 'recipe' => 'Gst^(S)', 'description' => 'Rage Shadow Trip TimeAndSpace S Swing Die'),
+        );
+        $expData['playerDataArray'][1]['activeDieArray'] = array(
+            array('value' => null, 'sides' => 20, 'skills' => array(), 'properties' => array(), 'recipe' => '(20)', 'description' => '20-sided die'),
+            array('value' => null, 'sides' => 20, 'skills' => array(), 'properties' => array(), 'recipe' => '(20)', 'description' => '20-sided die'),
+            array('value' => null, 'sides' => 20, 'skills' => array(), 'properties' => array(), 'recipe' => '(20)', 'description' => '20-sided die'),
+            array('value' => null, 'sides' => 20, 'skills' => array(), 'properties' => array(), 'recipe' => '(20)', 'description' => '20-sided die'),
+            array('value' => null, 'sides' => 20, 'skills' => array(), 'properties' => array(), 'recipe' => '(20)', 'description' => '20-sided die'),
+            array('value' => null, 'sides' => 20, 'skills' => array(), 'properties' => array(), 'recipe' => '(20)', 'description' => '20-sided die'),
+        );
+
+        $retval = $this->verify_api_loadGameData($expData, $gameId, 10);
+
+
+        ////////////////////
+        // Move 01 - responder003 specifies swing dice
+        // this causes 3 of JennieGirl's dice to be rolled
+
+        $this->verify_api_submitDieValues(
+            array(2, 1, 2),
+            $gameId, 1, array('S' => 6), NULL);
+
+        $expData['validAttackTypeArray'] = array('Skill', 'Shadow', 'Trip');
+        $expData['gameState'] = 'START_TURN';
+        $expData['activePlayerIdx'] = 0;
+        $expData['playerWithInitiativeIdx'] = 0;
+        $expData['playerDataArray'][0]['roundScore'] = 9;
+        $expData['playerDataArray'][1]['roundScore'] = 60;
+        $expData['playerDataArray'][0]['sideScore'] = -34.0;
+        $expData['playerDataArray'][1]['sideScore'] = 34.0;
+        $expData['playerDataArray'][0]['activeDieArray'][0]['value'] = 2;
+        $expData['playerDataArray'][0]['activeDieArray'][0]['sides'] = 6;
+        $expData['playerDataArray'][0]['activeDieArray'][0]['description'] .= ' (with 6 sides)';
+        $expData['playerDataArray'][0]['activeDieArray'][1]['value'] = 1;
+        $expData['playerDataArray'][0]['activeDieArray'][1]['sides'] = 6;
+        $expData['playerDataArray'][0]['activeDieArray'][1]['description'] .= ' (with 6 sides)';
+        $expData['playerDataArray'][0]['activeDieArray'][2]['value'] = 2;
+        $expData['playerDataArray'][0]['activeDieArray'][2]['sides'] = 6;
+        $expData['playerDataArray'][0]['activeDieArray'][2]['description'] .= ' (with 6 sides)';
+        $expData['playerDataArray'][1]['activeDieArray'][0]['value'] = 13;
+        $expData['playerDataArray'][1]['activeDieArray'][1]['value'] = 2;
+        $expData['playerDataArray'][1]['activeDieArray'][2]['value'] = 7;
+        $expData['playerDataArray'][1]['activeDieArray'][3]['value'] = 4;
+        $expData['playerDataArray'][1]['activeDieArray'][4]['value'] = 6;
+        $expData['playerDataArray'][1]['activeDieArray'][5]['value'] = 20;
+        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder003', 'message' => 'responder003 set swing values: S=6'));
+        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => '', 'message' => 'responder003 won initiative for round 1. Initial die values: responder003 rolled [Gst(S=6):2, Gst(S=6)?:1, Gst^(S=6):2], responder004 rolled [(20):13, (20):2, (20):7, (20):4, (20):6, (20):20]. responder004\'s button has the "slow" button special, and cannot win initiative normally.'));
+        $expData['gameActionLogCount'] += 2;
+
+        $retval = $this->verify_api_loadGameData($expData, $gameId, 10);
+
+
+        ////////////////////
+        // Move 02 - responder003 performs a trip attack using Gst(S=6)?:1 against (20):20
+        $this->verify_api_submitTurn(
+            array(
+                4,  // resize attacker to index 4 (20 sides)
+                15, // attacker rolls 15
+                4,  // defender rolls 4
+                3,  // resize attacker again (wrongly) to index 3 (12 sides)
+            ),
+            'responder003 performed Trip attack using [Gst(S=6)?:1] against [(20):20]; Attacker Gst(S=6)? remained the same size, recipe changed from Gst(S=6)? to Gst(S=20)?, rerolled 1 => 15; Defender (20) rerolled 20 => 4, was captured. ',
+            $retval, array(array(0, 1), array(1, 5)),
+            $gameId, 1, 'Trip', 0, 1, '');
+
+        // This yields an internal error: Caught exception in BMInterface::load_game: Invalid die value: 15 is not between 1 and 12 for die st(S)?
+        $retval = $this->verify_api_loadGameData($expData, $gameId, 10);
+    }
 }
```

**Comment by cgolubi1** [comment]
Okay, after applying this change, this responderTest passes, which is a good sign.  IMO, the test should be folded into the test suite:
```diff
diff --git a/test/src/api/responderTest.php b/test/src/api/responderTest.php
index 01aa296..3981c0c 100644
--- a/test/src/api/responderTest.php
+++ b/test/src/api/responderTest.php
@@ -12383,4 +12383,124 @@ class responderTest extends PHPUnit_Framework_TestCase {
 
         $retval = $this->verify_api_loadGameData($expData, $gameId, 10);
     }
+
+    /**
+     * @depends test_request_savePlayerInfo
+     * @group fulltest_deps
+     *
+     * This test reproduces a trip mood bug, and standardizes the
+     * behavior of trip mood dice during successful trip attacks.
+     */
+    public function test_interface_game_043() {
+
+        // responder003 is the POV player, so if you need to fake
+        // login as a different player e.g. to submit an attack, always
+        // return to responder003 as soon as you've done so
+        $this->game_number = 43;
+        $_SESSION = $this->mock_test_user_login('responder003');
+
+
+        ////////////////////
+        // initial game setup
+
+        // 0 of JennieGirl's dice, and 6 of Giant's dice, are initially rolled
+        $gameId = $this->verify_api_createGame(
+            array(13, 2, 7, 4, 6, 20),
+            'responder003', 'responder004', 'JennieGirl', 'Giant', 3);
+
+        // Initial expected game data object
+        $expData = $this->generate_init_expected_data_array($gameId, 'responder003', 'responder004', 3, 'SPECIFY_DICE');
+        $expData['gameSkillsInfo'] = $this->get_skill_info(array('Giant', 'Chance', 'Mood', 'Ornery', 'Rage', 'Reserve', 'Shadow', 'TimeAndSpace', 'Trip'));
+        $expData['playerDataArray'][0]['button'] = array('name' => 'Jenniegirl', 'recipe' => 'Gst(S) Gst(S)? Gst(S)^ cor(V) cor@(X)!', 'artFilename' => 'BMdefaultRound.png');
+        $expData['playerDataArray'][1]['button'] = array('name' => 'Giant', 'recipe' => '(20) (20) (20) (20) (20) (20)', 'artFilename' => 'giant.png');
+        $expData['playerDataArray'][0]['swingRequestArray'] = array('S' => array(6, 20));
+        $expData['playerDataArray'][1]['waitingOnAction'] = FALSE;
+        $expData['playerDataArray'][0]['activeDieArray'] = array(
+            array('value' => null, 'sides' => null, 'skills' => array('Rage', 'Shadow', 'Trip'), 'properties' => array(), 'recipe' => 'Gst(S)', 'description' => 'Rage Shadow Trip S Swing Die'),
+            array('value' => null, 'sides' => null, 'skills' => array('Rage', 'Shadow', 'Trip', 'Mood'), 'properties' => array(), 'recipe' => 'Gst(S)?', 'description' => 'Rage Shadow Trip S Mood Swing Die'),
+            array('value' => null, 'sides' => null, 'skills' => array('Rage', 'Shadow', 'Trip', 'TimeAndSpace'), 'properties' => array(), 'recipe' => 'Gst^(S)', 'description' => 'Rage Shadow Trip TimeAndSpace S Swing Die'),
+        );
+        $expData['playerDataArray'][1]['activeDieArray'] = array(
+            array('value' => null, 'sides' => 20, 'skills' => array(), 'properties' => array(), 'recipe' => '(20)', 'description' => '20-sided die'),
+            array('value' => null, 'sides' => 20, 'skills' => array(), 'properties' => array(), 'recipe' => '(20)', 'description' => '20-sided die'),
+            array('value' => null, 'sides' => 20, 'skills' => array(), 'properties' => array(), 'recipe' => '(20)', 'description' => '20-sided die'),
+            array('value' => null, 'sides' => 20, 'skills' => array(), 'properties' => array(), 'recipe' => '(20)', 'description' => '20-sided die'),
+            array('value' => null, 'sides' => 20, 'skills' => array(), 'properties' => array(), 'recipe' => '(20)', 'description' => '20-sided die'),
+            array('value' => null, 'sides' => 20, 'skills' => array(), 'properties' => array(), 'recipe' => '(20)', 'description' => '20-sided die'),
+        );
+
+        $retval = $this->verify_api_loadGameData($expData, $gameId, 10);
+
+
+        ////////////////////
+        // Move 01 - responder003 specifies swing dice
+        // this causes 3 of JennieGirl's dice to be rolled
+
+        $this->verify_api_submitDieValues(
+            array(2, 1, 2),
+            $gameId, 1, array('S' => 6), NULL);
+
+        $expData['validAttackTypeArray'] = array('Skill', 'Shadow', 'Trip');
+        $expData['gameState'] = 'START_TURN';
+        $expData['activePlayerIdx'] = 0;
+        $expData['playerWithInitiativeIdx'] = 0;
+        $expData['playerDataArray'][0]['roundScore'] = 9;
+        $expData['playerDataArray'][1]['roundScore'] = 60;
+        $expData['playerDataArray'][0]['sideScore'] = -34.0;
+        $expData['playerDataArray'][1]['sideScore'] = 34.0;
+        $expData['playerDataArray'][0]['activeDieArray'][0]['value'] = 2;
+        $expData['playerDataArray'][0]['activeDieArray'][0]['sides'] = 6;
+        $expData['playerDataArray'][0]['activeDieArray'][0]['description'] .= ' (with 6 sides)';
+        $expData['playerDataArray'][0]['activeDieArray'][1]['value'] = 1;
+        $expData['playerDataArray'][0]['activeDieArray'][1]['sides'] = 6;
+        $expData['playerDataArray'][0]['activeDieArray'][1]['description'] .= ' (with 6 sides)';
+        $expData['playerDataArray'][0]['activeDieArray'][2]['value'] = 2;
+        $expData['playerDataArray'][0]['activeDieArray'][2]['sides'] = 6;
+        $expData['playerDataArray'][0]['activeDieArray'][2]['description'] .= ' (with 6 sides)';
+        $expData['playerDataArray'][1]['activeDieArray'][0]['value'] = 13;
+        $expData['playerDataArray'][1]['activeDieArray'][1]['value'] = 2;
+        $expData['playerDataArray'][1]['activeDieArray'][2]['value'] = 7;
+        $expData['playerDataArray'][1]['activeDieArray'][3]['value'] = 4;
+        $expData['playerDataArray'][1]['activeDieArray'][4]['value'] = 6;
+        $expData['playerDataArray'][1]['activeDieArray'][5]['value'] = 20;
+        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder003', 'message' => 'responder003 set swing values: S=6'));
+        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => '', 'message' => 'responder003 won initiative for round 1. Initial die values: responder003 rolled [Gst(S=6):2, Gst(S=6)?:1, Gst^(S=6):2], responder004 rolled [(20):13, (20):2, (20):7, (20):4, (20):6, (20):20]. responder004\'s button has the "slow" button special, and cannot win initiative normally.'));
+        $expData['gameActionLogCount'] += 2;
+
+        $retval = $this->verify_api_loadGameData($expData, $gameId, 10);
+
+
+        ////////////////////
+        // Move 02 - responder003 performs a trip attack using Gst(S=6)?:1 against (20):20
+        $this->verify_api_submitTurn(
+            array(
+                4,  // resize attacker to index 4 (20 sides)
+                15, // attacker rolls 15
+                4,  // defender rolls 4
+            ),
+            'responder003 performed Trip attack using [Gst(S=6)?:1] against [(20):20]; Attacker Gst(S=6)? remained the same size, recipe changed from Gst(S=6)? to Gst(S=20)?, rerolled 1 => 15; Defender (20) rerolled 20 => 4, was captured. ',
+            $retval, array(array(0, 1), array(1, 5)),
+            $gameId, 1, 'Trip', 0, 1, '');
+
+        $expData['validAttackTypeArray'] = array('Power', 'Skill');
+        $expData['activePlayerIdx'] = 1;
+        $expData['playerDataArray'][0]['waitingOnAction'] = FALSE;
+        $expData['playerDataArray'][1]['waitingOnAction'] = TRUE;
+        $expData['playerDataArray'][0]['roundScore'] = 36;
+        $expData['playerDataArray'][1]['roundScore'] = 50;
+        $expData['playerDataArray'][0]['sideScore'] = -9.3;
+        $expData['playerDataArray'][1]['sideScore'] = 9.3;
+        $expData['playerDataArray'][0]['capturedDieArray'][] = array('value' => 4, 'sides' => 20, 'recipe' => '(20)', 'properties' => array('WasJustCaptured'));
+        array_splice($expData['playerDataArray'][1]['activeDieArray'], 5, 1);
+        $expData['playerDataArray'][0]['activeDieArray'][1]['sides'] = 20;
+        $expData['playerDataArray'][0]['activeDieArray'][1]['value'] = 15;
+        $expData['playerDataArray'][0]['activeDieArray'][1]['skills'] = array('Shadow', 'Trip', 'Mood');
+        $expData['playerDataArray'][0]['activeDieArray'][1]['properties'] = array('JustPerformedTripAttack');
+        $expData['playerDataArray'][0]['activeDieArray'][1]['recipe'] = 'st(S)?';
+        $expData['playerDataArray'][0]['activeDieArray'][1]['description'] = 'Shadow Trip S Mood Swing Die (with 20 sides)';
+        array_unshift($expData['gameActionLog'], array('timestamp' => 'TIMESTAMP', 'player' => 'responder003', 'message' => 'responder003 performed Trip attack using [Gst(S=6)?:1] against [(20):20]; Attacker Gst(S=6)? remained the same size, recipe changed from Gst(S=6)? to Gst(S=20)?, rerolled 1 => 15; Defender (20) rerolled 20 => 4, was captured'));
+        $expData['gameActionLogCount'] += 1;
+
+        $retval = $this->verify_api_loadGameData($expData, $gameId, 10);
+    }
 }
```

**Comment by cgolubi1** [comment]
Note that there's a minor bug in there --- the log message is:
```
responder003 performed Trip attack using [Gst(S=6)?:1] against [(20):20]; Attacker Gst(S=6)? remained the same size, recipe changed from Gst(S=6)? to Gst(S=20)?, rerolled 1 => 15; Defender (20) rerolled 20 => 4, was captured.
```

and obviously "remained the same size" is not true.  (I imagine that should be moved into a separate issue.)

**Comment by cgolubi1** [comment]
Okay.  So basically i'll just play back a bunch of RandomBM games and look for regressions, then play new RandomBM games with trip or mood and look for internal errors.

**Comment by cgolubi1** [comment]
Didn't find any internal errors, so i'm inclined to accept this, but (1) maybe only after the push to prod, since the bug only affects dev and i might have missed something, and (2) i'd like the responderTest folded in.

**Comment by blackshadowshade** [comment]
I've merged in the responder test.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/932/ (if it passes)

**Comment by blackshadowshade** [comment]
Go ahead and open an issue about the logging bug. I'm probably going to be addressing all of our logging bugs at the same time, possibily next month.

**Comment by cgolubi1** [comment]
Thanks.  As noted above, i'll merge this after the November release.

**Comment by cgolubi1** [comment]
Merging - i'll plan to fix the dev game as part of the next dev push.

**Pull request merged**
