### PR TITLE
Updated images for Kolat and Ninja

### LINKED ISSUE #2698: Ninja/Kolat art was backwards
I found a couple files that was Fog placing the names on the Ninja/Kolat buttons (Everything 2 Gain L5R Seattle Kotei set).  I had always been puzzled by how other images didn't have a name on them, and why the names didn't match with the recipes.  I even had an expert on L5R point out the person labelled "Ninja" was a Kolat master.

Turns out that Fog put the names on them, and swapped them.  Here's fixed ones.

150pxKolatHqNamed
150pxNinjaHqNamed

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #2698.

### CODE REVIEW

**Comment by TheOrgg** [comment]
I'm not sure what I'm being asked to do here.

**Comment by blackshadowshade** [comment]
I've put you as a reviewer to check that the pull request matches your proposed changes.

**Comment by TheOrgg** [comment]
Any reason this didn't get into the last update?  (Granted, it's super low priority, but I wanted to make sure there wasn't an issue with the images or something)

**Comment by cgolubi1** [comment]
No issue --- i was really slow getting the site moved from staging to prod, so these all came in after i'd finished processing stuff to go to staging.

**Comment by blackshadowshade** [comment]
The pull request went in after we froze accepting pull requests.

If you're not aware, each time that we deploy, there's a period where we freeze accepting pull requests so that we know what we're testing for deployment.

The pull request freeze period ends about now, so we'll be looking to accept pull requests again real soon.

**Comment by TheOrgg** [comment]
Okay.  I don't know exactly the process, so that's why I checked to make sure this wasn't just overlooked.

**Comment by cgolubi1** [comment]
This seems reasonable to me; the new versions look more like the recipes than the old versions, and the art is more clear (Ninja) or at least no less clear (Kolat).  Thanks!

**Comment by TheOrgg** [comment]
No problem!

**Pull request merged**
