### PR TITLE
Testing the GWAR fan button set

### PR DESCRIPTION
**Pull request by blackshadowshade**
This pull request is in response to issue #2408, but should *never* be accepted. It is intended solely for testing purposes.

The code changes here are the following:
- added support for P swing dice
- a database update to add the GWAR set for testing
- a merge of pull request #2389 (custom recipes) to allow proper testing of Flesh Column.

I have intentionally not changed the file data.button.sql nor updated any of the test files because I intend this pull request only for testing, not for merging into master.

I have intentionally left out the images from this pull request for a number of reasons:
- there may be testers who are unhappy with the image content
- images are not the right size
- images will eventually need to be finalised with button recipes

I propose that we create a dev site with the code in this branch, in spite of the fact that CircleCI will fail, so that the set can be tested.

All database updates (00344_custom_recipe_01.sql, 02408_gwar_01.sql, 02408_gwar_02.sql) will be required.

### CODE REVIEW

**Comment by cgolubi1** [comment]
I think we'll need instructions for playtesters to use in testing Flesh Column --- i had to go hunting through the other PR to find the situation at all, and i'm still not sure how i'd implement it for testing.

More concretely actionable: go ahead and set the flavor text for the buttons who have specials, so we can look at the button pages the dev site during testing to remind us what the button specials are supposed to do.

**Comment by blackshadowshade** [comment]
Good idea. I'll add an extra update file with button special descriptions in the flavour text.

**Comment by blackshadowshade** [comment]
02408_gwar_02.sql has been added.

**Comment by cgolubi1** [comment]
Stood up a dev site --- irilyth, can you sync up 54.224.17.168 == gwar in DNS?

**Comment by irilyth** [comment]
> Stood up a dev site --- irilyth, can you sync up 54.224.17.168 == gwar in DNS?

Done!

**Comment by blackshadowshade** [comment]
Okay, I've just added a quick fix to enable P swing properly. @cgolubi1, would you mind updating the site, please?

**Comment by cgolubi1** [comment]
Updated.

**Comment by blackshadowshade** [comment]
I've submitted a database update that adds two new buttons (Bozo Destructo 2 and Dr. Skullheadface 2), sets the old version to be artificially disabled (via having a button special), and removes the commas there are causing grief in #2410.

@cgolubi1, if you're happy with this, please update the GWAR site.

**Comment by blackshadowshade** [comment]
@cgolubi1, I've added a new update file (02408_gwar_04.sql) for the GWAR testing site.

**Comment by blackshadowshade** [comment]
I've updated the update file to include the new recipe for Beefcake the Mighty.

**Comment by cgolubi1** [comment]
Okay, i updated the dev site and ran the new database file:

```
chaos@ip-10-150-185-123:~$ cat /buttonmen/deploy/database/updates/02408_gwar_04.sql | mysql -u root buttonmen
chaos@ip-10-150-185-123:~$ 
```

**Comment by blackshadowshade** [comment]
I've cherry-picked the change made in #2427 into this branch also, to directly address the warrior stinger die bug for GWAR testing.

**Comment by blackshadowshade** [comment]
Okay, I've removed that change again based on @irilyth's feedback, so there's no update necessary on this branch at the moment.

**Comment by blackshadowshade** [comment]
Based on a comment in #2427, I've updated the recipe for Mr. Perfect to (1) (1) (2) (3) (V).

New database update file is 02408_gwar_05.sql.

**Comment by blackshadowshade** [comment]
New update file 02408_gwar_06.sql addresses the changes requested in #2408.

**Comment by cgolubi1** [comment]
I applied the database change to the dev site.

**Comment by blackshadowshade** [comment]
Closing this so that we can start a fresh pull request based on the final recipes.

**Comment by TheOrgg** [comment]
Leave those off.  Bozo was made into a Winslow-style swing modifier (makes your swings twin, but they gain Poison), Scroda and Porcelon don't play well without their abilities, and they might have a hard time testing Flesh Column if they're not familiar with the game.

**Pull request closed without merging**
