### PR TITLE
Reversed order of open games

### LINKED ISSUE #2774: Open games page should display more recent games first
As discussed recently on the forums. There's the reasonable assumption that people will have seen the older games already, and chosen not to play them at that time. They can always scroll a bit further if they want to.

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #2774.

### CODE REVIEW

**Comment by cgolubi1** [comment]
Dev site at https://blip.dev.buttonweavers.com/ --- someone check this out and see if it seems fine?

**Comment by dwvanstone** [comment]
I've tried two browsers and I'm unable to connect to https://blip.dev.buttonweavers.com/ .

**Comment by cgolubi1** [comment]
Thanks for pointing it out.  I bet there are still some problems with my new vagrant setup, taking a look.

**Comment by cgolubi1** [comment]
Okay, try now, should be fixed.  This is the usual old problem with needing to run puppet twice to get letsencrypt to do its thing; i should try to solve that at some point, because clearly "i'll just remember" is not a good plan.

**Comment by dwvanstone** [comment]
I'm in and I'm testing!

**Comment by dwvanstone** [comment]
This works as expected. I think it'll be a nice feature.

**Comment by cgolubi1** [comment]
Merging this now.

**Pull request merged**
