### PR TITLE
Added images for Free Radicals buttons

### LINKED ISSUE #2539: New art for Free Radicals set
Well, I never heard from Skeeve again, so I went ahead and went through the artwork on the weather site that hosted Maskin's artwork.  I got permission to use the art to recreate the set from the photographer, and made the buttons.  They are not quite the same-- I couldn't find the font used for the capital letter "M" in Maskin, though I found a font very similar with the lowercase letters.  I picked a font (out of 160,000 I searched through on archive.org) with a similar 'mystic night' feel to it as the original font.  I didn't know how to do the effect on the dice frames from the original, but I think mine turned out pretty well despite not being perfect.  I found too much good art, so I put together a couple of new ones.

If bigger ones are needed, they'll be on the wiki page when it'll let me upload stuff agian (something about invalid kernal).

smLorrie
smMaskin
smRandy
smTony
smBernie
smCyn
smGG
smLoren

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #2539.

I'm putting this pull request up for comment. I think that the readability of the text on the button images could be better, but these images are still better than having nothing.

I've added the new Maskin image as an alternate (unused) image, but I'm open to having this replace the original image if you'd like.

Also, I have no idea about the images of other buttons (Bernie and GG) that are apparently part of this set but don't show up on our dev site.

### CODE REVIEW

**Comment by blackshadowshade** [comment]
For ease of review, here is what I see when I take a look at the Free Radicals page after adding these images:

free_radicals

**Comment by dwvanstone** [comment]
Cool to have these! The button "Randy" looks like "Kandy" because the top part of the R is cut off. That's the only issue I see.

I prefer the original Maskin to the new one (from #2539).

**Comment by TheOrgg** [comment]
The "R" in that font just looks funky.

Yeah, the original looks a bit better, but I couldn't figure out how to do the effects used on the dice frames from the original.

GG and Bernie are new; I had extra art I didn't want to dich, so I made a few matching low-powered buttons.

**Comment by TheOrgg** [comment]
I went through thousands of fonts and couldn't find the one used on Maskin.  

If we can find that font, I can redo the new ones to use that font.  I didn't delete the GIMP file yet.

Should I  try increasing the size of the names?

**Comment by blackshadowshade** [comment]
I think the issue with readability of the names isn't size, it's rather that the contrast is low. Could you try an outline or a different colour (light on dark, dark on light)?

**Comment by TheOrgg** [comment]
Bernie150

Cyncyn150

GG150

Loren150

Lorrie150

Maskin150

Randy150

Tony150

**Comment by TheOrgg** [comment]
Just saw the contrast post.  Lemme see what I can do.

**Comment by TheOrgg** [comment]
I tried messing with the colors of the names to improve readability at 150, but nothing really worked that well.  The bigger names is probably the best I can do.  

Any further suggestions, let me know.

**Comment by blackshadowshade** [comment]
The increased size of the names *does* actually improve readability more than I thought it would.

What do others think?

**Comment by TheOrgg** [comment]
GG150b
I didn't like how the new GG looked, so I put it back at the top where it was originally instead of rotating it like the others.

**Comment by TheOrgg** [comment]
Forgot I needed to change Loren's text on his Ornery for it to be readable at 150.
Loren150

**Comment by cgolubi1** [comment]
What's the status of this?  Do we want a dev site, or are y'all still iterating on the images via this PR?

**Comment by TheOrgg** [comment]
I don't see why a dev site would be needed.  There's nothing new with the two new buttons.

**Comment by blackshadowshade** [comment]
A dev site is the standard thing that we do so that testers can see the changes (in this case, button images) on a functioning site.

I'll update the images to use the ones with larger font, and then we can put up a dev site.

**Comment by blackshadowshade** [comment]
Right, I've updated the images and rebased. This is ready for a dev site.

Note that I haven't made Bernie or GG playable, I think the willy-nilly addition of buttons needs some consideration.

**Comment by blackshadowshade** [comment]
Here's what it looks like on my screen now:

screenshot

**Comment by TheOrgg** [comment]
I didn't mean to offend with adding to the set.  It just felt like the right thing to do since there was that many good (awesome looking) arts that had a aethrial looking person in them.

**Comment by blackshadowshade** [comment]
Oh, the problem is not with offending. It's with unexpected bugs popping up that might break the site---like the one with fire and konstant. Thus, we require all new recipes to be approved and tested, even when they appear to be simple and non-breaking.

**Comment by TheOrgg** [comment]
If we've got to test those two, can we throw them in with Eberk, Largo, Julz, and the non-ability Durer characters, too?

**Comment by TheOrgg** [comment]
Re-cleaned and further highlighted for readability; I couldn't figure out how to get the transparent number thing to work, though.  I'll keep trying if this isn't good enough.

Bernie150
Cyncyn150
GG150
Loren150
Lorrie150
Maskin150
Randy150
Tony150

**Comment by blackshadowshade** [comment]
I've updated the images and rebased.

Here's a screenshot of what I'm seeing now:

FreeRadicals

**Comment by TheOrgg** [comment]
I took a look at the artwork (which are actual photos, mostly unmanipulated) because of the 'too dark' critical analysis.  The only one I felt needed some alteration was GG, as in 150px it is hard to see the... 'ethereal being' in the art.  Here's the 'highlighted' GG.  It looks like crap big, though.

GGSmallBoost

**Comment by blackshadowshade** [comment]
I think that GG should be fine without the highlighting. I'll leave it as it is for the moment.

So, testers, what do you think of the new images?

**Comment by TheOrgg** [comment]
As long as we're adding images, why not Blademasters 1?  These are the best images of the set still available unless Ligaya finds her original drawings.

BlademastersScott


BlademastersArashi
BlademastersDanielle
BlademastersDanny
BlademastersHorace
BlademastersInez
BlademastersJohnny
BlademastersKainar
BlademastersMacky
BlademastersMagistra
BlademastersMichie
BlademastersRenee

**Comment by blackshadowshade** [comment]
@TheOrgg, please open a new issue for that, since this current issue will be closed when we accept the Free Radicals pull request.

**Comment by cgolubi1** [comment]
This is waiting for someone to look at https://github.com/buttonmen-dev/buttonmen/pull/2541#issuecomment-609103684 or the dev site and say it's good to go.

**Comment by cgolubi1** [comment]
Err, wait, there is no dev site.  Do we need one, or can we just look at the images in the comment i linked.

**Comment by blackshadowshade** [comment]
I think it's safest to have a dev site.

**Comment by TheOrgg** [comment]
Can we combine the dev site for this with the dev site for Blademasters?

**Comment by blackshadowshade** [comment]
Doesn't work that way, because the pull requests are separate and need to be approved separately.

**Comment by cgolubi1** [comment]
Standing up a dev site (either now or the next time i loop back to this).

**Comment by cgolubi1** [comment]
Irilyth, can you sync up 54.144.80.10 == temporary.dev.buttonweavers.com when you get a moment?

**Comment by dwvanstone** [comment]
The Free Radicals buttons artwork looks Beautiful! Well done, all!

**Comment by irilyth** [comment]
> Irilyth, can you sync up 54.144.80.10 == temporary.dev.buttonweavers.com when you get a moment?

Done!

**Comment by blackshadowshade** [comment]
Images are showing up fine for me on the dev site, and the names and recipes are nice and clear to my eye.

**Comment by cgolubi1** [comment]
Seems like this is ready to go and has been approved by two people.  Merging.

**Pull request merged**
