### PR TITLE
Fixed logic for a konstant trip die targeting a maximum die

### LINKED ISSUE #1575: Backend erroneously includes Trip in validAttackTypeArray given konstant trip attacker
This happened:
konstant_trip_attacker

There's no legal trip attack because the stealth dice can't be tripped and the maximum dice can't reroll low enough to be captured, so trip should not be offered as a choice.

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #1575.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/660/ (if it passes)

### CODE REVIEW

**Comment by blackshadowshade** [comment]
I don't understand why Jenkins won't pass this code. When some other pull request is merged, I'll try merging upstream/master and running it again.

**Comment by blackshadowshade** [comment]
The new run is http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/668/. Let's see if this passes.

**Comment by cgolubi1** [comment]
I'll test this against my captured buggy test, regression test it against a bunch of misc games, and play some RandomBMMixed games looking for trouble.

**Comment by cgolubi1** [comment]
Seems fine.  Merging.

**Pull request merged**
