### PR TITLE
Uninstall mysql-server, rather than installing it, on RDS sites

### PR DESCRIPTION
**Pull request by cgolubi1**
* Also cleanup the current IP of the RDS dev site so it can be used for testing

### CODE REVIEW

**Comment by cgolubi1** [comment]
Testing done: with these changes, vagrant provision succeeds on the RDS dev site rather than failing.  Successful output looks like this (without these changes, i get a long stack of errors about mysql-server not being able to be started):

```
$ vagrant rsync && vagrant provision
==> default: Rsyncing folder: /Users/chaos/src/git/buttonmen-dev/dev-cgolubi1-2523_rds/ => /buttonmen
==> default: Rsyncing folder: /Users/chaos/src/git/buttonmen-dev/dev-cgolubi1-2523_rds/deploy/vagrant/ => /vagrant
==> default: Rsyncing folder: /Users/chaos/src/git/buttonmen-dev/dev-cgolubi1-2523_rds/deploy/vagrant/manifests/ => /tmp/vagrant-puppet/manifests-a11d1078b1b1f2e3bdea27312f6ba513
==> default: Rsyncing folder: /Users/chaos/src/git/buttonmen-dev/dev-cgolubi1-2523_rds/deploy/vagrant/modules/ => /tmp/vagrant-puppet/modules-81fa734b1bce498866b1292ff684d1ee
==> default: Running provisioner: shell...
    default: Running: /var/folders/fl/y1vv5ts96296lb3v7b020_qc0000gn/T/vagrant-shell20211229-4982-1nhofms.sh
    default: Puppet is already installed
==> default: Running provisioner: puppet...
==> default: Running Puppet with init.pp...
==> default: Warning: Variable access via 'puppet_hostname' is deprecated. Use '@puppet_hostname' instead. template[/tmp/vagrant-puppet/modules-81fa734b1bce498866b1292ff684d1ee/postfix/templates/main.cf.erb]:22
==> default:    (at /usr/lib/ruby/vendor_ruby/puppet/parser/templatewrapper.rb:77:in `method_missing')
==> default: Notice: Compiled catalog for ip-10-151-200-204.ec2.internal in environment production in 0.87 seconds
==> default: Notice: /Stage[main]/Apt::Client/Exec[apt_client_update]/returns: executed successfully
==> default: Notice: /Stage[main]/Buttonmen::Server/Exec[buttonmen_src_rsync]/returns: executed successfully
==> default: Notice: /Stage[main]/Buttonmen::Server/Exec[buttonmen_setup_ui_cache_links]/returns: executed successfully
==> default: Notice: /Stage[main]/Buttonmen::Server/Exec[buttonmen_uitest_rsync]/returns: executed successfully
==> default: Notice: Finished catalog run in 10.61 seconds
```

**Comment by cgolubi1** [comment]
I may need to change this a bit more to make circleci pass, but i want to call out why this change is important: the same vagrant/puppet blowup i see on the RDS dev site, i also see on the staging and prod sites.  If i really want to do frequent mostly-automated releases, the deployment itself has to be low-drama, meaning no error text that i have to read past.  And definitely the deployment actually blowing up is no good.

**Comment by cgolubi1** [comment]
FYI, this passes circleci now --- i had a typo in the original version, but i fixed it (good on circleci for catching it for me).

**Comment by blackshadowshade** [comment]
The fact that this passes CircleCI and you're happy with it is enough for me.

**Pull request merged**
