### PR TITLE
Added Peloton set

### LINKED ISSUE #2360: New Peloton button set
AnnoDomini is interested in creating a new set of buttons based on cycling:

http://buttonweavers.wikia.com/wiki/Sets/Peloton

He's looking to get these on a dev site for testing.

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #2360.

This pull request supersedes #2368.

@AnnoDomino has asked for feedback on the flavour texts from native speakers. I'd especially like input from people who are bike-lingo-savvy and who can give an informed opinion on what is idiomatic and what is not. However, all other input welcomed as always.

### CODE REVIEW

**Comment by blackshadowshade** [comment]
Also, take a look at the images and tell me what you think.

I think it may be an issue that the recipes are sometimes indistinct.

**Comment by blackshadowshade** [comment]
Also, @cgolubi1, we're now getting consistent failures on CircleCI because it doesn't have pdepend.

No hurry, just letting you know why these runs are failing.

**Comment by blackshadowshade** [comment]
@Hurtay, what's your take on the image quality of the recipes on the buttons? Do the skill letters need to be larger?

**Comment by blackshadowshade** [comment]
Flavour text updated, pull request rebased to hopefully fix that pdepend problem.

**Comment by cgolubi1** [comment]
Yikes, where are we on this?  Should we redeploy a dev site?  Are we done?  I'm psyched about this set, and apologise for having lost track.

**Comment by blackshadowshade** [comment]
In my mind, this is fully functional, but I have reservations about the button recipes on the images. I don't consider that to be a blocker, but it may need work in the future.

**Comment by AnnoDomino** [comment]
Hi,

I have setup a game with Glassonion to discuss this but she did not log in to the site for some time now.

James,
I dont have graphic skills or software to make the receipes better. If what we have there now is not sufficient then please let me know if there is anybody in the community who could help me with this - I would greatly apreciate some help here.

Regards
AnnoDomini

**Comment by cgolubi1** [comment]
Whoops, sorry.  I've accepted the game now, and will track it.

**Comment by cgolubi1** [comment]
Shadowshade: it sounds like Hurtay may not have time to do image work right now.  My feeling is we should go ahead and accept the set with the current art, and if someone wants to clean up the lettering on the recipes on the images later, there's no reason we can't do that.

What do you think?

**Comment by blackshadowshade** [comment]
That's fine by me.

**Comment by cgolubi1** [comment]
Okay, merging this now.

**Comment by CarltonN** [comment]
Are the graphics on the site as good as it gets? are there higher
resolution images? does it matter which font I use for the numbers (as long
as its easily legible)?
Carlton Noles
-------------------

**Comment by blackshadowshade** [comment]
@CarltonN, our standard image size is 150 x 150 px. However, there's discussion of this on #1950, and you should feel free to add to the discussion there, we can certainly expand it to include image quality.

**Comment by CarltonN** [comment]
the reason I asked is I'd be likely to blow up the image to work on it then
shrink it back down. Not a major issue but rather a point of curiosity

oh and also are there standard colors for the skills.
Carlton Noles
-------------------

**Comment by CarltonN** [comment]
how does this look?

Carlton Noles
-------------------

**Comment by blackshadowshade** [comment]
I can't see your image.

Also, for standard colours, I think the answer is no, but Fog did a great job of doing some standardisation on the Classic Fanatics that had no button image. You might want to take a look there.

**Comment by CarltonN** [comment]
Unable to download? its attached nit embedded.

Carlton Noles
-------------------

**Pull request merged**
