### PR TITLE
Added number of active games to overview

### LINKED ISSUE #1119: Add count to list of active games
Could your list of active games also show how many total games you're in? I think the old site did this.

### PR DESCRIPTION
**Pull request by blackshadowshade**
@AdmiralJota's solution that fixes #1119.

When #1821 has been accepted, this pull request will probably need to be deconflicted.

I am currently unsure whether the count of closed games is really necessary for consistency, since I don't think the number would every be really meaningful.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1001/ (if it passes)

### CODE REVIEW

**Comment by blackshadowshade** [comment]
This is currently missing a QUnit test for the new function Overview.updateSectionHeaderCounts(). I'll get to that when I can.

**Comment by blackshadowshade** [comment]
I don't know how to write test_Overview.updateSectionHeaderCounts() correctly. For some reason, the call to Overview.updateSectionHeaderCounts('activeGames') isn't doing anything in the unit test.

Any idea how to fix this test?

**Comment by cgolubi1** [comment]
Okay, so: this has been kicking around for awhile.  It needs to be deconflicted.  It does not have any code in it that Shadowshade cares about.  IIRC, i had some reservations about it, though i would be hard-pressed to remember what they are.

We think this was something Jota implemented in response to an issue irilyth opened.  Either of y'all want to weigh in on your attachment to our sorting this out, vs closing this PR and revisiting the original issue in the fullness of time?  Any responses are fine, but we don't want to think about it too hard if no one actually cares.  (But if you do care, please say so.)

**Comment by AdmiralJota** [comment]
Am I correct in my reading that it's only the test file that's conflicted, not the code for the feature itself? Seeing as I didn't even write the test, I would certainly have no objections to test_Overview.js being rolled back and some other less conflict-y test getting written for it instead. 

Or for that matter, having the whole pull replaced with a new pull based off of https://gist.github.com/AdmiralJota/8afe049bd2fd46dc23c4, if that code is still salvageable (and if the test is the only thing that's conflicted, I don't see why it wouldn't be).

**Comment by blackshadowshade** [comment]
So, this has been rebased into one commit and deconflicted.

**Comment by blackshadowshade** [comment]
Note that I previously commented that one of the unit tests is broken. I'll need help to fix this unit test.

**Comment by AdmiralJota** [comment]
I'm not spotting which is broken from the jenkins report. Is the test anything that I can help with without having a BM dev environment set up?

**Comment by blackshadowshade** [comment]
Jenkins passes, the issue is more a logical one.

You'll note that in the test, the header should actually contain the number of games, but it doesn't, because the call to Overview.updateSectionHeaderCounts('activeGames') doesn't actually do anything in this context.

**Comment by AdmiralJota** [comment]
Are we certain that active games are coming back from the server when we call Overview.getOverview()? (I.e., gamesource.length isn't 0 on line 265 of Overview.js?)

**Comment by blackshadowshade** [comment]
So, I've just checked, and the values of gamesource.length (line 265 of Overview.js) are 129, 418, and 408.

The value of count (line 144 of Overview.js) is 0.

Any idea how I can debug the JQuery at line 144 to work out what's missing?

**Comment by cgolubi1** [comment]
I stood up a dev site for this, see https://github.com/buttonmen-dev/buttonmen/wiki/Dev-site-index for IP.  I'm trying to debug getting Jota's IP able to load /test-ui, but i don't know if i'll get that done in the time i have or not.

**Comment by cgolubi1** [comment]
FYI, here's the error the apache log is getting when the test fails:
```
[Fri May 05 19:55:23 2017] [error] [client X.X.X.X] DummyApiResponder tried to read nonexistent file 50.json in response to an API query for loadActivePlayers, referer: http://54.146.5.143/test-ui/
```

You probably have a UI test looking for dummy data that no responder test defines.

**Comment by irilyth** [comment]
FWIW, the feature looks great to me.

**Comment by cgolubi1** [comment]
My understanding here is that the feature itself is potentially ready to go (irilyth has signed off, no one has vetoed), but someone needs to get the UI unit tests passing, so the action item goes to anyone who has time to/is able to do that.

**Comment by blackshadowshade** [comment]
So, I've finally worked out where the problem is here.

The issue is that the rows are present but aren't visible, so the selector tr:visible is obviously returning no rows. Time to work out why they're not visible.

**Comment by blackshadowshade** [comment]
So, I think this now works. Let's see what Jenkins says.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1366/ (if it passes)

**Comment by cgolubi1** [comment]
Tearing down the old dev site for this pull and standing up a new one.

**Comment by cgolubi1** [comment]
irilyth, when you get a chance can you repoint the `temporary` CNAME to 54.145.71.191?

**Comment by irilyth** [comment]
> irilyth, when you get a chance can you repoint the `temporary` CNAME to 54.145.71.191?

Done!

**Comment by irilyth** [comment]
http://temporary.dev.buttonweavers.com/ for anyone looking for a link.

And, just to confirm, this feature still looks good to me. :^)

**Comment by cgolubi1** [comment]
Okay, looks like this is ready to go now.  Merging it, and tearing down the dev site.

**Comment by cgolubi1** [comment]
Done: irilyth, you can reclaim `temporary` at your leisure.

**Pull request merged**
