### PR TITLE
Removed trailing space from Steven Universe button's name

### LINKED ISSUE #2318: Steven Universe button's name has a trailing space
The Steven Universe button's name has a trailing space at the end, in 01978_steven_universe_01.sql.

### PR DESCRIPTION
**Pull request by irilyth**
Fixes #2318 

http://jenkins.buttonweavers.com:8080/job/buttonmen-irilyth/54/ (if it passes)

### CODE REVIEW

**Comment by cgolubi1** [comment]
So that's not quite the way to do this, filewise.  The file you changed, like all committed files under /updates/, is the diff which was applied as part of a previous PR --- we're not going to apply that again.

You'll instead want to change data.button.sql (the file which is applied when a brand new database change is made), *and* create a new updates file which changes the name to "Steven Universe" when it is "Steven Universe ".

**Comment by irilyth** [comment]
Oh, this fixes #2318 , BTW.

I've made changes that I think are what you described; http://jenkins.buttonweavers.com:8080/job/buttonmen-irilyth/55/ is the new Jenkins run.

**Comment by cgolubi1** [comment]
Doing a local database check on this; assuming it seems fine, i'll merge it.

**Comment by cgolubi1** [comment]
LGTM.  Let me get this on staging and you can see if it solves your problem.

**Pull request merged**
