### PR TITLE
Push changes from master to staging on 2020-08-10

### PR DESCRIPTION
**Pull request by cgolubi1**
This update brings these approved pulls to the staging branch:

* User-visible:
    * #2549, #2531, #2582, #2582: Flavor text updates for several buttonsets, including supporting unicode in flavor text
    * #2541: Images for Free Radicals buttons
    * #2587: Updated Opedog image
    * #2562: Privacy policy
    * #2569: Button page should display TL status of buttons
    * #2568: Open Games page shows your open games first
    * #2570: Anchors that are hidden in spoilers should be unclickable
* Ideally not user-visible: none
    * #2543: changes to stats generation scripts
    * #2571: JS code cleanliness fix (semicolons)
    * #2590: emit cloudwatch metrics that we can use to alarm on down sites

Database updates:
```
UPDATES="02548_flavour_text_01.sql 02485_lotr_flavour_text_01.sql 02575_biased_flavour_text_01.sql"
SCRIPTS=""
```

Once this pull is merged, i will load the changes on staging.buttonweavers.com as part of #2577.

### CODE REVIEW

**Comment by cgolubi1** [comment]
Merging this, then i'll update staging.

**Comment by cgolubi1** [comment]
Okay, please take a look at the staging site.  Shadowshade, i think you fixed the staging tags being lost last time --- if so, please *don't* do that again, because it's just going to keep getting lost every time i do a release, but instead tell me what you did, and i'll add it to my script.  (And if i'm wrong and you didn't do anything before, i'll investigate this when i have a chance.)

**Comment by cgolubi1** [comment]
Worth noting: in addition to my usual activities, i had to do some dpkg/apt cleanup in order to be able to install awscli:

First: `sudo dpkg --configure -a`

Then: `sudo apt-get -f install`

The former said `Processing triggers for libc-bin (2.23-0ubuntu10)`, the latter seemed to install some python35-related packages.  So my guess is that this is just because we haven't touched packages on these systems in awhile, and i should expect approximately the same thing to happen on prod.

**Comment by blackshadowshade** [comment]
I've taken a look at the staging site, the favicon is not correct, so this indicates that the siteType isn't correct.

Here's my record of what I did to fix the staging favicon:

https://github.com/buttonmen-dev/buttonmen/issues/2301#issuecomment-639987007

> I've manually changed Config.1586785864.js to have the siteType set to 'staging'. After clearing my JS cache, this fixes this problem, so staging is now showing with the correct favicon and the yellow-backgrounded header.

Looks like it's just a matter of updating the Config.*.js file.

**Comment by dwvanstone** [comment]
I got confused as to whether this was ready to be tested (I thought we were waiting for blackshadowshade to fix something), and then I got confused by the other push from staging to production (#2577 which showed no visible changes), but I think it's okay to test now? I'm assuming so! Give me 20 minutes...

(It would help me if there were a general "Testers please go ahead and test" statement. The statement above on first glance like it was written for blackshadowshade to test. I wasn't positive it was ready for us to test.)

**Comment by dwvanstone** [comment]
Note that approved pull "#2582" is listed twice - not sure if there was another pull meant to be in that list.

It all looks good. I'm particularly excited about all the new descriptions. Sorry about my whine - it should have been clear that it was ready for testing but I've been stressed and more stressed. This is a great release.

**Comment by cgolubi1** [comment]
Sorry about the confusion, and thank you for testing!  (I'll double-check the list of PRs when i prep the prod release, thanks for flagging the duplicate.)

**Pull request merged**
