### PR TITLE
final: Removed word 'Game' from the first column on the overview page

### LINKED ISSUE #1955: 5-digit game numbers causing two-line-high rows on Overview screen
Recently the Overview page got a lot less dense, because 5-digit game numbers aren't fitting on a single line, yuk:
screen shot 2016-02-21 at 11 12 58 pm

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #1955.

Testing pull request: #2107.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1210/

### CODE REVIEW

**Comment by irilyth** [comment]
This looks ok to me. One suggestion: I think it'd look better without the "#" in the column header, i.e. just "Game" rather than "Game #". Anyone else have a preference?

If no one else cares enough to change it, or if anyone prefers to keep the "#", I think it's fine to shipit as is.

**Comment by dwvanstone** [comment]
My overview page is almost always too wide and thus everything word wraps. This looks great everywhere except for "Game #" where the "#" wraps to the second line and does seem funny. Also, it's not as if the contents of the column is the game number - it is the action to be taken for the game. So I agree that the "#" can disappear without issue.

**Comment by blackshadowshade** [comment]
So, what do others think? Does the title "Game" (without the #) work for the first column? Or do we change it to something like "Action"?

**Comment by AdmiralJota** [comment]
It's fine with me.

**Comment by cgolubi1** [comment]
Okay, the hash symbol removal has been merged onto the dev site, so folks should weigh in on whether this is good to go.

**Comment by irilyth** [comment]
This looks good to me. Shipit!

**Comment by cgolubi1** [comment]
Merging to master now.

**Pull request merged**
