### PR TITLE
Added 2020 Fanatics

### PR DESCRIPTION
**Pull request by blackshadowshade**
Addresses issue #2346 for the year 2020.

The button blackshadowshade has been disabled because zero-sided option dice are not yet supported.

I've marked the pull request incomplete because the images for jimmosk and Blargh currently have white instead of transparent backgrounds.

I've tested pairs of these Fanatics against each other, and all games start correctly, proceed through swing selection, and then an attack is possible.

Naturally, the unit test will conflict with #2389 because of the addition of buttons.

### CODE REVIEW

**Comment by blackshadowshade** [comment]
@dwvanstone, would you be able to chase up the transparency issue for jimmosk and Blargh, please?

**Comment by blackshadowshade** [comment]
Current CircleCI run can be found here: https://circleci.com/gh/blackshadowshade/buttonmen/322

**Comment by dwvanstone** [comment]
> @dwvanstone, would you be able to chase up the transparency issue for jimmosk and Blargh, please?

Yes, I'll follow up.

**Comment by blackshadowshade** [comment]
I've replaced those two images so all images now have transparent backgrounds.

I think that this should be ready for test site deployment.

**Comment by cgolubi1** [comment]
Dev site is up.  irilyth, can you sync up fanatics.dev.buttonweavers.com=3.80.183.255 when you get a moment?

**Comment by dwvanstone** [comment]
I get "Internal error when calling loadButtonData" when I view jimmosk's button:

http://3.80.183.255/ui/buttons.html?button=jimmosk


Also, the description for Nala is missing the final text "Nala". It should end:
  
    ... but i think you're doing quite well for you anyway" -Nala

**Comment by blackshadowshade** [comment]
Okay, I can replicate those. I'll take a look.

**Comment by irilyth** [comment]
> Dev site is up. irilyth, can you sync up fanatics.dev.buttonweavers.com=3.80.183.255 when you get a moment?

Done!

```
+$ host fanatics.dev.buttonweavers.com
fanatics.dev.buttonweavers.com has address 3.80.183.255
```

**Comment by blackshadowshade** [comment]
The Nala bug is due to the flavour text field not being long enough, so that's simple to fix.

I'm taking a look at the Jimmosk one now.

**Comment by blackshadowshade** [comment]
I can't reproduce the issue with the Jimmosk button locally on my MAMP stack. Also, I can't find the log message to work out what the issue is. @cgolubi1, can you help me out here? Where's the log that I should be looking at?

**Comment by blackshadowshade** [comment]
After investigating further, I can guess why there are no log entries being produced: the POST requesting the button data does not complete, it simply times out after 350 ms.

Considering this doesn't happen on my AMP stack, I'd love ideas on how to debug this problem.

**Comment by blackshadowshade** [comment]
Found it! It's the dash in Jimmosk's flavour text, somehow. Let me work out how to fix that now.

**Comment by blackshadowshade** [comment]
Okay, this should work after update. It requires database update 02346_2020fanatics_02.sql to be applied.

**Comment by cgolubi1** [comment]
So... i'd much rather change jimmosk's dash to be a normal ascii dash, than futz around with the database to cover the dash type he submitted.  I guess if people feel that the non-ascii dash is philosophically important somehow, we can go for it.  But why not just take the easy solution and put an ascii dash in his flavour text?  I'm over 90% sure the non-ascii dash was an accident.

**Comment by cgolubi1** [comment]
Ohh, you're making the database column longer for Nala.  Yeah, okay, fine.

**Comment by blackshadowshade** [comment]
I've increased the flavour text field length again to account for LoFR flavour texts (see #2485), which are between 1.2k and 1.4k characters in length.

**Comment by cgolubi1** [comment]
Dev site is updated.

**Comment by dwvanstone** [comment]
The two bugs I reported were fixed.

I've created a few games and played a few turns. They look great!


I have a question out to Blargh whether his description should be changed from

"Blargh likes to sail the seven seas, raiding merchants..."

to

"Blarh likes **sailing** the seven seas, raiding merchants..."

for verb consistency.

**Comment by blackshadowshade** [comment]
I'd suggest hitting him up in a game and asking him there.  :)

**Comment by AdmiralJota** [comment]
> I have a question out to Blargh whether his description should be changed 

Hmm. That would change the meaning of the sentence (from "...likes to sail the seven seas, *while* raiding merchants, [etc.]" to "...likes sailing the seven seas *and* raiding merchants [etc.]"). 

I can't say for certain which Blargh intended, but I personally think the current meaning works better and makes more sense.

**Comment by dwvanstone** [comment]
I think you're right. I'd say it's fine then.

**Comment by cgolubi1** [comment]
Can someone summarize where we are on this?  Do we just need devious and a second person to say this is ready to go, or are there still outstanding issues?  No rush, just checking in on it.

**Comment by dwvanstone** [comment]
I believe this is ready to go. It would be great if another person went to fanatics.dev.buttonweavers.com to see if they see any issues.

**Comment by cgolubi1** [comment]
I don't see any issues from looking at the buttons page.  Shadowshade, can you give a thumbs-up that this is good to go as far as you're concerned, and i'll merge it?

**Comment by blackshadowshade** [comment]
Everything looks okay to me.

**Comment by cgolubi1** [comment]
Awesome.  This is ready to be rebased down to one commit and merged.

**Comment by blackshadowshade** [comment]
Rebased.

**Comment by cgolubi1** [comment]
Merging, and taking down the dev site.  Exciting!

**Pull request merged**
