### PR TITLE
Added flavour texts

### PR DESCRIPTION
**Pull request by blackshadowshade**
This addresses part of #2860, namely the flavour texts for already existing buttons.

Flavour texts have been lightly edited for grammar and spelling.

I have merged the flavour texts (old and new) for Rikachu and Skeeve.

[dev test site: <a href="https://ephemeral.dev.buttonweavers.com/">ephemeral.dev.buttonweavers.com</a>]

### CODE REVIEW

**Comment by cgolubi1** [comment]
DB update-vs-rebuild check looks fine.  Let me setup a dev site so someone can check out the flavor texts.

**Comment by cgolubi1** [comment]
Okay, it's up at https://ephemeral.dev.buttonweavers.com/ui/ - can someone look through the flavor texts added in this PR and see if they look fine?

**Comment by TheOrgg** [comment]
Unless I looked at the wrong spot, the RandomBM flavor text isn't there.

**Comment by blackshadowshade** [comment]
We already have flavour texts for our various different RandomBM flavours, the old one doesn't really fit, considering that we have so many types now.

**Comment by blackshadowshade** [comment]
@TheOrgg, are you okay with the rest of the flavour texts?

**Comment by TheOrgg** [comment]
I have been so busy with the new job that I haven't been able to check anything other than ChiCrew, Horsemen, and RandomBM.  I was hoping to check the others this weekend.

**Comment by dwvanstone** [comment]
The punctuation for **Lizzie** seems odd:

"Lizzie can break out of any prison through raw determination, as such she is good at beating people up."

Maybe:

"Lizzie can break out of any prison through raw determination. As such, she is good at beating people up."


**Monty Brown** too:

"Monty Brown, also known as Zoomkitty, appreciates chewing on a good book, ordering in Italian and rushing out the door. Oh, by the way he likes to beat people up."

I'd prefer commas after "Italian" and "way."


**Octavia** too:

"Don't cross her, she may look scrappy but she'll beat people up."

I'd prefer "Don't cross her: she may look scrappy, but she'll beat people up."


Oxford comma issues??  **eon**, **spindisc**, **Notorious**, and others.

"eon likes to make prank calls, contemplate about deep feelings, impersonate a police officer and beat people up."
spindisc: "He likes binary digits, graphical outbursts and beating people up."
"Notorious likes Looney Tunes, sunny Junes, common loons, silver spoons, half-past noons and harvest moons."

I'd prefer a commas after "office," "outbursts," and "noons". I'll ignore the other Oxford comma examples I find -- sometimes we use them, sometimes we don't. In all cases the intention is clear so maybe we can let them be.


**Hrodgar**: "rangning from delerious to suicidal,"   <-- should be "ranging" and "delirious"

**yakboy**: Perhaps the first letter could be capitalized?  ("sidekick of Llama Man! ")

**Iron Chef Italian**:  Could we not have "mother-******"? Even commented out it's still bad to have on our site. Simply: "He makes pasta like a stallion!" would be fine.

**Marilyn Monroe**: "Unfortunatly for her" <-- should be "Unfortunately"

**Da Pimp**: I don't think our site is better with "hos" and "pimp". The whole button is trouble. I don't have a solution for this one. Maybe it could be retired as just too much ... grossness?

**Comment by blackshadowshade** [comment]
I've made the suggested changes to the flavour texts for Lizzie, Monty Brown, Octavia, Hrodgar, yakboy, and Marilyn Monroe.

I've not added the other potential Oxford commas, nor have I altered the flavour texts for Iron Chef Italian or Da Pimp.

What do others think I should do about the flavour texts for Iron Chef Italian and Da Pimp?

**Comment by cgolubi1** [comment]
I don't have a problem with `mother-******` (except that i don't understand how `-` plus six stars is the correct bleep-out pattern, but that's not important), but i also don't have a problem with omitting the word, so i vote for that.

I agree that Da Pimp's flavor text is offensive.  Let's just not add flavor text for this button.  Maybe we should take another action related to the button overall, but that's not part of this PR; let's just settle for not making things worse.

**Comment by cgolubi1** [comment]
BTW, i'm also pro-Oxford comma in the cases devious flagged, but i don't feel strongly about it.

**Comment by irilyth** [comment]
I'm pro Oxford comma; I think they generally make things clearer, except in obviously contrived examples.

**Comment by blackshadowshade** [comment]
I've removed the flavour text for Da Pimp, altered the flavour text for Iron Chef Italian, and added a number of Oxford commas.

I also had to rebase because I somehow mucked up my git state, so this will need a full redeploy, as well as another update-vs-rebuild DB test.

**Comment by cgolubi1** [comment]
update-vs-rebuild test looks fine!

The dev site at https://ephemeral.dev.buttonweavers.com/ui/ has been rebuilt.  Please take a look there, and let shadowshade know if the changes look fine.  He said:

> I've removed the flavour text for Da Pimp, altered the flavour text for Iron Chef Italian, and added a number of Oxford commas.

Assuming those look reasonable to someone, i think this should be merged.

**Comment by blackshadowshade** [comment]
@dwvanstone, @irilyth, did one of you want to take a look at these and comment?

**Comment by dwvanstone** [comment]
I've reviewed the changes - thanks! We still need an Oxford Comma for Boot2daHead. Everything else is great!

**Comment by blackshadowshade** [comment]
I've added an Oxford comma to Boot2daHead's flavour text and then rebased.

I think this should be good to go.

**Comment by cgolubi1** [comment]
Remind me what the status of this is, since it came up in the original request.  You're not hoping for another dev site, right Shadowshade?  You're hoping someone will review something?

I know i've been a bit AWOL in terms of processing buttonmen stuff, but afaik this particular PR is actually not in my court right now, so tell me i'm wrong!

**Comment by blackshadowshade** [comment]
I believe this should be good to go, the changes have been reviewed and approved as far as I can tell.

**Comment by cgolubi1** [comment]
Got it --- i should be able to redo the DB update-vs-rebuild check and merge in the next couple of days.  Thanks.

**Comment by cgolubi1** [comment]
Database check looks fine; merging.

**Pull request merged**
