### PR TITLE
Fixed recipe of Libra, and flavour text of Aries and Capricorn

### PR DESCRIPTION
**Pull request by blackshadowshade**
Continues to address #1957.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1097/

### CODE REVIEW

**Comment by blackshadowshade** [comment]
I've also fixed the single quotes in the flavour texts for Aries and Capricorn.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1098/ (if it passes)

**Comment by cgolubi1** [comment]
Let me do a database update-vs-build test, then merge this.

**Comment by cgolubi1** [comment]
All is not well in database update land.  Here's my diff:
```diff
$ diff -u ~/buttonmen_db.*
--- /home/chaos/buttonmen_db.rebuilt.sql        2016-02-29 13:11:09.958814672 +0000
+++ /home/chaos/buttonmen_db.updated.sql        2016-02-29 13:11:18.192407293 +0000
@@ -733,7 +733,7 @@
   (693,'Pai Gow II','(4) :(10) :(10) (12) (12)',0,0,18,NULL),
   (694,'Magician','(6) (8) (10) (12) (T)',0,0,18,NULL),
   (695,'Aquarius','(6) p(6) (8) s(12) (X)',0,0,77,'Aquarius is an honest and loyal humanitarian. He is easy going and makes friendships naturally. He accomplishes his goals in a quiet, unorthodox but surprisingly effective way. He loves arts, poetry, and beating people up.'),
-  (696,'Aries','(6) s(8) z(10) (20) (X)',0,0,77,'Aries is a strong-willed warrior and a bundle of energy. He is creative and spontaneous, quick to anger, but doesn\'t take it personally. Although he works best alone, he likes parties, humor, and beating people up.'),
+  (696,'Aries','(6) s(8) z(10) (20) (X)',0,0,77,'Aries is a strong-willed warrior and a bundle of energy. He is creative and spontaneous, quick to anger, but doesnâ€™t take it personally. Although he works best alone, he likes parties, humor, and beating people up.'),
   (697,'Cancer','p(6) g(8) (8) (12) (X)',0,0,77,'Cancer is a loyal, sympathetic friend with a special interest in history. He is known to be a conservative traditionalist who occasionally needs solitude. He loves his home, his family, and beating people up.'),
   (698,'Capricorn','(4) s(6) (10) g(12) (X)',0,0,77,'Capricorn is a good organizer with broad shoulders for other people\'s problems. He is highly intelligent and shrugs off any negative comment about his personality. He loves stability and order, and beating people up.'),
   (699,'Gemini','(4,4) (12) (12) z(X) s(X)',0,0,77,'Gemini is an adaptable and flexible duo. They may turn from hot to cold in no time since their attention easily drifts to something new. They love to inspire others, talking and playing with their mobile phones, and beating people up.'),
@@ -2406,4 +2406,4 @@
 /*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
 /*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
 
--- Dump completed on 2016-02-29 13:10:23
+-- Dump completed on 2016-02-29 13:10:18
```

Looks like you fixed the Capricorn single quote in both places, but only fixed the Aries single quote in the rebuild file, not in the update file.

**Comment by blackshadowshade** [comment]
Okay, let's see if this is fixed better.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1100/ (if it passes)

**Comment by cgolubi1** [comment]
Okay, once more from the top.

**Comment by cgolubi1** [comment]
Looks good to me.  Database test passes, and i can see all the button flavor text.

**Pull request merged**
