### PR TITLE
Added Steven Universe set

### LINKED ISSUE #1978: Add and playtest Steven Universe button set
I've created a set of button recipes themed off of the Steven Universe television show, and @Hurtay has created images for them. The SQL for the recipes is at https://gist.github.com/AdmiralJota/68df2efb27411f22a4c4a0ccc0867f0b. Once the Turbo skill has been implemented, I'd like to test these recipes out on the dev site.

Blocked by  #91.

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #1978.

Testing pull request: #2129.

This pull request should not be accepted until the set has been playtested.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1240/ (if it passes)

### CODE REVIEW

**Comment by cgolubi1** [comment]
Over on the testing pull, we were discussing that turbo won't be available this month.  That blocks Steven and Greg, but not the other buttons, so i'm interested in Jota's opinion on whether that's in fact a blocker for making the buttons that are implemented available on prod next month.  Maybe we should playtest them and see where we get.

**Comment by AdmiralJota** [comment]
My current plan is not to collect any official playtesting stats for the set (to see which buttons need balancing) until after the whole set is available. 

But anyone who wants to do any unofficial playtesting and give their own feedback on how the buttons play is encouraged to do so!

**Comment by cgolubi1** [comment]
Making the previous discussion expicit: i think we are not planning to release SU for the prod site until after Turbo is available, so it won't be in the December release.

**Comment by cgolubi1** [comment]
I stood up a dev site for this pull, see https://github.com/buttonmen-dev/buttonmen/wiki/Dev-site-index for IP address.

I hacked random button selection so that it would always choose a button from the Steven Universe set.

**Comment by blackshadowshade** [comment]
Okay, on this particular deploy, the mailutils were not installed. To fix that, I did

    sudo apt-get mailutils

**Comment by blackshadowshade** [comment]
Just a note that this will need to be deconflicted from the database changes made in #2187, since the button and set ids need to be unique.

**Comment by blackshadowshade** [comment]
Just shifting @AdmiralJota's comment here:

Here are some revised recipes we should try for round 2 of testing: https://gist.github.com/AdmiralJota/ee4e30f7d34e70bb7181d161697738ef

**Comment by blackshadowshade** [comment]
Recipes added, and old recipes given the button special flag.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1240/ (if it passes)

**Comment by cgolubi1** [comment]
Jota and irilyth asked for the button art to be visible on the new recipes and not on the old recipes, so i did this by hand on the SU dev site:
```
cd /var/www/ui/images/button/
sudo mv connie.png connie2.png
sudo mv garnet.png garnet2.png
sudo mv greguniverse.png greguniverse2.png
sudo mv lionsu.png lionsu2.png
sudo mv rosequartz.png rosequartz2a.png
sudo ln -s rosequartz2a.png rosequartz2b.png
sudo mv stevenuniverse.png stevenuniverse2a.png
sudo ln -s stevenuniverse2a.png stevenuniverse2b.png
```

**Comment by AdmiralJota** [comment]
Another update here, for round 3 of testing: https://gist.github.com/AdmiralJota/8de348ceb103bd27c93176744faa4995

I'd also like to update the images to go with them:

    sudo mv connie2.png connie3.png
    sudo mv garnet2.png garnet3.png
    sudo mv greguniverse2.png greguniverse3.png
    sudo mv peridot.png peridot3.png
    sudo rm rosequartz2b.png
    sudo rm stevenuniverse2b.png

**Comment by cgolubi1** [comment]
Shadowshade: can you update this branch with the new recipes Jota listed in https://gist.github.com/AdmiralJota/8de348ceb103bd27c93176744faa4995 ?

**Comment by blackshadowshade** [comment]
Updated.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1343/ (if it passes)

**Comment by cgolubi1** [comment]
Updated.  FYI, Jota, the image files all get reset by the update, so what i actually did was:
```
cd /var/www/ui/images/button/
sudo mv connie.png connie3.png
sudo mv garnet.png garnet3.png
sudo mv greguniverse.png greguniverse3.png
sudo mv peridot.png peridot3.png
sudo mv lionsu.png lionsu2.png
sudo mv rosequartz.png rosequartz2a.png
sudo mv stevenuniverse.png stevenuniverse2a.png
```

But it doesn't matter, because in general what i'm going to do is load http://steven-universe.dev.buttonweavers.com/ui/buttons.html?set=Steven%20Universe and iterate until the non-grey buttons are the ones with art.  :>)  So don't worry about providing sample commands, though it can't hurt to remind me to fix the art.

**Comment by cgolubi1** [comment]
So, where are we here?  Any chance we're on track to merge this in the next day or so and release it in August, or do we still want to do a bunch more playtesting?

**Comment by cgolubi1** [comment]
So, i've heard crickets about this, either here or on the forum.  I think we should plan to release these buttons in September, and i'm going to assume by fiat that all of the currently active button versions are the good ones.  So that's:
* Amethyst
* Connie 3
* Garnet 3
* Greg Universe 3
* Jasper
* Lapis Lazuli
* Lion (SU) 2
* Pearl (SU)
* Peridot 3
* Rose Quartz 2A
* Steven Universe 2A

Shadowshade, when you're next working on this, make a new version of the pull that has just those recipes in un-numbered format, and run Jenkins on it.

If anyone objects to fiat, let me know, but please say *something* (at a high level is fine) about what you think the next step is.

**Comment by irilyth** [comment]
I think of this set as being Jota's brainchild, and think we shouldn't release it until he signs off on it.

(That said, if thinks the results of the latest round of playtesting are good and we're ready to go, I think that's great.)

**Comment by blackshadowshade** [comment]
This has been rebased down to one commit and one update file.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1353/ (if it passes)

**Comment by cgolubi1** [comment]
Jota: if you happen to swing by and want to ack this, we'd ideally like to release it for September, but want your signoff before doing so.

**Comment by AdmiralJota** [comment]
Sorry about being out of touch -- I'll look into this this this week and see where it stands.

**Comment by cgolubi1** [comment]
Thanks, Jota (and no apology needed; life happens to all of us).  If it's not ready to release this month, no pressure.  But i'm very enthusiastic to get to play these buttons on the main site, and i'm sure other players are too, so identifying the next step would be great.

**Comment by blackshadowshade** [comment]
I've added a new database update file for testing new recipes with explicitly large button IDs, but not changed any of the rest of the files. Note that the new recipe suggested by @AdmiralJota for Peridot is the same as we currently have, so I haven't included it.

Once we are happy with final recipes, I'll rework the real database creation and update files.

**Comment by AdmiralJota** [comment]
Can we also disable the three buttons that those are replacing?

**Comment by blackshadowshade** [comment]
I'm going to leave the disabling to Chaos, because I don't exactly know how she'll be rolling out the database update---whether she's doing a fresh deploy plus update, or just applying the update to the currently running instance.

**Comment by cgolubi1** [comment]
Okay, sorry to be so slow.  I think i've updated Connie, Garnet, and Greg 4 to be the active versions of each of those buttons on the dev site.  Can y'all check it out?

**Comment by blackshadowshade** [comment]
The update looks good to me.

**Comment by blackshadowshade** [comment]
So, just a reminder to myself that this pull request should not be accepted until the images are updated to match the finally accepted recipes.

**Comment by cgolubi1** [comment]
How do we think people are doing on testing?  I haven't heard anything.  I'll ask on the forum.

**Comment by irilyth** [comment]
I've played games with Connie 4 against all the other buttons. :^ ) I'm not sure what else has gone on.

**Comment by dwvanstone** [comment]
I'm playing a set of games with Jota -- there is no question with functionality, it's just whether Jota is ready to let them go live.

**Comment by AdmiralJota** [comment]
I added an update to the forum post. So far, it looks like Connie is good, Peridot might be OK, and Greg and Garnet need more testing.

**Comment by cgolubi1** [comment]
Okay, cool.  Let's target merging this by 20 November and putting it in the December release.

**Comment by AdmiralJota** [comment]
One more final variation to test:

I'd like to re-enable Garnet 3 and Greg Universe 3 (disabling Garnet 4 and Greg Universe 4).

I'd also like to add Peridot 4 as "(4) (6) (8) (8) r(4/10) r(6/12) r(8/16) r(8/20)" (disabling Peridot 3).

**Comment by blackshadowshade** [comment]
I've added a new database update file 01978_steven_universe_testing_temp2.sql.

This update script is entirely untested, so please scrutinise it before using it, but I think it should be okay.

**Comment by cgolubi1** [comment]
AFAICT the SQL file looks fine.  Updating the dev site.

**Comment by cgolubi1** [comment]
Okay, i copied the new temp file up and did:
```
cat 01978_steven_universe_testing_temp2.sql | mysql -u root buttonmen
sudo mv garnet4.png garnet3.png
sudo mv greguniverse4.png greguniverse3.png
sudo mv peridot3.png peridot4.png
```

Enjoy!  Also, note to self: because of all the merges, i can't use my scripts to update this dev site, and should stop trying.  :>)  Hopefully we won't have any more non-database changes to make, so it'll be fine.

**Comment by blackshadowshade** [comment]
Now that Jota is happy with the recipes (using Lion 2, Rose 2A, Steven 2A, Connie 4, Garnet 3, Greg 3 and Peridot 3), I've updated the pull request and rebased. In doing so, I've removed the temp SQL files that we used to update the database during testing.

@AdmiralJota, please check the recipes.

Next step: to get the images updated to match the recipes, @Hurtay, whenever you're able to do that.

**Comment by AdmiralJota** [comment]
Yup, data.button.sql looks right.

**Comment by cgolubi1** [comment]
Looks good to me.  I think we're waiting for the art before merging.

**Comment by cgolubi1** [comment]
What's the next step on getting setup with art for the current buttons?  Shadowshade, are you following up with that offline?

**Comment by blackshadowshade** [comment]
Yep, @Hurtay is on it, and is just about there. The only change that's not trivial is the change to an option die.

**Comment by blackshadowshade** [comment]
Images have been updated and pull request has been rebased.

Thanks so much, @Hurtay!

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1414/ (if it passes)

**Comment by blackshadowshade** [comment]
There's one mismatch with the images: Lion. I've let @Hurtay know about that, and I anticipate the change should be easy to make.

**Comment by blackshadowshade** [comment]
Okay, the image for Lion has been fixed. I think we're ready to go with this!

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1423/ (if it passes)

**Comment by cgolubi1** [comment]
Let's do this.  Hooray!

**Pull request merged**
