### PR TITLE
Correct calculation of trip attack validity vs Maximum Mood

### LINKED ISSUE #2809: backend incorrectly thinks trip attack vs maximum weak mood die won't work
This attack should be allowed, right?  It isn't:

sure_it_can

(Found this via testing to allow mad/mood in RandomBM.)  If someone can +1 that this should indeed be allowed and i'm not missing something, i'll throw together a responder test.

### PR DESCRIPTION
**Pull request by cgolubi1**
* Fixes #2809

### CODE REVIEW

**Comment by cgolubi1** [comment]
Once i make sure circleci passes, i'll kick off some replay testing to look for any other regressions here --- there shouldn't be any, since presumably no dice currently have Maximum Mood or we would have seen this already.

Shadowshade, do you want a dev site, or just want to look at the code?  Either way is fine with me.

**Comment by blackshadowshade** [comment]
Would you mind adding a test for Mad too, please?

**Comment by cgolubi1** [comment]
Sure, no problem.

**Comment by blackshadowshade** [comment]
Looks good to me. Once you're satisfied with replay testing, I'm happy to merge this.

**Review by blackshadowshade — APPROVED** [review]

**Comment by cgolubi1** [comment]
Okay, over 10000 games played, nothing to see.  Since i have Shadowshade's permission, i'll go ahead and merge this, and then i can go back to testing mad/mood in RandomBM.

**Pull request merged**
