### PR TITLE
Push changes from master to staging on 2017-12-03

### PR DESCRIPTION
**Pull request by cgolubi1**
This update brings these approved pulls to the staging branch:

* User-visible:
    * #2130: Steven Universe set
    * #2286: Apple touch/android icon
    * #2292: Allow History page to show new games
    * #2293: Change wording of dropdown select text for cancelling during fire turndown
* Ideally not user-visible:

Database updates:
```
UPDATES="01978_steven_universe_01.sql 01839_new_in_progress_history_01.sql"
```

Once this pull is merged, i will load the changes on staging.buttonweavers.com as part of #2295.

### CODE REVIEW

**Comment by cgolubi1** [comment]
I'll go ahead and load this on staging now.

**Comment by cgolubi1** [comment]
Okay, it's up.  Check it out, and i'll do the prod release Tuesday if i don't hear any reasons not to.

**Comment by dwvanstone** [comment]
I don't know if it's an issue, but when I go to the History page and look for Unstarted games I find games 98 and 99 which are user "emuking" vs. user "null". I assume this is a data migration issue and wouldn't happen on the production site, but I wanted to check.

**Comment by blackshadowshade** [comment]
@dwvanstone, that's a real issue, because emuking has two open games with no selected opponent's button. I'll look at getting a fix in for this ASAP.

**Comment by dwvanstone** [comment]
The fix looks great - thank you! (The button art for SU also looks great.) Congratulations!!

**Pull request merged**
