### PR TITLE
Added button name to compact mode

### LINKED ISSUE #1807: Compact mode missing button names
If I play with the preference "Use compact version of game interface" I can't tell the name of my button or my opponent's button.

This causes trouble when there is a button-based skill (such as The Japanese Beetle) but I can't tell which button it relates too.

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #1807.

### CODE REVIEW

**Comment by blackshadowshade** [comment]
On my computer, with compact mode turned on, this now looks like this:

compact_mode_with_button_names

**Comment by blackshadowshade** [comment]
Oh oops, just noticed the logical problem with "Your button:" for the opponent. Just changing this now.

**Comment by blackshadowshade** [comment]
Image updated with change.

compact_mode_with_button_names

**Comment by dwvanstone** [comment]
Yes, just "Button" seems like the right solution. Nice.

**Comment by cgolubi1** [comment]
Dev site for compact mode button name - http://stopgap.dev.buttonweavers.com/ui/ - check it out.

**Comment by dwvanstone** [comment]
This looks good to me!

**Comment by cgolubi1** [comment]
Thanks!  Merging.

**Pull request merged**
