### PR TITLE
Upgrade buttonweavers site to Ubuntu Xenial

### LINKED ISSUE #2398: Site upgrade
The production instance that we are currently running needs updating, for a number of reasons:
- to bring various software products up to a currently-supported version
- to allow us to use new features
- to bring in security patches

Specific issues that may relate to this site upgrade are:
- [ ] #161: Downloading PHPUnit via puppet
- [ ] #224: Using SSL
- [ ] #439: JQuery version
- [ ] #440: JSHint version
- [ ] #575: Puppet version
- [ ] #1083: Manage third-party Javascript libraries
- [ ] #1097: buttonweavers.com should redirect to www.buttonweavers.com
- [ ] #1167: Upgrade PHP
- [ ] #1168: Upgrade PHPUnit
- [ ] #1339: Backup drive running out of space
- [ ] #1989: Connection errors
- [ ] #2143: MySQL settings to enable temporary backups
- [ ] #2197: Python 3 compatibility
- [ ] #2208: Adding the statistical environment R
- [ ] #2342: Changing CircleCI to use the new upgraded versions

### PR DESCRIPTION
**Pull request by cgolubi1**
* Fixes #2398 
* See discussion in #2398 for site upgrade plan, and in #2411 for shadowshade's code changes

### CODE REVIEW

**Comment by cgolubi1** [comment]
Ugh.  With shadowshade's new changes, this is failing out on every Dead Guy game, because it's no longer rolling zero-sided dice in all cases.

**Comment by blackshadowshade** [comment]
I'm happy to do the site upgrade first and postpone the changes to make the code fully PHP 5.4+ compliant. I agree that the code changes are not harmless if they're causing your test rig to fail.

However, I have to disagree that most of the changes are unnecessary. With the PHP 5.4+ changes, many of the tests are simply not testing anything---I've tested manually, and they're not picking up bad cases, even when I create them artificially. Because the unit tests are compromised, that reduces my security that the live site code is actually doing the right thing too.

After the site upgrade is done and dusted, I'd suggest that we need a test that specifically targets the Dead Guy bug. We should also put our live site users on alert that there may be odd behaviour, and that they should report their suspicions sooner rather than later.

**Comment by blackshadowshade** [comment]
BTW, have I mentioned recently that I dislike PHP and it's weakly-typed variables?

**Comment by blackshadowshade** [comment]
And have I mentioned recently that PHP's object orientation is still broken?

**Comment by blackshadowshade** [comment]
Let's close this pull request then, in favour of #2413.

**Pull request closed without merging**
