### PR TITLE
Addresses multiple issues regarding RandomBM

### PR DESCRIPTION
**Pull request by blackshadowshade**
Addresses part of #779.

See commit message for details of changes.

Requires database update 00779_05_RandomBM.sql

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/663/ (if it passes)

### CODE REVIEW

**Comment by blackshadowshade** [comment]
Jenkins won't pass this, and again, I have no idea why not. Perhaps it's PHPUnit timing out or something. I'll wait until we have another pull request accepted, then try a merge of upstream/master and another Jenkins run then.

**Comment by blackshadowshade** [comment]
Oh wait, ignore that. I've found the error under responder test test_interface_game_026.

**Comment by blackshadowshade** [comment]
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/665/ (if it passes)

**Comment by cgolubi1** [comment]
Hmm.  I hadn't looked at this at all --- shadowshade, will this database update work?  Don't existing games index buttons by ID?  If you change button IDs on deployed buttons, won't that break all existing games which contain those buttons?

**Comment by blackshadowshade** [comment]
Can you believe that I didn't even think of how this would impact currently existing games?  XD

I've just realised that I don't know how to do the button id swap (and the related button ids in the game table) in a single transaction in MySQL, so it might actually be best if I just back out the database changes and leave the database unchanged.

**Comment by blackshadowshade** [comment]
Would it be something like this?

START TRANSACTION;

UPDATE game SET button_id = 20000 WHERE button_id=(SELECT id FROM button WHERE name = "RandomBMFixed");
UPDATE game SET button_id = 20001 WHERE button_id=(SELECT id FROM button WHERE name = "RandomBMAnime");

DELETE FROM button WHERE name="RandomBMFixed";
DELETE FROM button WHERE name="RandomBMAnime";

INSERT INTO button (id, name, recipe, btn_special, tourn_legal, set_id) VALUES
(10002, 'RandomBMAnime',   '', 1, 0, (SELECT id FROM buttonset WHERE name="RandomBM")),
(10004, 'RandomBMFixed',   '', 1, 0, (SELECT id FROM buttonset WHERE name="RandomBM"));

UPDATE game SET button_id = (SELECT id FROM button WHERE name = "RandomBMAnime") WHERE button_id=20000;
UPDATE game SET button_id = (SELECT id FROM button WHERE name = "RandomBMAnime") WHERE button_id=20001;

UPDATE button
SET flavor_text='This button gets a different random recipe in each game, with a fixed random formula: 5 dice, no swing dice, two of them having a single skill chosen from c, f, and d (the same skill on both)'
WHERE name='RandomBMFixed';

UPDATE button
SET flavor_text='This button gets a different random recipe in each game, with a fixed random formula: 5 dice, no swing dice, three skills chosen from {cdfgkMnopqstvz}, with each skill dealt out twice randomly and independently over all dice)'
WHERE name='RandomBMMixed';

UPDATE button
SET flavor_text='This button gets a different random recipe in each game, with a fixed anime formula: 4 normal dice and 4 reserve dice, chosen from standard die sizes'
WHERE name='RandomBMAnime';

COMMIT;

**Comment by blackshadowshade** [comment]
Okay, new update file is in place.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/675/ (assuming it passes)

**Comment by blackshadowshade** [comment]
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/676/ (assuming it passes)

**Comment by blackshadowshade** [comment]
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/690/ (if it passes)

**Comment by cgolubi1** [comment]
So, at the end of the day, this pull doesn't actually change gameplay behavior much.  The only thing that's really of interest is the database update script.  To that end, i need to:
* Create some games with each of the RandomBM buttons in various states of gameplay, perform the update, and visually diff the games to make sure they look the same
* Run the update on a copy of the actual DB from bmdev, to get the same effect with live data
* Run a few RandomBM games using RandomAI, to look for unexpected internal errors
* Run a few RandomBM games by hand, to look for unexpected regressions

**Comment by cgolubi1** [comment]
Okay, nothing unexpected here.  It can be merged once the freeze is lifted.

**Comment by cgolubi1** [comment]
Merging this now to unblock things, and then we'll see what else is unconflicted.

**Pull request merged**
