### PR TITLE
Added FAQ text

### PR DESCRIPTION
**Pull request by blackshadowshade**
Addresses part of #2469.

### CODE REVIEW

**Comment by cgolubi1** [comment]
I stood up a dev site for this.  Irilyth, when you get a second, please sync up 54.89.147.252 == blip.dev.buttonweavers.com

**Comment by cgolubi1** [comment]
Testers, the new FAQ page is http://54.89.147.252/ui/faq.html

**Comment by cgolubi1** [comment]
I want to flag the use of the `createDocumentFragment` function.  We don't use it anywhere else.  Does it have any side effects or implications we need to care about?

I'm particularly interested because the new page is accessible without logging in, so i want to make sure the new page is very boring in terms of what it talks to.  It doesn't make any API calls at all, right?

**Comment by blackshadowshade** [comment]
The createDocumentFragment function is a standard Javascript function. It creates a placeholder node that is removed when the fragment is attached to something else.

https://www.w3schools.com/jsref/met_document_createdocumentfragment.asp

On this link (point 5), it even extols the virtues of using DocumentFragments:

https://www.toptal.com/javascript/10-most-common-javascript-mistakes


And yes, you are correct that there are no API calls.

**Comment by irilyth** [comment]
> I stood up a dev site for this. Irilyth, when you get a second, please sync up 54.89.147.252 == blip.dev.buttonweavers.com

Done!

```
+$ host blip.dev.buttonweavers.com
blip.dev.buttonweavers.com has address 54.89.147.252
```

**Comment by cgolubi1** [comment]
Playtesters, feedback on http://blip.dev.buttonweavers.com/ui/faq.html ?  Any obvious things that should be added/removed/fixed before we call this a good start?

**Comment by dwvanstone** [comment]
* I might suggest changing:

"If you select the trip attack, the (8):5 rerolls and might not even be captured."

to

"If you select the trip attack, both dice reroll and the (8):5 might not even be captured."

* "The Flying Squirrel has a [button special](http://blip.dev.buttonweavers.com/ui/faq.html#ButtonSpecial) that says that it can't do Skill attacks. Too bad. At least it has Speed dice."

Could the link on "button special" go The Flying Squirrel's button page instead so the person can read the text describing the specialness? 

* "The Japanese Beetle has a [button special](http://blip.dev.buttonweavers.com/ui/faq.html#ButtonSpecial) that says that it can't be attacked by Skill attacks. Too bad. Not much you can do."

Same with this page. Also perhaps "Not much you can do." could be, instead, "At least he only has four dice."

Great! It's nice to see this started!!!

**Comment by blackshadowshade** [comment]
What about having the name "The Flying Squirrel" and "The Japanese Beetle" link to their respective button pages?

**Comment by cgolubi1** [comment]
> What about having the name "The Flying Squirrel" and "The Japanese Beetle" link to their respective button pages?

Sounds fine to me.

**Comment by blackshadowshade** [comment]
Changes made as requested. We need to check that I have the correct relative path to the button pages when this has been updated.

**Comment by cgolubi1** [comment]
Updated the dev site.

**Comment by dwvanstone** [comment]
The dev site looks good! Yay!

**Comment by blackshadowshade** [comment]
The links from The Flying Squirrel and The Japanese Beetle work correctly, so yay from me!

**Comment by cgolubi1** [comment]
Sounds like this is ready to merge.  Shadowshade, want to rebase it when you get a chance?

**Comment by blackshadowshade** [comment]
Rebased.

**Pull request merged**
