### PR TITLE
Enable Mad and Mood skills in RandomBM

### PR DESCRIPTION
**Pull request by cgolubi1**
* Partially addresses #2067 

Replacement PR for #2800 which is now ready to test

Replay testing has been done using commit [47ae228](https://github.com/buttonmen-dev/buttonmen/pull/2844/commits/47ae228d2d1f419ee5fff3dea1d5a9dee3139d89), see comment below for details.

Dev site: https://2067-enable-mad-mood.cgolubi1.dev.buttonweavers.com/

### CODE REVIEW

**Comment by cgolubi1** [comment]
Dev site is up at https://transient.dev.buttonweavers.com/ui/ which allows mad and mood in RandomBM variants.

**Comment by blackshadowshade** [comment]
Okay, this is a call for testers to have a look at mad and mood in RandomBM.

**Comment by blackshadowshade** [comment]
That's a good question, and from what I can remember, yes it's possible to have both Mad and Mood on a die.

Don't ask me what would happen, I have no idea! I *guess* that perhaps Mad might take priority over Mood? This could be tested on staging with a CustomBM.

**Comment by blackshadowshade** [comment]
Also, I don't consider RandomBM to be fun, generally, so adding meaningless skills doesn't change the fun quotient for me.  :)

**Comment by cgolubi1** [comment]
Hmm, yeah, maybe it'd be a good idea to make a set of skills that, if they're chosen for the button, go on the swing die rather than on a random subset of dice.  Not sure how logically complicated that would be; i'll take a look when i get a chance.

**Comment by blackshadowshade** [comment]
The logic is not difficult, it's just a matter of adding a conditional or two into BMButtonSkillRandomBM->generate_die_skills() to ensure that Mad/Mood/Turbo are added first and only to Swing dice.

**Comment by dwvanstone** [comment]
> Don't ask me what would happen, I have no idea! I guess that perhaps Mad might take priority over Mood? This could be tested on staging with a CustomBM.

I've confirmed that, on customrecipe, Mad & Mood can share space on a swing die. It seems that Mad takes precedence -- one of my dice became 18-sided.

**Comment by cgolubi1** [comment]
I'll do more replay testing after i make the code changes.

**Comment by cgolubi1** [comment]
I've stood up a new dev site at https://2067-enable-mad-mood.cgolubi1.dev.buttonweavers.com/ --- this code should allow Mad and Mood skills on RandomBM, but only on swing dice (there are no option dice in RandomBM at the moment).

**Comment by cgolubi1** [comment]
I stood up a replay site.  For now, i'm just having it play whatever games, so i can address any issues that arise with replay and `bm_skill_rand()`.  I'll be more targeted in the future.

**Comment by cgolubi1** [comment]
I realised the previous version wasn't quite right, because it changed the behavior of `bm_skill_rand()` in a way that was going to break the replay benefits which are why i built `bm_skill_rand()` to begin with.  So i refactored the logic a bit.  Behavior should be exactly the same, but i rebuilt the dev site just in case.

**Comment by cgolubi1** [comment]
I fixed another logic bug and rebuilt the sites yesterday evening.  Since then, it's played 1100 novel games with unspecified random buttons.  Now i'm testing play and replay with `RandomBM*` buttons.

**Comment by cgolubi1** [comment]
Replay testing played and replayed 1300 games using RandomBM buttons, in addition to the previous 1100 with miscellaneous buttons, and the same number of replayed games from the main branch.

Given the nature of the changes, if we were going to find any issues via replay testing, that would be enough to find them, so i've torn down the replay site.  Now it's just to testers to take a look at the dev site (and James to look at the code).  No rush on any of that.

**Comment by dwvanstone** [comment]
I've created several RandomBM v RandomBM games and have found no issues.

**Comment by blackshadowshade** [comment]
Code changes look good to me. I'm happy to approve this based on automated testing, manual testing, and CircleCI.

**Pull request merged**
