### PR TITLE
Updated Fanatics images

### LINKED ISSUE #2721: Additional image updates (Fanatics, Hodgepodge, etc)
This issue will be for further Classic Fanatics being updated to include new images from the suggestions of their creators.

This is submitted for Limax's approval.  This is the nicest public domain picture I could find of a wombat.

Large (if he wants a button)
LimaxFanatic

150px (for the site, with shine/shade)
150pxLimax

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #2721.

This is a pull request that updates images for some Classic Fanatics and adds an image for Tyler Durdan.

I note that the spelling of Tasslehoff B on the button is incorrect because it has an "el" instead of the correct "le".

Dev site: https://2721-fanatics-images.blackshadowshade.dev.buttonweavers.com/ui/

### CODE REVIEW

**Comment by blackshadowshade** [comment]
@TheOrgg, if you're able to alter the text on the Tasslehoff B button, that would be super! If not, the current version is still better than the old version.

**Comment by TheOrgg** [comment]
I'll see if the PSP8 is working or not on my new laptop.  If it is, I can correct the misspelling.  If it isn't...  well, the error persists on the Fog-designed one we are currently using.

**Comment by blackshadowshade** [comment]
> Tyler Durden's last name ends in `en`, not `an`.
> 
> (The button art is correct, but the filename is wrong.)

Fixed! Thanks for picking that up!

**Comment by TheOrgg** [comment]
I was able to get psp8 working again, but you've got to go in and follow the directions to delete the registry.  Every.  Time.  You.  Start.  It.

**Comment by blackshadowshade** [comment]
I've updated the image but the font is gray instead of orange. Just waiting for confirmation that this is correct.

**Review by TheOrgg — APPROVED** [review]

**Comment by cgolubi1** [comment]
I stood up a dev site at https://2721-fanatics-images.blackshadowshade.dev.buttonweavers.com/ui/ so someone can take a look at the images and see if they're correct in context.

**Comment by TheOrgg** [comment]
Briefly scrolling through the Fanatics, it looks right to me.

**Comment by cgolubi1** [comment]
@blackshadowshade what else do you think is needed on this?  TheOrgg looked at the images on the dev site, you addressed irilyth's spelling callout.  Is it ready to go, or are there more things?  If there are more things, let's make a checklist.

**Comment by blackshadowshade** [comment]
I think this is good to go.

**Comment by cgolubi1** [comment]
Thanks!  Merging.

**Pull request merged**
