### PR TITLE
Updated broken links, part two (including removing old help page)

### LINKED ISSUE #2821: Remove the unused help page
In #2818, we discovered that we have two help pages. Remove the unused one, and transfer any relevant changes to the new help page.

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #2821.

I've removed the old help page, updated the relevant links in the new help pages, and updated a number of other similar links.

### CODE REVIEW

**Comment by cgolubi1** [comment]
I'm going to stand up a dev site and see if i can review this myself in time for this week's release; if not, it'll go next week.

**Comment by cgolubi1** [comment]
* The help link at https://momentary.dev.buttonweavers.com/ui/help.html seems to have the right stuff
* The forum `[wiki=]` syntax seems to successfully link to pages on the fandom site.
* Hmm, as far as i can tell, https://cheapass.com/free-games/button-men/ doesn't link anywhere good --- but neither does http://cheapass.com/free-games/button-men/ so this isn't a regression in this PR.  Is it new, though?  Did it recently link anywhere good?

**Comment by cgolubi1** [comment]
Anyway, i don't see any regressions in this PR, so i'm going to merge it.

**Comment by blackshadowshade** [comment]
Looks like this is a moving target. I'll put in another pull request to address the newly broken link.

**Pull request merged**
