### PR TITLE
testing: Added logging logic for mood recipe changes

### PR DESCRIPTION
**Pull request by blackshadowshade**
Proposed fix for #1411 and #1663.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1230/

### CODE REVIEW

**Comment by cgolubi1** [comment]
If the pull adds significant code, the pull must add enough tests to keep PHP and JS code coverage percentages at their previous level
    If the pull contains database changes, the changes must apply identically to fresh DB loads and to DB updates (the reviewer should do an update-vs-reload test to verify this)
    The code must not contain anything so offensive we are unwilling to have it in our codebase (this is necessarily subjective, and hopefully unlikely to come up)

**Comment by cgolubi1** [comment]
I hope this isn't me being too picky:
* If the pull adds significant code, the pull must add enough tests to keep PHP and JS code coverage percentages at their previous level

This change adds 51 lines to BMGameAction, and afaict the code coverage drops somewhat --- i'm comparing http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1230/cloverphp-report/_srv_jenkins-jobs_buttonmen-blackshadowshade_workspace_src_engine_BMGameAction.php/ to, say, http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1228/cloverphp-report/_srv_jenkins-jobs_buttonmen-blackshadowshade_workspace_src_engine_BMGameAction.php/

I think it'd be better to add another test for BMGameAction to cover the new logic there.

**Comment by blackshadowshade** [comment]
I've added unit tests to BMGameActionTest.php.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1241/

**Comment by blackshadowshade** [comment]
Closing this because we have #1675.

**Pull request closed without merging**
