### PR TITLE
1904 warrior help text

### LINKED ISSUE #1904: Warrior die help text doesn't mention starting value
The Warrior die help text says "The Warrior die adds its full value to the Skill Attack.", but doesn't say that its initial showing-value is equal to its maximum value. (Another player asked about this in a game we're playing, so I have at least one live example of someone being surprised by this.)

### PR DESCRIPTION
**Pull request by irilyth**
Fixes #1904.

http://jenkins.buttonweavers.com:8080/job/buttonmen-irilyth/17/

### CODE REVIEW

**Comment by blackshadowshade** [comment]
Personally, I don't like the phrase "initial showing value". Could we go with something more like "value showing at the beginning of the round"?

**Comment by cgolubi1** [comment]
Okay, there's nothing to test here because Jenkins took care of that, so we just need to adjudicate what we actually want the text to be.  My suggestion is to replace the sentence:
```
At the start of the round, their initial showing value is equal to their maximum value; when they\'re brought into play, they\'re rolled as usual.
```

with something like:
```
At the start of the round, each Warrior die shows its maximum value; when it\'s brought into play, it\'s rolled as usual.
```

That's a little shorter, and gets rid of the "initial showing value" phrase that shadowshade dislikes.  I think it's clear.  Do others?

Throwing this back over the fence to irilyth for further opinions about the various proposals.

**Comment by blackshadowshade** [comment]
I like Chaos's suggestion for wording here.

**Comment by blackshadowshade** [comment]
Just a reminder to @irilyth that this is awaiting his update.

**Comment by irilyth** [comment]
Sure, that wording seems fine to me; http://jenkins.buttonweavers.com:8080/job/buttonmen-irilyth/18/ (if it passes).

(Did I correctly merge dev into my branch? I feel like there are a whole bunch of commits now on this PR that have nothing to do with my fix, but maybe that's normal.)

**Comment by blackshadowshade** [comment]
The way to tell if the merge went correctly is to look at what Github thinks is the diff. I get the feeling that you've added changes to the Python files at some time. Perhaps you want to try creating a new pull request from scratch, considering that the changes you're proposing are so small.

**Comment by irilyth** [comment]
Hmm, so the diff is actually pretty close, but it thinks there are  tools/api-client/python/lib/bmapi.py  and  tools/api-client/python/lib/bmutils.py changes in here, which I think aren't mine. Oh, maybe I merged the wrong thing -- I pulled upstream/dev, did I actually want upstream/master?

**Comment by blackshadowshade** [comment]
I thought that the two should currently be identical. However, upstream/master is the one that we normally merge, yes.

**Comment by irilyth** [comment]
Yeah, that's the problem, I've picked up stuff that Dan Bagels merged into upstream/dev for whatever reason.

Hmm, lemme see if I can rebase my way out of this, or if that confuses Jenkins too much.

**Comment by blackshadowshade** [comment]
That code that is merged into upstream/dev is something we should certainly check out (and by we here, I'm thinking that Chaos is going to have to do some funky gitting to get us out of it).

**Comment by irilyth** [comment]
Ok, I have rebased stuff to death, which seems not to have confused GitHub, which now thinks I have one commit to merge, which looks like the commit I want. It makes somewhat nonsensical people's comments about previous versions of this, since those versions no longer exist. Jenkins is currently building a commit that's now orphaned, and which may vanish entirely at some point. I'm not sure if this is pleasantly clean, or crazy time travel, or what -- if anyone has opinions, let me know. :^)

I think this PR will end up ok, though. But if it's not, I can certainly open a new one.

**Comment by irilyth** [comment]
Ok, http://jenkins.buttonweavers.com:8080/job/buttonmen-irilyth/19/ passed but not for the commit that this PR is now about. http://jenkins.buttonweavers.com:8080/job/buttonmen-irilyth/20/ is now building the commit that this PR is about, and should pass.

**Comment by blackshadowshade** [comment]
The pull request looks good now. Remember that you can always cancel Jenkins runs that are not required by hitting the red cross.

**Comment by irilyth** [comment]
I had forgotten about canceling Jenkins runs, that's good to know. In this case, I was interested in finding out if the useless run worked because it did have the correct contents, so if it passed, then I could safely commit and push my new real commit, and be confident that that would pass too.

**Comment by cgolubi1** [comment]
Hmm... i just realised that the entirety of the Warrior help text does not say whether or not your inactive Warrior dice are still worth half-points to you.  I'm going to go ahead and merge this, because it seems silly not to and that wasn't part of this initial issue, but i'm going to open an issue for that.

**Pull request merged**
