### PR TITLE
Added images from old site, part 3 (sk to z)

### PR DESCRIPTION
**Pull request by blackshadowshade**
Third part of the images pull request, open for comment.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1155/

### CODE REVIEW

**Comment by blackshadowshade** [comment]
@Hurtay has already noted that Zeno has no recipe.

**Comment by blackshadowshade** [comment]
To my eye, all these look like improvements.

**Comment by AdmiralJota** [comment]
Looks good to me.

**Comment by cgolubi1** [comment]
Okay, this is the usual drill.

**Comment by cgolubi1** [comment]
Again, don't see any issues.  Merging.

**Pull request merged**
