### PR TITLE
Push changes from master to staging on 2019-03-12

### PR DESCRIPTION
**Pull request by cgolubi1**
This update brings these approved pulls to the staging branch:

* User-visible:
    * #2429: Change copyright year to 2019
    * #2426, #2434: Change the API to use JSON serialization rather than URL encoding for all API methods
    * #2428: Add skill interaction description for warrior and stinger
* Ideally not user-visible:
    * #2431: test infrastructure fix: get phpcs from somewhere else
    * #2437: update stats script (only used by the stats site)

Database updates:
```
UPDATES=""
SCRIPTS=""
```

Once this pull is merged, i will load the changes on staging.buttonweavers.com as part of #2438.

### CODE REVIEW

**Comment by cgolubi1** [comment]
I'll merge and load this later today.

**Comment by cgolubi1** [comment]
...or maybe in a couple of days.  Now, anyway.

**Comment by cgolubi1** [comment]
Okay, that's done.  Can folks check out the staging site over the next day or two, and make sure things look normal?  The API encoding is the big change, so make sure you can run your bots and scripts using the newer version of `bmapi.py` or whatever client you're using, and make sure the web UI looks okay.  I'll plan to do the prod release Thursday morning barring the unexpected.

**Comment by dwvanstone** [comment]
"Add skill interaction description for warrior and stinger" and the 2019 copyright look fine. I poked around a bit. Looks good!

**Comment by cgolubi1** [comment]
Thanks, dwvanstone!  No other comments, so i'm going to say this is good to go.

**Pull request merged**
