### PR TITLE
Added text to About page

### LINKED ISSUE #2468: Fill in page about the site
Spawned from #1924.

Fill in the contents of the page about.html

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #2468.

I've also taken this opportunity to add a link from the main help page to the Button Men wiki.

### CODE REVIEW

**Comment by blackshadowshade** [comment]
If anyone wants to add anything to the "About this site" page, let me know, and I'll add it to this pull request.

**Comment by cgolubi1** [comment]
Testers, please check this out on http://stopgap.dev.buttonweavers.com/ui/about.html

**Comment by dwvanstone** [comment]
The About page is fantastic. All links works fine. Thanks!

**Comment by cgolubi1** [comment]
Thanks, dwvanstone!  Merging.

**Pull request merged**
