### PR TITLE
pull changes from master to dev on 2015-01-07

### PR DESCRIPTION
**Pull request by cgolubi1**
This update brings these approved pulls to the dev branch:
* User-visible:
    * #1474: vanilla RandomBM
    * #1490, #1492: new button art for soldiers and art for radioactive fanatics
    * #1484: in the overview page, display games waiting for opponent from most- to least- recently updated
    * #1486: increase maximum chat length to 2000 chars
* Ideally not user-visible:
    * #1478, #1482: work on cleaning up UI unit tests

Database updates:
```
00367_chat_length.sql
00779_RandomBM.sql
```

Once this pull is merged, i will load the changes on dev.buttonweavers.com as part of #217.

### CODE REVIEW

**Comment by cgolubi1** [comment]
Merging, then i'll test on vagrant.

**Comment by cgolubi1** [comment]
Oh, hi, i need a database update sort order:
```bash
$ UPDATES="00367_chat_length.sql 00779_RandomBM.sql"
$ git log --reverse --first-parent --oneline $UPDATES
9f9cd4e Merge pull request #1486 from blackshadowshade/367_chat_length
dadd1fa Merge pull request #1474 from blackshadowshade/779_RandomBM
$ UPDATES="00367_chat_length.sql 00779_RandomBM.sql"
```

**Comment by cgolubi1** [comment]
Database changes are as expected --- new RandomBMVanilla button and RandomBM buttonset, and the message field is longer.  I can login and play part of a game, and start a RandomBMVanilla game.  Loading on dev now.

**Comment by blackshadowshade** [comment]
The order of the database updates shouldn't matter in the slightest in this instance.

**Comment by cgolubi1** [comment]
> The order of the database updates shouldn't matter in the slightest in this instance.

Yeah, but it's never *wrong* to just do the process, and the process is one 3 lines of shell that i copy and paste.

**Pull request merged**
