### PR TITLE
Make CustomBM actually work under RandomAI replay loops

### LINKED ISSUE #2753: random_ai replay of custom games doesn't work
Stock replay of games containing CustomBM fails:

```
Time: 35.85 minutes, Memory: 132.00Mb

There was 1 failure:

1) responder99Test::test_interface_game_00035
API call should succeed:
ARGS: array (
  'type' => 'createGame',
  'playerInfoArray' => 
  array (
    0 => 
    array (
      0 => 'responder003',
      1 => 'CustomBM',
    ),
    1 => 
    array (
      0 => 'responder004',
      1 => 'Agatha',
    ),
  ),
  'maxWins' => 3,
  'description' => '',
)
RETURN: array (
  'data' => NULL,
  'message' => 'customRecipeArray must be supplied',
  'status' => 'failed',
)
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'ok'
+'failed'

/buttonmen/test/src/api/responderTestFramework.php:986
/buttonmen/test/src/api/responderTestFramework.php:1022
/buttonmen/test/src/api/responder99Test.php:48562

FAILURES!
Tests: 101, Assertions: 29262, Failures: 1.
```

I'm very sure this is just a `prep_replay_games` bug (i.e. we're failing to pipe the customRecipeArray through the transition from novel CustomBM game to responderTest), and is not actually a codebase problem.

### PR DESCRIPTION
**Pull request by cgolubi1**
* Fixes #2753

### CODE REVIEW

**Comment by cgolubi1** [comment]
I ran some test games with a modified replay_loop that has a higher than usual chance of choosing CustomBM for one or both buttons, and it seemed to work.  Some example outputs:

```php
    /**
     * @depends responder00Test::test_request_savePlayerInfo
     * @group fulltest_deps
     */
    public function test_interface_game_00008() {

        // responder003 is the POV player, so if you need to fake
        // login as a different player e.g. to submit an attack, always
        // return to responder003 as soon as you've done so
        $this->game_number = 8;
        $_SESSION = $this->mock_test_user_login('responder003');


        // Expect game creation to fail
        $args = array(
            'type' => 'createGame',
            'playerInfoArray' => array(array('responder003', 'Agatha'),
                                       array('responder004', 'CustomBM')),
            'maxWins' => '3',
            'customRecipeArray' => array(1 => '^o(W) &(18) (91) ;aIA(17)'),
        );
        $this->verify_api_failure($args, 'Custom recipe ^o(W) &(18) (91) ;aIA(17) is not allowed to contain unimplemented skills.');
    }
```

```php
    /**
     * @depends responder00Test::test_request_savePlayerInfo
     * @group fulltest_deps
     */
    public function test_interface_game_00009() {

        // responder003 is the POV player, so if you need to fake
        // login as a different player e.g. to submit an attack, always
        // return to responder003 as soon as you've done so
        $this->game_number = 9;
        $_SESSION = $this->mock_test_user_login('responder003');


          $gameId = $this->verify_api_createGame(
              array('bm_rand' => array(5, 1, 2, 1, 3, 5), 'bm_skill_rand' => array()),
              'responder003', 'responder004', 'CustomBM', 'Agatha', 3,
              '', NULL, 'gameId', array(0 => 'w(7) `(R)')
          );

        $expData = $this->squash_game_data_timestamps(json_decode('{"previousGam
...
```

**Comment by cgolubi1** [comment]
I'm now running a normal "archival" replay loop using this code, and i'd like to see whether it works well for a day or two before merging this.  I don't think there's any issue with merging it during the code freeze --- it's random_ai only --- and i would like to make sure replay testing of CustomBM is working okay in general.

Shadowshade: i'll let you know when i've done enough testing of this that i'm comfortable with it.  Please lmk if you have any other concerns about it.

**Comment by blackshadowshade** [comment]
As you say, this is a change to random_ai only, so I have no problems with us merging this during merge freeze.

**Comment by cgolubi1** [comment]
Okay, i'd be happy to have you merge this, and thanks --- it's replayed 1100 games without problems, which doesn't prove everything, but is much better than what was happening before, and i would expect any new bugs to be superficial.

**Comment by blackshadowshade** [comment]
And done!

**Pull request merged**
