### PR TITLE
Reversed display order of games awaiting opponent's action

### LINKED ISSUE #1169: Sort Overview page in reverse chronological order
Suggested by nkmcalli at http://www.buttonweavers.com/ui/forum.html#!threadId=3

Nicole would like the "waiting for opponent's turn" section sorted in reverse chronological order, but I think that it wouldn't hurt to apply this to the "waiting for you" section also.

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #1169.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/571/

### CODE REVIEW

**Comment by cgolubi1** [comment]
I don't like this approach, because it's reversing the API load order, not the display order.  That's going to be confusing to future developers.  Why not use something like the JS `reverse()` method when setting up `gamesource` within `Overview.pageAddGameTable()`, to make it clear what the code is doing?

**Comment by blackshadowshade** [comment]
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/584/

**Comment by cgolubi1** [comment]
Thanks, that's better.  It should be quick for me to check this one out and make sure it actually does the right thing, then i'll merge it.

**Comment by cgolubi1** [comment]
Looks right.  Games waiting for me are still sorted most-stale-to-least-stale, while games waiting for my opponent are sorted least-to-most stale.  Clicking around using the "Next game" button still does what i expect.  Completed games still show up most-stale-to-least-stale, and dismissing completed games still works.  Merging.

**Pull request merged**
