### PR TITLE
Footer

### PR DESCRIPTION
**Pull request by blackshadowshade**
I'm putting this pull request up so that I can get some help with working out how to get the QUnit tests to pass.

This is based on Jota's footer incomplete pull request #1218. The current status of the pull request is that the footer is now flush to the bottom of the page. There are still a number of other comments from #1218 that remain unaddressed, and I'll deal with them once I get the QUnit tests passing.

### CODE REVIEW

**Comment by blackshadowshade** [comment]
As a summary of what I've done, I have added a new div structure:
- div container
  - div c_header
    - div login_header
    - hr header_separator
  - div c_body
    - div env_message
    - div ...
  - div c_footer
    - hr footer_separator
    - div footer

The divs starting with c_ are all there to implement the method that you suggested to force the footer to be at the bottom of the screen.

**Comment by blackshadowshade** [comment]
I've been doing some digging, and it seems that most of the errors are occurring because env_message is now inside of c_body, plus there are the four extra divs (container, c_header, c_body, c_footer). I can't seem to get the QUnit tests to pass by deleting the extra divs, since other things break.

Also, there's a whole pile of tests that have a call of .remove() followed by .empty(). I thought that .remove() already did an implicit .empty() first, so the .empty() makes no sense. Have I missed something?

**Comment by cgolubi1** [comment]
I notice the footer seems to be visually a mess if there's more than a page worth of stuff going on:
footer_in_game

Do you in fact want to debug the QUnit tests before sorting that out?  It seems like there might be a big refactor needed to make that work.

**Comment by blackshadowshade** [comment]
Right, Chaos and I have chatted about this on IRC, and I'll be breaking this pull request up into little bits. The first part is to add the enclosing <div> and get the QUnit tests working with that.

I'll leave this pull request open just for convenience. Eventually, we'll close it unmerged.

**Comment by blackshadowshade** [comment]
Closing this because we now have pull request #1702, which contains most of the content of this pull request.

**Pull request closed without merging**
