### PR TITLE
Push changes from master to staging on 2016-12-08

### PR DESCRIPTION
**Pull request by cgolubi1**
This update brings these approved pulls to the staging branch:
* User-visible:
    * #2084, #2140: Removed word 'Game' from the first column on the overview page
    * #2121: Added logic to check what sort of click is used on a pseudolink
    * #2126: Updated images for Cowboy Bebop
    * #2128: Changed button name Peri to Perf
* Ideally not user-visible:
    * #2124: Changed Cheese Weasel to having a button special
    * #2135: Define puppet_hostname for new IP for staging.buttonweavers.com so its mail will be accepted by more servers 

Database updates:
```
UPDATES="02115_cheese_weasel.sql 02122_perf.sql"
```

Once this pull is merged, i will load the changes on staging.buttonweavers.com as part of #2133.

### CODE REVIEW

**Comment by cgolubi1** [comment]
I'll test this on vagrant, since there are a couple of database updates.

**Comment by cgolubi1** [comment]
Merging, then i'll load on virtualbox to test.

**Comment by cgolubi1** [comment]
Seems okay; database diffs are to Cheese Weasel and Peri/Perf, as expected.  Loading on staging.

**Comment by cgolubi1** [comment]
Okay, i can't do a database diff check on the staging site itself because of #2143 --- i worked around this on virtualbox by manually hacking /etc/mysql/my.cnf, but obviously i don't want to do that on a live site.  I'm just going to declare that the database check isn't very important at this moment given the small number of changes, and keep going.

**Comment by blackshadowshade** [comment]
Just mentioning that #2124 should be user-visible, because it changes the display of button specials on the button description page.

**Pull request merged**
