### PR TITLE
Changed Open Games page to show your open games first

### LINKED ISSUE #2567: The open games page should show my open games section first
On the open games page, please display the section "Your open games (waiting for other players to join)" BEFORE the section "Games you can join."  I want to see my open games first.

Also the my open games list will almost always be much smaller that the full list of open games.  So sorting my games first means much less scrolling to see my games and much less scrolling to see the open games.

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #2567.

### CODE REVIEW

**Comment by cgolubi1** [comment]
Dev site up: http://ephemeral.dev.buttonweavers.com

**Comment by cgolubi1** [comment]
Hi testers - this dev site http://ephemeral.dev.buttonweavers.com is for testing Shadowshade's change to make the Open Games page show your games first.  Can someone check it out, maybe especially @nkmcalli who opened the issue it's addressing?

**Comment by dwvanstone** [comment]
This looks good on the ephemeral site!

**Comment by cgolubi1** [comment]
Thanks, dwvanstone!  Merging.

**Comment by nkmcalli** [comment]
THANK YOU!

**Pull request merged**
