### PR TITLE
Upgrade buttonweavers site to Ubuntu Xenial

### LINKED ISSUE #2398: Site upgrade
The production instance that we are currently running needs updating, for a number of reasons:
- to bring various software products up to a currently-supported version
- to allow us to use new features
- to bring in security patches

Specific issues that may relate to this site upgrade are:
- [ ] #161: Downloading PHPUnit via puppet
- [ ] #224: Using SSL
- [ ] #439: JQuery version
- [ ] #440: JSHint version
- [ ] #575: Puppet version
- [ ] #1083: Manage third-party Javascript libraries
- [ ] #1097: buttonweavers.com should redirect to www.buttonweavers.com
- [ ] #1167: Upgrade PHP
- [ ] #1168: Upgrade PHPUnit
- [ ] #1339: Backup drive running out of space
- [ ] #1989: Connection errors
- [ ] #2143: MySQL settings to enable temporary backups
- [ ] #2197: Python 3 compatibility
- [ ] #2208: Adding the statistical environment R
- [ ] #2342: Changing CircleCI to use the new upgraded versions

### PR DESCRIPTION
**Pull request by cgolubi1**
* Fixes #2398
* Replaces #2412 and partially addresses the same issues as #2411 --- we'll bring those changes in after the upgrade

### CODE REVIEW

**Comment by cgolubi1** [comment]
I just opted to redo the branch so i didn't have to worry about merge issues and teasing out Shadowshade's changes that i had rebased in.  I think this version has the right stuff in it:

```
$ diff -r --brief buttonmen-2398_site_upgrade buttonmen-2398_site_upgrade_redo | grep -v '/.git/' | grep -v '/.git: ' | grep -v /dummy_data/ | grep -v /.vagrant/ | grep -v .pyc
Files buttonmen-2398_site_upgrade/deploy/vagrant/Vagrantfile and buttonmen-2398_site_upgrade_redo/deploy/vagrant/Vagrantfile differ
Only in buttonmen-2398_site_upgrade_redo/deploy/vagrant: ubuntu-xenial-16.04-cloudimg-console.log
Files buttonmen-2398_site_upgrade/src/engine/BMAttack.php and buttonmen-2398_site_upgrade_redo/src/engine/BMAttack.php differ
Files buttonmen-2398_site_upgrade/src/engine/BMButton.php and buttonmen-2398_site_upgrade_redo/src/engine/BMButton.php differ
Files buttonmen-2398_site_upgrade/src/engine/BMDie.php and buttonmen-2398_site_upgrade_redo/src/engine/BMDie.php differ
Files buttonmen-2398_site_upgrade/src/engine/BMDieTwin.php and buttonmen-2398_site_upgrade_redo/src/engine/BMDieTwin.php differ
Files buttonmen-2398_site_upgrade/src/engine/BMEmail.php and buttonmen-2398_site_upgrade_redo/src/engine/BMEmail.php differ
Files buttonmen-2398_site_upgrade/src/engine/BMGame.php and buttonmen-2398_site_upgrade_redo/src/engine/BMGame.php differ
Files buttonmen-2398_site_upgrade/src/engine/BMGameAction.php and buttonmen-2398_site_upgrade_redo/src/engine/BMGameAction.php differ
Files buttonmen-2398_site_upgrade/src/engine/BMInterface.php and buttonmen-2398_site_upgrade_redo/src/engine/BMInterface.php differ
Files buttonmen-2398_site_upgrade/src/engine/BMInterfaceGame.php and buttonmen-2398_site_upgrade_redo/src/engine/BMInterfaceGame.php differ
Files buttonmen-2398_site_upgrade/src/engine/BMInterfaceNewuser.php and buttonmen-2398_site_upgrade_redo/src/engine/BMInterfaceNewuser.php differ
Files buttonmen-2398_site_upgrade/src/engine/BMPlayer.php and buttonmen-2398_site_upgrade_redo/src/engine/BMPlayer.php differ
Files buttonmen-2398_site_upgrade/src/engine/BMSkillMaximum.php and buttonmen-2398_site_upgrade_redo/src/engine/BMSkillMaximum.php differ
Files buttonmen-2398_site_upgrade/src/engine/BMSkillMighty.php and buttonmen-2398_site_upgrade_redo/src/engine/BMSkillMighty.php differ
Files buttonmen-2398_site_upgrade/src/engine/BMSkillTimeAndSpace.php and buttonmen-2398_site_upgrade_redo/src/engine/BMSkillTimeAndSpace.php differ
Files buttonmen-2398_site_upgrade/src/engine/BMSkillTrip.php and buttonmen-2398_site_upgrade_redo/src/engine/BMSkillTrip.php differ
Files buttonmen-2398_site_upgrade/src/engine/BMSkillTurbo.php and buttonmen-2398_site_upgrade_redo/src/engine/BMSkillTurbo.php differ
Files buttonmen-2398_site_upgrade/src/engine/BMSkillWeak.php and buttonmen-2398_site_upgrade_redo/src/engine/BMSkillWeak.php differ
Files buttonmen-2398_site_upgrade/src/engine/BMUtilityHitTable.php and buttonmen-2398_site_upgrade_redo/src/engine/BMUtilityHitTable.php differ
Files buttonmen-2398_site_upgrade/test/src/engine/BMButtonTest.php and buttonmen-2398_site_upgrade_redo/test/src/engine/BMButtonTest.php differ
Files buttonmen-2398_site_upgrade/test/src/engine/BMDieOptionTest.php and buttonmen-2398_site_upgrade_redo/test/src/engine/BMDieOptionTest.php differ
Files buttonmen-2398_site_upgrade/test/src/engine/BMGameTest.php and buttonmen-2398_site_upgrade_redo/test/src/engine/BMGameTest.php differ
Files buttonmen-2398_site_upgrade/test/src/engine/BMInterfaceGameTest.php and buttonmen-2398_site_upgrade_redo/test/src/engine/BMInterfaceGameTest.php differ
Files buttonmen-2398_site_upgrade/test/src/engine/BMInterfaceTest.php and buttonmen-2398_site_upgrade_redo/test/src/engine/BMInterfaceTest.php differ
Files buttonmen-2398_site_upgrade/test/src/engine/BMSkillBerserkTest.php and buttonmen-2398_site_upgrade_redo/test/src/engine/BMSkillBerserkTest.php differ
Files buttonmen-2398_site_upgrade/test/src/engine/BMSkillRadioactiveTest.php and buttonmen-2398_site_upgrade_redo/test/src/engine/BMSkillRadioactiveTest.php differ
Files buttonmen-2398_site_upgrade/test/src/engine/BMSkillRageTest.php and buttonmen-2398_site_upgrade_redo/test/src/engine/BMSkillRageTest.php differ
Files buttonmen-2398_site_upgrade/test/src/engine/BMSkillTimeAndSpaceTest.php and buttonmen-2398_site_upgrade_redo/test/src/engine/BMSkillTimeAndSpaceTest.php differ
```

The Vagrantfile changes:
```
$ diff buttonmen-2398_site_upgrade/deploy/vagrant/Vagrantfile buttonmen-2398_site_upgrade_redo/deploy/vagrant/Vagrantfile
23c23
<   config.vm.hostname = "sandbox.buttonweavers.com"
---
>   #config.vm.hostname = "sandbox.buttonweavers.com"
```

I'm honestly not sure why that became necessary --- the default virtualbox hostname is now ubuntu-xenial, and it didn't like me setting it to sandbox early in the boot process.  I don't think it's a big deal, though, because it's not going to break the running site.  Either it'll work or it won't (and right now it does work on virtualbox and on the AWS replay site).  Anyway, everything else is Shadowshade's changes from #2411 that we're not bringing in now, and we can tell that i got all of my changes from before, because the unit tests pass.

**Comment by cgolubi1** [comment]
Schedule:
* I'd like to merge this tomorrow (Tuesday) during my morning, and stand up a staging site
* At that point, we'll ask people to spend some time on the staging site, and when we schedule the actual prod migration will depend on when people are able to do that.  This Thursday or Friday is an option if people have time to test and are happy; or next week if things take longer or we see any problems.

**Comment by blackshadowshade** [comment]
Any reason this doesn't run CircleCI?

**Comment by blackshadowshade** [comment]
Also, did you mean to include deploy/vagrant/ubuntu-xenial-16.04-cloudimg-console.log?

**Comment by cgolubi1** [comment]
I don't know why it didn't have CircleCI before --- maybe the run was too old.

Anyway, thanks for catching the logfile.  I've removed it, and now it is running CircleCI.

**Comment by blackshadowshade** [comment]
Looks good to me. This is ready to be merged whenever you're ready for it.

**Comment by cgolubi1** [comment]
We're at 5300 new and replayed games with this branch (plus the initial 13000 from what i believe to be the same code), so let's do this.

**Pull request merged**
