### PR TITLE
Push changes from master to staging on 2017-09-21

### PR DESCRIPTION
**Pull request by cgolubi1**
This update brings these approved pulls to the staging branch:

* User-visible:
    * #2234: Add history links to button description pages
    * #1849: Add number of active games to overview page
    * #2203: Add floating header for forums
    * #2244, #2252, #2248: UI for creating third-party games and displaying information about who created third-party games
    * #2085: Stop Dead Guy from turning up in random matches
    * #2256: Use simple autoversioning to avoid UI cache problems when the site is updated
    * #2250: UI to set chat to private within a game
* Ideally not user-visible:
    * #2083: don't unnecessarily reroll zero-sided dice
    * #2243, #2237, #2249, #2251: fixes affecting RandomAI/replay test rig only
    * #2245: checkin of in-progress stats scripts
    * #2247: improve error log grepping used by devs to detect unreported internal errors

Database updates:
```
UPDATES="01784_game_creation_action_log.sql 02032_no_random_dead_guy_01.sql"
```

Once this pull is merged, i will load the changes on staging.buttonweavers.com as part of #2246.

### CODE REVIEW

**Comment by cgolubi1** [comment]
Testing on vagrant first.

**Comment by cgolubi1** [comment]
Pausing because i see a weird artifact on testing:

created_by_undefined

What's "Created by undefined"?  I can't immediately figure out what's going on --- the API appears to be reporting the right thing.  I'm going to go ahead and load this on staging, and leave it for other people to reproduce or not.  For all i know it's a JS caching artifact (though i am seeing it on two browsers).

**Comment by cgolubi1** [comment]
Reproduced the issue on staging and opened #2260

**Comment by blackshadowshade** [comment]
I'm seeing "Created by glassonion". Odd.

**Comment by blackshadowshade** [comment]
Okay, at first glance:
- history links look good
- number of games on overview page looks good
- floating header is behaving itself on Firefox, including the after-page-load jump that needs to happen sometimes
- third party games can be created using the new UI

**Comment by dwvanstone** [comment]
I've poked around a bit too and found no new issues.

**Pull request merged**
