### PR TITLE
Added flag HasJustBeenMoody to mood dice that have just attacked

### PR DESCRIPTION
**Pull request by blackshadowshade**
This is the first component extracted from pull request #1675. It simply adds the flag HasJustBeenMoody, which will be used for correctly logging mood die size changes.

### CODE REVIEW

**Comment by cgolubi1** [comment]
Remind me what the intended behavior is here.  In your code as written, this attack:

```
responder004 performed Speed attack using [z(8,8)?:10] against [(4):3,(U=21):7]; Defender (4) was captured; Defender (U=21) was captured; Attacker z(8,8)? remained the same size, rerolled 10 => 9'
```

does *not* cause `HasJustBeenMoody` to be set for the `z(8,8)?`.  Is that what you expect, or would you expect the flag to be set?

**Comment by cgolubi1** [comment]
Just as a status report, i'm replaying with this version of `update_replay_games`, and i think that's getting me below one failure per 100 games (the only failure mode i know so far it doesn't handle is a button like `Piro` with two identical-sized mood dice, where if they end up the same size as each other, it sometimes guesses wrong about which one was moody, which i think should happen rarely enough that i can spot-check them):

```
#!/usr/bin/python
##### update_replay_games
# This should have the same functionality as prep_replay_games, but
# can be modified to adjust the API output to account for changes
# between the master version against which games were recorded, and
# the version under test.  One-off changes which will not be needed
# once the API update is committed should be made in this file and
# should not be committed.  Support for permanent API changes should
# be made in random_ai.py.

import sys
sys.path.append('lib')

import random_ai

def get_recipe_and_sides(recipe_str):
  lparenl, lparenr = recipe_str.split('(')
  size_part, rparenr = lparenr.split(')')
  sizels = []
  sides = 0
  for size_subpart in size_part.split(','):
    if size_subpart.count('=') == 0:
      sizel = size_subpart
      sizer = size_subpart
    else:
      assert size_subpart.count('=') == 1, "Can't parse recipe string: %s" % recipe_str
      sizel, sizer = size_subpart.split('=')
    sizels.append(sizel)
    sides += int(sizer)
  recipe = lparenl + '(' + ','.join(sizels) + ')' + rparenr
  return recipe, sides

def find_moody_attacker_recipes_remained_same(logmsg):
  # 'responder004 performed Power attack using [(X=12)?:1] against [(6):1]; Defender (6) was captured; Attacker (X=12)? remained the same size, rerolled 1 => 5. '
  splitter = ' remained the same size,'
  sections = logmsg.split(splitter)
  moody_changes = []
  for recipe_section in sections[:-1]:
    words = recipe_section.split()
    from_recipe = words[-1].strip(',')
    to_recipe = from_recipe
    if not (from_recipe.endswith('?') or from_recipe.endswith('&')): continue
    if not (to_recipe.endswith('?') or to_recipe.endswith('&')): continue
    if from_recipe.endswith('z(8,8)?'): continue # FIXME: get a response about whether this is expected
    recipe, sides = get_recipe_and_sides(to_recipe)
    moody_changes.append({'from': from_recipe, 'to': to_recipe, 'recipe': recipe, 'sides': sides})
  return moody_changes

def find_moody_attacker_recipes_changed(logmsg):
  splitter = ' recipe changed from '
  sections = logmsg.split(splitter)
  moody_changes = []
  for recipe_section in sections[1:]:
    words = recipe_section.split()
    from_recipe = words[0]
    to_recipe = words[2].strip(',')
    if not (from_recipe.endswith('?') or from_recipe.endswith('&')): continue
    if not (to_recipe.endswith('?') or to_recipe.endswith('&')): continue
    recipe, sides = get_recipe_and_sides(to_recipe)
    moody_changes.append({'from': from_recipe, 'to': to_recipe, 'recipe': recipe, 'sides': sides})
  return moody_changes

def find_moody_attacker_recipe_change(logmsg):
   attacker_idx = 0 if logmsg.startswith('responder003') else 1
   moody_changes = find_moody_attacker_recipes_changed(logmsg)
   moody_changes.extend(find_moody_attacker_recipes_remained_same(logmsg))
   if moody_changes:
     return attacker_idx, moody_changes
   return None, False
   
def find_moody_defender_recipe_change(logmsg):
  splitter = ' recipe changed to '
  sections = logmsg.split(splitter)
  if len(sections) == 1: return None, False
  defender_idx = 1 if logmsg.startswith('responder003') else 0
  moody_changes = []
  for i in range(len(sections) - 1):
    from_recipe = sections[i].split()[-1]
    to_recipe = sections[i + 1].split()[0].strip(',')
    if not (from_recipe.endswith('?') or from_recipe.endswith('&')): continue
    if not (to_recipe.endswith('?') or to_recipe.endswith('&')): continue
    if to_recipe.replace('n', '') == from_recipe: continue
    recipe, sides = get_recipe_and_sides(to_recipe)
    moody_changes.append({'from': from_recipe, 'to': to_recipe, 'recipe': recipe, 'sides': sides})
  return defender_idx, moody_changes

def add_moody_flag_to_active_die_props(props):
  if 'HasJustGrown' in props:
    props.insert(props.index('HasJustGrown'), 'HasJustBeenMoody')
  elif 'HasJustRerolledOrnery' in props:
    props.insert(props.index('HasJustRerolledOrnery'), 'HasJustBeenMoody')
  elif 'Twin' in props:
    props.insert(props.index('Twin'), 'HasJustBeenMoody')
  else:
    props.append('HasJustBeenMoody')

########################################################################
# Custom classes
class PHPBMClientOutputWriter(random_ai.PHPBMClientOutputWriter):
  # If you need to make any changes to the syntax of PHP output which is
  # translated from the internal game state format for regression-testing
  # previously recorded games against this PR (e.g. if the new code
  # changes the API and you need to reflect those changes for replays
  # to succeed), make those overrides here for clarity during testing.
  #
  # As a first resort, trying overriding apply_known_changes_to_game_data()
  def apply_known_changes_to_game_data(self, data):
    newlogs = []
    if data['gameActionLogCount'] > self.last_log_len:
      for i in range(data['gameActionLogCount'] - self.last_log_len):
        newlogs.append(data['gameActionLog'][i])
      self.last_log_len = data['gameActionLogCount']
    moody_attacker_changes = []
    for newlog in newlogs:
      if 'must turn down fire dice' in newlog['message']:
        newlogs.extend(self.last_newlogs)
    for newlog in newlogs:
      if newlog['message'].startswith('End of round'): break
      if newlog['message'].endswith(' passed'): break
      attacker_idx, moody_attacker_changes = find_moody_attacker_recipe_change(newlog['message'])
      if moody_attacker_changes:
        active_dice = data['playerDataArray'][attacker_idx]['activeDieArray']
        for change in moody_attacker_changes:
          matching_idx = [idx for idx in range(len(active_dice)) \
            if active_dice[idx]['recipe'] == change['recipe'] \
            and active_dice[idx]['sides'] == change['sides']]
          # If it's greater than 1, we're guessing, and we may well guess wrong, but what's to be done
          assert len(matching_idx) >= 1, "Found %s looking for moody_attacker_changes=%s based on newlogs=%s in active_dice=%s" % (matching_idx, moody_attacker_changes, newlogs, active_dice)
          add_moody_flag_to_active_die_props(active_dice[matching_idx[0]]['properties'])
      defender_idx, moody_defender_changes = find_moody_defender_recipe_change(newlog['message'])
      if not moody_defender_changes: continue
      for change in moody_defender_changes:
        if 'was captured' in newlog['message']:
          captured_dice = data['playerDataArray'][1 - defender_idx]['capturedDieArray']
          matching_idx = [idx for idx in range(len(captured_dice)) \
            if captured_dice[idx]['recipe'] == change['recipe'] \
            and captured_dice[idx]['sides'] == change['sides'] \
            and 'WasJustCaptured' in captured_dice[idx]['properties']]
          assert len(matching_idx) >= 1, "Found %s looking for moody_defender_changes=%s based on newlogs=%s in captured_dice=%s" % (matching_idx, moody_defender_changes, newlogs, captured_dice)
          props = captured_dice[matching_idx[0]]['properties']
          props.append('HasJustBeenMoody')
        else:
          search_dice = data['playerDataArray'][defender_idx]['activeDieArray']
          matching_idx = [idx for idx in range(len(search_dice)) \
            if search_dice[idx]['recipe'] == change['recipe'] \
            and search_dice[idx]['sides'] == change['sides']]
          # If it's greater than 1, we're guessing, and we may well guess wrong, but what's to be done
          assert len(matching_idx) >= 1, "Found %s looking for moody_defender_changes=%s based on newlogs=%s in active_dice=%s" % (matching_idx, moody_defender_changes, newlogs, search_dice)
          add_moody_flag_to_active_die_props(search_dice[matching_idx[0]]['properties'])
    self.last_newlogs = newlogs
    return data

########################################################################
# Initial setup
if len(sys.argv) < 2:
  raise ValueError("Usage: update_replay_games <dirname>")

DIRNAME = sys.argv[1]

d = PHPBMClientOutputWriter(DIRNAME)
for gamepath in d.find_games():
  sys.stderr.write("Updating and prepping game for replay from: %s\n" % gamepath)
  d.last_log_len = 0
  d.translate_game(gamepath)
```

I'll let that run for awhile and see where i get.  Let me know about `z(8,8)?` when you have a chance.

**Comment by cgolubi1** [comment]
Another case i don't handle:

```php
        $this->verify_api_submitTurn(
            array(2, 1, 7),
            'responder003 performed Trip attack using [t(4):4] against [(V=8)?:8]; Attacker t(4) rerolled 4 => 2; Defender (V=8)? rerolled 8 => 7, was not captured. ',
            $retval, array(array(0, 0), array(1, 2)),
            $gameId, 3, 'Trip', 0, 1, '', array());
```

The old action log doesn't show that defender as having been moody (there's no commentary about the size), but clearly it was, because the 1 is a size check leading to V=8.  So this is a case where the new code is correct, and the old action log was wrong.  Good enough.

**Comment by cgolubi1** [comment]
I replayed 5400 games, and there was quite a bit of activity, but all of it was the cases i've outlined here, and the only one of those where i'm not sure the code is doing the right thing is `z(8,8)?`.  So, shadowshade, weigh in on that: is it intended that that die *not* get `HasJustBeenMoody` when it rerolls?  If it's intended, i'm happy to merge this.

**Comment by blackshadowshade** [comment]
I believe that the z(8,8)? behaviour is correct, since it doesn't actually trigger the Mad/Mood code.

**Comment by cgolubi1** [comment]
Okay, i can live with that.  Merging.  When you get a chance, put up a PR with the other half, and i'll figure out what i need to do to test that.

**Pull request merged**
