### PR TITLE
138 button images

### PR DESCRIPTION
**Pull request by ManvilleFog**
Radioactive fanatics, plus new Soldiers images, and a couple others.  I am redoing images I submitted before I started using 145px as the standard size diameter.  Also, I found a new source for Soldiers. 

http://jenkins.buttonweavers.com:8080/job/buttonmen-ManvilleFog/95/console
Jenkins seems happy with it.

### CODE REVIEW

**Comment by blackshadowshade** [comment]
I'm really liking the representation of radioactive. Also, those new Soldiers images are excellent.

**Comment by cgolubi1** [comment]
Cool.  Testing this is just a question of creating games with each of the buttons which have new/changed images, and making sure the new images show up.

**Comment by cgolubi1** [comment]
Okay, i tried these out and they all work.  My only complaint is that the new Niles is a lot darker than the old Niles.  IMO, something closer to the lighter purple/blue that used to be the coloring is nicer, though i agree the larger art is an improvement.

Fog: any thoughts?

**Comment by cgolubi1** [comment]
On reflection, i'm going to go ahead and merge this, since it's an improvement overall and i don't see any gameplay problems.  Just consider this a vote for taking another whack at Niles later and making him a bit brighter when you do.

**Comment by cgolubi1** [comment]
Rats, my bad for not noticing this --- Fog, you have an old version of the tree, and more responder tests with gman97216 have been added since then.  I'll go ahead and submit a pull for this, but try to remember to pull from upstream before testing changes (since we keep adding responder tests), and i'll try to remember to notice when you're missing tests.

**Comment by ManvilleFog** [comment]
I'm confused now.  I pulled from upstream.  My fork's master has no gman97216 responder tests, so I couldn't have goofed and pulled from origin.   

I keep a copy of my changes in another directory and don't add them until I'm about to push the changes.  Right now, after a fetch --all, I checkout upstream/master then checkout a new branch to add the changes.  This method seems to been causing me the least amount of problems.  Anyhow, there's less than a half hour between when I get the latest from upstream and push my new branch.  Then there's the time I spend to run Jenkins, look at the file comparisons, and make changes before submitting a pull request.

**Comment by blackshadowshade** [comment]
Fog, that procedure sounds right, so I don't see immediately why those unit tests weren't there in your pull request.

**Pull request merged**
