### PR TITLE
Changed W/L/T to –/–/– for rejected games on the history page

### LINKED ISSUE #1840: When showing New and Cancelled games in the History UI, use -/-/- for the W/L/T
What it says on the tin.

### PR DESCRIPTION
**Pull request by blackshadowshade**
Addresses part of #1840.

I am aware that the logic to detect new games is not really the best way, but until we explicitly add the ability to search for New Games in the history page (and perhaps add an extra game status type), the current implementation seems to be the easiest way to achieve the goal.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1011/

### CODE REVIEW

**Comment by cgolubi1** [comment]
Hmm.  So IMO it would be better not to solve this issue yet for new games, than to use timestamps to guess which games are new.  That never ends well.

**Comment by blackshadowshade** [comment]
Okay, logic for new games removed. 'Fixes' comment changed.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1012/ (if it passes)

**Comment by cgolubi1** [comment]
Thanks.  This looks pretty reasonable to me, let me check it out in virtualbox.

**Comment by cgolubi1** [comment]
Looks good.  Merging.

**Pull request merged**
