### PR TITLE
Migrate BMInterfaceGame.php to BMDB

### PR DESCRIPTION
**Pull request by cgolubi1**
* Partially addresses #712

### CODE REVIEW

**Comment by cgolubi1** [comment]
Obviously we're currently in the merge freeze for the September release, but i figured now that custom recipes are merged, i can go back to making some progress on getting this refactor over the fence.

**Comment by blackshadowshade** [comment]
I've taken a cursory view of the code, and it all appears to be consistent, but we know from past experience that random_ai is the best way of picking up edge cases in this sort of change.

What say we run your standard testing regime on this before accepting it?

**Comment by blackshadowshade** [comment]
Let me know when you're happy with your tests on this, then we'll merge it and see if there are any interactions with the other changes.

**Comment by cgolubi1** [comment]
I had to fix merge conflicts, but only in `deploy/circleci/audit_php_files.php`, which i don't think requires additional replay testing.  This has replayed around 10000 games with no failures, so i think it's good to go.  Please double-check that you don't have any concerns about the merge change, then merge it.

**Comment by blackshadowshade** [comment]
Merge change looks clean. Merging this one now.

**Pull request merged**
