### PR TITLE
Made Largo playable, and fixed recipe

### LINKED ISSUE #2488: Make Largo playable
Largo cannot make Skill Attacks, which is the same button skill as The Flying Squirrel.

It should be trivial to make Largo playable.

### LINKED ISSUE #2489: Fix Largo's missing (X)-Swing Die
Largo as written on the dev site is missing an (X) swing.

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #2488. Fixes #2489.

### CODE REVIEW

**Comment by cgolubi1** [comment]
DB update looks fine.  Let's get a dev site for this.

**Comment by cgolubi1** [comment]
http://makeshift.dev.buttonweavers.com/ui/buttons.html?button=Largo - please check this out, playtesters.

**Comment by dwvanstone** [comment]
Welcome to Largo! The button works fine.

**Comment by cgolubi1** [comment]
Thanks, dwvanstone!

**Pull request merged**
