### PR TITLE
Fixed naming of Order of Dolls button set, added button images

### LINKED ISSUE #2491: Change "Order of the Dolls" to "Order of Dolls"
The BM Book shows that the correct name for the set name doesn't have a "the" in it.

### LINKED ISSUE #2560: Order of Dolls original artwork, 150px button'd.
https://buttonmen.fandom.com/wiki/Order_of_Dolls

Rhea Shelley sent the original artwork for the set.  If anyone'd like to kick him a buck or five, feel free.  The paypal email is on the wiki page above the set of original blanks.

Here's them done for BMO

BMOChaka
BMOFuma
BMOstrotzie
BMOVox

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #2491. Fixes #2560.

### CODE REVIEW

**Comment by blackshadowshade** [comment]
For interest, this is a screenshot of my dev button set page for Order of Dolls:

order_of_dolls

**Comment by cgolubi1** [comment]
Database change looks fine.  Standing up a dev site.

**Comment by cgolubi1** [comment]
the dev site should be up at http://momentary.dev.buttonweavers.com/ - note that that name was used earlier today for a different dev site, so if you tested that one, you may have to wait an hour to test this one.

**Comment by blackshadowshade** [comment]
@TheOrgg, want to take a look at this one?

**Comment by dwvanstone** [comment]
I think it looks good -- well done getting in the new artwork, @TheOrgg!

**Comment by TheOrgg** [comment]
Looks right to me.  Recipes are good, and they're greyed out because Assassin Dice aren't implemented yet.

DV, I was VERY thrilled to get into contact with Reah.  He was very helpful-- he had the Blademasters art, the missing Vegas playtest arts, and the official Japanese Beetle blanks..

**Comment by cgolubi1** [comment]
Thanks, all.  Merging.

**Pull request merged**
