### PR TITLE
Cache chat across toggle of chat visibility

### LINKED ISSUE #2296: Changing chat settings should preserve chat textbox
I'd prefer it if hitting "Prefer private chat" or "Prefer public chat" wouldn't clear out the Chat textbox.

The use case was that I was in a game with a public chat, and as I was responding to a chat I decided partway that this was might be better as a private chat. And so I hit "Prefer private chat" which deleted all of the content I had typed in. Hitting the Back button did not bring back the chat contents, so I had to start again.

Thanks!

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #2296.

This is the new improved (and much simplified!) version of #2324.

### CODE REVIEW

**Comment by cgolubi1** [comment]
LGTM; standing up dev site so someone (possibly including me) can smoke test it.

**Comment by cgolubi1** [comment]
And thanks for the redo; i think Future Us will appreciate the reduction in complexity.

**Comment by cgolubi1** [comment]
Done.  irilyth, can you link up temporary == 54.145.111.226?

**Comment by cgolubi1** [comment]
irilyth, can you link up temporary == 54.145.111.226?

**Comment by irilyth** [comment]
Done!

**Comment by dwvanstone** [comment]
The main use case is fixed.

There's a related bug which I'm happy to report as a new bug if you like.

1. It is your turn. Type text into the chat box. Do an attack. Your text appears. Yay!

2. Before the other player plays their turn, hit Add/Edit Chat.

3. Start working on next text message. Partway through, hit "Prefer private chat" 

4. The chat window disappears. 

Thankfully, when you hit "Add/Edit Chat" again the text is still there, so it's not as destructive as the original bug.

**Comment by blackshadowshade** [comment]
Okay, I'll take a look at that.

**Comment by blackshadowshade** [comment]
Okay, the second bug should now be fixed.

**Comment by cgolubi1** [comment]
Updated dev site; check it out.

**Comment by dwvanstone** [comment]
Looks great to me!

**Comment by cgolubi1** [comment]
Okay, sounds like this is good to go.  Shadowshade: can you rebase?

**Comment by blackshadowshade** [comment]
Rebased.

**Comment by cgolubi1** [comment]
Thanks!

**Pull request merged**
