### PR TITLE
Added logic to handle logging of complex size changing that starts with berserk

### LINKED ISSUE #1620: Add a flag for "this die shrank due to Berserk"
Because we do all the logging after the attack is complete, and thus don't know what happened during the attack unless something flags it, we can't tell if a die shrank due to Berserk, and thus don't log this, which gets confusing if the die also changes size for some other reason (e.g. Mood Swing).

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #1620.

This should probably have a responder test added eventually. I tested using spindisc vs spindisc.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/743/

### CODE REVIEW

**Comment by cgolubi1** [comment]
This is complicated.  Deferring for now in hopes of trying to knock off some simpler pulls.

**Comment by cgolubi1** [comment]
Okay, so, basically, what James did here is:
* Add a flag JustPerformedBerserkAttack which is associated with an action log entry type recipeAfterBerserkAttack
* Make a new parent class BMFlagJustPerformedTypeOfAttack and refactor BMFlagJustPerformedTripAttack to use it
* In BMGameAction, implement additional messaging using the Berserk information

So, what i want to do here is:
* Play a game by hand using spindisc as James suggests, and see if i like the result
* Play back a lot of games containing no Berserk dice, and make sure there are no changes to visible logging in those games
* Play back a bunch of games containing Berserk dice, and see what the differences are and make sure they are reasonable
* Play some new games containing size-changing skills, and look for internal errors
* See if i can easily make a short responderTest for this

**Comment by cgolubi1** [comment]
The berserk mood behavior looks reasonable:
berserk_mood_behavior

**Comment by cgolubi1** [comment]
Hmm, this doesn't look so good --- why is the intermediate value 0 sides?
berserk_mighty

**Comment by cgolubi1** [comment]
My assumption is that it's because of your new `max_from_recipe()` function - i don't really understand how that works.  My request, orthogonal to fixing the bug above, would be add some unit tests to `max_from_recipe()` so its behavior can be seen.

**Comment by cgolubi1** [comment]
Okay, i added a responder test in https://github.com/cgolubi1/buttonmen/tree/demonstrate_berserk_logging_bug which demonstrates the incorrect behavior here (and also, basically by chance, has a boom attack targeting a stealth die).

**Comment by blackshadowshade** [comment]
Yes, I'm pretty sure you're exactly right, in that the regexp is actively searching for an equals sign, which will fail for a non-swing die.

**Comment by blackshadowshade** [comment]
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/753/ (if it passes)

**Comment by blackshadowshade** [comment]
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/756/ (if it passes)

**Comment by blackshadowshade** [comment]
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/757/

**Comment by cgolubi1** [comment]
Okay, trying this again.

* Play a game by hand using spindisc, and make sure i still like the result
* Play a game by hand using RandomBMMixed, trying to get a berserk size-changing non-swing die
* Play back a lot of games containing no Berserk dice, and make sure there are no changes to visible logging in those games
* Play back a bunch of games containing Berserk dice, and see what the differences are and make sure they are reasonable
* Play some new games containing size-changing skills, and look for internal errors

**Comment by cgolubi1** [comment]
This seems good to the extent of my testing ability, but it's new logic and i want to give the testers a crack at it, so i'll merge it after the code freeze.

**Pull request merged**
