### PR TITLE
Re-enabled Oregon

### LINKED ISSUE #2333: Oregon has the unique die skill
In #2279, we implemented the unique die skill for Gordo and Guillermo.

Oregon also has the unique die skill, so it should be trivial to enable this button by giving it the same button-level skill.

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #2333.

### CODE REVIEW

**Comment by cgolubi1** [comment]
Let's do some replay testing for this and then call it good.

**Comment by cgolubi1** [comment]
Can you add this diff to random_ai.py please?

```
$ git diff tools/
diff --git a/tools/api-client/python/lib/random_ai.py b/tools/api-client/python/lib/random_ai.py
index 0bd93e3..3c760c9 100755
--- a/tools/api-client/python/lib/random_ai.py
+++ b/tools/api-client/python/lib/random_ai.py
@@ -1332,7 +1332,7 @@ class LoggingBMClient():
   def _game_action_specify_dice_player(self, b, playerData):
     swing_array = {} 
     if playerData['swingRequestArray']:
-      unique_swing_among_swing = playerData['button']['name'] == 'Guillermo'
+      unique_swing_among_swing = playerData['button']['name'] in ['Guillermo', 'Oregon']
       unique_swing_among_dice = playerData['button']['name'] == 'Gordo'
       for swing_type in sorted(playerData['swingRequestArray'].keys()):
         [swing_min, swing_max] = playerData['swingRequestArray'][swing_type]
```

**Comment by blackshadowshade** [comment]
I'm getting odd QUnit tests failures now, in spite of not actually changing any JavaScript.

If the next CircleCI build fails, I think I'm going to need help to work out why QUnit is being ornery.

**Comment by cgolubi1** [comment]
This replay site has been plugging away for awhile with no problems.  Merging.

**Pull request merged**
