### PR TITLE
Visually indicate that die is irrelevant for initiative

### LINKED ISSUE #835: During take initiative, indicate which dice are not relevant
I've often thought that it shouldn't be hard to show the player which dice are not part of the initiative process, to avoid confusion when using focus and chance dice.

Mostly, for me, I puzzle over situations where I or my opponent have Trip dice, but perhaps there are other dice which are ignored in the initiative process that I'm forgetting.

Anyway, I'd think it should be fairly easy to dim such dice (and include a note in the rollover to explain?) to clarify things a bit.

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #835.

On my system, the updated display looks like this:

irrelevant_for_initiative

Let me know what you think about how this looks.

### CODE REVIEW

**Comment by TheOrgg** [comment]
This'll be nice.

**Comment by cgolubi1** [comment]
This is going to want dev and replay testing; dev so people can report what they think of it, replay because it adds a flag.

**Comment by cgolubi1** [comment]
Dev site is at http://momentary.dev.buttonweavers.com/ui/ --- check it out

**Comment by TheOrgg** [comment]
Created a few games on the test server, but I'm not sure what bugs to look out for.

**Comment by blackshadowshade** [comment]
I guess you want to check for matchups between buttons with varied skills, some which affect initiative and some which don't. However, don't let me guide you on testing too much, part of the skill in testing is finding things that the developers never thought of.

**Comment by jl8e** [comment]
A thing to probably check is how it handles focus/chance dice that don't count  (I know there's at least one fanatic that does this)

**Comment by blackshadowshade** [comment]
Also, as you test, it would be useful for us (and this is generally true of non-trivial pull requests) if you list in some detail what you have tested.

**Comment by TheOrgg** [comment]
Had a little time, set up a few matches against a friend's account he's letting me use.

Game 194 is frozen for some reason; every time either accountt ries to go to it, the screen is blank and doesn't load.

So far the only thing I've noticed is during the swing die selection, the non-initiative dice are not indicated.  During Chance or Focus, they are.  Is that the correct behavior?

**Comment by irilyth** [comment]
BTW, on the staging site and dev sites, it's totally fine to create multiple accounts for testing.

**Comment by blackshadowshade** [comment]
I've only indicated non-initiative dice in the phase where you're trying to gain initiative.

Did people want me to indicate them also during swing/option setting?

**Comment by TheOrgg** [comment]
I could see it going either way.  I'd say post a thread asking about it on the Forum.  I know most people use the formula to determine their swing die, but I usually just eyeball it.

**Comment by blackshadowshade** [comment]
@nkmcalli, @Caligari, your thoughts?

**Comment by cgolubi1** [comment]
Trying replay testing again with this updater, which expects to see the new property during REACT_TO_INITIATIVE only and on dice with rage, stinger, or trip only:

```python
#!/usr/bin/python
##### update_replay_games
# This should have the same functionality as prep_replay_games, but
# can be modified to adjust the API output to account for changes
# between the master version against which games were recorded, and
# the version under test.  One-off changes which will not be needed
# once the API update is committed should be made in this file and
# should not be committed.  Support for permanent API changes should
# be made in random_ai.py.

import sys
sys.path.append('lib')

import random_ai

SKIP_INITIATIVE_SKILLS = set(['Rage', 'Stinger', 'Trip'])
def add_initiative_flag(diearray):
  retval = []
  for die in diearray:
    if SKIP_INITIATIVE_SKILLS.intersection(die['skills']):
      die['properties'].append('IrrelevantForInitiative')
    retval.append(die)
  return retval

########################################################################
# Custom classes
class PHPBMClientOutputWriter(random_ai.PHPBMClientOutputWriter):
  # If you need to make any changes to the syntax of PHP output which is
  # translated from the internal game state format for regression-testing
  # previously recorded games against this PR (e.g. if the new code
  # changes the API and you need to reflect those changes for replays
  # to succeed), make those overrides here for clarity during testing.
  #
  # As a first resort, trying overriding apply_known_changes_to_game_data()
  def apply_known_changes_to_game_data(self, data):
    if data['gameState'] == 'REACT_TO_INITIATIVE':
      for i in range(len(data['playerDataArray'])):
        data['playerDataArray'][i]['activeDieArray'] = add_initiative_flag(data['playerDataArray'][i]['activeDieArray'])
    return data

########################################################################
# Initial setup
if len(sys.argv) < 2:
  raise ValueError("Usage: update_replay_games <dirname>")

DIRNAME = sys.argv[1]

d = PHPBMClientOutputWriter(DIRNAME)
for gamepath in d.find_games():
  sys.stderr.write("Updating and prepping game for replay from: %s\n" % gamepath)
  d.translate_game(gamepath)
```

**Comment by TheOrgg** [comment]
What about slow?  (Also Evil (E) and Sleep (Z) also don't count, though they're not yet active.  Noting it here for reference)

**Comment by blackshadowshade** [comment]
The current code does not gray out the dice for a slow button (like Giant).

**Comment by cgolubi1** [comment]
Yeah, but Slow *dice* should count, and i'll make sure they do in testing.  Incidentally, i didn't notice slow initially because (see http://www.buttonweavers.com/ui/skills.html ) the slow skill uses the wording "These dice are not counted for the purposes of initiative." whereas all other initiative-excluded skills seem to use "...do not count for determining who goes first."

**Comment by blackshadowshade** [comment]
This code should work perfectly fine for slow dice.

**Comment by TheOrgg** [comment]
There's at least two sets that have Slow dice other than Giant (and he has a button special to make sure he NEVER goes first, not slow dice).

**Comment by blackshadowshade** [comment]
@TheOrgg, should be easy enough to test these out on the dev site!

**Comment by TheOrgg** [comment]
I will do so if they've been added.

Also, did you find what is hanging up Game 194 on the test server?

**Comment by blackshadowshade** [comment]
Regarding Game 194, here's the information I have:

The two players are theorgg and SextusUrungus.

The two buttons are

    Stumbling Clowns: (8):5 t(8):6 (10):7 t(10):2 (X=4):1

and

    IIconfused: fn(X=6):5 fn(X=6):4 gn(X=6):1 gn(X=6):2 `H(Y,Y=3):6 `d(Y=3)!:3 `mp(Y=3):3 `^(1,Y=3):4

The game is currently in BMGameState:REACT_TO_INITIATIVE, waiting for SextusUrungus to decide whether or not to react with focus.

**Comment by blackshadowshade** [comment]
Right, I think I've dealt with that bug. @cgolubi1, if you wouldn't mind updating the code base for us, please.

@TheOrgg, once the code has been updated, that game should work perfectly well.

**Comment by TheOrgg** [comment]
What exactly happened?

**Comment by blackshadowshade** [comment]
Basically, Javascript didn't want to evaluate die.properties... when 'properties' was not a property of 'die'. As usual, it simply stopped rendering the page beyond that line.

**Comment by TheOrgg** [comment]
The dev site is still getting hung up on that  Game 194.

**Comment by blackshadowshade** [comment]
It hasn't been updated yet.

**Comment by cgolubi1** [comment]
I tried to update this dev site, and the instance wound up in (possibly was already in) a weird state --- i'll look into it more later.  (Nobody panic; no dev action is needed.  Just wanted to let people know this dev site appears to be down right now.)

**Comment by cgolubi1** [comment]
I think i've updated the code and the new Game.js is in place and http://momentary.dev.buttonweavers.com/ui/game.html?game=194 still isn't loading.  Do other folks see the same thing?  If not, then i just have bad JS cached.

**Comment by cgolubi1** [comment]
For what it's worth, though, i haven't done JS debugging in forever, but firefox dev tools is telling me jquery is throwing:

```
Uncaught TypeError: right-hand side of 'in' should be an object, got undefined
```

So i wonder if `in` doesn't work if `die` isn't defined in the first place, and if that's the situation you're in.

**Comment by TheOrgg** [comment]
Nothing's coming up at all for me.

**Comment by blackshadowshade** [comment]
> For what it's worth, though, i haven't done JS debugging in forever, but firefox dev tools is telling me jquery is throwing:
> 
> ```
> Uncaught TypeError: right-hand side of 'in' should be an object, got undefined
> ```
> 
> So i wonder if `in` doesn't work if `die` isn't defined in the first place, and if that's the situation you're in.

I'm seeing the same error, but I can't work out why 'die' is returning undefined.

**Comment by blackshadowshade** [comment]
Interesting. By hacking the dev site (sorry Chaos if this complicates things!), apparently the issue is that the die index is going up to 5, while there are only four dice in the activeDieArray (thus the index should only go up to 4).

I'll take a look at why that's happening.

**Comment by blackshadowshade** [comment]
Oh! Obvious!

The for loop in Game.js at line 2402 is running from i = 0 to maxDice, where maxDice is the maximum number of dice for both the player and opponent.

Argh.

Easy fix coming up.

**Comment by blackshadowshade** [comment]
Okay, bug should now be fixed better. Try that.

**Comment by TheOrgg** [comment]
Game 194 is still held up and not loading.

**Comment by blackshadowshade** [comment]
Not surprising, the bug fix needs to be deployed to the test site before you'll see any change in behaviour.

**Comment by cgolubi1** [comment]
Dev site is updated.

**Comment by cgolubi1** [comment]
The game is loading for me now; check it out, other testers.

**Comment by blackshadowshade** [comment]
Yep, loading for me now.

**Comment by TheOrgg** [comment]
I played out that dozen or so matches out, and everything seemed just fine.  

Was the 194 bug related to this enhancement, or was that a separate issue that hadn't been discovered before?

**Comment by blackshadowshade** [comment]
The bug you found was related to the changes I made, so specific to this enhancement.

**Comment by cgolubi1** [comment]
Where are we?
* I never reported back on the success of my replay-testing, so i should check on that.
* TheOrgg says this works now UI-wise
* Anyone else have anything to say or test before we merge this, assuming replay testing looks fine?

**Comment by dwvanstone** [comment]
I've tried a bunch of games on this -- it looks really good. Wranklepig adds its own wrinkle - you can reroll a chance stinger die at the beginning and the die is grayed out but it still works. I think it's nice.

I don't know what would happen with a focus-stinger (or focus-trip or focus-rage) but I couldn't find a button to test it on.

**Comment by cgolubi1** [comment]
Replay testing tells me that Warrior dice are also going to show up as greyed out (try a game with IIconfused).  dwvanstone, do you approve of how that looks too?  If so, i'll call this good and merge it.

**Comment by dwvanstone** [comment]
> Replay testing tells me that Warrior dice are also going to show up as greyed out (try a game with IIconfused). dwvanstone, do you approve of how that looks too? If so, i'll call this good and merge it.

Yes. I like that the warrior dice are greyed out. You can also see other players' games greyed out even if you're not part of the game. Go as a user who is not "dvstest2" nor "dvstest3":

http://momentary.dev.buttonweavers.com/ui/game.html?game=221

I think that's okay too.

**Comment by cgolubi1** [comment]
Great!  Thanks for all the iteration on this, everyone.  Shadowshade, why don't you rebase this down to one commit, and i'll merge it?

**Comment by blackshadowshade** [comment]
Rebase done, CircleCI is happy.  :)

**Pull request merged**
