### PR TITLE
Reactivated Berserk in RandomBMMixed

### PR DESCRIPTION
**Pull request by blackshadowshade**
Reactivated berserk in RandomBMMixed (#779).

Depends on #1579.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/703/

### CODE REVIEW

**Comment by cgolubi1** [comment]
Shadowshade: this pull doesn't strictly need merge help, but if you updated it, github would figure out that the diff is much smaller than it thinks, and it'd be easier for me to see what's actually changing.

**Comment by cgolubi1** [comment]
Test plan here should be pretty simple:
* have RandomAI play a lot of RandomBMMixed games, and look for internal errors
* play a few games by hand (or look at a few of RandomAI's) and look for incorrect behavior

**Comment by blackshadowshade** [comment]
So, this should now be updated correctly.

**Comment by blackshadowshade** [comment]
http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/704/ (if it passes)

**Comment by cgolubi1** [comment]
RandomAI played 500 berserk-containing games with no internal errors, and i played part of a game by hand and it looked okay.  I'm sure some incorrect-behavior bugs remain, but i'd rather let the dev testers find those.  Merging.

**Pull request merged**
