### PR TITLE
Migrate BMInterface.php to BMDB

### PR DESCRIPTION
**Pull request by cgolubi1**
* Partially addresses #712

### CODE REVIEW

**Comment by cgolubi1** [comment]
I'll stand up a replay site for this one too.  Also i expect us to merge #2750 first and make sure these play nicely with each other.  From a code level, there shouldn't be conflicts (this PR doesn't touch either `save_game()` or `__construct()`), and i don't expect subtle conflicts --- but we'll want to check.

**Comment by cgolubi1** [comment]
This replayed 5800 games with no errors.  Rebuilding the replay site to get more data points in save_game-under-transaction-land.

**Comment by blackshadowshade** [comment]
Let me know when you're happy with your tests on this, then we'll merge it and see if there are any interactions with the other changes.

**Comment by cgolubi1** [comment]
This played another 9400 games.  I'm happy with it if you are.  Merging!

**Pull request merged**
