### PR TITLE
Added tutorial on how to play BM

### LINKED ISSUE #2843: Add rules of Button Men on our site
In #2837, @jl8e mentioned that he would like the rules of Button Men on the site.

I think this is reasonable, but we've previously flagged that we need to explicitly clear this with relevant authorities so that we don't inadvertently breach copyright.

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #2843.

Depends on #2837.

This is adding a lightly-edited version of @jl8e's tutorial to our site. Thanks very much for the work, @jl8e!

### CODE REVIEW

**Comment by blackshadowshade** [comment]
I've added the incomplete flag to ensure that we don't merge this before #2837. Once that is merged, this pull request should be ready for review.

**Comment by blackshadowshade** [comment]
I've rebased this, so this should now be ready for review on a dev site.

**Comment by cgolubi1** [comment]
I stood up a dev site, https://blip.dev.buttonweavers.com/ --- check out the new tutorial there

**Comment by cgolubi1** [comment]
Initial comment:
* on help.html, it says: "We have a [tutorial to help you get started](https://blip.dev.buttonweavers.com/ui/getting-started.html) using this site."
* when you click that link, and go to getting-started.html, it says: There is also a tutorial: [How to Play Button Men](https://blip.dev.buttonweavers.com/ui/how_to_play.html).

That's confusing --- we shouldn't use the word "tutorial" in two different places to link to two different things.

**Comment by cgolubi1** [comment]
I also want to call out that the page `getting-started.html` has a dash, and *all* other page names use underscores.

That's not a new regression --- but it might be just as easy to fix here, as to file a whole different issue for it.

**Comment by dwvanstone** [comment]
On the page how_to_play.html:

  Capitalization should be consistent between the links at the top and the names of the sections below. ("The next round" vs. "The Next Round").
  Perhaps in "Written by jl8e" the "jl8e" could link to his profile? 
  
On the page getting-started.html:

  Perhaps "ElihuRoot" could link to his profile?

  "A full list of button sets, along with the skills used, can be found on the [button page](https://blip.dev.buttonweavers.com/ui/buttons.html)"
      I suggest changing this to match the navigation bar at the top
  "A full list of button sets, along with the skills used, can be found on the [Buttons](https://blip.dev.buttonweavers.com/ui/buttons.html) page"

  "A full list of skills can be found on the [skills reference page](https://blip.dev.buttonweavers.com/ui/skills.html),"
       I suggest changing this to match the destination page:
  A full list of skills can be found on the [Die Skills and Types](https://blip.dev.buttonweavers.com/ui/skills.html) page,"
 
  "(Note: Random Button does not currently restrict its choice based on skill or set filters.)"
      I suggest changing "Random Button" to "_Random button_" to be consistent with the previous sentence.

**Comment by blackshadowshade** [comment]
I believe that I've implement all those changes that were suggested. Let's see if they look right once we update the test site.

**Comment by cgolubi1** [comment]
Dev site should be updated.

**Comment by cgolubi1** [comment]
I glanced at the text, and it looks fine to me.  Devious, were your comments addressed?  If so, we can merge this IMO.

**Comment by dwvanstone** [comment]
On the "how_to_play.html" page, these capitalizations don't match between the links at the top and the section below:

  Starting the game  vs. Starting the Game
  Playing the round vs. Playing the Round
  Really basic strategy vs. Really Basic Strategy

Otherwise it's fine.

**Comment by blackshadowshade** [comment]
I've made the changes to capitalisation as required.

**Comment by cgolubi1** [comment]
Devious: dev site is updated.

**Comment by dwvanstone** [comment]
Looks great!

**Pull request merged**
