### PR TITLE
Added Jolene

### LINKED ISSUE #1997: Add "Jolene" Rare Promo BM
Rare BM, exclusive to the Lord of the Fries Kickstarter:

7fe5738b8f8c8ed3ca7f5bf1dc37b774_original

See: https://www.kickstarter.com/projects/cheapassgames/lord-of-the-fries/description

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #1997

### CODE REVIEW

**Comment by blackshadowshade** [comment]
Just a note that the unit tests here will conflict with #2389, so #2389 should be accepted first, then this needs to be fixed.

**Comment by blackshadowshade** [comment]
TheOrgg has supplied an alternative image for Jolene:

JoleneButton

What do people think? Do we use this (with appropriate shadows) or go with the image I currently have?

**Comment by AdmiralJota** [comment]
I don't really like the way things are cut off at the left, especially her name.

**Comment by cgolubi1** [comment]
Database files seem fine.  Let me stand up a dev site.

**Comment by cgolubi1** [comment]
Oh, yeah, this dev site happened.  Josh, when you get a sec, can you sync up momentary == 3.84.227.179?

**Comment by cgolubi1** [comment]
Huh, you forgot to define the "2017 Rare / Promo" buttonset... and nothing seems to disallow adding buttons with no sets, they just show up as set null.  That's not fantastic.  A test should totally fail if there's a button with no set.

**Comment by blackshadowshade** [comment]
So I did! Let me add the missing set now then.

**Comment by blackshadowshade** [comment]
No, wait. The button set should be there, since I added it for Mutton Ben.

**Comment by blackshadowshade** [comment]
See line 71 of data.button.sql.

**Comment by blackshadowshade** [comment]
My suspicion is that the database update that added Mutton Ben

https://github.com/buttonmen-dev/buttonmen/blob/b50ce06e882af3da465813daf934073fa1e98e69/deploy/database/updates/02345_mutton_ben_01.sql

wasn't applied to the testing database that was used for this test dev site.

**Comment by cgolubi1** [comment]
> My suspicion is that the database update that added Mutton Ben
> 
> https://github.com/buttonmen-dev/buttonmen/blob/b50ce06e882af3da465813daf934073fa1e98e69/deploy/database/updates/02345_mutton_ben_01.sql
> 
> wasn't applied to the testing database that was used for this test dev site.

Why would it have been?  That's not how anything works.  Why isn't '2017 Rare / Promo' in master's data.button.sql any more?  #2449 has it there.

**Comment by blackshadowshade** [comment]
At https://github.com/buttonmen-dev/buttonmen/blob/master/deploy/database/data.button.sql, I see 2017 Rare / Promo there, line 71.

**Comment by irilyth** [comment]
> Oh, yeah, this dev site happened. irilyth, when you get a sec, can you sync up momentary == 3.84.227.179?

Done!

```
[21:54:27] irilyth@azazel:/home/irilyth
+$ host momentary.dev.buttonweavers.com
momentary.dev.buttonweavers.com has address 3.84.227.179
```

**Comment by TheOrgg** [comment]
Just saw this thread.  Didn't notice the cutoff.  Lemme try and fix it.
JoleneButton2

Also, here's the original file.
JoleneFinalSingleCard

**Comment by cgolubi1** [comment]
Shadowshade, want to update the art on the dev site, or can we evaluate it without a dev site?  What do we need to do before this can be merged; it should be pretty simple, right?

**Comment by blackshadowshade** [comment]
I'm happy to leave the pull request as-is at the moment. We can always update the images later. Our major issue at the moment generally with button images is that we don't have anyone available who knows how to apply the reflection/drop-shadow to button images. @dwvanstone said that he was going to investigate this, but it shouldn't stop us accepting this pull request.

BTW, did you find out why the deployed test instance wasn't showing the 2017 Rare/Promo set?

**Comment by cgolubi1** [comment]
Okay, the new site (3.87.152.169) is also missing "2017 Rare / Promo".

**Comment by blackshadowshade** [comment]
Remind me, how are the test databases generated? Are they copies of staging? Or of some older database?

**Comment by cgolubi1** [comment]
Turns out i hadn't updated the database the dev sites use since April.  So that's definitely the problem; let me see if i can easily fix this dev site up.

**Comment by cgolubi1** [comment]
Okay, i rebuilt the dev site database --- it's still at the same IP.  It has 2017 Rare/Promo now, so that should be all set.  Sorry for the stupidity.

**Comment by blackshadowshade** [comment]
Right, this looks fine now. Jolene exists in the button selector, image is visible, and the button set is visible.

**Comment by cgolubi1** [comment]
Thanks.  Merging.

**Comment by cgolubi1** [comment]
I left this dev site running.  Shutting it down now.

**Pull request merged**
