### PR TITLE
Make swing input field trigger number pad on touch devices

### LINKED ISSUE #2172: The site could be more mobile friendly.
Couple quick thoughts:
1) The swing dice selection could pull up the number-only keyboard with minimal changes.
2) The hover-over / tool-tip information on special skills is inaccessible to the mobile user. I had to search in another page to find what each skill did during a game.

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #2172.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1298/ (if it passes)

### CODE REVIEW

**Comment by cgolubi1** [comment]
I think i should bring this up on a dev site so people can try it out on different devices, but not try to push it for May - let's be singleminded and get Turbo out for May.

**Comment by cgolubi1** [comment]
Dev site for this pull - http://54.160.0.59 - please check it out.  Reminder: if you have an account on staging, it'll be installed here; if not, you can create one.

**Comment by irilyth** [comment]
This seems to have put two weird little arrows into the text box in Firefox on my laptop:

bm

Chrome too:

bm

That seems undesirable.

It looks in Chrome for Android on my Nexus 5.

**Comment by blackshadowshade** [comment]
Could you also test the turbo swing selector box? That one has no range, and if the range is causing the arrows to display, I can remove the range.

**Comment by irilyth** [comment]
Looks like it's in the Turbo Swing selector box too:

bm

Hmm.

**Comment by blackshadowshade** [comment]
I guess the next thing to try is to change "number" to "cal" and see if that works better. I'll put in a change to this pull request when I can.

**Comment by blackshadowshade** [comment]
I'll just note for myself that the QUnit tests also fail here, so I'll need to fix those too.

**Comment by blackshadowshade** [comment]
http://stackoverflow.com/questions/3790935/can-i-hide-the-html5-number-input-s-spin-box

This may be the fix needed to hide the arrows.

**Comment by blackshadowshade** [comment]
This should now work without spinners.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1301/ (if it passes)

**Comment by blackshadowshade** [comment]
Okay, after some help from @AdmiralJota, I realised that I put the wrong sort of comment into the CSS, and that stopped the parsing entirely. This should be fixed now.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1315/ (if it passes)

**Comment by irilyth** [comment]
This now looks good to me on both my desktop and my phone. Yay!

**Comment by cgolubi1** [comment]
What's happening here?  irilyth thinks this is okay to merge.  Has anyone else looked at it either way, and if so does everyone else who has looked at it think it's okay to merge?

**Comment by cgolubi1** [comment]
irilyth said this was okay to merge, and no one else has weighed in, and it's been awhile.  Let's call this good to go - shadowshade, can you rebase down to one commit, and then i'll merge it?

**Comment by blackshadowshade** [comment]
Right, this has been rebased.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1341/ (if it passes)

**Comment by cgolubi1** [comment]
Merged this; taking down the dev site.

**Pull request merged**
