### PR TITLE
JSON serialize API input for submission

### PR DESCRIPTION
**Pull request by cgolubi1**
* Prerequisite for #1209
* This change modifies the format of ALL API posts, so it is a breaking change for clients, but the required changes should be very simple
* No API method syntax is changing, but the purpose of this commit is to unblock future work by allowing us to pass args more cleanly than urlencoding would allow

### CODE REVIEW

**Comment by cgolubi1** [comment]
I'm going to do a fair bit of replay testing on this --- you'll see a few changes to `ApiSpec.php`, which are all because the quality of the data types we are giving the API by default are improving, but ApiSpec had to be updated to allow the better data type, so i want to use testing to find any other edge cases where that's true, though ideally everything in the spec would be covered by responder tests already.

**Comment by blackshadowshade** [comment]
So, if I understand correctly, currently I just sit on this pull request until replay testing is done?

I don't see any issues with the pull request after a brief look, although there's a function or two that I'll need to research.

**Comment by cgolubi1** [comment]
Yep, you understand correctly: i put it up for PR to find out what concerns you have other than anything replay testing will turn up.

**Comment by cgolubi1** [comment]
My replay site has played 4400 replayed and novel games with no differences, so i feel pretty good about that.

I'll go ahead and rebase this, and then you can review it?

**Comment by blackshadowshade** [comment]
I've loaded this onto my MAMP stack, tested that a standard Soldiers game can start, swing setting works, turns can be played, and a round ends correctly. I've also tried this with a Lady Luck mirror match, and that worked too.

Looks good to me.

**Pull request merged**
