### PR TITLE
Added a grayscale favicon for monitor mode.

### LINKED ISSUE #1125: Change page title in Monitor mode
It'd be cool if the page title changed when you were in Monitor mode, so that if you have it in a non-active tab, the title of the tab would change (back to the usual title) if you had active games.

### PR DESCRIPTION
**Pull request by irilyth**
This doesn't fix #1125, but it could be used by someone who was going to do so.

### CODE REVIEW

**Comment by irilyth** [comment]
http://jenkins.buttonweavers.com:8080/job/buttonmen-irilyth/11/

**Comment by cgolubi1** [comment]
Okay, so i think my test plan here is to look at this supposed "black and white favicon" file and make sure it actually looks like a black and white favicon.

**Comment by cgolubi1** [comment]
Seems to be as advertised.  Will merge once merge freeze is over.

**Comment by cgolubi1** [comment]
Merging.

**Pull request merged**
