### PR TITLE
Option dice now work correctly when they are to the right of a reserve die 

### LINKED ISSUE #1631: assertion failure on dev site
Uh oh: apache logs say:

```
[Mon Jun 01 21:13:05 2015] [error] [client X.X.X.X] PHP Warning: assert(): Assertion failed in /var/www/engine/BMGame.php on line 666, referer: http://dev.buttonweavers.com/ui/game.html?game=1664
[Mon Jun 01 21:13:05 2015] [error] [client X.X.X.X] PHP Fatal error: Call to undefined method BMDie::set_optionValue() in /var/www/engine/BMGame.php on line 667, referer: http://dev.buttonweavers.com/ui/game.html?game=1664
```

This happened several times over a period of a few minutes, all with the same details and game number.

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #1631.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/738/

### CODE REVIEW

**Comment by cgolubi1** [comment]
Okay.  I should just be able to play back some games looking for regressions, play some new games containing option dice, and call that good enough.

**Comment by cgolubi1** [comment]
Oh, whoops, it'd make my life easier wrt other testing if the new test function was named test_interface_game_034 rather test_interface_game_00034...

**Comment by blackshadowshade** [comment]
Test name fixed

**Comment by cgolubi1** [comment]
All the regression tests seemed fine, and various new games both random and with bobby 5150 in particular seem to be completing, which wasn't so much the case before.  So i think this is an improvement, and am happy to merge it.

**Pull request merged**
