### PR TITLE
Stopped unnecessary reroll of zero-valued dice

### LINKED ISSUE #2041: Dead Guy's dice are rolled after reactToAuxiliary, and again after submitDieValues
Obviously this has no player impact, since Dead Guy's dice always roll 0.  But it seems like a bug, and it'd be nice to verify that it's a bug which only affects Dead Guy.

### PR DESCRIPTION
**Pull request by blackshadowshade**
Fixes #2041.

testing pull: #2106

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1208/

### CODE REVIEW

**Comment by cgolubi1** [comment]
No one has commented on this proposed change.

**Comment by blackshadowshade** [comment]
Yeah, I think this might be one where your RandomAI might want to do the checking for us.

**Comment by cgolubi1** [comment]
As noted on #2133 punting this for December until the new workflow is sorted.

**Comment by cgolubi1** [comment]
I'll create a replay site for this and not even bother with dev testing, since i'm sure no one cares.

**Comment by blackshadowshade** [comment]
Okay, rebased to bring this to apply after turbo swing.

http://jenkins.buttonweavers.com:8080/job/buttonmen-blackshadowshade/1306/ (if it passes)

**Comment by cgolubi1** [comment]
I have this up on a replay site, with the following diff, which suppresses all zero rolls obtained during `submitDieValues` when "Dead Guy" is one of the players.  That's obviously not very targeted, but it catches the case we're aware of, so it should alert me to any cases other than that which turn up in random games.  So far it's replayed 1100 games --- i might as well give it a couple of days and let it replay a couple thousand games, and i don't see any need for any testing other than replay testing for this pull.  Unless i turn up anything unexpected, i'll merge this later this week.
```diff
diff --git a/tools/api-client/python/update_replay_games b/tools/api-client/python/update_replay_games
index 3243e4f..8a09fe2 100755
--- a/tools/api-client/python/update_replay_games
+++ b/tools/api-client/python/update_replay_games
@@ -23,7 +23,18 @@ class PHPBMClientOutputWriter(random_ai.PHPBMClientOutputWriter):
   # to succeed), make those overrides here for clarity during testing.
   #
   # As a first resort, trying overriding apply_known_changes_to_game_data()
-  pass
+  def _write_log_entry(self, entry):
+    write_function = '_write_entry_type_%s' % entry['type']
+    if not hasattr(self, write_function):
+      raise ValueError("Don't know how to write entry of type %s" % entry['type'])
+    if entry['type'] == 'createGame':
+      self.game_has_dead_guy = 'Dead Guy' in [ entry['button1'], entry['button2'], ]
+    if entry['type'] in [ 'submitDieValues', ]:
+      if self.game_has_dead_guy:
+        while entry['retval'].rand_vals.count(0) > 0:
+          entry['retval'].rand_vals.remove(0)
+    getattr(self, write_function)(entry)
+
 
 ########################################################################
 # Initial setup
```

**Comment by cgolubi1** [comment]
This looks good, sorry it took so long to get back to it.  There's only one failure in the 5 days of games it replayed after i put it down, and that's because of a `submitTurn` which ended a round, and thus isn't caught by my simple diff.  I am ready to merge this.

**Pull request merged**
